table d_mascara_DRE
	lineageTag: bc99d188-7da9-4280-a342-f429bfd77325

	column ORDEM
		dataType: int64
		formatString: 0
		lineageTag: 9e53dac9-f303-47c9-88fe-26a367a47640
		summarizeBy: none
		sourceColumn: ORDEM

		annotation SummarizationSetBy = Automatic

	column 'NÍVEL 1'
		dataType: string
		lineageTag: 885417f7-9d33-4835-9eb6-0da7ecc00845
		summarizeBy: none
		sourceColumn: NÍVEL 1
		sortByColumn: ORDEM

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'NIVEL 1 SEM SINAL'
		dataType: string
		lineageTag: 1afa0b26-3d89-49b2-a8ac-86b6634e2d4b
		summarizeBy: none
		sourceColumn: NIVEL 1 SEM SINAL

		annotation SummarizationSetBy = Automatic

	column SUBTOTAL
		dataType: string
		lineageTag: 66732edb-09e6-4679-8549-ba6a8391d00e
		summarizeBy: none
		sourceColumn: SUBTOTAL

		annotation SummarizationSetBy = Automatic

	column SINAL
		dataType: string
		lineageTag: 06eb8d13-a4ad-48df-864a-953b997a33ca
		summarizeBy: none
		sourceColumn: SINAL

		annotation SummarizationSetBy = Automatic

	column 'SINAL 2'
		dataType: string
		lineageTag: 32a95aae-408b-43e7-817e-b956108c3d20
		summarizeBy: none
		sourceColumn: SINAL 2

		annotation SummarizationSetBy = Automatic

	partition d_mascara_DRE = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jZPJTsMwEEB/xcqJiqKQ0rIcOEBZVBTUqJW4VD1YsYUsNXbx0l+qhMSRL8iPMXaT0Noh5WDLnuXNjGe8WERJ1I9mNKdMY3QvjcYt93NYJ7e9al/2F9HAns966IESU27Lb6oQwcj369Za6g7jkBcVclKshdJCoQnPGaFcg7eKa28wOmrggYd7FaXl14dhBLeLkqDOUZXU2LiIBFYmBTH28kY5YSABkyNqL6HLEDqncsPK7Z/UVr2HvYLzK5bvtGie2LuG9V03fVRrqrBCz1RiplzvfIkX7sa9oTIrjYlA0zWY5UxwvOqQhwkkbrZOY8jh1+mJccyhO1IcsA7EdTbWdUdKGtLUaAmZVx1WcV0LGHSoQuKgIT7CiGzwqvyEkcMow1qyQnDmiurShUw75qnJpagHT6A7N8K2zfVo/9Om5TmH9S+aZS/xeJ6m9sPsnb0mJqMgVJvAC7T8AQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ORDEM = _t, #"NÍVEL 1" = _t, #"NIVEL 1 SEM SINAL" = _t, SUBTOTAL = _t, SINAL = _t, #"SINAL 2" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"ORDEM", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

