table dlogo_cliente
	lineageTag: 9a57552b-6666-4086-86dd-428ff283973e

	column grupo
		dataType: string
		lineageTag: fed27615-9f3b-4d1c-b134-238c6f79f473
		summarizeBy: none
		sourceColumn: grupo

		annotation SummarizationSetBy = Automatic

	column Url_Logo_Normal
		dataType: string
		lineageTag: b97e91bf-9a3b-4760-9d10-37894b79f409
		summarizeBy: none
		sourceColumn: Url_Logo_Normal

		annotation SummarizationSetBy = Automatic

	column Url_logo_branca_sem_fundo
		dataType: string
		lineageTag: fa48f37a-4e28-4e0c-b492-3e28267223b2
		summarizeBy: none
		sourceColumn: Url_logo_branca_sem_fundo

		annotation SummarizationSetBy = Automatic

	partition dlogo_cliente = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("vZrLlqLMloBfhfWPT1R4z/TMBBVNARFINfP0PwgBEeUmIJpO+xH6DfoMetSj8wj1Yh1cLMmqHVb+vXr1IFe6Ft+OHRHEvgb/+McfYnyKQm5C3AOJ//jbH7s0jZK/Y+x+czebb2aId07nvStucUl8iwIHotS31qbxfsG7gkJe6IQF+uffbhoUkp5i+0ogac1o7vnNDOdiKKhAlqpo/fS+aW0A+K5MDz14NcuztDmMW6VwklMsNQyypiOKQ0hwdRG3aquFE/r82z4CB7+ug+va6eB8DGS6wS8LkM0hJDeUJ2N9nJaT8k3W3Bfy29Kw/E/YfWzjtLHjretBkv1YvRxFH6cVw9JwDBpv5+72B4c2MQlMUqz3rmlJ/DABxT/2/R0VLwAk3U4LQPbU4zb+8H8ma6/B9u0gtRNO//5Pum8ktU+gSmHlC8FCqt5nJYQSQjeokGFN4CK9tBRxj296kI5CJN9F7jMZupm7DWMfPOKHfuzwRws7OYqsG8rS2g+OmdnOfsaRbbkpsX7eAzEmW9exwTf63G8pgbmpRnIqkqX3AX1XNx2q4BLXguXPzErWtSJkJ+YpZr7aj2N/fzxMsGvl8A8d0yAjiZvZkEjcPi/8pXBTUZFMBXq31dF5fOOQSa2Y5C8fbU/BL7uo2pHNGW6QEvAAWbO4LY/POKIYSguMpXgomhudWlENRa2ftGmhReLU5rQ2OELci9qxXp7WuJ2cotjNz1+YfDvbmwicX7ppHhd7rLVRid9s8rPeJTmebBd2XdLLKlp2FZxVDHNju92JKTd+cL8sTtBA93Xo9DLRzLAZW/cQAXDr5H22VVfl6nPYDhI3CJGNIjs5ntzk50VJbnCEBkpbzmK75LFHn7OUdcXomTfTgkGp7dlm6P+yIFUcgAtqf6QdvlOdx8hh6jh03v2xiiPHJ27CPIFa6Kaw288+tuIRx/Q5Kjcl9MLYtZg7KHWb8VU93CV+WQ8nD6Y66CjPm3Ojsf6/WpNu7twosmPQpiaBwvORg2Ud/eBY+phsbVUeMQ9gvImum+PbGefxAxUUmtD9u4bUND2ku0lq+9RGhTBI0viUuhmNNU3WRPjzJesdUxwV45RGxlz+mCQpN7E90GSlQyRfpDPeUmhHmfJNMXIGM94u5FavgFFB/6L6c/QdmKZNPQxoF7zfXb9s8EAQRpoxemiMTLam6ZSB/kSbbDPD2uHB63L+UAcM3hXwEw3OOnvdxfaM6eOHw4NcbfRTcLDBdPEp6PqZOMb8qzIbPdbBQmtOkQRhBCcnL2nvIDxvsTBQ5uqr/lARk61pckli2xao6u3Qb6zeAixMB/poNHysiw3X0x5qMyQ5gdnH8Mx3ttdnPJzqhjbQX6WHR/wBXejrjMFMXZcmqRRj+vjhYkDuk/MIiJeCB/mSHLV2f4tVaaAMJOPxYWbDn84C/ff/cRYMXoAkm9trM/7oYNk14zAJtykybOInyPWJY7N931fEavEMVN2Wu7OV38A0A4pd50RTauEU7MjDhf5Wpra1oU+oM4RGERuryxv1twWIKpClkg3XvLu9sT3CDRwaZwPrRA3BJaAdWJKxGXaH1WClGEsxk62tkRfm4DYp/YWm8VXitDFDZrbIIHMVMo0ldBncJEwiWm0wKulNcxatxyKuaHSnWev6jUQtnNDt9L7/y3FNsJSSFGk5FJ9wgaGcYmZBMFk/K0FmJ3CMlJXj1dj52KyYh+eTDddqemLuiOUGO/BsnmdO4+Njh/0f1EOFj/B6sp+niWCL4OX97dKcVFleVnDMdgKLrSmyAysiDrgymX+T9fMYL0fKUB2Ic+YeQlzNmdiJHWeEa3fBNpWvBe/tFo5LCrW7LDUM8q7ohZjhhiZutHYFt+7YlQ5+SyxNZ5/DzC4JTNa2zU3sExirhOZ7ezssJat9z9ky56NpeWyn7ED3ZeHa4ayMXrO31MHaMfn+X9//CcdCZ9VoR8equVTZcnwTMwk7Ln5JsFY5kG0MOoDszeh09EPVyskplkoGWQv6OztwL5xBNyaJQpotgyF5uei1VrM+jgoa0XQniJibz2Jrb32iv4GlVzPrPTt8s5hutkNUium/WWjtjeoCpwasblh3Zna3tz6PnzBbiTBYb5qk8fd/RaHngnpMwwrGa+VWTFI4LFiWuod83Re4nBVyvu0xDukk/ugvaUER2y6y6LxpCGWeSyZbd91nK/HsD7BD6Tv79+MS35gEybRCs+OiWYk0kUftRuPS7PaYLc6/NEBtEwwdzK9EY+n7lwznzx/GEBj85NR3hFNjwimnzPZBA/MvK0FWysKaMijKO2wEBbkA0yp/K1Srzexg/8kJVIXJilfU5zP7QS2b2MON0d1H77mn9qs0K6eYEQMma5OMaQiOwCxitpzJQ90pPdCm5BC5npjKHgvUWl6n62/d1mrV7ssd7J2uhR+qUHZ2/1gg162MVpw0VUZg79jZPVu8gAP7jDw3YLZlQe5T9udGYQAmPYvLfmXMKu9ASpCZITHhuh+50sQFfHFb8UXLDtQ4SgTV9rrqDv6vhGqeM3Z9H/bO+kvnqk+y8gxEJcdSyWTrxWZC/u3UaLR6hh3DIXXMO+dO69ZxpTxKc7TKGFj1+hekakaicbLredzAqzrZYMMhisYqv7idfp8KIHITQK1+89JsPTO7FV8Wvs+qAx7lywt9i8mq9FCdETOjAbB8aIFqjEPOsrl5kHdqHZdw04kItrrbO2OS9co5U4bZEoe4QtdIMbQ5Nx/pxogrGidT/nU6nGsDbjji1JEw0LnBqzGX58Z0SX+PptpImoIl4TbReFWt3maxBBTmxQyzKH8okE8uT6I9i9CNMGKb5qAk4KTUAk9g4yV7umzVci9vNBoldP/yMv9MM0WmDXxZtt4cpZknNUzQit/S5tqqXLCovapzNBC00XiuGUiYa6hzQa1G5/ny1GY7gr84RK36CPN7zGHou4ED20hHjaxDO8MvQ7S045RWtV6Z0j9MGL8gVbvhC7Zu4KZgvuMs98dGlmC3YlhbAHI11+uaOztJQN8rpdnT9cnA2lSYjHSdaX8gV6jId5wbSNKrBtr3bikd1+oLJtRDRMGD218YrNUop8iOgzCD73ybonLerXFyg1haYPBzQ2Rg0t0Cc13npa1lqwUuenDMpAugan0sN05STvBIAp645nW2kXaN4jSHD5qDAFbz/8RxXHABzbU+XCwdvCkItDsFDmFfPj6g6weYRiLv+3/mRSY0yHVido+7qv1lxcQh7FYZky3cL/FMErv5ec4T5pi6OpnmNEU9Cyb7Lx/B+py8YWkuzpEwkASkTefF33KkDZlH/UtyxYR4sEmeXUW+cYwxfcxMy39C8tEM7VWYyaANOdK72vR7crkvaXwyD7R2QlvqU2wUeSQlD79w+CvixUzmKiePwGtlxWkf9sHsvfL/YYRk22LlLGw418IL3Ii+PQc+NULiN4Vu2sO8gCqMWTcz0JoDbHOYJqDHkxvADUgh0py+fF7kN/o3jqmOxdbuaWgp7V5AN7pKu4KxKo/WUJur0zXT4zLQmq/itQkk2WoE403WSnEOsIb/FaoN7PkEnP7TRW45ncm53u8i/oV5UfcAv2ub0QB8sOHbIKX37LxdVg6+QSxVMFhbkm/HNBAHW88GV9b326uDFexxHWT6qQd0vZPhJpwaet//m0JwfiG0HeF6Ft9xziLKohxlnjw2/Sn319WpMAK7XsaWt4TOM+Y1VEIsVTBY76bGKVxQZZ00O/riBZcI0wMCWD68Htkm9VABx8MBrPfUWYzfZAXfQERBpidnwsVK5tM8SddVmimOOEF65WHnu1Ge4venDyyGLkloqlsUmUjwThumj/itTL0Ffr1yZcnICeE3+LStG+fg0sQ5iwTmckGuqA1GmkaLkQG3nEoDAfy8Rkh21vO2WcWILa0tbTcmmesR9p3Pb2XKsDZQ8kppoIivEniT1hQ3q6VwXNzCEwmKy73AOXnszOR3MsUGcwJXqC/eMGgQq5X2tp+lSeWhzLw35ybpg4uu30h86lQlrkctBS7C4pm4SvikjTcFl1GMpZKF3nV9/498Agl1ObTcCEC7VCy935MbXWxMhQGSB5oxVZjmz4ZznRMSW5yeH2lQkzGcPS2fEx5PBtoQFZuvIyncEzQP8iYU0ndhZNuo3CCmB/rro9TcU3hldKtXmf8kiEoLUwTRepH4tF5l5C9M9lO/J++bM77w1Vu9TF1jYUANgMZviaUIBnMtqyGX39FNFbCjIWbj87hrVFZwtpjdZ4irxca8aZZ/kQHJBkq8OVz8zq0le2NZuh7yRdacO1puOOe0kQz6g17U/ti0n3H+nOnZf2bykVVtKoPO7Wr0F0bWjHDetGOaGUAVEWkkjxTqPjhjruW/QA38bH+Wkpcu/vG5c0pTavqr/G4idSOmK/uqaD6XJa2zBWk0UMCEcbJePq9aOKMVtOnZJHh4I/GArh1vO7aJR90b4Wjqnn9/Clr8cLi+ntuX7PYBxw8pdJNizeKLkvcZvYehd0rBy2JVzD6iQyrjkkmZl+wwWATKMfi59UqJr/1Wg8f0OTMu/MzUvhkn8QkOAvLBMVb6TsUlwsw3Qa5W35yIuYPkupd+e3lWGrggWFMHqNrkZRX8INBcD8cbfrfEOfCNRv3tF6l700h81eXv/w76gPHR6b88XyXsnBKfhMjLLZLVGmexd0383BDmCq3eddB61fegNY7PFubDtPisJE6YXoLJ3rW9KtPFK5hLtvio2d33ypquxFirYqF//vk/", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [grupo = _t, Url_Logo_Normal = _t, Url_logo_branca_sem_fundo = _t]),
				    #"Duplicatas Removidas" = Table.Distinct(Fonte, {"grupo"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

