table estrutura_roic
	lineageTag: 97dcda8f-78ce-4497-b73d-45212fe5377b

	column nome
		dataType: string
		lineageTag: 2e60b53d-b799-450e-b12f-3147f312faf6
		summarizeBy: none
		sourceColumn: nome
		sortByColumn: ordem

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column ordem
		dataType: int64
		formatString: 0
		lineageTag: 42c73bb4-d575-4d89-b11b-565cbccdc488
		summarizeBy: none
		sourceColumn: ordem

		annotation SummarizationSetBy = Automatic

	partition estrutura_roic = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("XY6/CoMwEIdf5chkUCn9P3UQbUEQE6x0EYegGVJKYpO69HU6+xS+WK9aOnS7u+/7cb+qIt6BQtY31oDpgVt57cfhaSAbh3uvWkMCsiR1gF5IoZCNVA8BJ6WFxtEKxKsZ+xQS6Trp/vD6ixfhT3Cgx5cB1kkrGmW0UA7FzSxinZzxqMTLdrrEEU/LKIM0vxzPZZow8HgGPsSiwy43aCWU0n7eGUcxtZtSBUtjXPakrt8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [nome = _t, ordem = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"ordem", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

