table F_Aging_List_Contas_Pagar
	lineageTag: f321134d-66f9-4928-a868-70b2e633f23e

	measure som_valor_contas_pg =
			
			SUM(F_Aging_List_Contas_Pagar[valor])
		lineageTag: 9e731614-b835-44ec-9204-6e4ac4a040d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure volumetria_aging_contas_pagar =
			
			IF(NOT(ISBLANK([som_valor_contas_pg])), "🟢", "🔴")
		lineageTag: df65afe0-bacc-4a4b-9d26-99e957810456

	measure som_valor_pendente_contas_pg =
			
			SUM(F_Aging_List_Contas_Pagar[valor_pendente])
		formatString: #,0.00
		lineageTag: 938b6d28-99e9-4df2-9dc7-898d31ec18b7

	column empresa_filial
		dataType: string
		lineageTag: becd3e63-66d7-4784-9e93-c7afb4cb104c
		summarizeBy: none
		sourceColumn: empresa_filial

		annotation SummarizationSetBy = Automatic

	column cnpj
		dataType: string
		lineageTag: e5758e81-4219-42cb-a2ce-f2069207d095
		summarizeBy: none
		sourceColumn: cnpj

		annotation SummarizationSetBy = Automatic

	column nome_cliente_fornecedor
		dataType: string
		lineageTag: 79915695-d171-4fda-9542-b0f28301e623
		summarizeBy: none
		sourceColumn: nome_cliente_fornecedor

		annotation SummarizationSetBy = Automatic

	column tipo_titulo
		dataType: string
		lineageTag: 22dbeca3-842d-4851-b09b-c89cf5b8ff4f
		summarizeBy: none
		sourceColumn: tipo_titulo

		annotation SummarizationSetBy = Automatic

	column data_emissao
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2b5c89df-b437-42c4-88b2-c90665445c40
		summarizeBy: none
		sourceColumn: data_emissao

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column data_vencimento
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9a452acf-b809-4264-80cb-cabb16f5cf81
		summarizeBy: none
		sourceColumn: data_vencimento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column data_pagamento
		dataType: dateTime
		formatString: Long Date
		lineageTag: 082c6169-259c-4d3c-8d37-b14a12669876
		summarizeBy: none
		sourceColumn: data_pagamento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column valor
		dataType: double
		lineageTag: c3ac887d-3011-4ee9-b286-425b18353535
		summarizeBy: sum
		sourceColumn: valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column valor_pago
		dataType: double
		lineageTag: 3c0216b1-c67e-45d3-89c4-561dd0c41de3
		summarizeBy: sum
		sourceColumn: valor_pago

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column valor_pendente
		dataType: double
		formatString: #,0
		lineageTag: 78e76570-7743-40b3-9d1d-d7c6225a8c37
		summarizeBy: sum
		sourceColumn: valor_pendente

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column data_base
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7e84e9a6-d4c7-4558-9bd3-3e5c39dfc95c
		summarizeBy: none
		sourceColumn: data_base

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column origem_operacao
		dataType: string
		lineageTag: 5617c64d-a797-44c7-83a4-e0ae6b2b655d
		summarizeBy: none
		sourceColumn: origem_operacao

		annotation SummarizationSetBy = Automatic

	column diferenca_data_base = ```
			// calcula a diferença entre a data de vencimento e a data base
			DATEDIFF(
			    F_Aging_List_Contas_Pagar[data_vencimento], 
			    F_Aging_List_Contas_Pagar[data_base], 
			    DAY
			    )
			```
		formatString: 0
		lineageTag: d9acb9d1-d449-4ca5-b79f-eeecf41e4b62
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Status_data_base = ```
			// Determina se o título está vencido ou a vencer com base na diferença de dias.
			IF(
			    F_Aging_List_Contas_Pagar[diferenca_data_base] > 0, 
			    "Vencido", 
			    "A Vencer"
			)
			```
		lineageTag: de4168ff-9d54-4824-a6ee-cff2cffbbb77
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column categoria_atraso_data_base = ```
			// Classifica o título em uma das categorias da tabela de dimensões "d_aging_list_dbase".
			var diferenca = DATEDIFF(
			                            F_Aging_List_Contas_Pagar[data_vencimento], F_Aging_List_Contas_Pagar[data_base], DAY
			                        )   
			RETURN
			IF(F_Aging_List_Contas_Pagar[Status_data_base] = "Vencido",
			  IF(diferenca <= 30, "Vencidos de 0 a 30 dias",
			        IF(diferenca <= 60, "Vencidos de 31 a 60 dias",
			            IF(diferenca <= 90, "Vencidos de 61 a 90 dias",
			                IF(diferenca <= 120, "Vencidos de 91 a 120 dias",
			                    IF(diferenca <= 180, "Vencidos de 121 a 180 dias",
			                        IF(diferenca <= 360, "Vencidos de 181 a 360 dias",
			                            IF(diferenca > 360, "Vencidos acima de 360 dias"
			                            )
			                        )
			                    )
			                )
			            )
			        )
			    ), "A Vencer"
			)
			```
		lineageTag: 95aa83dd-6508-490d-b1a4-e07284840b39
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Chave Primária'
		dataType: string
		lineageTag: 3555c8ee-6c54-47ab-803c-95275a004ab1
		summarizeBy: none
		sourceColumn: Chave Primária

		annotation SummarizationSetBy = Automatic

	column tipo_relatorio
		dataType: string
		lineageTag: 0e9e67ee-395b-4677-a561-890160cd4b62
		summarizeBy: none
		sourceColumn: tipo_relatorio

		annotation SummarizationSetBy = Automatic

	column chave_operacao
		dataType: string
		lineageTag: d2e832f4-c720-47c9-97ad-e2150050fe79
		summarizeBy: none
		sourceColumn: chave_operacao

		annotation SummarizationSetBy = Automatic

	column uaid
		dataType: string
		lineageTag: 2f447509-8a04-4ec9-b64c-330ebfb865a6
		summarizeBy: none
		sourceColumn: uaid

		annotation SummarizationSetBy = Automatic

	partition F_Aging_List_Contas_Pagar = m
		mode: import
		source =
				let
				    Fonte = GoogleBigQuery.Database(),
				    #"bi-planning-367317" = Fonte{[Name="bi-performance"]}[Data],
				    BI_tratado_Schema = #"bi-planning-367317"{[Name="BI_PROD",Kind="Schema"]}[Data],
				    Aging_List_Contas_Pagar_Table = BI_tratado_Schema{[Name="Aging_List_Contas_Pagar",Kind="Table"]}[Data],
				    #"Valor Substituído" = Table.ReplaceValue(Aging_List_Contas_Pagar_Table,".","",Replacer.ReplaceText,{"cnpj"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","/","",Replacer.ReplaceText,{"cnpj"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1","-","",Replacer.ReplaceText,{"cnpj"}),
				    #"Valor Substituído6" = Table.ReplaceValue(#"Valor Substituído2","00066871000","66871000",Replacer.ReplaceText,{"cnpj"}),
				    #"Valor Substituído8" = Table.ReplaceValue(#"Valor Substituído6","66871000","00066871000",Replacer.ReplaceText,{"cnpj"}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Valor Substituído8", "Chave Primária", each Text.Combine({[cnpj], " ", [origem_operacao]}), type text),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Coluna Mesclada Inserida",{"grupo", "empresa", "numero_titulo"}),
				    #"Texto Substituído inserido" = Table.AddColumn(#"Colunas Removidas", "tipo_relatorio", each "aging_contas_pagar"),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Texto Substituído inserido",{{"tipo_relatorio", type text}}),
				    #"Texto em Maiúscula" = Table.TransformColumns(#"Tipo Alterado",{{"Chave Primária", Text.Upper, type text}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Texto em Maiúscula", "chave_operacao", each [Chave Primária] & " " & [tipo_relatorio]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"chave_operacao", type text}}),
				    #"Texto em Maiúscula1" = Table.TransformColumns(#"Tipo Alterado1",{{"origem_operacao", Text.Upper, type text}}),
				    #"Valor Substituído3" = Table.ReplaceValue(#"Texto em Maiúscula1","Í","I",Replacer.ReplaceText,{"origem_operacao"}),
				    #"Valor Substituído4" = Table.ReplaceValue(#"Valor Substituído3","09534517000135","9534517000135",Replacer.ReplaceText,{"cnpj"}),
				    #"Valor Substituído5" = Table.ReplaceValue(#"Valor Substituído4","9534517000135","09534517000135",Replacer.ReplaceText,{"cnpj"}),
				    #"Valor Substituído7" = Table.ReplaceValue(#"Valor Substituído5","","SEM CNPJ",Replacer.ReplaceValue,{"cnpj"}),
				    #"Valor Substituído9" = Table.ReplaceValue(#"Valor Substituído7","095345170001350","09534517000135",Replacer.ReplaceText,{"cnpj"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Valor Substituído9", each ([data_base] <> null)),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Linhas Filtradas", each ([data_emissao] <> null)),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Linhas Filtradas1",{{"data_vencimento", type date}, {"data_emissao", type date}, {"data_pagamento", type date}}),
				    #"Erros Substituídos" = Table.ReplaceErrorValues(#"Tipo Alterado2", {{"data_emissao", #date(1900, 1, 1)}}),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Erros Substituídos",{{"data_base", type date}}),
				    #"Valor Substituído10" = Table.ReplaceValue(#"Tipo Alterado3"," ","_",Replacer.ReplaceText,{"origem_operacao"}),
				    #"Valor Substituído11" = Table.ReplaceValue(#"Valor Substituído10"," ","",Replacer.ReplaceText,{"Chave Primária"})
				in
				    #"Valor Substituído11"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

