table Medidas_balancetenew
	lineageTag: 3603c923-b033-450c-84aa-8d5a68abc2f3

	measure MReceita_Liquida = ```
			
			SUMX(
			    FILTER(balancetenew,
			        balancetenew[Query] = "Receita Bruta" || 
			        balancetenew[Query] = "Deduções da Receita Bruta" || 
			        balancetenew[Query] = "DRE_Imp_Incidentes_Sobre_Receita"
			    ),
			    balancetenew[vlr]
			    )
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 851fb383-47f4-46d2-942a-4b655da44fb8

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MReceita_Liquida_LM = CALCULATE('Medidas_balancetenew'[MReceita_Liquida],DATEADD(dCalendario[data],-1,MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: b40d8e71-32a3-4f01-8a52-7c77f7d39104

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MReceita_Liquida_ACU = ```
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    CALCULATE(
			        [MReceita_Liquida],
			        DATESYTD(
			            dCalendario[data]
			        )
			    ),
			    Medidas_balancetenew[MReceita_liquida_selecionado]
			)
			
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 3fdb7b3d-ebef-481e-a90f-57853aeca12a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MReceita_Liquida_Acumulada_LY =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    Medidas_balancetenew[MReceita_Liquida_acu_LY_normal_card],
			    Medidas_balancetenew[MReceita_Liquida_selecionado_LY_normal_card]
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: ddc3b952-6f96-449e-9346-3ad21b979134

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	/// calcula a receita bruta
	measure MReceita_bruta = ```
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Receita Bruta"
			        ),
			        balancetenew[vlr]
			    ),
			    TOPN(1, balancetenew, balancetenew[data], DESC)
			)
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: b9a5a0ae-950c-40a4-a66c-391a4094df1e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure liq|bruta = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			        SUMX('Medidas_balancetenew', 
			        'Medidas_balancetenew'[MReceita_Liquida]), 
			        SUMX(
			            Medidas_balancetenew,
			            Medidas_balancetenew[MReceita_bruta]
			        )
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bb608d91-d28d-43b7-b69d-01c864a62f61

	measure liq|brutaLM = CALCULATE('Medidas_balancetenew'[liq|bruta],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1df82197-1b12-4b30-88ab-38e93e813691

	measure %liq|bruta_acu = ```
			
			DIVIDE(
			    'Medidas_balancetenew'[MReceita_Liquida_ACU], 
			    'Medidas_balancetenew'[MReceita_Bruta_ACU]
			    )
			
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2b24faad-4569-457c-a4ee-66f89b314334

	measure MReceita_Bruta_ACU = ```
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    CALCULATE(
			        SUMX(
			        FILTER(balancetenew, 
			        balancetenew[Query] = "Receita Bruta"
			        ),
			    balancetenew[vlr]
			),
			        DATESYTD(
			            dCalendario[data]
			        )
			    ),
			    Medidas_balancetenew[MReceita_bruta_selecionado]
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 4111cdc1-eb07-4396-8f05-5bfea14c3246

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure receita_brutaAcuml_anoAnterior = ```
			CALCULATE([MReceita_bruta], DATESYTD(SAMEPERIODLASTYEAR(dCalendario[data])))
			
			```
		formatString: 0
		lineageTag: 1931345f-b55f-4639-a5ad-bb3a2fca0807

	measure %liq|bruta_acu_LY = ```
			
			DIVIDE(
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[MReceita_Liquida_Acumulada_LY]
			    ), 
			    SUMX(
			        'Medidas_balancetenew', 
			        'Medidas_balancetenew'[MReceita_Bruta_Acumulada_LY]
			        )
			        )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 43c35f46-b5ec-420a-b99b-668534dbe044

	measure MMargem_bruta_actual_month = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    CALCULATE(
			        SUM(
			            balancetenew[vlr]
			        ),
			        FILTER(
			                balancetenew,
			                balancetenew[Query] = "DRE_Lucro_bruto"
			            ),
			                dCalendario[data] = UltimoMesTrimestre
			    )
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 881aacef-1983-4d59-9aa1-1b82a126aa6c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	/// calcula a margem bruta do mês anterior
	measure MMargem_brutaLM = ```
			
			CALCULATE(
			    Medidas_balancetenew[MMargem_bruta_actual_month],
			    DATEADD(dCalendario[data], -1,MONTH)
			)
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 0501f04b-948f-49d4-ba35-7d83b81f25ff

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MargemBru|ReceitaLiquida = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[MMargem_bruta_actual_month]), 
			            SUMX('Medidas_balancetenew', 
			            'Medidas_balancetenew'[MReceita_Liquida]
			        )
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 317091cb-f878-4282-9ff4-df5ba234e8bc

	measure MargemBruta|ReceitaLiLM = CALCULATE('Medidas_balancetenew'[MargemBru|ReceitaLiquida],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 90115e68-f6c8-45a9-b526-01dd022fc6cf

	measure MMargem_Bruta_ACU = ```
			
			VAR v_margem_ano_civil = IFERROR(
			CALCULATE(
			        [MMargem_bruta],
			        DATESYTD(
			            dCalendario[data]
			        )
			    ), BLANK())
			
			VAR v_margem_selecionado = [MMargem_bruta_selecionado] 
			
			RETURN
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    v_margem_ano_civil,
			    v_margem_selecionado
			)
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 0a62f3de-965d-417a-8794-93ca723338df

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Margem_brutaAcuml_anoAnterior = CALCULATE('Medidas_balancetenew'[MMargem_bruta_actual_month],DATESYTD(dCalendario[data]))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 1aff80a9-4366-4d8a-aa85-22a326f8ee22

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MargemBruta|ReceitaLiacu = CALCULATE('Medidas_balancetenew'[MargemBru|ReceitaLiquida],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0ebbb48e-ece5-4dad-bae7-10b5e546393e

	measure %margemBruAcu|receiliq_acu = DIVIDE([MMargem_Bruta_ACU], [MReceita_Liquida_ACU])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f1326235-d119-4bd3-ac31-00535671a27f

	measure MMargem_Bruta_acu_LY = ```
			
			VAR v_margem_acu_LY =
			IFERROR(
			    CALCULATE(
			    TOTALYTD(
			    [MMargem_bruta],
			    SAMEPERIODLASTYEAR(dCalendario[data])
			    )
			), BLANK())
			
			VAR v_margem_acu_selecionado_LY =
			IFERROR(
			    CALCULATE(
			    [MMargem_Bruta_ACU],
			    SAMEPERIODLASTYEAR(dCalendario[data]),
			    ALL(dCalendario)
			), BLANK())
			
			RETURN
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    v_margem_acu_LY,
			    v_margem_acu_selecionado_LY
			)
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 8e5bd139-7151-4a2f-8c9b-a4cf8003f929

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure %MargemB_acu_LY|receita_liq_acu_LY = ```
			
			CALCULATE(
			DIVIDE(
			    SUMX('Medidas_balancetenew',
			    'Medidas_balancetenew'[MMargem_Bruta_acu_LY]), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[MReceita_Liquida_Acumulada_LY])))
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 10f6286f-a262-4c37-a5b0-06ad09a11aa0

	measure rresultado_operacional = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			    RETURN
			CALCULATE(
			        SUM(
			            balancetenew[vlr]
			        ),
			        FILTER(
			                balancetenew,
			                balancetenew[Query] = "DRE_LO_antes_res_financeiro"
			            ),
			            dCalendario[data] >= UltimoMesTrimestre && 
			            dCalendario[data] <= UltimoDiaTrimestre
			            
			    )
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 1aa48d9b-35aa-458f-9599-fcb4858d564a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure rresultado_operacionalLM = CALCULATE('Medidas_balancetenew'[rresultado_operacional],DATEADD(dCalendario[data],-1,MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: c57aa2b8-c466-4207-8337-cbebaeb0ae0c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure despesaope = ```
			SUMX(FILTER(balancetenew, balancetenew[Query] in {
			    "DRE_Desp_Operacionais_Despesas_comerciais",
			    "DRE_Desp_Operacionais_Despesas_com_pessoal_Salarios_ordenados"
			,"DRE_Desp_Operacionais_Despesas_com_pessoal_Beneficios"
			,"DRE_Desp_Operacionais_Despesas_com_pessoal_Impostos"
			,"DRE_Desp_Operacionais_Despesas_com_pessoal_Provisoes"
			,"DRE_Desp_Operacionais_Despesas_administrativas"
			,"DRE_Desp_Operacionais_Despesas_com_Ocupacao"
			,"DRE_Desp_Operacionais_Despesas_com_depreciacao"
			,"DRE_Desp_Operacionais_Despesas_tributarias"
			,"DRE_Desp_Operacionais_Outras_despesas_operacionais"
			,"DRE_Desp_Operacionais_Outras_receitas_operacionais"
			}
			), 
			balancetenew[vlr]
			) * -1
			```
		formatString: #,0
		lineageTag: 331c0e65-554d-4a21-b466-fb2471593be7

	measure rresultado_operacional_ACU = ```
			
			VAR vresultadooperacional = 
			CALCULATE(
			        SUMX(
			        FILTER(
			                balancetenew,
			                balancetenew[Query] = "DRE_LO_antes_res_financeiro"
			            ), 
			            balancetenew[vlr]),
			            DATESYTD(dCalendario[data])
			        )
			
			 RETURN            
			IF (
			    SELECTEDVALUE(d_clientes_time[tipo_analise], BLANK()) = "Ano Civil",
			        vresultadooperacional,
			    Medidas_balancetenew[rresultado_operacional_selecionado_normal_card]
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 4d5997fe-3bc6-4840-bdee-cdbee2f751c0

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure rresultado_operacional_ACU_LY = ```
			
			//IF (
			//    SELECTEDVALUE(d_clientes_time[tipo_analise], BLANK()) = "Ano Civil",
			//    [RResultado_Operacional_acu_LY_normal_card],
			//    [RResultado_Operacional_selecionado_LY_normal_card]
			//)
			CALCULATE(
			    [rresultado_operacional_ACU],
			    DATEADD(
			        dCalendario[data], -1, YEAR))
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 681dab80-1da4-40df-aa2b-0331acfc4119

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Resultado_Operacional|ReceitaLiquida = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			        SUMX(
			            'Medidas_balancetenew', 
			        'Medidas_balancetenew'[rresultado_operacional]
			        ), SUMX(
			                'Medidas_balancetenew', 
			            'Medidas_balancetenew'[MReceita_Liquida]
			            )
			        ),
			        dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f124b462-af51-4d95-acfe-ec1a346185ed

	measure Resultado_Operacional|ReceitaLiLM =
			
			CALCULATE(
			    'Medidas_balancetenew'[Resultado_Operacional|ReceitaLiquida],
			    DATEADD(
			        dCalendario[data],-1,MONTH
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8b23e052-e8d6-4c0d-a4fb-36ab8107ab59

	measure Resultado_Operacional_ACU_ReceitaLiquida_ACU =
			
			DIVIDE(
			    [rresultado_operacional_ACU],
			    [MReceita_Liquida_ACU_normal_card]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 57b2f302-9f67-4af9-958e-5058de6b4aa0

	measure %Resultado_Op_ACU|Receita_Liq_ACU_LY = ```
			
			DIVIDE(
			    SUMX(
			        'Medidas_balancetenew', 
			        'Medidas_balancetenew'[rresultado_operacional_ACU_LY]
			        ), 
			        SUMX('Medidas_balancetenew', 
			        'Medidas_balancetenew'[MReceita_Liquida_Acumulada_LY]
			        )
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9ee8e7db-587b-4399-b03b-6a47a0dceb1a

	measure LLucro_liquido_actual_month = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    CALCULATE(
			        SUMX(FILTER(balancetenew, 
			            balancetenew[Query] = "DRE_Lucro_ou_Prejuizo_liquido"), 
			            balancetenew[vlr]
			        ),
			        dCalendario[data] = UltimoMesTrimestre
			    )
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 4122fdb4-9a41-4567-a712-61f39926ba78

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure LLucro_liquidoLM = CALCULATE('Medidas_balancetenew'[LLucro_liquido_actual_month], DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 7a15eb13-999c-4edd-9b5b-246fc9b1de7e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure LLucro_liquido_ACU =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    CALCULATE(
			        [LLucro_liquidoII],
			        DATESYTD(
			            dCalendario[data]
			        )
			    ),
			    Medidas_balancetenew[LLucro_liquido_selecionado]
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 3fd77b24-ad8d-4dab-b2f7-70396cc62a09

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure LLucro_liquido_acu_LY = ```
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    Medidas_balancetenew[LLucro_Liq_acu_LY_normal_card],
			    Medidas_balancetenew[LLucro_Liq_selecionado_LY_normal_card]
			)
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 30ceba44-fafb-451e-8445-ab385cfc6e68

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'LLucro_liquido | ReceitaLiquida' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(    
			    DIVIDE(
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[LLucro_liquido_actual_month]
			            ), 
			            SUMX('Medidas_balancetenew', 
			            'Medidas_balancetenew'[MReceita_Liquida]
			        )
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5bd46b09-ff0f-4f85-abef-f42a1611e811

	measure '%LLucro_liquido | ReceitaLiLM' = CALCULATE('Medidas_balancetenew'[LLucro_liquido | ReceitaLiquida], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c5270017-a8b6-4f8f-97a0-84d59e0007a9

	measure LLucro_liquido_Acu_ReceitaLiq_Acu = DIVIDE(SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[LLucro_liquido_ACU]), SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[MReceita_Liquida_ACU]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0fb2a090-bfa2-4ad2-9561-168c68c104bc

	measure %LLucro_liquido_Acu|ReceitaLiq_Acu_LY = ```
			
			CALCULATE(
			DIVIDE(
			    SUMX('Medidas_balancetenew',
			    'Medidas_balancetenew'[LLucro_liquido_acu_LY]), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[MReceita_Liquida_Acumulada_LY])))
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a251e4d2-7282-4687-9e60-00e273d0f3e1

	measure FFaturamento = ```
			
			
			SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "receita bruta"
			        ), 
			        balancetenew[vlr]
			        )
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 62ce5da9-2467-4aa5-9303-04f66a906c6b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure FFaturamentoLM = CALCULATE('Medidas_balancetenew'[FFaturamentoII], DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 765e4400-1ee6-4dea-92fa-4422d73e8156

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure FFaturamento_ACU = CALCULATE([FFaturamento], DATESYTD(dCalendario[data]))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: b1276581-aec4-4ccf-beee-8ca3a8be6dac

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MReceita_bruta_acu_LY =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    CALCULATE(
			    [MReceita_Bruta_acu_LY_normal_card]),
			    CALCULATE(
			    [MReceita_Bruta_selecionado_LY_normal_card])
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 416c0cef-2324-40d8-889f-210fc9672d43

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure CCusto_actual_month = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    SUMX(
			    FILTER(
			        balancetenew, 
			                balancetenew[Query] = "Custo dos Produtos Vendidos" ||
			                balancetenew[Query] = "Custo dos Serviços" ||
			                balancetenew[Query] = "custo_vendas"
			    ), 
			        balancetenew[vlr]
			    ),
			dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 299740d3-7a03-467a-862a-11535b81b95d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure CCustoLM = CALCULATE('Medidas_balancetenew'[CCusto_actual_month], DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 5a1c9e8f-1f3b-4492-9c65-911b48149292

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure CCusto_ACU = ```
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			CALCULATE(
			    /*SUMX(
			    FILTER(
			        balancetenew, 
			                balancetenew[Query] = "Custo dos Produtos Vendidos" ||
			                balancetenew[Query] = "Custo dos Serviços" ||
			                balancetenew[Query] = "custo_vendas"
			    ), 
			        balancetenew[vlr]
			    )*/
			    [CCusto], 
			    DATESYTD(dCalendario[data]
			    )
			),
			[CCusto_selecionado_normal_card]
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 50556b19-3c4f-4a01-a22f-6411f392a35f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure CCusto_acu_LY =
			
			CALCULATE(
			    [CCusto_ACU],
			    DATEADD(
			        dCalendario[data],
			        -1,
			        YEAR
			    )
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 2dc11224-4e34-48fb-aa61-f1e875f1ef90

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure CCusto|ReceitaLiquida = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[CCusto_actual_month]), 
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[MReceita_Liquida]
			            )
			        ),
			    dCalendario[data] = UltimoMesTrimestre
			) *-1
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 16e371f0-9cd4-40eb-90ab-bb1d178541ab

	measure CCusto|ReceitaLiLM = CALCULATE('Medidas_balancetenew'[CCusto|ReceitaLiquida],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b43d6673-13d5-418c-80c3-4501c113c663

	measure %ccustoAcu_receiliq_acu = ```
			
			CALCULATE(
			DIVIDE(
			    SUMX('Medidas_balancetenew',
			    'Medidas_balancetenew'[CCusto_ACU]), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[MReceita_Liquida_ACU]))) *-1
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e93878e2-83f5-4115-ac85-07112f059008

	measure %CCustoAcu_receita_bruta_acu_LY = ```
			
			CALCULATE(
			DIVIDE(
			    SUMX('Medidas_balancetenew',
			    'Medidas_balancetenew'[CCusto_acu_LY] *-1), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[MReceita_Bruta_Acumulada_LY])))
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bfdb6fcc-1574-4707-8516-ef97b2bd872f

	measure %CCustovsanterior = DIVIDE('Medidas_balancetenew'[CCusto_actual_month] - 'Medidas_balancetenew'[CCustoLM],'Medidas_balancetenew'[CCustoLM])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9d41bb21-82c1-434f-b71e-22ec7d467958

	measure %MMargemBrutvsanterior = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    CALCULATE(
			    DIVIDE(
			        
			        'Medidas_balancetenew'[MMargem_bruta_actual_month] - 'Medidas_balancetenew'[MMargem_brutaLM],
			       'Medidas_balancetenew'[MMargem_brutaLM]
			        ),
			        dCalendario[data] = UltimoMesTrimestre
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b97c15ca-4853-44c1-8f71-ea4b262c0730

	measure %LLucroLiquidovsanterior = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    CALCULATE(
			        DIVIDE(
			            'Medidas_balancetenew'[LLucro_liquido_actual_month] - 'Medidas_balancetenew'[LLucro_liquidoLM],
			            'Medidas_balancetenew'[LLucro_liquidoLM]
			        ),
			    dCalendario[data] = UltimoMesTrimestre
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f077e96f-89f9-4cb5-a583-c9ec56a12e48

	measure DDespesaADM = ```
			
			VAR v_desp_adm =
			SUMX(
			FILTER(balancetenew,
			balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_administrativas"), balancetenew[vlr])
			
			VAR v_desp_ocupacao = 
			SUMX(
			    FILTER(balancetenew,
			balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Ocupacao"), balancetenew[vlr])
			
			VAR v_desp_depreciacao =
			SUMX(
			    FILTER(balancetenew,
			balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao"), balancetenew[vlr])
			
			VAR despesas_agrologica =
			SUMX(
			    FILTER(balancetenew,
			balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Utilidades_Servicos" ||
			balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Servicos_Profissionais" ||
			balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Comunicacao" ||
			balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Viagens_Estadia" ||
			balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_Bancarias" ||
			balancetenew[Query] = "DRE_Desp_Operacionais_Despesass_com_Outras_Provisoes"
			), balancetenew[vlr])
			RETURN
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[cnpj]) = "07134550000142",        
			v_desp_adm + v_desp_depreciacao + v_desp_ocupacao + despesas_agrologica,
			v_desp_adm + v_desp_depreciacao + v_desp_ocupacao
			)
			
			//SUMX(
			//    FILTER(balancetenew,
			//        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_administrativas" || 
			//        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Ocupacao" || 
			//        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao"),
			 //   balancetenew[vlr]
			//)
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 83f68b5f-37a9-4715-a912-36477809b3d2

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaADMLM = ```
			CALCULATE('Medidas_balancetenew'[DDespesaADM], DATEADD(dCalendario[data], -1, MONTH)
			)
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 001353d6-3e19-4c39-8e04-c4ebe087844c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesa_adm_acu = ```
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			CALCULATE([DDespesaADM], 
			DATESYTD(dCalendario[data])
			),
			Medidas_balancetenew[DDespesaADM_selecionado]
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 89334ded-8924-4284-a2c2-f85157216a7a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesa_adm_acu_LY = ```
			
			IF(
			    SELECTEDVALUE(d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    Medidas_balancetenew[ddespesa_adm_acu_LY_normal_card],
			    Medidas_balancetenew[ddespesa_adm_selecionado_LY_normal_card]
			)
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: a71529c5-5b04-43ee-9363-1889bd2b74b1

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaComercial_contratual = ```
			
			
			SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_comerciais" || 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_contratuais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Propaganda_Publicidade" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Frota_Transportes"
			       ), 
			        balancetenew[vlr])
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 5aa4940b-76bc-41d7-8414-99165eb96774

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaComercialLM = ```
			
			COALESCE(
			CALCULATE(
			    'Medidas_balancetenew'[DDespesaComercial_Actual_month], 
			    DATEADD(dCalendario[data], -1, MONTH)
			    ), 0)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: d5ea2f96-5a74-4d90-9d68-690b06adb989

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesa_Comercial_ACU = ```
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    CALCULATE(
			    [DDespesaComercial_contratual], 
			    DATESYTD(dCalendario[data]
			    )
			    ),
			    Medidas_balancetenew[DDespesa_comercial_contrat_selecionado]
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: b78c48db-f759-47df-81d2-1b734c0a8fc7

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesa_com_acu_LY =
			
			COALESCE(
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    Medidas_balancetenew[DDespesa_com_acu_LY_normal_card],
			    Medidas_balancetenew[DDespesa_com_selecionado_LY_normal_card]
			), 0)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 47e6b836-8cd0-4fc0-979e-5cbf1a130bd6

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaPessoal = ```
			SUMX(
			    FILTER(balancetenew,
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Salarios_ordenados" || 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Beneficios" || 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Impostos" || 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Provisoes" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal"
			    ),
			    balancetenew[vlr]
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: fe4ee44c-bb77-413a-b586-a8a8f3a3edbf

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaPessoalLM = ```
			CALCULATE(
			    'Medidas_balancetenew'[DDespesaPessoal],
			    DATEADD(dCalendario[data], -1, MONTH)
			)
			
			
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 43154711-a9ce-4f68-8b9c-194f7302eae1

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesa_com_pessoal_ACU =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			CALCULATE([DDespesaPessoal], DATESYTD(dCalendario[data])),
			Medidas_balancetenew[DDespesa_com_pessoal_selecionado]
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: acf37cb4-5c6f-4181-b110-c9cb6acc14dc

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaPessoal_acu_anoAnterior =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], blank())
			        = "Ano Civil",
			        Medidas_balancetenew[DDespesa_com_pessoal_acu_LY_normal_card],
			        Medidas_balancetenew[DDespesa_com_pessoal_selecionado_LY_normal_card]
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 246f1de0-d642-4dc3-b77f-6d3a48217f9d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesa_outras = ```
			
			    SUMX(
			    FILTER(balancetenew,
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" || 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Outras_despesas_operacionais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Outras_receitas_operacionais"
			    ),
			    balancetenew[vlr]
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: f9060659-6d25-4f62-9808-304a8d61c9c2

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesa_outras_LM = ```
			
			CALCULATE(
			    'Medidas_balancetenew'[DDespesa_outras], 
			    DATEADD(dCalendario[data], -1, MONTH)
			    )
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 2f38a936-cd45-4453-a1f3-77f8fda54be5

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesa_outras_ACU =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			CALCULATE([DDespesa_outras], DATESYTD(dCalendario[data])),
			Medidas_balancetenew[DDespesa_outras_selecionado]
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: ee8031fd-94a6-4c24-a927-39a4d5d0a364

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesa_outras_acu_LY = ```
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    Medidas_balancetenew[DDespesa_outras_acu_LY_normal_card],
			    Medidas_balancetenew[DDespesa_outras_selecionado_LY_normal_card]
			)
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 0458366b-836b-4850-985a-abd1c75c9c50

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DespesaOutros|ReceitaLiquida = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			        SUMX(
			            Medidas_balancetenew, 
			            Medidas_balancetenew[DDespesa_outras]
			            ), 
			            SUMX(Medidas_balancetenew, 
			            Medidas_balancetenew[MReceita_Liquida]
			        )
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 529c5df6-4796-4533-abd2-1092d45d45e8

	measure DespesaOutros|ReceitaLiLM = CALCULATE('Medidas_balancetenew'[DespesaOutros|ReceitaLiquida],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3fba0bd5-cc96-4604-80eb-e1f79267e866

	measure DespesaOutrosAcu_ReceitaLiqAcu = DIVIDE(SUMX('Medidas_balancetenew','Medidas_balancetenew'[DDespesa_outras_ACU]), SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[MReceita_Liquida_ACU]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: dcd87957-4cc4-424f-ab16-8fb18df90f2e

	measure DespesaOutrosAcu_ReceitaLiqAcuAnoAnterior = DIVIDE(SUMX('Medidas_balancetenew','Medidas_balancetenew'[DDespesa_outras_acu_LY]), SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[MReceita_Liquida_Acumulada_LY]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a5a93651-f331-4a9a-9c0a-154434612cbc

	measure DespesaPessoal|ReceitaLiquida = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[DDespesaPessoal]
			            ), 
			            SUMX('Medidas_balancetenew', 
			            'Medidas_balancetenew'[MReceita_Liquida]
			        )
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ac6cd40a-9ea3-4f76-8e4e-6ba2237a098c

	measure DespesaPessoal|ReceitaLiLM = CALCULATE('Medidas_balancetenew'[DespesaPessoal|ReceitaLiquida], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3fca38d8-0815-4c5e-ab48-13f8d2341bb3

	measure despesaPessoalAcu_receiliq_acu = DIVIDE(SUMX('Medidas_balancetenew','Medidas_balancetenew'[DDespesa_com_pessoal_ACU]), SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[MReceita_Liquida_ACU]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9532e259-3e56-4907-9dfb-be63a75f5586

	measure despesaPessoalAcu_receiliq_acuAnoanterior = DIVIDE(SUMX('Medidas_balancetenew','Medidas_balancetenew'[DDespesaPessoal_acu_anoAnterior]), SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[MReceita_Liquida_Acumulada_LY]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7fbaca59-8663-405d-b0fa-0cf87370c8c6

	measure DespesaComercial|ReceitaLiquida = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[DDespesaComercial_Actual_month]
			
			        ), 
			            SUMX('Medidas_balancetenew', 
			            'Medidas_balancetenew'[MReceita_Liquida_actual_month]
			            )
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 36dac576-98f4-49fd-92f0-2ce25e9d95f4

	measure DespesaComercial|ReceitaLiLM =
			
			COALESCE(
			    CALCULATE('Medidas_balancetenew'[DespesaComercial|ReceitaLiquida],DATEADD(dCalendario[data],-1,MONTH)), "0%")
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3a91f2c0-0d65-475a-89a5-0b5f91a0f5bf

	measure DespesaComercialAcu_receiliq_acu = DIVIDE(SUMX('Medidas_balancetenew','Medidas_balancetenew'[DDespesa_Comercial_ACU]), SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[MReceita_Liquida_ACU]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d7cc7850-84f3-4abc-8975-0c737eecacf5

	measure DespesaComercialAcu_receiliq_acuAnoanterior = DIVIDE(SUMX('Medidas_balancetenew','Medidas_balancetenew'[DDespesa_com_acu_LY]), SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[MReceita_Liquida_Acumulada_LY]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f60f04d5-9a30-4a3f-aa0d-75a25e6f20c5

	measure DespesaADM|ReceitaLiquida = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			DIVIDE(
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[DDespesaADM]), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[MReceita_Liquida])
			),
			dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: eeb42223-4fe4-4b9d-9688-3a6b6f0f8877

	measure DespesaADM|ReceitaLiquidaLM = CALCULATE('Medidas_balancetenew'[DespesaADM|ReceitaLiquida],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ef4ed9b2-0ab1-44c4-bb57-8b4286f3d6d2

	measure DespesaADMAcu_receiliq_acu = DIVIDE(SUMX('Medidas_balancetenew','Medidas_balancetenew'[DDespesa_adm_acu]), SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[MReceita_Liquida_ACU]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 69c840f6-41df-4011-858a-60344ddcc16e

	measure DespesaADMAcu_receiliq_acuAnoanterior = DIVIDE(SUMX('Medidas_balancetenew','Medidas_balancetenew'[DDespesa_adm_acu_LY]), SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[MReceita_Liquida_Acumulada_LY]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: fb8f22c3-2952-43bd-b893-c1339bbdf9bf

	measure %DDespesaADMvsanterior = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			    'Medidas_balancetenew'[DDespesaADM_actual_month teste] - 'Medidas_balancetenew'[DDespesaADM_MesAnterior_tabela],
			    'Medidas_balancetenew'[DDespesaADM_MesAnterior_tabela]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2a6cba92-5dc6-47c8-91e9-6c93624e7949

	measure %DespesaPessoalvsanterior = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			    'Medidas_balancetenew'[DDespesaPessoal_actual_month] - 'Medidas_balancetenew'[DDespesaPessoal_MesAnterior],
			    'Medidas_balancetenew'[DDespesaPessoal_MesAnterior]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 74db2897-47c0-4b0f-b07b-bfab7717ab80

	measure %DDespComercialvsanterior = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			DIVIDE(
			    'Medidas_balancetenew'[DDespesaComercial_contratual] - 
			    'Medidas_balancetenew'[DDespesaComercialLM],
			    'Medidas_balancetenew'[DDespesaComercialLM]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 712db1ac-7b4f-4826-a9f2-c8d56c004e9e

	measure %DDespOutrosvsanterior = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE( 
			        DIVIDE(
			            'Medidas_balancetenew'[DDespesa_outras] - 
			            'Medidas_balancetenew'[DDespesa_outras_LM],
			            'Medidas_balancetenew'[DDespesa_outras_LM]
			        ),
			        dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5e5a4dc1-01f2-4216-abe1-de3645c0103a

	measure SomaAtivCircu = SUMX(FILTER(balancetenew, balancetenew[Query] = "BL_ATCIR_soma"), balancetenew[vlr])
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: c9b03dbf-91d9-485f-b310-59098c55a67e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure SomaAtivCircuLM = ```
			
			CALCULATE(
			    'Medidas_balancetenew'[SomaAtivCircu_Actual_Month], 
			    DATEADD(dCalendario[data], -1, MONTH
			    )
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 7c2f07fe-328e-49d4-aec2-d0af88101724

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure SomaAtivCircu_ACU = CALCULATE([SomaAtivCircu], DATESYTD(dCalendario[data]))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: c2989543-0799-46a5-b05d-54fcfcf4df0f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure SomaAtivCircu_acu_anoAnterior = CALCULATE([SomaAtivCircu], DATESYTD(SAMEPERIODLASTYEAR(dCalendario[data])))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: adf6e74c-76e1-4ce0-b123-5ee480064632

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure SomaAtivNCirculante = SUMX(FILTER(balancetenew, balancetenew[Query] = "BL_ATNCIR_soma"), balancetenew[vlr])
		formatString: 0
		lineageTag: 041393e9-c7f3-492f-9d3a-8592fab81ff5

	measure SomaAtivNCirculanteLM = CALCULATE('Medidas_balancetenew'[SomaAtivNCirculante], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0
		lineageTag: 7796080a-bc3b-4ea2-b6bb-fee9e0524778

	measure SomaAtivNCirculante_ACU = CALCULATE([SomaAtivNCirculante], DATESYTD(dCalendario[data]))
		formatString: 0
		lineageTag: d155c077-7a44-4c99-a568-3d6bc11d5287

	measure SomaAtivNCirculante_acu_anoAnterior = CALCULATE([SomaAtivNCirculante], DATESYTD(SAMEPERIODLASTYEAR(dCalendario[data])))
		formatString: 0
		lineageTag: 9f9c6f27-2523-47f6-9ee0-68e27d7ff589

	measure totativo = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			        CALCULATE(
			            SUMX('Medidas_balancetenew', 
			            'Medidas_balancetenew'[SomaAtivCircu]) +  
			            SUMX('Medidas_balancetenew', 
			            'Medidas_balancetenew'[SomaAtivNCirculante]
			        ),
			    dCalendario[data] = UltimoMesTrimestre
			 )
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: e9ec5d2c-e482-4121-a08e-a53f5781a392

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure atvcircu|totAtivo = ```
			
			VAR selected_date = CALCULATE(
			                    MAX('balancetenew'[data]), 
			                    ALLSELECTED('balancetenew'[data])
			                  )
			RETURN
			    DIVIDE(
			        SUMX(
			            FILTER('balancetenew', 
			                'balancetenew'[data] = selected_date
			            ),
			            'Medidas_balancetenew'[SomaAtivCircu]
			        ),
			        SUMX(
			            FILTER('balancetenew', 
			                'balancetenew'[data] = selected_date
			            ),
			            'Medidas_balancetenew'[totativo]
			        )
			    )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e630c331-5ab0-46e7-9106-f189c37a6231

	measure totAtivoLM = CALCULATE('Medidas_balancetenew'[totativo],DATEADD(dCalendario[data],-1,MONTH))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: c18f99e4-5e09-4699-bba5-1014139b9ad3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure atvcircu|totAtivoACU = DIVIDE(SUMX('Medidas_balancetenew','Medidas_balancetenew'[SomaAtivCircu_ACU]), SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[totalatvACU]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 37e648c4-582c-4fa3-9ce3-97b3bfe31a00

	measure totalatvACU = CALCULATE([totativo], DATESYTD(dCalendario[data]))
		formatString: 0
		lineageTag: 57f5b2cf-26fd-410b-859c-bbd19d65a18a

	measure totAtivo_acu_anoAnterior = CALCULATE([totativo], DATESYTD(SAMEPERIODLASTYEAR(dCalendario[data])))
		formatString: 0
		lineageTag: 3072be60-122a-4803-9095-d0e5e3ccb500

	measure atvcircu|totAativolm = CALCULATE(Medidas_balancetenew[atvcircu|totAtivo], DATEADD(dCalendario[data], -1, MONTH))
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 491a0e1a-b405-4bb9-a55f-222873e2628f

	measure atvcircu|totAtivoAcuAnterior = CALCULATE('Medidas_balancetenew'[atvcircu|totAtivo], DATEADD(dCalendario[data], -1, YEAR))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5d7245ca-c6e6-4ec2-9d83-cc6723195792

	measure BL_ATCIR_caixasequicaixas = SUMX(FILTER(balancetenew, balancetenew[Query] = "BL_ATCIR_caixasequicaixas"), balancetenew[vlr])
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: df093c07-1ba9-48c8-b89a-ef9434442f77

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure BL_ATCIR_Contas_Receber = SUMX(FILTER(balancetenew, balancetenew[Query] = "BL_ATCIR_Contas_Receber"), balancetenew[vlr])
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 0916c3c6-9309-4cd2-9708-8483a37d78f8

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure BL_ATCIR_Estoques = SUMX(FILTER(balancetenew, balancetenew[Query] = "BL_ATCIR_Estoques"), balancetenew[vlr])
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 7ad3b665-37c2-42b8-981f-1587b805301e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure BL_ATCIR_Impostos_recuperar = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			    RETURN
			    CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "BL_ATCIR_Impostos_recuperar"
			        ), 
			        balancetenew[vlr]
			        ),
			        dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre
			        )
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 87fb05f2-d85d-4cce-81fc-ae213b54962b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure BL_ATCIR_Adiantamentos = ```
			
			VAR v_adiantamento =
			SUMX(
			    FILTER(
			        balancetenew, 
			    balancetenew[Query] = "BL_ATCIR_Adiantamentos"), 
			    balancetenew[vlr]
			    )
			
			RETURN
			IF(v_adiantamento = BLANK(), "#,0.00", v_adiantamento)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: d76d708e-3607-47a2-a8db-dea9be1fc791

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ssomapasscircu = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			VAR _passivo_circulante =
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew, 
			                balancetenew[Query] = "BL_PASSCIR_soma"
			                ), 
			                balancetenew[vlr]) *-1,
			dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre)
			
			RETURN
			IF(_passivo_circulante < 0,
			    _passivo_circulante *-1,
			    _passivo_circulante
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 09163919-22cb-42d5-b19b-c4f72c0be4d6

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ssomapasscircuLM = ```
			CALCULATE('Medidas_balancetenew'[ssomapasscircu_actual_month], DATEADD(dCalendario[data], -1, MONTH)) 
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 77332d27-b992-4e80-a5a6-e5e69c669dc1

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ssomapasscircu_ACU = CALCULATE('Medidas_balancetenew'[ssomapasscircu], DATESYTD(dCalendario[data]))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: b99a4f86-9bc5-4672-890e-9f88d6d11c92

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ssomapasscircu_acu_anoAnterior = CALCULATE('Medidas_balancetenew'[ssomapasscircu], DATESYTD(SAMEPERIODLASTYEAR(dCalendario[data])))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 9898fdcb-acf3-4456-98eb-bbfe248b85ff

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure PassCirc|ReceitaLiquida = DIVIDE(SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[ssomapasscircu]), SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[MReceita_Liquida]))
		lineageTag: 75d6b73d-4a34-4173-aa58-4169c3729afb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ssomapassncirculante = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			    RETURN
			
			CALCULATE(
			SUMX(FILTER(balancetenew, balancetenew[Query] = "BL_PASSNCIR_soma"), balancetenew[vlr]) *-1,
			dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: c73c15aa-aa95-424b-afe1-b578369e8869

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ssomapassNcircuLM = CALCULATE('Medidas_balancetenew'[ssomapassncirculante], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0
		lineageTag: c4be7012-2932-4e3f-9f95-ad76b40a815c

	measure ssomapassNcircu_ACU = CALCULATE('Medidas_balancetenew'[ssomapassncirculante], DATESYTD(dCalendario[data]))
		formatString: 0
		lineageTag: 8003065d-e6c0-4605-8055-c22f3c140e87

	measure ssomapassNcircu_acu_anoAnterior = CALCULATE('Medidas_balancetenew'[ssomapassncirculante], DATESYTD(SAMEPERIODLASTYEAR(dCalendario[data])))
		formatString: 0
		lineageTag: cec7314e-0653-4859-aa06-d819ae03f219

	measure totpassivo = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			    RETURN
			    CALCULATE(
			SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[ssomapasscircu]
			    ) +  
			    SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[ssomapassncirculante]
			    ) -
			    SUMX(Medidas_balancetenew, Medidas_balancetenew[ssomaemprestEfinan]
			    ),
			    dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: e2facbb9-b37f-49bf-926c-7ae4de57bee5

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure totPassivoLM = CALCULATE('Medidas_balancetenew'[totpassivo],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0
		lineageTag: 64210413-821f-4c82-adb0-964e5dcacd2c

	measure totalPassACU = CALCULATE('Medidas_balancetenew'[totpassivo], DATESYTD(dCalendario[data]))
		formatString: 0
		lineageTag: 75d866fb-d917-4d24-95ba-5cd54da881e2

	measure totPassivo_acu_anoAnterior = CALCULATE([totpassivo], DATESYTD(SAMEPERIODLASTYEAR(dCalendario[data])))
		formatString: 0
		lineageTag: c3c12c43-f55e-480d-88a0-090802f33146

	measure passcircu|totPass = ```
			VAR selected_date = CALCULATE(
			                    MAX(balancetenew[data]), 
			                    ALLSELECTED(balancetenew[data])
			                  )
			RETURN
			    DIVIDE(
			        SUMX(
			            FILTER('balancetenew', 
			                'balancetenew'[data] = selected_date
			            ),
			            'Medidas_balancetenew'[ssomapasscircu_actual_month]
			        ),
			        SUMX(
			            FILTER('balancetenew', 
			                'balancetenew'[data] = selected_date
			            ),
			            'Medidas_balancetenew'[totpassivo II]
			        )
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5b64f125-a046-4613-8c75-da4fc035e0ae

	measure passcircu|totPasslm = CALCULATE(Medidas_balancetenew[passcircu|totPass], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 00ac540b-9b91-4a7b-b613-64e2198b1bd8

	measure passcircu|totpassACU = DIVIDE(SUMX('Medidas_balancetenew','Medidas_balancetenew'[ssomapasscircu_ACU]), SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[totalPassACU]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d9ca04a8-6895-4db8-aa5c-cde4e14b22c3

	measure passcircu|totPassACUAnterior = CALCULATE('Medidas_balancetenew'[passcircu|totPass], DATEADD(dCalendario[data], -1, YEAR))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: fde45596-f725-4661-a15d-be0f9ff147a8

	measure BL_PASSCIR_Emprestimos_Financiamentos = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "BL_PASSCIR_Emprestimos_Financiamentos"
			    ), 
			        balancetenew[vlr]
			),
			dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: db94a93a-7abb-4e81-8482-de6486a5d65a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure BL_PASSCIR_Fornecedores = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			VAR vfornecedores =
			CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "BL_PASSCIR_Fornecedores"
			    ), 
			    balancetenew[vlr]
			),
			dCalendario[data] = UltimoMesTrimestre
			)
			    RETURN
			IF(
			    vfornecedores < 0, vfornecedores *-1, vfornecedores
			)
			
			```
		formatString: #,0
		lineageTag: 07c3b14c-4f14-4499-b00f-ece9431f5df8

		annotation PBI_FormatHint = {"isDecimal":true}

	measure BL_PASSCIR_Obrigacoes_Tributarias = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias"
			    ), 
			    balancetenew[vlr]
			),
			dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 05f84f2c-f74a-4683-9ee4-cd084ee51b8e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure outras_contas_a_pagar = ```
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			RETURN
			CALCULATE(
			    SUMX(
			        FILTER(balancetenew, 
			        balancetenew[Query] = "BL_PASSCIR_Outras_Contas_Pagar" || 
			        balancetenew[Query] = "BL_PASSNCIR_Outras_Contas_Pagar"
			    ), 
			    
			    balancetenew[vlr]) * -1,
			    dCalendario[data] = UltimoMesTrimestre
			
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: ae2fa85b-1658-4a70-ac4f-16035a0d4a21

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Balanco_Passivo_PL_PASSCIR_Debitos_Diversos = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			SUMX(
			    FILTER
			    (balancetenew, 
			    balancetenew[Query] = "BL_PASSCIR_Debitos_Diversos"), 
			    balancetenew[vlr]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		lineageTag: cce9bd31-6385-48fe-a8bd-31ad1c34c9d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TributosIncidentes = ```
			
			VAR Vtributos =
			SUMX(
			    FILTER(balancetenew, 
			    balancetenew[Query] = "DRE_Imp_Incidentes_Sobre_Receita"), 
			    balancetenew[vlr]
			    )
			
			    RETURN
			    Vtributos
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 4b314415-2ebe-46d1-8b25-72f8ad31e15f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure TributosIncidentesLM = CALCULATE('Medidas_balancetenew'[TributosIncidentes], DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 620d8a71-1616-49c8-b0f8-37a7e66fb7e4

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure TributosIncidentes_ACU = ```
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			        CALCULATE(
			            [TributosIncidentes],
			                DATESYTD(dCalendario[data]
			            )
			        ),
			        Medidas_balancetenew[Tributos_incidentes_selecionado]
			        
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 6a895a42-a829-4e0f-928c-ca47de5f8d52

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure TributosIncidentes_acu_anoAnterior =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    Medidas_balancetenew[Tributos_incidentes_acu_LY_normal_card],
			    Medidas_balancetenew[Tributos_incidentes_selecionado_LY_normal_card]
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 13a5d0f7-9ec7-4019-bd2f-740401b53eff

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure TributosIncidentes|ReceitaBruta = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    COALESCE(
			CALCULATE(
			    DIVIDE(
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[TributosIncidentes]
			        ), 
			            SUMX(
			                Medidas_balancetenew,
			                Medidas_balancetenew[MReceita_bruta]
			            )
			    ),
			                dCalendario[data] = UltimoMesTrimestre
			), 0)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bc83e425-fa5d-4178-95d8-19d1bc4b48fa

	measure TributosIncidentes|ReceitaLiLM = CALCULATE('Medidas_balancetenew'[TributosIncidentes|ReceitaBruta],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0527cf5b-eb24-4abf-a74f-0537979a017f

	measure TributosIncidentes|ReceitaLiquida_ACU = DIVIDE(SUMX('Medidas_balancetenew','Medidas_balancetenew'[TributosIncidentes_ACU]), SUMX(Medidas_balancetenew , Medidas_balancetenew[MReceita_Bruta_ACU]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 860751a8-6963-4abb-a5c7-a479cdd34610

	measure TributosIncidentes|ReceitaLi_acu_anoAnterior = ```
			
			DIVIDE(
			    SUMX(
			        'Medidas_balancetenew',
			    'Medidas_balancetenew'[TributosIncidentes_acu_anoAnterior]
			    ), 
			    SUMX(
			        'Medidas_balancetenew', 
			        'Medidas_balancetenew'[MReceita_Bruta_Acumulada_LY]
			    )
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f58963fb-8957-467c-844d-183a754dbe2b

	measure TributosIncidentesPIS = ```
			SUMX(
			    FILTER(balancetenew, 
			    balancetenew[Query] = "Tributos_Incidentes_PIS"
			   // balancetenew[Query] = "DRE_Imp_Incidentes_Sobre_Receita" && balancetenew[descricao_cliente] 
			   // IN {
			   //     "(-) PIS S/VENDAS",
			   //     "(-) Pis s/ Vendas", 
			   //     "(-) PIS SOBRE VENDAS", 
			   //     "( - ) PIS", 
			   //     "(-) PIS - Receita Antecipada - LP", 
			   //     "(-) Pis S/Comissões", 
			   //     "(-) PIS S/COMISSÃO", 
			   //     "PIS",
			   //      "(-) PIS",
			   //     "() PIS/PASEP",
			   //     "PIS SOBRE EXCLUSÃO DO ICMS DA BASE",
			   //     "PIS SOBRE RECEITAS FINANCEIRAS",
			   //     "PIS S/ DEVOLUCAO DE VENDAS",
			   //     "PIS SOBRE OUTRAS ENTRADAS",
			   //     "(-) PIS SOBRE VENDAS ESTADUAIS",
			   //     "(-) PIS SOBRE ANULAÇÕES DE SERVIÇOS",
			   //     "(-) PIS SOBRE SERVIÇOS PRESTADOS",
			    //    "(-) PIS SOBRE DEVOLUÇÕES DE VENDAS",
			     //   "(-) PIS S/COMISSÕES",
			     //   "(-) PIS SIMPLES NACIONAL",
			     //   "(-) PIS S/SERVIÇOS TERCEIROS",
			    //    "(-) PIS S/ FATURAMENTO",
			     //   "(-)PIS",
			      //  "(-) PIS SOBRE MERCADORIAS A PRAZO",
			      //  "( - ) PIS S/ FATURAMENTO",
			      //  "( - ) PIS"
			      //  }
			      ), 
			    balancetenew[vlr]) * -1
			```
		lineageTag: 8e854a48-d232-4efd-baf1-939fc968001d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TributosIncidentesCofins = ```
			
			CALCULATE(
			    SUM(balancetenew[vlr]), 
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "Tributos_Incidentes_COFINS"
			        //balancetenew[Query] = "DRE_Imp_Incidentes_Sobre_Receita" && 
			        //balancetenew[descricao_cliente] IN {
			        //"(-) COFINS S/VENDAS", 
			        //"(-) Cofins s/ Vendas", 
			        //"(-) COFINS SOBRE VENDAS", 
			        //"( - ) COFINS",
			        //"(-) COFINS",
			        //"(-) COIFNS - Receita Antecipada - LP",
			        //"(-) COFINS - Receita Antecipada - LR",
			        //"(-) Cofins S/Comissões",
			        //"(-) COFINS S/COMISSÃO",
			        //"COFINS",
			        //"() COFINS",
			        //"COFINS SOBRE EXCLUSÃO DO ICMS DA BASE",
			        //"COFINS SOBRE RECEITAS FINANCEIRAS",
			        //"COFINS S/ DEVOLUCAO DE VENDAS",
			        //"COFINS SOBRE OUTRAS ENTRADAS",
			        //"(-) COFINS SOBRE VENDAS ESTADUAIS",
			        //"(-) COFINS SOBRE ANULAÇÕES DE SERVIÇOS",
			        //"(-) COFINS SOBRE SERVIÇOS PRESTADOS",
			        //"(-) COFINS SOBRE DEVOLUÇÕES DE VENDAS",
			        //"(-) COFINS S/VENDAS",
			        //"(-) COFINS S/ FATURAMENTO",
			        //"(-) COFINS S/COMISSÕES",
			        //"(-) COFINS SIMPLES NACIONAL",
			        //"(-) COFINS S/SERVIÇOS TERCEIROS",
			        //"( - ) COFINS - SCPs",
			        //"(-) COFINS SOBRE MERCADORIAS A PRAZO",
			        //"( - ) COFINS S/ FATURAMENTO",
			        //"( - ) COFINS"
			        //}
			    )
			) * -1
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: c39ae1dd-ba25-45ca-8be4-37a170051369

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure TributosIncidentesIcms = ```
			SUMX(
			    FILTER(balancetenew, 
			    balancetenew[Query] = "Tributos_Incidentes_ICMS"
			    //balancetenew[Query] = "DRE_Imp_Incidentes_Sobre_Receita" && balancetenew[descricao_cliente] 
			    //IN {"(-) ICMS S/VENDAS",
			    //"(-) Icms s/ Vendas", 
			    //"(-) ICMS SOBRE VENDAS",
			    // "( - ) ICMS sobre Vendas",
			    //"(-) Icms s/Vendas",
			    //"(-) Icms S/Venda",
			    //"(-) ICMS S/ DEVOLUCAO DE VENDA",
			    //"ICMS S/ DEV. DE VENDAS",
			    //"(-) ICMS SOBRE DEVOLUÇÕES DE VENDAS",
			    //"(-)ICMS S/ DEV DE COMPRAS",
			    //"ICMS PARTILHA",
			    //"ICMS",
			    //"(-) ICMS",
			    //"() DIFAL Entrada",
			    //"(-) ICMS DIFAL/FCP",
			    //"() ICMS",
			    //"( - ) ICMS Subst Tributaria",
			    //"( + ) ICMS",
			    //"(-) ICMS EC 87/15 - fora SP",
			    //"(-) ICMS SUB. TRIBUTARIA S/ VENDAS",
			    //"(-) REDUÇÃO DA BASE DO ICMS",
			    //"REDUÇÃO DA BASE DO ICMS",
			    //"ICMS SOBRE OUTRAS SAÍDAS",
			    //"(-)Estorno Crédito ICMS e-PTA-RE 45.000",
			    //"Incentivo Fiscal ICMS e-PTA-RE 45.00001",
			    //"(-) ICMS SOBRE VENDAS ESTADUAIS",
			    //"(-) ICMS SOBRE ANULAÇÕES",
			    //"(-) ICMS SOBRE SERVIÇO",
			    //"ICMS - Outros Débitos",
			    //"(-)ICMS",
			    //"(-) ICMS SOBRE MERCADORIAS A PRAZO"
			    //}
			    ), 
			    balancetenew[vlr]) * -1
			```
		lineageTag: c9c13e2c-b1c0-4ce4-8456-f20c99afca07

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ATCIR_Estoques = ```
			
			CALCULATE(
			    SUM(balancetenew[vlr]),
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "BL_ATCIR_Estoques" &&
			        balancetenew[data] = MAX(balancetenew[data])
			    )
			)
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: da2f75ec-7d09-4208-a9c9-cf9c3b5948f0

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ATCIR_EstoquesLM = CALCULATE('Medidas_balancetenew'[ATCIR_Estoques], DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 6d99073f-f663-4710-8a56-6e27d1b76a89

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ATCIR_Estoques_ACU = ```
			CALCULATE([ATCIR_Estoques], DATESYTD(dCalendario[data]))
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: e4249671-9b57-4847-a20b-e3e35b6c8439

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ATCIR_Estoques_acu_anoAnterior = CALCULATE([ATCIR_Estoques], DATESYTD(SAMEPERIODLASTYEAR(dCalendario[data])))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 6041f098-361c-4838-ab7b-b402c0291565

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Estoques|SomaAtivCircu = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[ATCIR_Estoques]), 
			        SUMX('Medidas_balancetenew', 
			        'Medidas_balancetenew'[SomaAtivCircu]
			        )
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d9e32941-a077-4a1a-a2e6-9aa039abf13a

	measure Estoques|SomaAtivCircuLM = CALCULATE('Medidas_balancetenew'[Estoques|SomaAtivCircu], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 84453ac0-6b1c-490b-a42e-7724a81f2234

	measure estoquesAcu_somaAtivCircuAcu = DIVIDE(SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[ATCIR_Estoques_ACU]), SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[SomaAtivCircu_ACU]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2fc26c87-2871-4275-b450-029832aaa8c0

	measure estoquesAcu_somaAtivCircuAcuAnoanterior = ```
			
			DIVIDE(
			    SUMX(
			        'Medidas_balancetenew', 
			        'Medidas_balancetenew'[ATCIR_Estoques_acu_anoAnterior]), 
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[SomaAtivCircuLY]
			        )
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1a08e47e-eb19-421e-ba31-71ea061fc048

	measure PASSCIR_Obrigacoes_Trabalhistas = ```
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew, 
			            balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Trabalhistas"
			        ), 
			        balancetenew[vlr]
			    ),
			    FILTER(ALL(dCalendario), dCalendario[data] = MAX(dCalendario[data]))
			)
			
			
			```
		lineageTag: 481cf2e9-007c-4d7d-80fa-7a11b375575c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PASSCIR_Obrigacoes_TrabalhistasLM =
			
			CALCULATE(
			    'Medidas_balancetenew'[PASSCIR_Obrigacoes_Trabalhistas_Actual_Month],
			    DATEADD(
			        dCalendario[data], -1, MONTH
			    )
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 63ac944d-4d16-46b5-ae6d-8af1d63711a7

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure PASSCIR_Obrigacoes_Trabalhistas_ACU = CALCULATE([PASSCIR_Obrigacoes_Trabalhistas], DATESYTD(dCalendario[data]))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 8c968cf1-8816-48c3-a1ed-b28de8a5fbb3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure PASSCIR_Obrigacoes_Trabalhistas_acu_LY = ```
			
			CALCULATE(
			    [PASSCIR_Obrigacoes_Trabalhistas_Actual_Month], 
			    DATESYTD(
			        SAMEPERIODLASTYEAR(dCalendario[data])))
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 3508bcfe-3325-4fd0-8b0c-c1c2d5c1ca57

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure PASSCIR_Obrigacoes_Trabalhistas|SomaPassCircu = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    
			DIVIDE(
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[PASSCIR_Obrigacoes_Trabalhistas_Actual_Month]), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[ssomapasscircu]
			    )
			),
			dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 571d9957-4857-472a-a1aa-15270126b0e4

	measure PASSCIR_Obrigacoes_Trabalhistas|SomaPassCircuLM = CALCULATE('Medidas_balancetenew'[PASSCIR_Obrigacoes_Trabalhistas|SomaPassCircu], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 40d25035-0cb6-4bc6-bc21-1470bcb19551

	measure passcirObrigacoesTrabalhistasAcu_somaPassCircuAcu = DIVIDE(SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[PASSCIR_Obrigacoes_Trabalhistas_ACU]), SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[ssomapasscircu_ACU]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 66d353b1-8a43-4192-9add-fa1e0ac649c6

	measure passcirObrigacoesTrabalhistasAcu_somapassAcuAnoanterior = ```
			
			DIVIDE(
			    SUMX(
			        'Medidas_balancetenew', 
			        'Medidas_balancetenew'[PASSCIR_Obrigacoes_Trabalhistas_acu_LY]), 
			        SUMX('Medidas_balancetenew', 
			        'Medidas_balancetenew'[ssomapasscircuLY]
			    )
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 10dbb0f3-f3ea-4ae7-bcf0-fee1744657b7

	measure ccapit_giro = ```
			
			VAR vativo = [SomaAtivCircu]
			VAR vpassivo = IF(
			    [ssomapasscircu] < 0, 
			    ([ssomapasscircu]*-1), 
			    [ssomapasscircu])
			
			RETURN
			vativo - vpassivo
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 648de85a-8b30-4a1b-a048-7226cfc17fdd

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure caixasequicaixas = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    COALESCE(IF(
			        CALCULATE(
			            SUMX(
			                FILTER(
			                    balancetenew,
			                    balancetenew[Query] = "BL_ATCIR_caixasequicaixas"
			                ),
			                balancetenew[total_mes_atual]
			            ),
			            dCalendario[data] = UltimoMesTrimestre
			        ) < 0,
			        CALCULATE(
			            SUMX(
			                FILTER(
			                    balancetenew,
			                    balancetenew[Query] = "BL_ATCIR_caixasequicaixas"
			                ),
			                balancetenew[total_mes_atual]
			            ),
			            dCalendario[data] = UltimoMesTrimestre
			        ) *-1, 
			        CALCULATE(
			            SUMX(
			                FILTER(
			                    balancetenew, 
			                    balancetenew[Query] = "BL_ATCIR_caixasequicaixas"
			                    ), 
			                    balancetenew[vlr]
			                    ),
			            dCalendario[data] = UltimoMesTrimestre
			        )
			), 0)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 72c85706-cdfc-46d8-9b62-b145743da200

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Emprestimos_Financiamentos = SUMX(FILTER(balancetenew, balancetenew[Query] = "BL_PASSCIR_Emprestimos_Financiamentos"), balancetenew[vlr])*-1
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 806ba64e-ea6e-4672-808e-d872bfc311c0

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure aaconew = ```
			
			[SomaAtivCircu_Actual_Month] - 
			[caixasequicaixas]
			```
		lineageTag: 6b6c989d-ef20-497e-bd62-20c7bdedb419

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ppconew =
			
			VAR _passivo_circ = IF(
			    [ssomapasscircu] < 0,
			    [ssomapasscircu] *-1,
			    [ssomapasscircu]
			)
			VAR _emprestimos = IF(
			    [Emprestimos_Financiamentos] < 0,
			    [Emprestimos_Financiamentos] *-1,
			    [Emprestimos_Financiamentos]
			)
			
			RETURN
			_passivo_circ  - _emprestimos
		lineageTag: da032fd4-0963-44f0-8529-c9a2df7c0a76

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure NNecessidadeCPTgiro = ```
			
			VAR _ativo = [aaconew] 
			VAR _passivo = [ppconew]
			
			RETURN
			_ativo - _passivo
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 1cbb1cba-630d-4f4c-85ca-597bffd0281d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'lliquidez imediata' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			DIVIDE(
			    'Medidas_balancetenew'[caixasequicaixas],
			    'Medidas_balancetenew'[ssomapasscircu],0
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00
		lineageTag: 3ed4dc69-9ece-4882-889c-ce64147e64d8

	measure LLiquidezImediataLM = CALCULATE('Medidas_balancetenew'[lliquidez imediata], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0.00
		lineageTag: fdc9cacb-8cd3-4405-bc4d-20795b786585

	measure 'lliquidez corrente' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			DIVIDE('Medidas_balancetenew'[SomaAtivCircu],
			'Medidas_balancetenew'[ssomapasscircu],0
			),
			dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00
		lineageTag: e3090d66-6467-4f83-97b4-d95199f49f78

	measure LLiquidezCorrenteLM = CALCULATE('Medidas_balancetenew'[lliquidez corrente], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0.00
		lineageTag: 37b47f4f-dc58-4d09-ba55-a097ab9db61b

	measure 'lliquidez seca' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			DIVIDE('Medidas_balancetenew'[SomaAtivCircu] - 'Medidas_balancetenew'[ATCIR_Estoques],'Medidas_balancetenew'[ssomapasscircu],0
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00
		lineageTag: fb04e594-aaf9-4106-97f0-d80a32d52234

	measure 'Lliquidez secalm' = CALCULATE('Medidas_balancetenew'[lliquidez seca],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0.00
		lineageTag: 7c521802-75ee-4042-a9f0-681bda887882

	measure 'lliquidez geral' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			(
			    Medidas_balancetenew[totativo] - Medidas_balancetenew[investimentosatvncircu] - Medidas_balancetenew[Imobilizadoatvncircu] - Medidas_balancetenew[Intangivel_atvncircu] - Medidas_balancetenew[Ativo_Direito_Uso] - Medidas_balancetenew[Liq_Geral_Ativo_Diferido]) 
			    / Medidas_balancetenew[totpassivo II],
			dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00
		lineageTag: 7dbc8b64-8bf8-414d-a2fa-8348da92fea2

	measure 'Liq GeralLM' = CALCULATE('Medidas_balancetenew'[lliquidez geral],DATEADD(dCalendario[data],-1,MONTH))
		lineageTag: f152d48b-f84f-4690-8460-5e148d1b2c47

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure patrimonioLiq = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew, 
			            balancetenew[Query] = "BL_PL_Soma"
			        ),
			        balancetenew[vlr]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 9acfe21f-89fb-4d07-a8e8-86342e5d758a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'IInvestimento Total' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    CALCULATE(
			DIVIDE(
			    SUMX('Medidas_balancetenew',
			    'Medidas_balancetenew'[LLucro_liquido_actual_month]), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[totativo]
			        )),
			    dCalendario[data] = UltimoMesTrimestre
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a8b8bc49-f263-49c6-951a-3ef631bc2132

	measure 'IInvestimento TotalLM' = CALCULATE('Medidas_balancetenew'[IInvestimento Total], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 73e9bf2d-a1be-42bc-99e5-a3c9c7f91418

	measure 'PPatrimonio Liquido_retorno_invest' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			        SUMX(
			        'Medidas_balancetenew','Medidas_balancetenew'[LLucro_liquido_actual_month]), 
			            SUMX('Medidas_balancetenew', 
			            'Medidas_balancetenew'[patrimonioLiq]
			                )
			            ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 462e26b6-ebb0-43cb-b628-172e4255f0f4

	measure 'PPatrimonio Liquido_LM' = CALCULATE('Medidas_balancetenew'[PPatrimonio Liquido_retorno_invest],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 122cc4f0-750b-40d8-9d1e-4429b25c4929

	measure 'rentabilidade cpt' = ```
			
			DIVIDE(
			    SUMX(
			        'Medidas_balancetenew',
			        'Medidas_balancetenew'[LLucro_liquido_actual_month]), 
			        SUMX('Medidas_balancetenew', 
			        'Medidas_balancetenew'[patrimonioLiq]
			        )
			        )
			```
		lineageTag: 6235e240-46c4-4740-90dc-eab7aad3b8e0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Endividamento total' = ```
			
			DIVIDE(
			(SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[ssomapasscircu] + 'Medidas_balancetenew'[ssomapassncirculante])), 
			'Medidas_balancetenew'[patrimonioLiq])
			
			```
		formatString: #,0.00
		lineageTag: 98f9d256-689c-4a94-be5c-c39bbe28166c

	measure solvencia = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			(
			    0.05 * 'Medidas_balancetenew'[rentabilidade cpt] +
			    1.65 * 'Medidas_balancetenew'[lliquidez geral] +
			    3.55 * 'Medidas_balancetenew'[lliquidez seca] -
			    1.06 * 'Medidas_balancetenew'[lliquidez corrente] -
			    0.33 * 'Medidas_balancetenew'[Endividamento total]
			),
			dCalendario[data] = UltimoMesTrimestre
			)
			
			```
		lineageTag: 9a5dc4b2-c385-4786-9277-0610e6bef384

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AcumuladoCCusto =
			
			VAR MesAtual = MONTH(MAX(balancetenew[data]))
			RETURN
			    SUMX(
			        FILTER(
			            VALUES(balancetenew[data]),
			            MONTH(balancetenew[data]) <= MesAtual
			        ),
			        'Medidas_balancetenew'[CCusto_actual_month]
			    )
		formatString: #,0
		lineageTag: e6efff71-a031-4a54-bcae-94bc8b060bf3

	measure PASSCIR_Fornecedores = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			RETURN
			IF(
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew, 
			                balancetenew[Query] = "BL_PASSCIR_Fornecedores"
			            ), 
			            balancetenew[vlr]
			        ),
			        dCalendario[data] = UltimoMesTrimestre
			    ) < 0,
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew, 
			                balancetenew[Query] = "BL_PASSCIR_Fornecedores"
			            ), 
			            balancetenew[vlr]
			        ),
			        dCalendario[data] = UltimoMesTrimestre
			    ) * -1,
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew, 
			                balancetenew[Query] = "BL_PASSCIR_Fornecedores"
			            ), 
			            balancetenew[vlr]
			        ),
			        dCalendario[data] = UltimoMesTrimestre
			    )
			)
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 13a82aa0-f4aa-4605-a8ca-e97d06c5beca

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Fornecedores liquidos' = ```
			
			/*IF(
			    NOT(ISBLANK(medidas_aginglist[fornecedores_aging]))
			 && [fornecedores_aging] = [PASSCIR_Fornecedores], 
			    medidas_aginglist[fornecedores_aging], 
			    [PASSCIR_Fornecedores]
			)*/
			[PASSCIR_Fornecedores]
			```
		formatString: #,0
		lineageTag: c49a8e8a-83b3-4747-bfa8-455e79f83336

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Compras no ano' = ```
			
			Medidas_balancetenew[CCusto_ACU_normal_card] *-1 + 
			Medidas_balancetenew[ATCIR_Estoques] - 
			Medidas_balancetenew[ATCIR_Estoques_prazos medios]
			```
		formatString: #,0
		lineageTag: 5c33b2fa-6768-4949-b817-0a1a56d50bdc

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Valor_mensal =
			
			VAR vswitch =
			SWITCH(
			    MONTH(MAX(dCalendario[data])),
			    1, 30,
			    2, 60,
			    3, 90,
			    4, 120,
			    5, 150,
			    6, 180,
			    7, 210,
			    8, 240,
			    9, 270,
			    10, 300,
			    11, 330,
			    12, 360
			)
			
			
			RETURN
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    vswitch,
			    [Valor_mensal_selecionado])
		formatString: 0
		lineageTag: def7f5a4-8266-4073-a084-c7222a00bc5e

	measure 'Prazo Médio Contas a Pagar_compras_ano_X_valor mensal' = ```
			Medidas_balancetenew[Fornecedores liquidos] / Medidas_balancetenew[Compras no ano]
			    
			
			```
		formatString: 0
		lineageTag: 07a8317e-9fab-424c-a6e0-92e36c1c804a

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'contas receber' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew, 
			            balancetenew[Query] = "BL_ATCIR_Contas_Receber"
			        ), 
			        balancetenew[vlr]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: #,0
		lineageTag: 7293e263-431e-4713-8b72-95f3ac50c27b

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Vendas no Mês menos devoluções' = [MReceita_bruta] + [deducoes]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cf8fbb57-ec9e-4c4a-8156-bcaddd83e39d

	measure deducoes = ```
			SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "Deduções da Receita Bruta"), 
			        balancetenew[vlr]
			        ) +0
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: d95a8e1a-fe93-4ef5-96a4-5ee7e61969c9

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure deducoesLM = CALCULATE('Medidas_balancetenew'[deducoes], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0
		lineageTag: d976ba0c-f1d0-4268-9399-bb546869038d

	measure 'vendas no mês no menos devLM' = CALCULATE('Medidas_balancetenew'[Vendas no Mês menos devoluções],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0
		lineageTag: 8cb19e85-2193-4d68-8c71-c8f7664f555d

	measure VendasANOMenosDevACU = ```
			[MReceita_Bruta_ACU] - 
			IF([deducoes_ACU] < 0,
			[deducoes_ACU] *-1, [deducoes_ACU])
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f3cc40c7-4c37-48a2-8206-ea4f5e5ffc99

	measure 'Prazo Médio Contas a Receber' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			    Medidas_balancetenew[Contas_receber_prazo_medio], 
			    Medidas_balancetenew[VendasANOMenosDevACU]) * 
			    Medidas_balancetenew[Valor_mensal_prazos_medios]
			    //,    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0
		lineageTag: 9b012767-77de-4c02-84e6-08a44eb9f212

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Prazo Médio do Giro do Estoque' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			    Medidas_balancetenew[ATCIR_Estoques] ,
			    Medidas_balancetenew[CCusto_ACU]) * Medidas_balancetenew[Valor_mensal_prazos_medios] * -1
			    //, dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0
		lineageTag: d498d719-820b-4f29-9cab-0591e782e29a

		annotation PBI_FormatHint = {"isDecimal":true}

	measure PrazomédioPagamentoLM =
			
			CALCULATE(Medidas_balancetenew[Prazo Médio Contas a Pagar],
			DATEADD(dCalendario[data],-1,MONTH)
			
			)
		formatString: 0
		lineageTag: 840630c3-3703-4a2e-9a5a-96fad15a7ed3

		annotation PBI_FormatHint = {"isDecimal":true}

	measure PrazomédiorRecebimentoLM = CALCULATE(Medidas_balancetenew[Prazo Médio Contas a Receber],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0
		lineageTag: 311d8307-4dfa-49b4-9966-474dccb1c035

		annotation PBI_FormatHint = {"isDecimal":true}

	measure GIRODOESTOQUELM = CALCULATE(Medidas_balancetenew[Prazo Médio do Giro do Estoque],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0
		lineageTag: 59551c3e-a2cc-41a7-8c79-e8690e4f9d1e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Ciclo de Operacional' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			Medidas_balancetenew[Prazo Médio do Giro do Estoque] + medidas_aginglist[prazo_medio_contas_receber_misto_aging_balancete],
			dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0
		lineageTag: 96b3dab6-5d80-46e6-8c8a-273b3b8949b8

		annotation PBI_FormatHint = {"isDecimal":true}

	measure CicloOperacionalLM = CALCULATE(Medidas_balancetenew[Ciclo de Operacional], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0
		lineageTag: cd3a55cd-353d-4a46-8009-197c503ab2ff

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Ciclo Financeiro' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			Medidas_balancetenew[Ciclo de Operacional] -
			Medidas_balancetenew[Prazo Médio Contas a Pagar],
			dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre)
			```
		formatString: 0
		lineageTag: eb924498-4df5-4502-a461-32723b245299

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Ciclo FinanceiroLM' = ```
			
			CALCULATE(
			    'Medidas_balancetenew'[ciclo_financeiro II], 
			    DATEADD(dCalendario[data], -1, MONTH)
			    )
			```
		formatString: 0
		lineageTag: 696c0397-a15c-4dea-ad3d-73791154b122

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Obrigacoes_Tributarias = ```
			
			SUMX(
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" 
			    ),
			    balancetenew[vlr]
			)
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 7eaa61d3-3a2a-45e0-b3a5-368922a70813

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ObrigaTributaLM = CALCULATE('Medidas_balancetenew'[Obrigacoes_Tributarias], DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: d01394f2-497a-4f88-bdef-a3a188006c10

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure SomaAtivCircuLY = ```
			
			CALCULATE(
			    'Medidas_balancetenew'[SomaAtivCircu_Actual_Month], 
			    DATEADD(
			        dCalendario[data], -1, YEAR
			    )
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: cc3c3a1f-d5cb-4d14-bb98-16ca0f334f6c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ATCIR_EstoquesLY = CALCULATE('Medidas_balancetenew'[ATCIR_Estoques], DATEADD(dCalendario[data], -1, YEAR))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 4f617917-3bee-4a1f-992c-52a25e39811a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ssomapasscircuLY = ```
			
			CALCULATE(
			    'Medidas_balancetenew'[ssomapasscircu_actual_month], 
			    DATEADD(
			        dCalendario[data],-1,YEAR))
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: a54667d7-62d7-4876-b330-08cc5115aafa

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure PASSCIR_Obrigacoes_TrabalhistasLY = ```
			
			CALCULATE(
			    'Medidas_balancetenew'[PASSCIR_Obrigacoes_Trabalhistas_Actual_Month],
			    DATEADD(dCalendario[data], -1, YEAR
			    )
			)
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 43cda204-d6c2-4dae-b8d1-152e60b3d4ff

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure LLiquidezImediataLY =
			
			CALCULATE(
			    'Medidas_balancetenew'[lliquidez imediata],
			     DATEADD(dCalendario[data], -1, YEAR))
		lineageTag: dce59489-9e62-4eb9-a913-3bb8fdb9006a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure LLiquidezCorrenteLY = CALCULATE('Medidas_balancetenew'[lliquidez corrente], DATEADD(dCalendario[data], -1, YEAR))
		formatString: 0.00
		lineageTag: 1a469c9d-9777-4326-ab81-f4006b51071c

	measure 'Lliquidez secalY' = CALCULATE('Medidas_balancetenew'[lliquidez seca],DATEADD(dCalendario[data],-1,YEAR))
		formatString: 0.00
		lineageTag: 8dbbed12-c423-4132-bcce-91aeac985f16

	measure 'Liq GeralLY' = CALCULATE('Medidas_balancetenew'[lliquidez geral],DATEADD(dCalendario[data],-1,YEAR))
		lineageTag: f2c0518a-67eb-4090-9a81-59564dc218ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure EEBITDA_actual_month = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			RETURN
			//CALCULATE(
			//Medidas_balancetenew[rresultado_operacional] -
			//Medidas_balancetenew[Ebitda_despesa_depreciacao],
			CALCULATE(
			        SUMX(FILTER(
			        balancetenew,
			        balancetenew[Query] = "DRE_Ebitda"),
			        balancetenew[vlr]
			),
			
			dCalendario[data] = UltimoMesTrimestre
			)
			
			
			
			
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 8debe3bf-cf01-44db-884a-ceb46edee1ca

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Ebitda_Lucro_ou_Prejuizo_liquido = SUMX(FILTER(balancetenew, balancetenew[Query] = "Ebitda_Lucro_ou_Prejuizo_liquido"), balancetenew[vlr])
		formatString: 0
		lineageTag: 246e00e8-4616-434a-aac9-5dd3d9a01a97

	measure Ebitda_receita_financeira = ```
			SUMX(FILTER(balancetenew, balancetenew[Query] = "Ebitda_receita_financeira"), balancetenew[vlr])
			
			```
		formatString: 0
		lineageTag: 3f12440c-5874-4c39-992c-1321b8aef938

	measure Ebitda_despesa_financeira = ```
			
			SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "DRE_Despesa_financeira"), 
			        balancetenew[vlr]
			        )*-1 -
			        [TotalJuros]
			```
		formatString: #,0
		lineageTag: 6d2cc681-1678-4933-9589-19b43f2d5bd8

	measure Ebitda_despesa_depreciacao = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			RETURN
			CALCULATE(
			SUMX(
			    FILTER(balancetenew, 
			    balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao"), 
			    balancetenew[vlr]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: #,0
		lineageTag: 5d14557b-c4a7-4a2b-9e29-17abd965792a

	measure Ebitda_imposto_renda = SUMX(FILTER(balancetenew, balancetenew[Query] = "Ebitda_imposto_renda"), balancetenew[vlr])
		formatString: 0
		lineageTag: d00c7992-ebc4-430c-8c4f-6d6546bd914b

	measure Ebitda_contribuicao_social = SUMX(FILTER(balancetenew, balancetenew[Query] = "Ebitda_contribuicao_social"), balancetenew[vlr])
		formatString: 0
		lineageTag: fbda58c3-5f95-462c-94a0-7c134472a2be

	measure Ebitda_Despesas_receitas_nao_ope = SUMX(FILTER(balancetenew, balancetenew[Query] = "Ebitda_Despesas_receitas_nao_ope"), balancetenew[vlr])
		formatString: 0
		lineageTag: 1b766672-e075-4f56-8fd6-2ede9730110e

	measure EEbitdaLM = ```
			CALCULATE(
			    Medidas_balancetenew[EEBITDA_actual_month], 
			    DATEADD(dCalendario[data], -1, MONTH)
			    )
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: f6e17c80-552e-447f-b3b0-42985c7adb3d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure EEbitda_ACU = ```
			
			VAR ebitda_acu_anocivil =
			CALCULATE(
			    SUMX(FILTER(
			        balancetenew,
			        balancetenew[Query] = "DRE_Ebitda"),
			        balancetenew[vlr]), DATESYTD(dCalendario[data])
			)
			
			
			RETURN
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise],
			        BLANK()
			    ) = "Ano Civil",
			    ebitda_acu_anocivil,
			    Medidas_balancetenew[EEbitda_selecionado]
			)
			    
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: d5773be8-0bed-4fdf-bee5-82336888da97

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Ebitda_acu_anoAnterior =
			
			CALCULATE(
			    [EEbitda_ACU_IF],
			    DATEADD(
			        dCalendario[data], -1, YEAR
			    )
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 18b638d9-6cd7-4069-aea6-76323216f864

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Ebitda|ReceitaLiquida = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    COALESCE(
			CALCULATE(
			        DIVIDE(
			             SUMX(Medidas_balancetenew, 
			                Medidas_balancetenew[EEBITDA_actual_month]), 
			             SUMX('Medidas_balancetenew', 
			                'Medidas_balancetenew'[MReceita_Liquida])
			                ), dCalendario[data] = UltimoMesTrimestre), 0)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9bde1eff-c382-46ab-a5dd-7f44271b90df

	measure Ebitda|ReceitaLiLM =
			
			CALCULATE(
			    'Medidas_balancetenew'[Ebitda|ReceitaLiquida],
			    DATEADD(dCalendario[data],
			    -1,
			    MONTH
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 910fb4c3-2223-4ba2-a3e2-d26b11deb6f5

	measure %EbitdaAcu|receiliq_acu = ```
			
			COALESCE(
			DIVIDE(
			    SUMX('Medidas_balancetenew',
			    'Medidas_balancetenew'[EEbitda_ACU]
			    ), 
			    SUMX(
			        'Medidas_balancetenew', 
			        'Medidas_balancetenew'[MReceita_Liquida_ACU]
			        )
			        ), 0)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f2916e0f-163a-491b-b11c-79db7bfb3bd8

	measure EbitdaAcu_receiliq_acuAnoanterior = ```
			
			VAR vebitda_acu_LY =
			DIVIDE(
			    SUMX(
			        'Medidas_balancetenew',
			        'Medidas_balancetenew'[Ebitda_acu_anoAnterior]), 
			        SUMX('Medidas_balancetenew', 
			        'Medidas_balancetenew'[MReceita_Liquida_Acumulada_LY]
			    )
			)   
			
			RETURN
			IF(
			    ISBLANK(vebitda_acu_LY), 0, vebitda_acu_LY)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b8fd26f1-97a1-40e6-826f-96602d6a8b01

	measure eemprestEFinanc_CP = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    COALESCE(IF(
			        CALCULATE(
			            SUMX(
			                FILTER(
			                    balancetenew,
			                    balancetenew[Query] = "Emprestimos_Financiamentos_Curto_Prazo"
			                ),
			                balancetenew[total_mes_atual]
			            ),
			            dCalendario[data] = UltimoMesTrimestre
			        ) < 0,
			        CALCULATE(
			            SUMX(
			                FILTER(
			                    balancetenew,
			                    balancetenew[Query] = "Emprestimos_Financiamentos_Curto_Prazo"
			                ),
			                balancetenew[total_mes_atual]
			            ),
			            dCalendario[data] = UltimoMesTrimestre
			        ) *-1, 
			        CALCULATE(
			            SUMX(
			                FILTER(
			                    balancetenew,
			                    balancetenew[Query] = "Emprestimos_Financiamentos_Curto_Prazo"
			                ),
			                balancetenew[total_mes_atual]
			            ),
			            dCalendario[data] = UltimoMesTrimestre
			        )
			), 0)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 5f174331-36b4-4c0d-8b7c-ed346f76222d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure eemprestEFinanc_LP = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			   COALESCE(
			    IF(
			CALCULATE(
			            SUMX(
			                FILTER(
			                    balancetenew,
			                    balancetenew[Query] = "Emprestimos_Financiamentos_Longo_Prazo"
			                ),
			                balancetenew[total_mes_atual] +0
			            ),
			            dCalendario[data] = UltimoMesTrimestre
			        ) < 0,
			        CALCULATE(
			            SUMX(
			                FILTER(
			                    balancetenew,
			                    balancetenew[Query] = "Emprestimos_Financiamentos_Longo_Prazo"
			                ),
			                balancetenew[total_mes_atual] +0
			            ),
			            dCalendario[data] = UltimoMesTrimestre
			        ) *-1,
			        CALCULATE(
			            SUMX(
			                FILTER(
			                    balancetenew,
			                    balancetenew[Query] = "Emprestimos_Financiamentos_Longo_Prazo"
			                ),
			                balancetenew[total_mes_atual] +0
			            ),
			            dCalendario[data] = UltimoMesTrimestre
			        )
			), 0)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 588d5f52-8da0-463b-b6ae-e4ab0e69968d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ssomaemprestEfinan =
			
			COALESCE(
			Medidas_balancetenew[eemprestEFinanc_CP] + Medidas_balancetenew[eemprestEFinanc_LP], 0)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 998d1437-9523-4f63-b0ce-ad2008a4a9c3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure TotalJuros = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    COALESCE(
			CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "Juros_Pagos_Sobre_Emprestimos"
			    ),
			    balancetenew[vlr]
			),
			dCalendario[data] = UltimoMesTrimestre
			) *-1, 0)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 1e3e05dc-bbc3-4e4e-82f6-1553d88a0b0f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure emprest_CP|emprest_total = DIVIDE(Medidas_balancetenew[eemprestEFinanc_CP],Medidas_balancetenew[ssomaemprestEfinan])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7691eda1-998e-4550-9119-502886575751

	measure %JurosPagosLongoprazo = DIVIDE(Medidas_balancetenew[TotalJuros],Medidas_balancetenew[ssomaemprestEfinan])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d3ff0099-1c5a-456e-b4c0-6194c7df33b4

	measure eemprestEFinanc_CP_LM = CALCULATE(Medidas_balancetenew[eemprestEFinanc_CP], DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 7a74eb78-e9ce-4df5-ad5b-563c39d0be01

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure eemprestEFinanc_LP_LM = CALCULATE(Medidas_balancetenew[eemprestEFinanc_LP], DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 35ca1c1e-b591-457c-b251-4f2bc93e6c3f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure emprest_CP|emprest_total_LM = CALCULATE(Medidas_balancetenew[emprest_CP|emprest_total], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: da5f0de6-9946-46a6-91f7-998629bad616

	measure ssoma_emprestEFinanc_LM = ```
			CALCULATE(
			    Medidas_balancetenew[ssomaemprestEfinan], 
			    DATEADD(dCalendario[data], 
			    -1, MONTH)
			    )
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 2de5f357-16b3-4d12-9696-9fc5542b5ce0

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure JJurosPagos_LM = CALCULATE(Medidas_balancetenew[TotalJuros], DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: a9ed1c88-9a97-49e2-b3fb-720a0187cbfe

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure %JurosPagosLongoprazo_LM = CALCULATE(Medidas_balancetenew[%JurosPagosLongoprazo], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c1899398-e1d9-4589-9099-24bc6577eeb0

	measure TributosIncidentesISS = ```
			
			VAR v_issqn =
			CALCULATE(
			SUMX(
			    FILTER(balancetenew, 
			    balancetenew[Query] = "Tributos_Incidentes_ISS"),
			    balancetenew[vlr]))
			
			RETURN
			
			IF(v_issqn < 0, v_issqn * -1, v_issqn)
			
			```
		formatString: 0
		lineageTag: faed5b5e-aa3a-49b6-b217-175c8c0e874d

	measure %estoquevsanterior = DIVIDE(Medidas_balancetenew[ATCIR_Estoques] - Medidas_balancetenew[ATCIR_EstoquesLM],Medidas_balancetenew[ATCIR_EstoquesLM])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f5e475c7-ed69-443e-9c4e-83d3f7a85b90

	measure ATCIR_Despesas_Antecipadas = SUMX(FILTER(balancetenew, balancetenew[Query] = "BL_ATCIR_Despesas_Antecipadas"), balancetenew[vlr])
		formatString: 0
		lineageTag: 88fe700a-3eea-4295-8b6a-6dff230fc637

	measure Investimentototal_ACU = ```
			
			CALCULATE(
			DIVIDE(
			    IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    CALCULATE(
			        [LLucro_liquido II],
			        DATESYTD(
			            dCalendario[data]
			        )
			    ),
			    Medidas_balancetenew[LLucro_liquido_selecionado])
			,  
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[totativo]
			        ))
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 68c7a1d3-484c-4ff4-a75a-a1b0ff6b5ce3

	measure InvestimentoACUanoAnterior =
			
			CALCULATE(
			    Medidas_balancetenew[Investimentototal_ACU], SAMEPERIODLASTYEAR(dCalendario[data])
			    )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1f20d58c-0eed-4864-b253-79b00987cec8

	measure PPatrimonio_Liquido_ACU = ```
			
			VAR vlucro_liquido =
			CALCULATE(
			    SUMX(
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "DRE_Lucro_ou_Prejuizo_liquido"
			    ),
			    balancetenew[vlr]),
			     DATESYTD(
			        dCalendario[data]
			    )
			)
			
			RETURN
			
			CALCULATE(
			    DIVIDE(
			            IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			        vlucro_liquido,
			    Medidas_balancetenew[LLucro_liquido_selecionado]
			            ),
			            Medidas_balancetenew[patrimonioLiq])
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2419d19f-61b1-4ca6-bce5-9cb7c3c160ea

	measure PatrimonioLiquidoAcumuladoAnoAnterior =
			
			CALCULATE(
			    DIVIDE(
			            Medidas_balancetenew[LLucro_liquido_ACU],
			            Medidas_balancetenew[patrimonioLiq]),
			            SAMEPERIODLASTYEAR(dCalendario[data])
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: fd0aa5e8-dbd9-44f2-9fa6-e8dc08e26be5

	measure Obrigacoes_Tributarias_ICMS = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    IF(
			CALCULATE(
			    SUM(balancetenew[vlr]),
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "Tributos_Recolher_ICMS"
			       // balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			       // (balancetenew[descricao_cliente] = "ICMS A RECOLHER" ||
			       // balancetenew[descricao_cliente] = "ICMS A PAGAR" ||
			       //  balancetenew[descricao_cliente] = "ICMS a Recolher" ||
			       //  balancetenew[descricao_cliente] = "ICMS - Devedor" ||
			       //  balancetenew[descricao_cliente] = "ICMS - Outros Débitos" 
			         
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			) > 0,
			
			CALCULATE(
			    SUM(balancetenew[vlr]),
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "Tributos_Recolher_ICMS"
			       // balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			       // (balancetenew[descricao_cliente] = "ICMS A RECOLHER" ||
			       // balancetenew[descricao_cliente] = "ICMS A PAGAR" ||
			       //  balancetenew[descricao_cliente] = "ICMS a Recolher" ||
			       //  balancetenew[descricao_cliente] = "ICMS - Devedor" ||
			       //  balancetenew[descricao_cliente] = "ICMS - Outros Débitos" 
			         
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			) *-1,
			
			CALCULATE(
			    SUM(balancetenew[vlr]),
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "Tributos_Recolher_ICMS"
			       // balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			       // (balancetenew[descricao_cliente] = "ICMS A RECOLHER" ||
			       // balancetenew[descricao_cliente] = "ICMS A PAGAR" ||
			       //  balancetenew[descricao_cliente] = "ICMS a Recolher" ||
			       //  balancetenew[descricao_cliente] = "ICMS - Devedor" ||
			       //  balancetenew[descricao_cliente] = "ICMS - Outros Débitos" 
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			)
			```
		formatString: #,0
		lineageTag: f02eb2e7-b146-46c4-8d47-9763fa9782da

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Obrigacoes_Tributarias_PIS = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    IF(
			    CALCULATE(
			        SUM(balancetenew[vlr]),
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Tributos_Recolher_PIS"
			           // balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			           //     (   
			            //        balancetenew[descricao_cliente] = "PIS A RECOLHER" ||
			            //        balancetenew[descricao_cliente] = "PIS a recolher" ||
			           //         balancetenew[descricao_cliente] = "PIS A PAGAR" ||
			           //         balancetenew[descricao_cliente] = "PIS a Pagar" ||
			           //         balancetenew[descricao_cliente] = "PIS - Devedor" ||
			           //         balancetenew[descricao_cliente] = "PIS - Receita Antecipada" ||
			           //         balancetenew[descricao_cliente] = "PIS S/FATURAMENTO A RECOLHER"
			           //     )
			        ),
			        dCalendario[data] = UltimoMesTrimestre
			    ) >0,
			     CALCULATE(
			        SUM(balancetenew[vlr]),
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Tributos_Recolher_PIS"
			            //balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			            //    (   
			            //        balancetenew[descricao_cliente] = "PIS A RECOLHER" ||
			            //        balancetenew[descricao_cliente] = "PIS a recolher" ||
			            //        balancetenew[descricao_cliente] = "PIS A PAGAR" ||
			            //        balancetenew[descricao_cliente] = "PIS a Pagar" ||
			            //        balancetenew[descricao_cliente] = "PIS - Devedor" ||
			            //        balancetenew[descricao_cliente] = "PIS - Receita Antecipada" ||
			            //        balancetenew[descricao_cliente] = "PIS S/FATURAMENTO A RECOLHER"
			            //    )
			        ),
			        dCalendario[data] = UltimoMesTrimestre
			    ) *-1,
			     CALCULATE(
			        SUM(balancetenew[vlr]),
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Tributos_Recolher_PIS"
			           // balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			           //     (   
			           //         balancetenew[descricao_cliente] = "PIS A RECOLHER" ||
			           //         balancetenew[descricao_cliente] = "PIS a recolher" ||
			           //         balancetenew[descricao_cliente] = "PIS A PAGAR" ||
			           //         balancetenew[descricao_cliente] = "PIS a Pagar" ||
			           //         balancetenew[descricao_cliente] = "PIS - Devedor" ||
			           //         balancetenew[descricao_cliente] = "PIS - Receita Antecipada" ||
			           //         balancetenew[descricao_cliente] = "PIS S/FATURAMENTO A RECOLHER"
			           //     )
			        ),
			        dCalendario[data] = UltimoMesTrimestre
			    )
			)
			```
		formatString: #,0
		lineageTag: 37dbfb4c-d6e4-407e-8454-bc09c2d06e48

	measure Obrigacoes_Tributarias_COFINS = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    IF(
			    CALCULATE(
			        SUM(balancetenew[vlr]),
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Tributos_Recolher_COFINS"
			            //balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			            //    (balancetenew[descricao_cliente] = "COFINS A RECOLHER" ||
			            //    balancetenew[descricao_cliente] = "COFINS A PAGAR" ||
			            //    balancetenew[descricao_cliente] = "Cofins a Pagar" ||
			            //    balancetenew[descricao_cliente] = "Cofins a Recolher" ||
			            //    balancetenew[descricao_cliente] = "COFINS - Receita Antecipada" ||
			            //    balancetenew[descricao_cliente] = "COFINS - Devedor" ||
			            //    balancetenew[descricao_cliente] = "COFINS a Recolher"
			                )
			        ,
			        dCalendario[data] = UltimoMesTrimestre
			    ) > 0,
			    CALCULATE(
			        SUM(balancetenew[vlr]),
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Tributos_Recolher_COFINS"
			         //   balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			         //       (balancetenew[descricao_cliente] = "COFINS A RECOLHER" ||
			         //       balancetenew[descricao_cliente] = "COFINS A PAGAR" ||
			         //       balancetenew[descricao_cliente] = "Cofins a Pagar" ||
			         //       balancetenew[descricao_cliente] = "Cofins a Recolher" ||
			         //       balancetenew[descricao_cliente] = "COFINS - Receita Antecipada" ||
			         //       balancetenew[descricao_cliente] = "COFINS - Devedor"
			                )
			        ,
			        dCalendario[data] = UltimoMesTrimestre
			    ) *-1,
			    CALCULATE(
			        SUM(balancetenew[vlr]),
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Tributos_Recolher_COFINS"
			           // balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			           //     (balancetenew[descricao_cliente] = "COFINS A RECOLHER" ||
			           //     balancetenew[descricao_cliente] = "COFINS A PAGAR" ||
			           //     balancetenew[descricao_cliente] = "Cofins a Pagar" ||
			           //     balancetenew[descricao_cliente] = "Cofins a Recolher" ||
			           //     balancetenew[descricao_cliente] = "COFINS - Receita Antecipada" ||
			           //     balancetenew[descricao_cliente] = "COFINS - Devedor"
			                ),
			        dCalendario[data] = UltimoMesTrimestre
			    ) 
			)
			```
		formatString: #,0
		lineageTag: 046e5ffd-8fba-4db0-ba80-674cf7115896

	measure Obrigacoes_Tributarias_ISS = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    IF(
			CALCULATE(
			    SUM(balancetenew[vlr]),
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "Tributos_Recolher_ISS"
			      //  balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			      //  balancetenew[descricao_cliente] = "ISS NORMAL A RECOLHER" ||
			      //  balancetenew[descricao_cliente] = "ISSQN a Recolher" ||
			      //  balancetenew[descricao_cliente] = "ISS S/SERV A RECOLHER" ||
			      //  balancetenew[descricao_cliente] = "ISS A PAGAR" ||
			      //  balancetenew[descricao_cliente] = "ISS A RECOLHER" ||
			      //  balancetenew[descricao_cliente] = "ISSQN PROPRIO" ||
			      //  balancetenew[descricao_cliente] = "ISS" ||
			      //  balancetenew[descricao_cliente] = "ISS - Receita Antecipada" ||
			      //  balancetenew[descricao_cliente] = "ISSQN a Recolher"
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			) > 0,
			    
			CALCULATE(
			    SUM(balancetenew[vlr]),
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "Tributos_Recolher_ISS"
			        //balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			        //balancetenew[descricao_cliente] = "ISS NORMAL A RECOLHER" ||
			        //balancetenew[descricao_cliente] = "ISSQN a Recolher" ||
			        //balancetenew[descricao_cliente] = "ISS S/SERV A RECOLHER" ||
			        //balancetenew[descricao_cliente] = "ISS A PAGAR" ||
			        //balancetenew[descricao_cliente] = "ISS A RECOLHER" ||
			        //balancetenew[descricao_cliente] = "ISSQN PROPRIO" ||
			        //balancetenew[descricao_cliente] = "ISS" ||
			        //balancetenew[descricao_cliente] = "ISS - Receita Antecipada"
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			) *-1,
			    
			CALCULATE(
			    SUM(balancetenew[vlr]),
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "Tributos_Recolher_ISS"
			        //balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			        //balancetenew[descricao_cliente] = "ISS NORMAL A RECOLHER" ||
			        //balancetenew[descricao_cliente] = "ISSQN a Recolher" ||
			        //balancetenew[descricao_cliente] = "ISS S/SERV A RECOLHER" ||
			        //balancetenew[descricao_cliente] = "ISS A PAGAR" ||
			        //balancetenew[descricao_cliente] = "ISS A RECOLHER" ||
			        //balancetenew[descricao_cliente] = "ISSQN PROPRIO" ||
			        //balancetenew[descricao_cliente] = "ISS" ||
			        //balancetenew[descricao_cliente] = "ISS - Receita Antecipada"
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: cc5c58e6-65fb-411d-9b25-b791a4d6d4a4

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Obrigacoes_Tributarias_PIS_SF =
			
			IF(
			CALCULATE(
			    SUM(balancetenew[vlr]),
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			        balancetenew[descricao_cliente] = "PIS S/FATURAMENTO"
			    )
			) > 0,
			CALCULATE(
			    SUM(balancetenew[vlr]),
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			        balancetenew[descricao_cliente] = "PIS S/FATURAMENTO"
			    )
			) *-1,
			CALCULATE(
			    SUM(balancetenew[vlr]),
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			        balancetenew[descricao_cliente] = "PIS S/FATURAMENTO"
			    )
			)
			
			)
		formatString: 0
		lineageTag: 2eccfd20-3077-405d-a77d-2f860903d2b3

	measure Total_Obrigacoes_Tributarias = ```
			
			
			COALESCE(
			    CALCULATE(
			        SUMX(
			            VALUES(balancetenew[Query]),
			            [Obrigacoes_Tributarias_ICMS] + 
			            [Obrigacoes_Tributarias_PIS] +
			            [Obrigacoes_Tributarias_COFINS] +
			            [Obrigacoes_Tributarias_ISS]
			        )
			    ), 0)
			```
		lineageTag: a007a946-4fc0-4269-ae8e-3bfc0acb803e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Total_Obrigacoes_TributariasLM = CALCULATE('Medidas_balancetenew'[Total_Obrigacoes_Tributarias], DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 3257361d-becf-4063-8e4a-4ada5a43d03b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Total_Obrigacoes_Tributarias|ReceitaLiquida =
			
			COALESCE(
			DIVIDE(SUMX('Medidas_balancetenew', 'Medidas_balancetenew'[Total_Obrigacoes_Tributarias]), SUMX(Medidas_balancetenew,Medidas_balancetenew[MReceita_bruta])), 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 569d9bd7-c56a-4f25-b370-f8260b96047b

	measure Total_Obrigacoes_Tributarias|ReceitaLiquidaLM = CALCULATE('Medidas_balancetenew'[Total_Obrigacoes_Tributarias|ReceitaLiquida],DATEADD(dCalendario[data],-1,MONTH))
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: acbd3791-ee25-417b-9e94-eec1a005232d

	measure investimentosatvncircu = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew, 
			            balancetenew[Query] = "BL_ATNCIR_Investimentos"
			            ), 
			            balancetenew[vlr]
			            ),
			            dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0
		lineageTag: bb9a8b7f-9f49-463c-bb90-9e87facbfab0

	measure Imobilizadoatvncircu = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew, 
			            balancetenew[Query] = "BL_ATNCIR_Imobilizado_Liquido"), 
			            balancetenew[vlr]
			            ),
			            dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0
		lineageTag: afa76992-8163-401d-8190-fc46f63e8591

	measure %estoquesvsanterior = DIVIDE('Medidas_balancetenew'[ATCIR_Estoques] - 'Medidas_balancetenew'[ATCIR_EstoquesLM],'Medidas_balancetenew'[ATCIR_EstoquesLM])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6324bdb4-0b99-4dec-bb14-18b5d4a1e0aa

	measure Obrigacoes_TributariasLM = CALCULATE('Medidas_balancetenew'[Obrigacoes_Tributarias_actual_month], DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 8d6c4c2f-39f2-434e-bb5e-16249410a42a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Obrigacoes_TributariasLY = ```
			
			CALCULATE(
			    'Medidas_balancetenew'[Obrigacoes_Tributarias_actual_month], 
			    DATEADD(
			        dCalendario[data], 
			        -1, 
			        YEAR
			    )
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 45623869-7553-485e-83eb-3243ab0f4015

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Obrigacoes_Tributarias|SomaPassCircu = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			DIVIDE(
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[Obrigacoes_Tributarias]), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[ssomapasscircu]
			    )
			  ),
			  dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cf5e9151-239f-430d-9c63-d032bd1f1733

	measure Obrigacoes_Tributarias|SomaPassCircuLM = CALCULATE('Medidas_balancetenew'[Obrigacoes_Tributarias|SomaPassCircu], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4565aedc-38ad-4ad3-a5d3-2f0621cf160b

	measure obrigacoesTributariasLY = ```
			CALCULATE('Medidas_balancetenew'[Obrigacoes_Tributarias|SomaPassCircu], DATEADD(dCalendario[data], -1,YEAR)) 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a95ca01b-5337-416b-90fe-796b1c5e792a

	measure adiantamentosLM = ```
			CALCULATE(
			    SUMX(Medidas_balancetenew,
			    Medidas_balancetenew[adiantamentos_de_clientes]
			), 
			DATEADD(dCalendario[data], -1, MONTH
			)
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 7b8af04c-57fa-4f73-84f0-0d5ea4adbf82

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Balanco_Passivo_PL_PASSCIR_Debitos_DiversosLY = CALCULATE('Medidas_balancetenew'[Balanco_Passivo_PL_PASSCIR_Debitos_Diversos], DATEADD(dCalendario[data], -1, YEAR))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 36a67c65-f9fa-4fd3-ba7a-3d6704a00f7c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure outrascontaspagarLM = CALCULATE('Medidas_balancetenew'[outras_contas_a_pagar], DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 65b8dcaa-71b4-4caf-8ce0-54bee4f57398

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure outrascontaspagarLY = CALCULATE('Medidas_balancetenew'[outras_contas_a_pagar], DATEADD(dCalendario[data], -1, YEAR))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 2ac5ee66-7334-4d5e-8603-56970e74a426

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ano_anterior = ```
			CALCULATE(MAX(dCalendario[Ano]), DATEADD(dCalendario[data], -1, YEAR))
			 
			```
		formatString: 0
		lineageTag: a305534a-95f9-4b85-98db-564cf34bd600

	measure indicador_capital_terceiros_S_PL = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			 CALCULATE(
			DIVIDE(
			    Medidas_balancetenew[ssomapasscircu] + Medidas_balancetenew[ssomapassncirculante],Medidas_balancetenew[patrimonioLiq],0
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			 )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 89490226-175c-4249-928d-fb72daf4e461

	measure capital_terceiros_S_Atv = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    CALCULATE(
			DIVIDE(Medidas_balancetenew[ssomapasscircu] + Medidas_balancetenew[ssomapassncirculante],
			Medidas_balancetenew[totativo],0
			),
			dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a591a903-ea9d-4f78-8ab2-87e1ceff195d

	measure capital_terceiros_CP_LM = CALCULATE(Medidas_balancetenew[Capital_Terceiros_CP],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 21194d77-7245-4998-b3ef-4f8da8abfc1d

	measure Capital_Terceiros_CP = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			DIVIDE(
			    Medidas_balancetenew[ssomapasscircu],
			    Medidas_balancetenew[ssomapasscircu] + Medidas_balancetenew[ssomapassncirculante],0
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 67dff157-e698-4729-b9a7-c4fa69945de7

	measure capit_terc_S_PL_LM = CALCULATE(Medidas_balancetenew[indicador_capital_terceiros_S_PL],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 170644ee-9929-4ef0-b4ed-3abf26cf2bc2

	measure capit_terc_S_ATV_LM = CALCULATE(Medidas_balancetenew[capital_terceiros_S_Atv],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1b0c85a2-5c3d-4f87-8120-ca9e637759d1

	measure DDespesaComercialLM_YTD = ```
			CALCULATE(
			    'Medidas_balancetenew'[DDespesa_Comercial_ACU], 
			    DATEADD(dCalendario[data], -1, MONTH)
			    )
			```
		lineageTag: 4196def8-f62c-45fc-99b1-5153c89f7b36

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DDespesaADM_actual_month = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_administrativas" || 
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Ocupacao" || 
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao"
			        ),
			        balancetenew[vlr]
			    ),
			    LASTNONBLANK(
			        FILTER(
			            ALL(dCalendario[data]),
			            dCalendario[data] <= MAX(dCalendario[data])
			        ),
			        CALCULATE(
			            SUMX(
			                FILTER(
			                    balancetenew,
			                    balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_administrativas" || 
			                    balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Ocupacao" || 
			                    balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao"
			                ),
			                balancetenew[vlr]
			            )
			        )
			    ),
			dCalendario[data] = UltimoMesTrimestre
			)
			
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 2d9cfce5-001f-4879-b849-8ae9126401c8

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaADM_MesAnterior_tabela = ```
			
			CALCULATE(
			   [DDespesaADM_actual_month teste],
			    FILTER(
			        ALL(dCalendario[data]),
			        dCalendario[data] = EOMONTH(MAX(dCalendario[data]), -2) + 1
			    )
			)
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: dc528e05-c096-4de6-9201-0e4ab5f2ca33

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaPessoal_actual_month = ```
			
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Salarios_ordenados" || 
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Beneficios" || 
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Impostos" || 
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Provisoes" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal"
			        ),
			        balancetenew[vlr]
			    ),
			    LASTNONBLANK(
			        FILTER(
			            ALL(dCalendario[data]),
			            dCalendario[data] <= MAX(dCalendario[data])
			        ),
			        CALCULATE(
			            SUMX(
			                FILTER(
			                    balancetenew,
			                    balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Salarios_ordenados" || 
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Beneficios" || 
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Impostos" || 
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Provisoes" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal"
			                ),
			                balancetenew[vlr]
			            )
			        )
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: e8151c40-0b57-4098-84b9-f0f21f749478

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaPessoal_MesAnterior = ```
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Salarios_ordenados" || 
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Beneficios" || 
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Impostos" || 
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Provisoes" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal"
			        ),
			        balancetenew[vlr]
			    ),
			    FILTER(
			        ALL(dCalendario[data]),
			        dCalendario[data] = EOMONTH(MAX(dCalendario[data]), -2) + 1
			    )
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 6e11e185-87ee-4e6c-af12-daefac0d51c3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaComercial_Actual_month = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_comerciais" || 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_contratuais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Propaganda_Publicidade" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Frota_Transportes"
			       ), 
			        balancetenew[vlr]),
			    LASTNONBLANK(
			        FILTER(
			            ALL(dCalendario[data]),
			            dCalendario[data] <= MAX(dCalendario[data])
			        ),
			        CALCULATE(
			            SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_comerciais" || 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_contratuais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Propaganda_Publicidade" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Frota_Transportes"
			       ), 
			        balancetenew[vlr])
			        )
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: e679b327-757d-4ff8-9123-3032a6ef404c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaComercial_MesAnterior = ```
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_comerciais" || 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_contratuais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Propaganda_Publicidade" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Frota_Transportes"
			        ),
			        balancetenew[vlr]
			    ),
			    FILTER(
			        ALL(dCalendario[data]),
			        dCalendario[data] = EOMONTH(MAX(dCalendario[data]), -2) + 1
			    )
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 12eea3f8-0a73-4f58-90b0-b505bd2ce78e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesa_outras_actual_month = ```
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" || 
			
			        balancetenew[Query] = "DRE_Desp_Operacionais_Outras_despesas_operacionais" || 
			
			        balancetenew[Query] = "DRE_Desp_Operacionais_Outras_receitas_operacionais"
			        ),
			        balancetenew[vlr]
			    ),
			    LASTNONBLANK(
			        FILTER(
			            ALL(dCalendario[data]),
			            dCalendario[data] <= MAX(dCalendario[data])
			        ),
			        CALCULATE(
			            SUMX(
			                FILTER(
			                    balancetenew,
			                    balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" || 
			
			        balancetenew[Query] = "DRE_Desp_Operacionais_Outras_despesas_operacionais" || 
			
			        balancetenew[Query] = "DRE_Desp_Operacionais_Outras_receitas_operacionais"
			                ),
			                balancetenew[vlr]
			            )
			        )
			    )
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 28f068fa-41d0-4112-a9f9-bfd0c91cc38b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesa_outras_MesAnterior = ```
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" || 
			
			        balancetenew[Query] = "DRE_Desp_Operacionais_Outras_despesas_operacionais" || 
			
			        balancetenew[Query] = "DRE_Desp_Operacionais_Outras_receitas_operacionais"
			        ),
			        balancetenew[vlr]
			    ),
			    FILTER(
			        ALL(dCalendario[data]),
			        dCalendario[data] = EOMONTH(MAX(dCalendario[data]), -2) + 1
			    )
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: b70c737b-29a8-4687-9d61-817272a40fcd

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Balanco_Passivo_PL_PASSCIR_Debitos_Diversos | SomaPassCircu' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			DIVIDE(
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[Balanco_Passivo_PL_PASSCIR_Debitos_Diversos]), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[ssomapasscircu]
			    )
			  ),
			  dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e09135f3-7b0c-40f2-b86e-d2bf8908d3ce

	measure 'Prazo Médio Contas a Pagar' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			    VAR v_fornec_compras =
			    DIVIDE(
			    Medidas_balancetenew[Fornecedores liquidos], 
			    Medidas_balancetenew[Compras no ano])
			
			    RETURN
			    ROUNDDOWN(
			CALCULATE(
			     v_fornec_compras * 
			    Medidas_balancetenew[Valor_mensal_prazos_medios]
			    
			    //,dCalendario[data] = UltimoMesTrimestre
			), 0)
			```
		formatString: 0
		lineageTag: 2a5f409f-2a9f-405a-a22d-ee67f05ed9ad

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Impostos Incidentes sobre a receita' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			    RETURN
			    CALCULATE(
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Imp_Incidentes_Sobre_Receita"),
			            balancetenew[vlr]
			    )
			),
			    dCalendario[data] = UltimoMesTrimestre
			    ) *-1
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 615ce110-da2f-4111-806d-f5acf6697329

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure TributosIncidentesIPI = ```
			SUMX(
			    FILTER(balancetenew, 
			    balancetenew[Query] = "Tributos_Incidentes_IPI"),
			    balancetenew[vlr]
			) *-1
			```
		lineageTag: 19f5c667-317b-4a75-98fb-f5773d66f303

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure EBITDA_QUERY = ```
			
			SUMX(
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "Ebitda_total"
			    ),
			    balancetenew[total_mes_atual]
			)
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 15c7d743-5ab8-4ec8-a15c-63e062eeb33b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure rresultado_nao_operacional =
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_NAO_Operacionais_Receita_nao_operacional_TOTAL"
			        ),
			        balancetenew[vlr]
			    ))
		lineageTag: de091c6a-a89c-4988-bb25-efe1de94edb9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Prazo Médio CP_actual_month' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			DIVIDE(
			Medidas_balancetenew[Fornecedores liquidos] * (-30 * 1),
			Medidas_balancetenew[CCusto_actual_month]
			),
			dCalendario[data] = UltimoMesTrimestre
			) *-1
			
			
			
			```
		formatString: 0
		lineageTag: eb00fc5a-849f-4601-997b-b46b9b550a65

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Prazo Médio CR' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			DIVIDE(
			Medidas_balancetenew[contas receber] * (-30 * 1),
			Medidas_balancetenew[MReceita_Liquida]
			),
			dCalendario[data] = UltimoMesTrimestre
			) *-1
			```
		formatString: 0
		lineageTag: f52bae9a-6708-41d4-b7cf-5129bc2a373c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Ativo_Permanente = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			SUMX(
			    FILTER(balancetenew,
			            balancetenew[Query] = "BL_ATNCIR_Investimentos" ||
			            balancetenew[Query] = "BL_ATNCIR_Intangivel_Liquido" ||
			            balancetenew[Query] = "BL_ATNCIR_Imobilizado_Liquido" ||
			            balancetenew[Query] = "BL_ATNCIR_Ativo_Direito_Uso"
			    ), 
			    balancetenew[vlr]
			),
			dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 6b651fce-7959-4cf7-bf1d-3083d16be3d2

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Indice_grau_de_Imobilizacao = ```
			
			 DIVIDE(
			     Medidas_balancetenew[Ativo_Permanente],
			     Medidas_balancetenew[totativo]
			 )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2e94e206-f7fe-4443-b7e9-71567d8bb791

	measure indice_grau_de_imobilizacao_LM =
			
			CALCULATE(
			    Medidas_balancetenew[Indice_grau_de_Imobilizacao],
			    DATEADD(dCalendario[data], -1,MONTH
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: db564743-9f25-4fd7-b103-1fe1bbe2c768

	measure periodo_anterior = ```
			
			CALCULATE(
			    MAX(dCalendario[Mês Completo]),
			    FILTER(
			        ALL(dCalendario),
			        dCalendario[data] = EOMONTH(MAX(dCalendario[data]), -1)
			    )
			)
			
			
			
			```
		lineageTag: ef5672a8-9137-462d-ace3-78daec3f4b60

	measure periodo_atual = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    MAX(dCalendario[Mês Completo]),
			    ALL(dCalendario),
			    VALUES(dCalendario[Mês Completo]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			
			```
		lineageTag: 1cb0ad09-c3b9-422a-bcb4-4bcc7f2d5435

	measure Obrigacoes_Tributarias_actual_month = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" 
			    ),
			    balancetenew[vlr]
			),
			 dCalendario[data] = UltimoMesTrimestre
			    )
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 159073f1-ee52-4865-b363-3013bce7d2f3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure PASSCIR_Obrigacoes_Trabalhistas_Actual_Month = ```
			
			 VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    
			    RETURN
			CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Trabalhistas"), 
			        balancetenew[vlr]
			        ),
			         dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 8c91651a-730d-42e0-941b-2b8e8a6d6b5d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure adiantamentos_de_clientes = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			    RETURN
			CALCULATE(
			    SUM(balancetenew[vlr]),
			    FILTER(balancetenew,
			    balancetenew[Query] = "BL_PASSCIR_Adiantamentos_Clientes" ||
			    balancetenew[Query] = "BL_PASSCIR_Debitos_Diversos" &&
			    (
			        balancetenew[descricao_cliente] = "Adiantamento de CLientes" ||
			        balancetenew[descricao_cliente] = "498 ADIANTAMENTO DE CLIENTES - VENDA FUTURA" ||
			        balancetenew[descricao_cliente] = "497 ADIANTAMENTO DE CLIENTES" ||
			        balancetenew[descricao_cliente] = "Adiantamento dep Cliente" ||
			        balancetenew[descricao_cliente] = "Adiantamentos de Clientes" ||
			        balancetenew[descricao_cliente] = "VEICULOS NOVOS/USADOS" ||
			        balancetenew[descricao_cliente] = "PECAS E ACESSORIOS" ||
			        balancetenew[descricao_cliente] = "CREDORES DIVERSOS" ||
			        balancetenew[descricao_cliente] = "Despachante" ||
			        balancetenew[descricao_cliente] = "Retorno De Financiamentos" ||
			        balancetenew[descricao_cliente] = "FRANQUIA" ||
			        balancetenew[descricao_cliente] = "CLIENTES DIVERSOS" ||
			        balancetenew[descricao_cliente] = "CREDITO DE CLIENTES" ||
			        balancetenew[descricao_cliente] = "CREDITOS DE CLIENTES" ||
			        balancetenew[descricao_cliente] = "CLIENTES RECEBIDO EM DUPLICIDADE E NOTA FISCAL DEV" ||
			        balancetenew[descricao_cliente] = "CREDITO DE CLIENTE CAIXA 12" ||
			        balancetenew[descricao_cliente] = "BANCO SICOOB - COBS 756" ||
			        balancetenew[descricao_cliente] = "BANCO ITAU S/A - COBS 3411" ||
			        balancetenew[descricao_cliente] = "BANCO BRADESCO - COBS 237" ||
			        balancetenew[descricao_cliente] = "BANCO SAFRA - DNI 422" ||
			        balancetenew[descricao_cliente] = "BANCO BRADESCO - DNI 237" ||
			        balancetenew[descricao_cliente] = "ADIANTAMENTO  DE CLIENTES" ||
			        balancetenew[descricao_cliente] = "Adiantamentos de Clientes Diversos" ||
			        balancetenew[descricao_cliente] = "ADIANTAMENTO DE CLIENTES DIVERSOS"
			
			
			    )
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			
			
			
			
			
			
			
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 52a4f9ab-df2a-42de-a45d-734a04b78ce1

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ssomapasscircu_actual_month = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			RETURN
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew, 
			            balancetenew[Query] = "BL_PASSCIR_soma"
			        ), 
			    balancetenew[vlr]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)* -1
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 3f569cb9-85b5-4583-a603-40d0f98a43c3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure SomaAtivCircu_Actual_Month = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			RETURN
			CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "BL_ATCIR_soma"
			    ), 
			        balancetenew[vlr]
			),
			dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 1b71b5a2-a4cc-47b1-b843-6652055e0939

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Total_Obrigacoes_Tributarias_sinal_invertido = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			RETURN
			    CALCULATE(
			        SUMX(
			            VALUES(balancetenew[Query]),
			            [Obrigacoes_Tributarias_ICMS] + 
			            [Obrigacoes_Tributarias_PIS] +
			            [Obrigacoes_Tributarias_COFINS] +
			            [Obrigacoes_Tributarias_ISS] +
			            [Obrigacoes_Tributarias_PIS_SF]
			        ),
			dCalendario[data] = UltimoMesTrimestre
			    ) *-1
			```
		lineageTag: 16f7af6f-a242-42c5-b1dc-a379f93491d9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure OBRIGACOES_DFC = ```
			
			SUMX(
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "DFC_obrigacoes_tributarias"
			    ),
			    balancetenew[desvio]
			)
			
			
			```
		formatString: #,0
		lineageTag: 1d297f93-d696-4e71-8eb1-22daa44e0a42

		annotation PBI_FormatHint = {"isDecimal":true}

	measure DFC_Lucro_liquido = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    CALCULATE(
			        SUMX(FILTER(balancetenew, 
			            balancetenew[Query] = "DRE_Lucro_ou_Prejuizo_liquido"), 
			            balancetenew[vlr]
			        ),
			        dCalendario[data] = UltimoMesTrimestre
			    )
			```
		lineageTag: 9f858646-0648-41f0-83a1-d22538c2c271

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Obrigacoes_Tributarias_IPI = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    IF(
			    CALCULATE(
			        SUM(balancetenew[vlr]),
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Tributos_Recolher_IPI"
			            //balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			            //    (balancetenew[descricao_cliente] = "IPI A RECOLHER" ||
			            //    balancetenew[descricao_cliente] = "IPI A PAGAR" ||
			            //    balancetenew[descricao_cliente] = "Ipi a Pagar" ||
			            //    balancetenew[descricao_cliente] = "Ipi a Recolher" ||
			            //    balancetenew[descricao_cliente] = "IPI - Receita Antecipada" ||
			            //    balancetenew[descricao_cliente] = "IPI - Devedor"
			                
			        ),
			        dCalendario[data] = UltimoMesTrimestre
			    ) > 0,
			    
			    CALCULATE(
			        SUM(balancetenew[vlr]),
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Tributos_Recolher_IPI"
			           // balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			           //     (balancetenew[descricao_cliente] = "IPI A RECOLHER" ||
			           //     balancetenew[descricao_cliente] = "IPI A PAGAR" ||
			           //     balancetenew[descricao_cliente] = "Ipi a Pagar" ||
			           //     balancetenew[descricao_cliente] = "Ipi a Recolher" ||
			           //     balancetenew[descricao_cliente] = "IPI - Receita Antecipada" ||
			           //     balancetenew[descricao_cliente] = "IPI - Devedor"
			                
			        ),
			        dCalendario[data] = UltimoMesTrimestre
			    ) *-1,
			    
			    CALCULATE(
			        SUM(balancetenew[vlr]),
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Tributos_Recolher_IPI"
			            //balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" &&
			            //    (balancetenew[descricao_cliente] = "IPI A RECOLHER" ||
			            //    balancetenew[descricao_cliente] = "IPI A PAGAR" ||
			            //    balancetenew[descricao_cliente] = "Ipi a Pagar" ||
			            //    balancetenew[descricao_cliente] = "Ipi a Recolher" ||
			            //    balancetenew[descricao_cliente] = "IPI - Receita Antecipada" ||
			            //    balancetenew[descricao_cliente] = "IPI - Devedor"
			                
			        ),
			        dCalendario[data] = UltimoMesTrimestre
			    ))
			```
		lineageTag: a008e3eb-ab8b-4472-bb6d-e0337506edb8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure adiantamentos_clientes_LY = ```
			
			CALCULATE(
			    'Medidas_balancetenew'[adiantamentos_de_clientes], 
			    DATEADD(dCalendario[data], -1, YEAR
			    )
			)
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 40dec081-4fb0-43de-8afc-223059e20622

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'BL_PASSCIR_adiantamentos_de_clientes | SomaPassCircu' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			DIVIDE(
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[adiantamentos_de_clientes]), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[ssomapasscircu]
			    )
			  ),
			  dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 349e51bf-d0ab-4e4e-9af9-dab9150e0116

	measure PASSCIR_adiantamentos_de_clientes|SomaPassCircuLM = ```
			
			CALCULATE(
			    'Medidas_balancetenew'[BL_PASSCIR_adiantamentos_de_clientes | SomaPassCircu], 
			    DATEADD(dCalendario[data], -1, MONTH
			    )
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 586121ee-0aad-4c6a-9df8-6b7dc57bf37d

	measure PASSCIR_adiantamentos_de_clientes_LY|soma_pass_circ = ```
			
			DIVIDE(
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[adiantamentos_clientes_LY]
			    ), 
			    SUMX(
			        'Medidas_balancetenew', 
			        'Medidas_balancetenew'[ssomapasscircuLY]
			    )
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b3eedea6-503a-4bfc-9af8-76583199d745

	measure %outras_contas|totpassivo = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    
			DIVIDE(
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[outras_contas_a_pagar]), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[totpassivo]
			    )
			),
			dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7f6ef8b0-6611-4701-a673-2fce04f5e3e2

	measure %outras_contas_a_pagar|totpassivoLM = ```
			
			CALCULATE(
			    'Medidas_balancetenew'[%outras_contas|totpassivo], 
			    DATEADD(dCalendario[data], -1, MONTH
			    )
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f23dfb77-74f5-42ee-96df-9531fc5abae6

	measure %outras_contas_a_pagar|totpassivo_LY = ```
			
			CALCULATE(
			    'Medidas_balancetenew'[%outras_contas|totpassivo], 
			    DATEADD(
			        dCalendario[data], -1, YEAR
			    )
			)
			
			
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e2286cbe-eeed-417e-b252-86855b409b52

	measure ATCIR_Estoques_End_of_LY = ```
			
			CALCULATE(
			    'Medidas_balancetenew'[ATCIR_Estoques],
			    FILTER(
			        ALL(dCalendario),
			        YEAR(dCalendario[data]) = YEAR(MAX(dCalendario[data])) - 1
			            && MONTH(dCalendario[data]) = 12
			    )
			)
			
			
			```
		formatString: #,0
		lineageTag: b7989279-6486-4a28-903f-e5a3487b21df

		annotation PBI_FormatHint = {"isDecimal":true}

	measure grafico_CCusto_ACU = ```
			
			CALCULATE(
			    SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "Custo dos Produtos Vendidos"
			    ), 
			        balancetenew[vlr]
			    ), 
			    DATESYTD(dCalendario[data]
			    )
			) * -1
			```
		lineageTag: fbaca7ac-4182-4909-baff-8768b7eee635

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure desp_operac_ebit =
			
			SUMX(
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_comerciais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Salarios_ordenados" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Beneficios" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Provisoes" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Impostos" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_administrativas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Ocupacao" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_contratuais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_controladas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_nao_controladas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Marketing" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Logistica" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Consultoria_Tecnica" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Alugueis" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Prestacao_de_Servicos" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Manutencoes" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Informatica"
			
			    ),
			    balancetenew[vlr]
			)
		formatString: #,0
		lineageTag: 42f9c95d-51da-430a-b6f4-5d13cc6ce50d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure desp_operac_ebit_ACU =
			
			CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_comerciais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Salarios_ordenados" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Beneficios" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Provisoes" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Impostos" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_administrativas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Ocupacao" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_contratuais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_controladas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_nao_controladas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Marketing" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Logistica" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Consultoria_Tecnica" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Alugueis" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Prestacao_de_Servicos" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Manutencoes" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Informatica"
			    ),
			    balancetenew[vlr]
			),
			DATESYTD(dCalendario[data])
			) *-1
		formatString: #,0
		lineageTag: 103975c6-1158-480c-837a-5ac3b20eb67d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Ebitda_despesa_depreciacao_ACU = ```
			
			CALCULATE(
			    SUMX(
			        FILTER(
			        balancetenew, 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao"), 
			        balancetenew[vlr]
			    ),
			DATESYTD(dCalendario[data]
			))
			```
		lineageTag: 53859786-4f21-430a-8ab5-afb911ca6d47

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure EEbitda_ACU_LY = ```
			
			CALCULATE(
			    Medidas_balancetenew[EEbitda_ACU],
			    SAMEPERIODLASTYEAR(dCalendario[data])
			)
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: f8749f6c-22de-459e-82ed-be9f22a2e932

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Ano_Mes_Anterior = ```
			
			VAR MesSelecionado = MAX(dCalendario[data])
			VAR MesAnterior = EOMONTH(MesSelecionado, -1)
			VAR AnoMesAnterior = DATE(YEAR(MesAnterior), MONTH(MesAnterior), 1)
			RETURN YEAR(AnoMesAnterior)
			
			```
		formatString: 0
		lineageTag: fe4065d0-c814-4de5-9a3d-f68967445d8d

	measure DDespesaControladas_MCD = ```
			SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_controladas"), 
			        balancetenew[vlr])
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 546f214d-711f-4619-bd34-f4a3837d6dbd

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaNaoControladas_MC = ```
			SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_nao_controladas" ||
			         balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao"), 
			        balancetenew[vlr])
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: a4ef55a2-fddd-4a6a-b4f3-50f7f2ca4256

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaControladas_LM = ```
			
			CALCULATE(
			    'Medidas_balancetenew'[DDespesaControladas_MCD], 
			    DATEADD(dCalendario[data], 
			    -1, 
			    MONTH
			))
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 104b4430-8271-4297-aed8-b7baaed4bc26

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaNaoControladas_LM_MC = ```
			
			CALCULATE(
			    'Medidas_balancetenew'[DDespesaNaoControladas_actual_month], 
			    DATEADD(dCalendario[data], 
			    -1, 
			    MONTH
			))
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 2824dab0-d7f3-4df3-b01f-df0981a7cdf7

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaControladas_ACU = ```
			
			CALCULATE(
			    [DDespesaControladas_MCD], 
			    DATESYTD(dCalendario[data])
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 3e802eb7-c5bb-4761-93bc-50067f14154e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaNaoControladas_ACU_MC = ```
			
			CALCULATE(
			    [DDespesaNaoControladas_MC], 
			    DATESYTD(dCalendario[data])
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 6f2f5818-8be4-4c9f-929f-e9b2970145d3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaControladas_ACUanoAnterior = ```
			
			CALCULATE(
			    [DDespesaControladas_MCD], 
			    DATESYTD(
			        SAMEPERIODLASTYEAR(dCalendario[data]
			        )
			    )
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 7ef65574-1848-4cf4-8966-2fe82cb0cd19

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaControladas_actual_month = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_controladas"),
			        balancetenew[vlr]
			    ),
			    LASTNONBLANK(
			        FILTER(
			            ALL(dCalendario[data]),
			            dCalendario[data] <= MAX(dCalendario[data])
			        ),
			        CALCULATE(
			            SUMX(
			                FILTER(
			                    balancetenew,
			                    balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_controladas"),
			                balancetenew[vlr]
			            )
			        )
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: eefbf06b-51e5-465f-8034-407b56ab5132

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaControladas_MesAnterior_MC =
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_controladas"
			        ),
			        balancetenew[vlr]
			    ),
			    FILTER(
			        ALL(dCalendario[data]),
			        dCalendario[data] = EOMONTH(MAX(dCalendario[data]), -2) + 1
			    )
			)
		formatString: #,0
		lineageTag: 32eb1dd1-0131-4ff5-b369-6933a0102bf0

		annotation PBI_FormatHint = {"isDecimal":true}

	measure %DDespControladas_atual|anterior_MC = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			    'Medidas_balancetenew'[DDespesaControladas_actual_month] - 'Medidas_balancetenew'[DDespesaControladas_MesAnterior_MC],
			    'Medidas_balancetenew'[DDespesaControladas_MesAnterior_MC]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 93bc8efb-a96f-4782-9566-e1ad5ed64594

	measure DDespesaNaoControladas_ACUanoAnterior_MC = ```
			
			CALCULATE(
			    [DDespesaNaoControladas_MC], 
			    DATESYTD(
			        SAMEPERIODLASTYEAR(dCalendario[data]
			        )
			    )
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: a6147db8-03b7-4d74-a980-1f91a543a6f1

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaNaoControladas_actual_month = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    CALCULATE(
			        [DDespesaNaoControladas_MC],
			        Medidas_balancetenew,
			         dCalendario[data] = UltimoMesTrimestre
			    )
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 727f189c-696e-4187-96eb-b93fa87461d0

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaNaoControladas_MesAnterior_MC =
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_nao_controladas"
			        ),
			        balancetenew[vlr]
			    ),
			    FILTER(
			        ALL(dCalendario[data]),
			        dCalendario[data] = EOMONTH(MAX(dCalendario[data]), -2) + 1
			    )
			)
		formatString: #,0
		lineageTag: 865f8d25-11e6-4cbf-b5a2-bd21f186bc3a

		annotation PBI_FormatHint = {"isDecimal":true}

	measure %DDespNaoControladas_atual|anterior_MC = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			    'Medidas_balancetenew'[DDespesaNaoControladas_actual_month] - 'Medidas_balancetenew'[DDespesaNaoControladas_MesAnterior_MC],
			    'Medidas_balancetenew'[DDespesaNaoControladas_MesAnterior_MC]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b2fd858f-26f0-462f-afd5-1bc823a67dd1

	measure DDespesaADMACU_MC = CALCULATE([DDespesaADM_MC], DATESYTD(dCalendario[data]))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 5b27c9ce-fa32-4d07-b408-3160218803c2

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaADM_MC = ```
			
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_administrativas"
			        ),
			        balancetenew[vlr]
			    ) - CALCULATE(SUM(balancetenew[vlr]), balancetenew[Query] = "DRE_Desp_Operacionais_Depreciacao")
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 2461e233-a6b5-4ee5-b2c4-656d46d9765f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesaADMLM_MC =
			CALCULATE('Medidas_balancetenew'[DDespesaADM_MC], DATEADD(dCalendario[data], -1, MONTH)
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 9956b4fe-3ab7-4307-aa74-0d297a9686ad

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ddespesasNaoControladas_MC = ```
			
			    CALCULATE(
			        [DDespesaNaoControladas_MC] + [Ebitda_despesa_depreciacao],
			        Medidas_balancetenew,
			         dCalendario[data]
			    )
			
			
			
			
			```
		formatString: #,0
		lineageTag: 8c6e77b2-3cd0-439f-b193-5180487a61bd

		annotation PBI_FormatHint = {"isDecimal":true}

	measure DespesaADM|ReceitaLiquida_MC = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			DIVIDE(
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[DDespesaADM_MC]), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[MReceita_Liquida])
			),
			dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 02ab30a7-e138-46f0-9b98-75275acea5f2

	measure DespesaADM|ReceitaLiquidaLM_MC =
			
			CALCULATE(
			    'Medidas_balancetenew'[DespesaADM|ReceitaLiquida_MC],
			    DATEADD(dCalendario[data],-1,MONTH
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 33a6cf6c-834d-4d61-bc1e-50afff1df08e

	measure DespesaADMAcu_receiliq_acu_MC = ```
			
			DIVIDE(
			    SUMX(
			        'Medidas_balancetenew',
			        'Medidas_balancetenew'[DDespesaADMACU_MC]), 
			        SUMX('Medidas_balancetenew', 
			        'Medidas_balancetenew'[MReceita_Liquida_ACU]
			        )
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 63cbcb24-1b09-4e7c-bcd6-388667f10c3b

	measure DespesaADMAcu_receiliq_acuAnoanterior_MC = ```
			
			DIVIDE(
			    SUMX(
			        'Medidas_balancetenew',
			        'Medidas_balancetenew'[DDespesaADMACUanoAnterior_MC]
			        ), 
			    SUMX(
			        'Medidas_balancetenew', 
			        'Medidas_balancetenew'[MReceita_Liquida_Acumulada_LY]
			    )
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 04ea9515-c9d9-494a-a010-9cac7bc525e9

	measure DDespesaADMACUanoAnterior_MC = ```
			
			CALCULATE([DDespesaADM_MC], 
			DATESYTD(
			    SAMEPERIODLASTYEAR(dCalendario[data]
			    )
			    )
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: de106d52-f055-4a17-a719-94ec64c4baed

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure %DespesaNaoControladas|ReceitaLiquida_MC = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			        SUMX(
			            Medidas_balancetenew, 
			            Medidas_balancetenew[DDespesaNaoControladas_MC]
			            ), 
			            SUMX(Medidas_balancetenew, 
			            Medidas_balancetenew[MReceita_Liquida]
			        )
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			) *-1
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 609760cc-7435-47b8-b623-c60796a90067

	measure %DespesaNaoControladas|ReceitaLiLM_MC =
			
			CALCULATE(
			    'Medidas_balancetenew'[%DespesaNaoControladas|ReceitaLiquida_MC],
			    DATEADD(dCalendario[data],
			    -1,
			    MONTH
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5b5315cb-ee1a-432e-9420-ddfd114ed576

	measure %DespesaNaoControladasAcu_ReceitaLiqAcu_MC = ```
			
			DIVIDE(
			    SUMX(
			        'Medidas_balancetenew',
			        'Medidas_balancetenew'[DDespesaNaoControladas_ACU_MC]
			        ), 
			        SUMX('Medidas_balancetenew', 
			        'Medidas_balancetenew'[MReceita_Liquida_ACU]
			    )
			) *-1
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f1ff9877-04c8-4b23-af34-4bbf2f07425e

	measure %DespesaNaoControladasAcu_ReceitaLiqAcuAnoAnterior_MC = ```
			
			DIVIDE(
			    SUMX(
			        'Medidas_balancetenew',
			        'Medidas_balancetenew'[DDespesaNaoControladas_ACUanoAnterior_MC]
			        ), 
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[MReceita_Liquida_Acumulada_LY]
			        )
			) *-1
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d0fb2a6a-0f97-407e-b6af-73c6caa49c45

	measure %DespesaControladas|ReceitaLiquida_MC = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			        SUMX(
			            Medidas_balancetenew, 
			            Medidas_balancetenew[DDespesaControladas_MCD]
			            ), 
			            SUMX(Medidas_balancetenew, 
			            Medidas_balancetenew[MReceita_Liquida]
			        ) *-1
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c36e36de-265a-4703-93e6-c610f6e8a9fd

	measure %DespesaControladas|ReceitaLiLM_MC =
			
			CALCULATE(
			    'Medidas_balancetenew'[%DespesaControladas|ReceitaLiquida_MC],
			    DATEADD(dCalendario[data],
			    -1,
			    MONTH
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 759bf58e-0763-4f54-8724-1a09e32019f7

	measure %DespesaControladasAcu_ReceitaLiqAcu = ```
			
			DIVIDE(
			    SUMX(
			        'Medidas_balancetenew',
			        'Medidas_balancetenew'[DDespesaControladas_ACU]
			    ), 
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[MReceita_Liquida_ACU]
			        )
			) *-1
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: adb09ca5-c501-493b-8565-742dd689b643

	measure %DespesaControladasAcu_ReceitaLiqAcuAnoAnterior_MC = ```
			
			DIVIDE(
			    SUMX(
			        'Medidas_balancetenew',
			        'Medidas_balancetenew'[DDespesaControladas_ACUanoAnterior]
			    ), 
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[MReceita_Liquida_Acumulada_LY]
			        )
			) *-1
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 133cbbdc-1c53-4d64-a1c3-897e02a2230a

	measure MMargem_bruta =
			
			CALCULATE(
			        SUM(
			            balancetenew[vlr]
			        ),
			        FILTER(
			                balancetenew,
			                balancetenew[Query] = "DRE_Lucro_bruto"
			            )
			    )
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 15a6b09f-739e-46e1-834f-67bcb7f52d32

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DFC_Ajustes_Nao_Afetam_Caixa2 = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			RETURN
			CALCULATE(  
			    SUMX(
			        FILTER(balancetenew,
			        balancetenew[Query] = "DFC_ajustes_caixa_operacional"
			        ),
			        balancetenew[desvio]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			
			    
			
			
			```
		lineageTag: c80f7520-b7b0-4a8c-8190-5cdded3724e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure dfc_switch = ```
			
			CALCULATE(
			SWITCH (
			    SELECTEDVALUE ( d_mascara_dfc[classificação] ),
			    "lucro_prejuizo_liq", [total_mes_atual],
			    "ajustes_nao_afetam_caixa", [total_mes_atual],
			"depreciaçao", [total_mes_atual],
			"agio", [total_mes_atual],
			"resultado_acumulado", [desvio],
			"resultado_equivalencia_patrim", [total_mes_atual],
			"outros_ajustes", [total_mes_atual],
			"Resultado_ajustado", [total_mes_atual],
			"var_contas_patrimoniais", [total_mes_atual],
			"contas_receber", [total_mes_atual],
			"adiantamentos", [total_mes_atual],
			"impostos_recuperar", [total_mes_atual],
			"impostos_recuperar_lp", [total_mes_atual],
			"estoques", [total_mes_atual],
			"desp_antecipadas", [total_mes_atual],
			"fornecedores", [total_mes_atual],
			"obrigacoes_trabalhistas", [total_mes_atual],
			"obrigacoes_tributarias", [total_mes_atual],
			"partes_relacionadas", [total_mes_atual],
			"outras_contas_pagar", [total_mes_atual],
			"outras_obrig_pagar_lp", [total_mes_atual],
			"clientes_lp", [total_mes_atual],
			"prov_lp", [total_mes_atual],
			"ativo_dir_uso", [total_mes_atual],
			"caixa_liq_operacional", [total_mes_atual],
			"fluxo_investimentos", [total_mes_atual],
			"aquisicoes_imobilizado", [total_mes_atual],
			"distrib_lucros", [total_mes_atual],
			"investimentos", [total_mes_atual],
			"outros_investimentos", [total_mes_atual],
			"caixa_liq_investimentos", [total_mes_atual],
			"fluxo_financiamentos", [total_mes_atual],
			"emprestimos", [total_mes_atual],
			"afac", [total_mes_atual],
			"capital_social", [total_mes_atual],
			"outras_obrigacoes", [total_mes_atual],
			"distrib_lucros", [total_mes_atual],
			"caixa_liq_financiamentos", [total_mes_atual],
			"caixa_inicial", [total_mes_atual],
			"caixa_final", [total_mes_atual],
			"var_liq_caixa", [total_mes_atual],
			    0
			)
			)
			
			
			
			
			```
		formatString: #,0
		lineageTag: 630c3c9d-02d6-4a44-a197-7b9e28ea05c6

		annotation PBI_FormatHint = {"isDecimal":true}

	measure MReceita_Bruta_Acumulada_LY =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    Medidas_balancetenew[MReceita_Bruta_acu_LY_normal_card],
			    Medidas_balancetenew[MReceita_Bruta_selecionado_LY_normal_card]
			)
		lineageTag: b6d314e5-379f-4980-8c74-b2c142e64b24

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BL_PASSNCIR_Partes_Relacionadas = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			    RETURN
			CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "BL_PASSNCIR_Partes_Relacionadas"
			    ), 
			        balancetenew[vlr]
			),
			dCalendario[data] = UltimoMesTrimestre
			)
			```
		lineageTag: cef10bb4-67e1-4abf-8adf-8923a123d11d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BL_PASSCIR_outras_contas_a_pagar_CP = ```
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			VAR resultado =
			CALCULATE(
			    SUMX(
			        FILTER(balancetenew, 
			        balancetenew[Query] = "BL_PASSCIR_Outras_Contas_Pagar"
			    ), 
			    
			    balancetenew[vlr]),
			    dCalendario[data] = UltimoMesTrimestre)
			
			RETURN
			IF(resultado < 0, resultado *-1, resultado)
			```
		lineageTag: bc9b0123-982f-481e-98ec-8125b46961de

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Intangivel_atvncircu = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew, 
			            balancetenew[Query] = "BL_ATNCIR_Intangivel_Liquido"), 
			            balancetenew[vlr]
			            ),
			            dCalendario[data] = UltimoMesTrimestre
			)
			```
		lineageTag: e88ccbb8-30fe-4885-8cf3-5f6e8bb48ea2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Ativo_Direito_Uso = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew, 
			            balancetenew[Query] = "BL_ATNCIR_Ativo_Direito_Uso"), 
			            balancetenew[vlr]
			            ),
			            dCalendario[data] = UltimoMesTrimestre
			)
			```
		lineageTag: 8c953855-31fe-4602-ac21-36cd4a869203

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Liq_Geral_Ativo_Diferido = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew, 
			            balancetenew[Query] = "BL_ATNCIR_Ativo_Diferido"), 
			            balancetenew[vlr]
			            ),
			            dCalendario[data] = UltimoMesTrimestre
			)
			```
		lineageTag: 2cf03d56-4939-4450-8517-3e0a22371f2c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure emprest_partes_relacionadas = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    COALESCE(
			    IF(
			CALCULATE(
			    SUMX(
			        FILTER(balancetenew,
			        balancetenew[Query] = "BL_PASSNCIR_Partes_Relacionadas"
			        ),
			        balancetenew[total_mes_atual]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			) < 0,
			CALCULATE(
			    SUMX(
			        FILTER(balancetenew,
			        balancetenew[Query] = "BL_PASSNCIR_Partes_Relacionadas"
			        ),
			        balancetenew[total_mes_atual]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			) * -1,
			CALCULATE(
			    SUMX(
			        FILTER(balancetenew,
			        balancetenew[Query] = "BL_PASSNCIR_Partes_Relacionadas"
			        ),
			        balancetenew[total_mes_atual]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			), 0)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: c10c0c9e-205e-44c8-9386-c627fe89e21c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure emprest_partes_relacionadas_LM = ```
			
			CALCULATE(
			    Medidas_balancetenew[emprest_partes_relacionadas],
			    DATEADD(
			        dCalendario[data], 
			    -1,
			    MONTH
			    )
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 21445111-dc08-45a9-86f4-00728100c2f2

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MReceita_Liquida_acu_LY_normal_card =
			
			CALCULATE(
			    TOTALYTD(
			    [MReceita_Liquida],
			    SAMEPERIODLASTYEAR(dCalendario[data])
			    )
			)
		lineageTag: 315d1932-d536-4df9-9e7e-686d905d8f49

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MReceita_liquida_selecionado = ```
			
			VAR MesSelecionado = SELECTEDVALUE(dCalendario[data])
			RETURN
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew,
			                balancetenew[Query] = "dre_Receita_Liquida"
			            ),
			            balancetenew[vlr]
			        ),
			        DATESBETWEEN(dCalendario[data],
			        MIN(dCalendario[data]),
			        MAX(dCalendario[data])
			    ))
			
			
			
			
			
			```
		lineageTag: c01bbc8f-186d-45d2-8d13-aea79d9146bf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MReceita_bruta_selecionado = ```
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Receita Bruta"
			        ),
			        balancetenew[vlr]
			    )//,    REMOVEFILTERS(dCalendario[data])
			)
			
			```
		lineageTag: 806bd2b4-217f-457f-b5c1-deddc0641f88

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MMargem_bruta_selecionado = ```
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "dre_Lucro_bruto"
			        ),
			        balancetenew[vlr]
			    ),
			    dCalendario[data] >= MIN(dCalendario[data]) &&
			    dCalendario[data] <= MAX(dCalendario[data])
			)
			
			
			```
		lineageTag: f9d1e9f3-a5f4-4f4a-963d-17cd43d74bca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure LLucro_liquido_selecionado = ```
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Lucro_ou_Prejuizo_liquido"
			        ),
			        balancetenew[vlr]
			    ),
			    DATESBETWEEN(
			        dCalendario[data],
			        MINX(ALLSELECTED(dCalendario), dCalendario[data]),
			        MAXX(ALLSELECTED(dCalendario), dCalendario[data])
			    )
			)
			
			
			
			
			```
		lineageTag: 5fe1df7b-7291-4fc3-bb41-58e3d93e0e03

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RResultado_Operacional_selecionado =
			
			VAR MesSelecionado = SELECTEDVALUE(dCalendario[data])
			RETURN
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew,
			                balancetenew[Query] = "DRE_LO_antes_res_financeiro" &&
			                balancetenew[data] <= MesSelecionado
			            ),
			            balancetenew[vlr]
			        ),
			        ALL(dCalendario[data])
			    )
		lineageTag: a824f267-e6ff-451d-a328-bfd82508dfe7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MReceita_bruta_selecionado_LY = ```
			
			CALCULATE(
			    [MReceita_bruta],
			    SAMEPERIODLASTYEAR(dCalendario[data]),
			    ALL(dCalendario)
			)
			
			```
		lineageTag: 17788060-3bb5-49be-825b-582a81c6dbc0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MMargem_Bruta_selecionado_LY_normal_card = ```
			
			CALCULATE(
			    [MMargem_bruta],
			    SAMEPERIODLASTYEAR(dCalendario[data]),
			    ALL(dCalendario)
			)
			
			```
		lineageTag: e9416ca2-40ba-4456-bdcd-207a7045cb5f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MReceita_Liquida_selecionado_LY_normal_card = ```
			
			CALCULATE(
			    [MReceita_Liquida],
			    SAMEPERIODLASTYEAR(dCalendario[data]),
			    ALL(dCalendario)
			)
			
			
			
			
			
			
			
			
			
			
			
			
			
			```
		lineageTag: 6a3a7155-5437-44fc-8ffa-1aaf1b2a4716

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MReceita_Bruta_acu_LY_normal_card =
			
			CALCULATE(
			    [MReceita_Bruta_ACU],
			    SAMEPERIODLASTYEAR(dCalendario[data])
			    )
		lineageTag: 95ac0f4a-4180-4ff7-a2bc-9ab913a90ad3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MReceita_Bruta_selecionado_LY_normal_card =
			
			CALCULATE(
			    [MReceita_Bruta_ACU],
			    SAMEPERIODLASTYEAR(dCalendario[data]),
			    ALL(dCalendario)
			)
		lineageTag: 70825911-fdeb-47b4-a5c9-113fec8798ce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MMargem_Bruta_acu_LY_normal_card =
			
			CALCULATE(
			    TOTALYTD(
			    [MMargem_bruta],
			    SAMEPERIODLASTYEAR(dCalendario[data])
			    )
			)
		lineageTag: a09a54a9-1027-4cc7-9f4a-296cb14acbb3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RResultado_Operacional_selecionado_LY_normal_card =
			
			CALCULATE(
			    [rresultado_operacional],
			    SAMEPERIODLASTYEAR(dCalendario[data]),
			    ALL(dCalendario)
			)
		lineageTag: b08c1453-57f4-496c-93f7-40c96f2e41f7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RResultado_Operacional_acu_LY_normal_card =
			
			CALCULATE(
			    [rresultado_operacional_ACU],
			    SAMEPERIODLASTYEAR(dCalendario[data])
			    )
		lineageTag: 94003f70-0ce3-4d6e-a45a-b5a0abc93c2f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure LLucro_Liq_selecionado_LY_normal_card =
			
			CALCULATE(
			    [LLucro_Liq_selecionado_normal_card],
			    SAMEPERIODLASTYEAR(dCalendario[data]),
			    ALL(dCalendario)
			)
		lineageTag: c9eb68f9-1fa5-4630-8f24-db6d6ca2e440

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure LLucro_Liq_acu_LY_normal_card =
			
			CALCULATE(
			    TOTALYTD(
			    [LLucro_Liq_selecionado_normal_card],
			    SAMEPERIODLASTYEAR(dCalendario[data])
			    )
			)
		lineageTag: b57b5467-d0ce-43e2-8dc5-f11315764748

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure LLucro_Liq_selecionado_normal_card = ```
			
			SUMX(
			        FILTER(balancetenew, 
			        balancetenew[Query] = "DRE_Lucro_ou_Prejuizo_liquido"
			        ),
			    balancetenew[vlr]
			)
			    
			```
		lineageTag: ee5923d8-1dee-4639-b606-432cc13cd5c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CCusto_selecionado =
			
			/*
			VAR MesSelecionado = MAX(dCalendario[data])
			RETURN
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew,
			                balancetenew[Query] = "Custo dos Produtos Vendidos" &&
			                balancetenew[data] <= MesSelecionado &&
			                balancetenew[data] > EDATE(MesSelecionado, -12)
			            ),
			            balancetenew[vlr]
			        ),
			        REMOVEFILTERS(dCalendario[data])
			    )*/
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Custo dos Produtos Vendidos"
			        ),
			        balancetenew[vlr]
			    )//,    REMOVEFILTERS(dCalendario[data])
			)
		lineageTag: fc818ea7-8aca-40f8-b765-08a546e053a3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CCusto_selecionado_LY_normal_card =
			
			CALCULATE(
			    [CCusto_selecionado],
			    SAMEPERIODLASTYEAR(dCalendario[data]),
			    ALL(dCalendario)
			)
		lineageTag: 66339d66-a30d-40dd-86b9-7d995e0e35d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CCusto_selecionado_normal_card = ```
			
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Custo dos Produtos Vendidos"
			        ),
			        balancetenew[vlr]
			    )
			
			```
		lineageTag: 7f079731-0a6e-4f11-a9cf-69f7a42051e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CCusto_acu_LY_normal_card =
			
			CALCULATE(
			    [CCusto_ACU],
			    DATEADD(dCalendario[data], -1, YEAR)
			    )
		lineageTag: 0a063ca6-7416-466b-a091-98a9ce5c0705

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CCusto =
			
			CALCULATE(
			        SUM(
			            balancetenew[vlr]
			        ),
			        FILTER(
			                balancetenew,
			                balancetenew[Query] = "Custo dos Produtos Vendidos" ||
			                balancetenew[Query] = "Custo dos Serviços" ||
			                balancetenew[Query] = "custo_vendas"
			            )
			    )
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: f651d41e-6905-4a14-b088-c17d1758d004

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure EEbitda_selecionado = ```
			
			VAR MesSelecionado = SELECTEDVALUE(dCalendario[data])
			VAR vresultado_operacional =
			    CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Ebitda" 
			        ),
			        balancetenew[vlr]
			    ),
			    DATESBETWEEN(
			        dCalendario[data],
			        MIN(dCalendario[data]),
			        MAX(dCalendario[data])
			    )
			)
			                 
			
			
			VAR v_depreciacao =
			SUMX(
			        FILTER(balancetenew, 
			        balancetenew[Query] = "Ebitda_despesa_depreciacao"
			        ),
			    balancetenew[vlr]
			)
			
			RETURN
			vresultado_operacional 
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 80a78158-8823-4e00-ac59-8788d1875b13

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure EEbitda_ACU_IF =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise],
			        BLANK()
			    ) = "Ano Civil",
			    Medidas_balancetenew[EEbitda_ACU],
			    Medidas_balancetenew[EEbitda_selecionado]
			)
		lineageTag: 7ee779e7-ae32-4db5-bf75-bd4cec01cb2b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure EEbitda_selecionado_normal_card = ```
			
			SUMX(
			        FILTER(balancetenew, 
			        balancetenew[Query] = "DRE_Ebitda" 
			        ),
			    balancetenew[vlr]
			)
			```
		lineageTag: 10121acf-fec6-4aff-8b7d-db93a39e363b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure EEbitda_selecionado_LY_normal_card =
			
			CALCULATE(
			    [EEbitda_selecionado_normal_card],
			    SAMEPERIODLASTYEAR(dCalendario[data]),
			    ALL(dCalendario)
			)
		lineageTag: d17ee9a4-a9d3-4194-84de-cc83184caf52

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure EEbitda_acu_LY_normal_card =
			
			CALCULATE(
			    TOTALYTD(
			    [EEbitda_ACU],
			    SAMEPERIODLASTYEAR(dCalendario[data])
			    )
			)
		lineageTag: 9b8cfe97-d7f1-499f-8156-6b8eead2d2e9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure EEbitda = ```
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_LO_antes_res_financeiro" ||
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao"
			        ),
			        balancetenew[vlr]
			    )
			)
			
			```
		lineageTag: a6dc5b84-7a9e-43d2-b7fc-4969b59630c2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %LLucro_liquido_acu|receita_bruta_acu = ```
			
			DIVIDE(
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[LLucro_liquido_ACU]), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[MReceita_Bruta_ACU]
			    )
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 72c7d775-9857-44eb-aa14-7bad4ce2171a

	measure %margemBruAcu|receita_bruta_acu = ```
			
			DIVIDE(
			    SUMX(
			        'Medidas_balancetenew',
			        'Medidas_balancetenew'[MMargem_Bruta_ACU]), 
			        SUMX('Medidas_balancetenew', 
			        'Medidas_balancetenew'[MReceita_Bruta_ACU]
			        )
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6a93a835-576f-4bce-b2c7-1462a9f432e7

	measure %LLucro_liquido_acu_LY|Mreceita_bruta_acu_LY = ```
			
			CALCULATE(
			    DIVIDE(
			    SUMX('Medidas_balancetenew',
			    'Medidas_balancetenew'[LLucro_liquido_acu_LY]), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[MReceita_Bruta_Acumulada_LY]
			        )
			    )
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9402f4f3-dc83-4e94-8e81-d234de4d966e

	measure %MargemB_acu_LY|receita_bruta_acu_LY = ```
			
			CALCULATE(
			DIVIDE(
			    SUMX('Medidas_balancetenew',
			    'Medidas_balancetenew'[MMargem_Bruta_acu_LY]), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[MReceita_bruta_acu_LY]
			    )
			    )
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2be43d5a-3503-4342-a0bc-1db36b1c30e8

	measure DDespesaADM_selecionado = ```
			
			VAR MesSelecionado = SELECTEDVALUE(dCalendario[data])
			RETURN
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew,
			                balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_administrativas" || 
			                balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Ocupacao" || 
			                balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao" 
			                //&&
			                //balancetenew[data] <= MesSelecionado
			            ),
			            balancetenew[vlr]
			        ),
			        DATESBETWEEN(dCalendario[data],
			        MIN(dCalendario[data]),
			        MAX(dCalendario[data])
			    )
			)
			```
		lineageTag: 336269db-79bd-4936-9325-d097a239963c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DDespesa_comercial_contrat_selecionado =
			
			VAR MesSelecionado = SELECTEDVALUE(dCalendario[data])
			RETURN
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew,
			                balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_comerciais" ||
			                balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_contratuais" ||
			                balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Propaganda_Publicidade" ||
			                balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Frota_Transportes"
			                //&&
			                //balancetenew[data] <= MesSelecionado
			            ),
			            balancetenew[vlr]
			        ),
			        DATESBETWEEN(dCalendario[data],
			        MIN(dCalendario[data]),
			        MAX(dCalendario[data])
			    ))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: aeb36c08-9b90-4ca7-a6f0-c9fff82f5549

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DDespesa_com_pessoal_selecionado = ```
			
			VAR MesSelecionado = SELECTEDVALUE(dCalendario[data])
			RETURN
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew,
			                balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Salarios_ordenados" || 
			                balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Beneficios" || 
			                balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Impostos" || 
			                balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Provisoes" ||
			                balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal" 
			                //&&
			                //balancetenew[data] <= MesSelecionado
			           ),
			            balancetenew[vlr]
			        ),
			        DATESBETWEEN(dCalendario[data],
			        MIN(dCalendario[data]),
			        MAX(dCalendario[data])
			    ))
			```
		lineageTag: 709788bc-3737-4643-a401-494ee5823b58

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DDespesa_com_pessoal_normal_card = ```
			
			SUMX(
			        FILTER(balancetenew, 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal"
			        ),
			    balancetenew[vlr]
			)
			```
		lineageTag: 960afc90-ea69-424f-8c72-83ac4b00ad58

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DDespesa_outras_selecionado = ```
			
			VAR MesSelecionado = SELECTEDVALUE(dCalendario[data])
			RETURN
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew,
			                balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" || 
			                balancetenew[Query] = "DRE_Desp_Operacionais_Outras_despesas_operacionais" || 
			                balancetenew[Query] = "DRE_Desp_Operacionais_Outras_receitas_operacionais" 
			                //&&
			                //balancetenew[data] <= MesSelecionado
			            ),
			            balancetenew[vlr]
			        ),
			        DATESBETWEEN(dCalendario[data],
			        MIN(dCalendario[data]),
			        MAX(dCalendario[data])
			    ))
			```
		lineageTag: bc441855-0e9c-469a-9163-9c6d0098bb4c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ddespesa_adm_acu_LY_normal_card =
			
			CALCULATE(
			    TOTALYTD(
			    [DDespesaADM],
			    SAMEPERIODLASTYEAR(dCalendario[data])
			    )
			)
		lineageTag: ff00325a-73ff-4a51-bcbf-ad674bf86b8a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ddespesa_adm_selecionado_LY_normal_card =
			
			CALCULATE(
			    [DDespesaADM],
			    SAMEPERIODLASTYEAR(dCalendario[data]),
			    ALL(dCalendario)
			)
		lineageTag: 41f3268f-a91c-43f0-9971-1359983df4da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DDespesa_com_acu_LY_normal_card =
			
			CALCULATE(
			    TOTALYTD(
			    [DDespesa_comercial],
			    SAMEPERIODLASTYEAR(dCalendario[data])
			    )
			)
		lineageTag: 75ce339d-7eb4-46f3-a84d-151d612f9468

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DDespesa_comercial =
			SUMX(
			    FILTER(balancetenew,
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_comerciais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_contratuais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Propaganda_Publicidade" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Frota_Transportes"
			    ),
			    balancetenew[vlr]
			)
		lineageTag: 5bec6d96-42d3-422a-bad5-f8a66d8b9eba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DDespesa_com_selecionado_LY_normal_card =
			
			CALCULATE(
			    [DDespesa_comercial],
			    SAMEPERIODLASTYEAR(dCalendario[data]),
			    ALL(dCalendario)
			)
		lineageTag: 0f20b9c5-1ae6-4943-8d8b-7f62f3392ecc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DDespesa_com_pessoal_selecionado_LY_normal_card =
			
			CALCULATE(
			    [DDespesaPessoal],
			    SAMEPERIODLASTYEAR(dCalendario[data]),
			    ALL(dCalendario)
			)
		lineageTag: cf8f8e9f-887d-443c-9e90-4eea19ce0aad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DDespesa_com_pessoal_acu_LY_normal_card =
			
			CALCULATE(
			    TOTALYTD(
			    [DDespesaPessoal],
			    SAMEPERIODLASTYEAR(dCalendario[data])
			    )
			)
		lineageTag: 2bdf8b37-c675-4799-985f-bb2381e17b84

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DDespesa_outras_selecionado_LY_normal_card =
			
			CALCULATE(
			    [DDespesa_outras],
			    SAMEPERIODLASTYEAR(dCalendario[data]),
			    ALL(dCalendario)
			)
		lineageTag: d31ece93-d0bd-4b9c-9768-75361e23f8d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DDespesa_outras_acu_LY_normal_card =
			
			CALCULATE(
			    TOTALYTD(
			    [DDespesa_outras],
			    SAMEPERIODLASTYEAR(dCalendario[data])
			    )
			)
		lineageTag: 5590de55-9c22-4489-8437-5f49ccede288

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tributos_incidentes_selecionado = ```
			
			VAR MesSelecionado = SELECTEDVALUE(dCalendario[data])   
			RETURN
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew,
			                balancetenew[Query] = "DRE_Imp_Incidentes_Sobre_Receita"
			            ),
			            balancetenew[vlr]
			        ),
			        DATESBETWEEN(dCalendario[data],
			        MIN(dCalendario[data]),
			        MAX(dCalendario[data])
			    ))
			```
		lineageTag: 52024a99-04b3-4139-b2e5-09e6267462cb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tributos_incidentes_selecionado_LY_normal_card =
			
			CALCULATE(
			    [TributosIncidentes],
			    SAMEPERIODLASTYEAR(dCalendario[data]),
			    ALL(dCalendario)
			)
		lineageTag: cc100fd0-2453-41c0-83d6-f60f24ee5417

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tributos_incidentes_acu_LY_normal_card =
			
			CALCULATE(
			    TOTALYTD(
			    [TributosIncidentes],
			    SAMEPERIODLASTYEAR(dCalendario[data])
			    )
			)
		lineageTag: cadb0ec5-0362-49ff-ae3a-6ecd5dd66816

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MesMaisAntigo =
			
			CALCULATE(
			    MIN(dCalendario[Mês Completo]),
			    FILTER(
			        ALL(dCalendario),
			        dCalendario[data] = EOMONTH(
			            MIN(dCalendario[data]),-0
			    )
			)
			)
		lineageTag: 4509e6a4-c6d2-433d-a52b-cd2d4a7e6bd5

	measure DDespesaADM_sinal_positivo = ```
			SUMX(
			    FILTER(balancetenew,
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_administrativas" || 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Ocupacao" || 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao"
			    ),
			    balancetenew[vlr]
			) *-1
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 23f173dd-20f5-4cc5-ac27-7fff3a158002

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure %CCustoAcu|receita_bruta_acu = ```
			
			CALCULATE(
			DIVIDE(
			    SUMX('Medidas_balancetenew',
			    'Medidas_balancetenew'[CCusto_ACU]), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[MReceita_Bruta_ACU]))) * -1
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: afcfa5f9-4fa2-44aa-a081-6364b1fd0c42

	measure %Resultado_Op_ACU|Receita_Bruta_ACU = ```
			
			DIVIDE(
			    SUMX(
			        'Medidas_balancetenew', 
			        'Medidas_balancetenew'[rresultado_operacional_ACU]
			        ), 
			        SUMX('Medidas_balancetenew', 
			        'Medidas_balancetenew'[MReceita_Bruta_ACU]
			        )
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d104b627-d14f-4b67-97f9-d4c310d06834

	measure CCusto_grafico =
			
			CALCULATE(
			        SUM(
			            balancetenew[vlr]
			        ),
			        FILTER(
			                balancetenew,
			                balancetenew[Query] = "Custo dos Produtos Vendidos"
			            )
			    ) * -1
		formatString: #,0
		lineageTag: a12e1427-5f9b-47b7-9c98-8cc90006d1bd

		annotation PBI_FormatHint = {"isDecimal":true}

	measure BL_ATCIR_total_ativo_circulante = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			    RETURN
			    CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew, balancetenew[Query] = "BL_ATCIR_soma"
			        ), 
			        balancetenew[vlr]
			        ),
			        dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre)
			```
		formatString: #,0
		lineageTag: 1bdeb6de-f2d8-46e3-9443-23150fce5a07

		annotation PBI_FormatHint = {"isDecimal":true}

	measure BL_ATCIR_total_ativo_n_circulante = ```
			
			SUMX(
			    FILTER(
			        balancetenew, balancetenew[Query] = "BL_ATNCIR_soma"
			        ), 
			        balancetenew[vlr]
			        )
			```
		formatString: #,0
		lineageTag: c1b70b55-cd16-4a57-8a98-4a6bc6a7ba8b

		annotation PBI_FormatHint = {"isDecimal":true}

	measure BL_PASSCIR_total_passivo_circulante = ```
			
			SUMX(
			    FILTER(
			        balancetenew, balancetenew[Query] = "BL_PASSCIR_soma"
			        ), 
			        balancetenew[vlr]
			        ) * -1
			```
		formatString: #,0
		lineageTag: 83b762c4-f6d2-4c77-bea0-b033dd4c4ec9

		annotation PBI_FormatHint = {"isDecimal":true}

	measure BL_PASSNCIR_total_passivo_n_circulante = ```
			
			SUMX(
			    FILTER(
			        balancetenew, balancetenew[Query] = "BL_PASSNCIR_soma"
			        ), 
			        balancetenew[vlr]
			        ) * -1
			```
		formatString: #,0
		lineageTag: be8475ae-8dc1-4c08-a0fe-a73b30e5705e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure totpassivo_grafico = ```
			
			SUMX('Medidas_balancetenew', 
			'Medidas_balancetenew'[ssomapasscircu]) +  
			SUMX('Medidas_balancetenew', 
			'Medidas_balancetenew'[ssomapassncirculante]) * -1
			```
		lineageTag: 023005f8-3560-4fe9-b85a-293145fc3db4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Compras_mês_a_mês = Medidas_balancetenew[CCusto_ACU] *-1 + Medidas_balancetenew[ATCIR_Estoques] - Medidas_balancetenew[ATCIR_EstoquesLM]
		formatString: #,0
		lineageTag: 9e972f2a-5d0d-4d1c-b013-9058398b336c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure necessidade_cap_giro_menos_cap_giro =
			
			Medidas_balancetenew[ccapit_giro] - Medidas_balancetenew[NNecessidadeCPTgiro]
		lineageTag: 970d897e-e0c6-47ce-8fe7-95ab662aeb7d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BL_PASSNCIR_outras_contas_a_pagar_CP = ```
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			RETURN
			CALCULATE(
			    SUMX(
			        FILTER(balancetenew, 
			        balancetenew[Query] = "BL_PASSNCIR_Outras_Contas_Pagar"
			    ), 
			    
			    balancetenew[vlr])*-1,
			    dCalendario[data] = UltimoMesTrimestre
			
			)
			```
		lineageTag: f4a2aa96-010a-4ee4-b483-efd88e1e31cf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure outras_contas_a_pagar_grafico = ```
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			RETURN
			CALCULATE(
			    SUMX(
			        FILTER(balancetenew, 
			        balancetenew[Query] = "BL_PASSCIR_Outras_Contas_Pagar" || 
			        balancetenew[Query] = "BL_PASSNCIR_Outras_Contas_Pagar"
			    ), 
			    
			    balancetenew[vlr]),
			    dCalendario[data] = UltimoMesTrimestre
			
			)
			```
		lineageTag: 37555ed3-b863-4251-be5a-f4cc8a7cf165

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Obrigacoes_Tributarias_actual_month_grafico = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Tributarias" 
			    ),
			    balancetenew[vlr]
			),
			 dCalendario[data] = UltimoMesTrimestre
			    )
			```
		lineageTag: 384c4bd7-1be5-4e4a-ab28-e64014a85747

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PASSCIR_Obrigacoes_Trabalhistas_Actual_Month_grafico = ```
			
			 VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    
			    RETURN
			CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "BL_PASSCIR_Obrigacoes_Trabalhistas"), 
			        balancetenew[vlr]
			        ),
			         dCalendario[data] = UltimoMesTrimestre
			)
			```
		lineageTag: 4b33db35-1bc0-4860-ab50-515d372dc922

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RReceita_outras = ```
			SUMX(
			    FILTER(balancetenew,
			        balancetenew[Query] = "DRE_Desp_Operacionais_Outras_receitas_operacionais"
			    ),
			    balancetenew[vlr]
			) 
			```
		lineageTag: e3c8fa8f-ea57-4e1e-ac0e-2180c91713b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Variação de Caixa' = ```
			
			    SUMX(
			        FILTER(balancetenew, 
			        balancetenew[Query] = "DFC_caixasequicaixas"
			        ),
			    balancetenew[vlr]
			)
			
			```
		lineageTag: aef09985-3f8d-4d3c-a684-cf54fe6eae2d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %CCustovsanterior_acu =
			
			DIVIDE(
			    [CCusto_ACU] - [CCusto_acu_LY],
			    [CCusto_acu_LY]
			    )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 921437c8-e2ad-40c8-9a6c-4a948b50442d

	measure desvio_ccustos_acum =
			
			CALCULATE(
			'Medidas_balancetenew'[CCusto_ACU_tabela] - 'Medidas_balancetenew'[CCusto_acu_LY]) *-1
		lineageTag: 958aee02-6de1-4d7f-9c12-85cad457f9f0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %MMargemBrutaAcum = ```
			
			DIVIDE(
			        
			        'Medidas_balancetenew'[MMargem_Bruta_ACU] - 'Medidas_balancetenew'[MMargem_Bruta_acu_LY],
			       'Medidas_balancetenew'[MMargem_Bruta_acu_LY]
			        )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b0777f4e-b171-4cf4-a5f4-443b974e3024

	measure TributosIncidentes_grafico = ```
			SUMX(
			    FILTER(balancetenew, 
			    balancetenew[Query] = "DRE_Imp_Incidentes_Sobre_Receita"), 
			    balancetenew[vlr]
			    ) *-1
			```
		lineageTag: 0c8d6f0c-c00a-4e7f-82eb-aec1a76c6653

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure LLucro_liquido = ```
			
			CALCULATE(
			    SUM(balancetenew[vlr]),
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "DRE_Lucro_ou_Prejuizo_liquido" &&
			        YEAR(balancetenew[data]) = YEAR(MAX(dCalendario[data])) &&
			        MONTH(balancetenew[data]) = MONTH(MAX(dCalendario[data]))
			    )
			)
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 69e2224a-45d4-4980-91b6-dfb0841f7f3e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Lucro_liquido_LY = ```
			
			CALCULATE('Medidas_balancetenew'[LLucro_liquido],DATEADD(dCalendario[data],-1,YEAR))
			
			
			```
		lineageTag: 38a05512-ac33-461f-910f-5c44cf20ff48

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure receita_financeira = ```
			
			CALCULATE(
			        SUMX(FILTER(balancetenew, 
			            balancetenew[Query] = "DRE_Receita_financeira"), 
			            balancetenew[vlr]
			        ))
			```
		formatString: #,0
		lineageTag: 003f0a41-fb5a-4ba5-978a-9e308588d699

		annotation PBI_FormatHint = {"isDecimal":true}

	measure despesa_financeira = ```
			
			CALCULATE(
			        SUMX(FILTER(balancetenew, 
			            balancetenew[Query] = "DRE_Despesa_financeira"), 
			            balancetenew[vlr]
			        )
			)
			```
		formatString: #,0
		lineageTag: 8f8b5adf-dc15-4312-a432-590a6b20154d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure resultado_financeiro =
			
			CALCULATE(
			    SUMX(
			        VALUES(dCalendario[data]),
			        Medidas_balancetenew[receita_financeira] + Medidas_balancetenew[despesa_financeira]
			    )
			    )
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 1af13a1b-e6a1-495b-b1f6-2a6da98ff6f5

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure switch_operação_compras =
			
			SWITCH(
			    SELECTEDVALUE(
			        F_Aging_List_Contas_Pagar[origem_operacao]),
			        "Administrativo", "Produto",
			         "Imobilizado", "Produto",
			        "Oficina", "Produto",
			        "Produto", "Produto",
			        "Uso e Consumo", "Produto",
			        "Veículo", "Veículo",
			        "Serviço", "Produto"
			        )
		lineageTag: ac84c43d-bbec-438e-aec5-971223d9e797

	measure switch_operacao_vendas =
			
			SWITCH(
			    SELECTEDVALUE(
			        F_Aging_List_Contas_Receber[origem_operacao]),
			        "Administrativo", "Produto",
			         "Imobilizado", "Produto",
			        "Oficina", "Produto",
			        "Produto", "Produto",
			        "Uso e Consumo", "Produto",
			        "Veículo", "Veículo",
			        "Serviço", "Produto"
			        )
		lineageTag: 07d4c9f6-57ab-45a1-ab62-701fb9f877ab

	measure ciclo_economico = [Prazo Médio do Giro do Estoque] + [Prazo Médio Contas a Receber] - [Prazo Médio Contas a Pagar]
		lineageTag: 00d07389-9d8e-42a5-b619-4a524ff27fdd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lliquidez geral LY' = CALCULATE('Medidas_balancetenew'[lliquidez geral],DATEADD(dCalendario[data],-1,YEAR))
		lineageTag: 96b3cc96-3100-4306-8a46-f85a8a3373f1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure capit_terc_S_PL_LY = CALCULATE(Medidas_balancetenew[indicador_capital_terceiros_S_PL],DATEADD(dCalendario[data],-1,YEAR))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b9a638ea-1480-4ef9-90ef-142fd4f68424

	measure capit_terc_S_ATV_LY = CALCULATE(Medidas_balancetenew[capital_terceiros_S_Atv],DATEADD(dCalendario[data],-1,YEAR))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a420fd9b-e629-446a-89bf-3848bb0a9445

	measure capital_terceiros_CP_LY = CALCULATE(Medidas_balancetenew[Capital_Terceiros_CP],DATEADD(dCalendario[data],-1,YEAR))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e8550834-022f-421b-bb15-135c692ea586

	measure MReceita_Liquida_LY =
			
			CALCULATE('Medidas_balancetenew'[MReceita_Liquida],DATEADD(dCalendario[data],-1,YEAR))
		lineageTag: 774ad347-667c-4370-aa2f-fd10d29ab080

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure capital_de_giro = [contas receber] + [BL_ATCIR_Estoques] - [BL_PASSCIR_Fornecedores]
		lineageTag: b19787df-09fd-4455-b621-3df7b3dc8df7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'capital_de_giro_base_ $100' = ```
			
			 DIVIDE(
			    [capital_de_giro],
			 [MReceita_Liquida] * [Valor_mensal]
			 )
			```
		formatString: 0
		lineageTag: b80bd812-9bd4-49be-b83f-61100675c99c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure CCustoLY_grafico = CALCULATE('Medidas_balancetenew'[CCusto_actual_month], DATEADD(dCalendario[data], -1, YEAR)) * -1
		lineageTag: 705f2a99-3798-457e-9ecf-8febc1f7359c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure rresultado_operacionalLY = CALCULATE('Medidas_balancetenew'[rresultado_operacional],DATEADD(dCalendario[data],-1,YEAR))
		lineageTag: c3ee0f74-3581-4ffd-941b-2df32aa41414

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CCusto_ACU_tabela = ```
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			CALCULATE(
			    SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "Custo dos Produtos Vendidos"
			    ), 
			        balancetenew[vlr]
			    ), 
			    DATESYTD(dCalendario[data]
			    )
			),
			[CCusto_selecionado]
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 90577f3a-615d-44aa-a318-60f25fd0c214

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure CCusto_ACU_normal_card = ```
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			CALCULATE(
			    SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "Custo dos Produtos Vendidos"
			    ), 
			        balancetenew[vlr]
			    ), 
			    DATESYTD(dCalendario[data]
			    )
			),
			[CCusto_selecionado]
			)
			```
		formatString: #,0
		lineageTag: 4284c4fe-6709-4f50-9e6e-e0c90ea57aa6

		annotation PBI_FormatHint = {"isDecimal":true}

	measure DDespesaComercial_ACU_LY =
			
			CALCULATE(
			    [DDespesa_Comercial_ACU],
			    DATEADD(dCalendario[data], -1, YEAR
			    )
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: cadae60c-783c-46c8-baae-0f90a8276c8d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure %DDespesaComercial_ACU =
			
			CALCULATE(
			    DIVIDE([DDespesaComercial_ACU_LY] -
			    [DDespesa_Comercial_ACU],
			    ABS([DDespesa_Comercial_ACU]
			    ))
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 248810a3-20fa-4f8d-9343-f27311db2cd9

	measure %Despesa_pessoal_anterior_ACU =
			
			CALCULATE(
			    DIVIDE(
			        [DDespesa_com_pessoal_ACU] -
			        [DDespesaPessoal_acu_anoAnterior],
			        [DDespesa_com_pessoal_ACU]
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 164be6b1-1e72-49d4-b5a0-0b5d8427fca3

	measure %DDespesaAdm_anoanterior_ACU =
			
			CALCULATE(
			    DIVIDE(
			        [DDespesa_adm_acu_LY] -
			        [DDespesa_adm_acu],
			       ABS( [DDespesa_adm_acu]
			    )))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 14c0f7cf-f4fa-479a-ae52-96ae68fc2a72

	measure %_DDespesa_outras_LY_Acum =
			
			CALCULATE(
			    DIVIDE([DDespesa_outras_ACU] -
			        [DDespesa_outras_acu_LY]
			        ,
			        [DDespesa_outras_acu_LY]
			
			)
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c9ae72a8-829c-45df-b391-e5d8af364367

	measure ano_minimo = ```
			
			CALCULATE(
			    SELECTEDVALUE(dCalendario[Ano], MIN(dCalendario[Ano])
			    )
			)
			
			```
		formatString: 0
		lineageTag: d047c83a-8198-42eb-8665-d045a72895cf

	measure mes_minimo =
			
			CALCULATE(
			    SELECTEDVALUE(dCalendario[Mês], MIN(dCalendario[Mês])
			    )
			)
		lineageTag: 62c763bf-74f4-4e6f-91d1-a243bc52fd41

	measure EBIT_resultado_operacional =
			
			CALCULATE(
			        SUM(
			            balancetenew[vlr]
			        ),
			        FILTER(
			                balancetenew,
			                balancetenew[Query] = "DRE_LO_antes_res_financeiro"
			            )
			    )
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 06f63802-f653-407d-9494-087ae9be1bf6

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'EBITDA Médio' = ```
			
			VAR v_ebitda_selecionado = [EEbitda_selecionado_normal_card] 
			VAR v_MesesSelecionados =
			  VALUES(dcalendario[Mês Completo])
			VAR v_qtd_meses_selecionados =
			SUMX(
			    v_MesesSelecionados,
			    1
			)
			
			RETURN
			DIVIDE(
			v_ebitda_selecionado,
			v_qtd_meses_selecionados
			)
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 636a5698-3d49-4c49-8943-c50e4fa0d574

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure grupo_selecionado =
			
			SELECTEDVALUE(d_clientes_time[grupo])
		lineageTag: 704db20f-894a-4519-a3ce-69f65fce9e52

	measure Total_Obrigacoes_TributariasLY = CALCULATE('Medidas_balancetenew'[Total_Obrigacoes_Tributarias], DATEADD(dCalendario[data], -1, YEAR))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 8ff46948-3c0f-463b-89ce-31bbeba79d03

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Total_Obrigacoes_Tributarias|ReceitaLiquidaLY = CALCULATE('Medidas_balancetenew'[Total_Obrigacoes_Tributarias|ReceitaLiquida],DATEADD(dCalendario[data],-1,YEAR))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: fe12210d-286f-4c69-93fd-1a0b2d4ec93b

	measure Margem_liquida = ```
			
			
			CALCULATE(    
			    DIVIDE(
			    [LLucro_liquido_actual_month],
			    [MReceita_Liquida_actual_month]
			        )
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4a101953-2269-48b2-953f-0a9d89da5f11

	measure MReceita_Liquida_actual_month = ```
			
			 VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			    RETURN
			    CALCULATE(
			SUMX(
			    FILTER(balancetenew,
			        balancetenew[Query] = "Receita Bruta" || 
			        balancetenew[Query] = "Deduções da Receita Bruta" || 
			        balancetenew[Query] = "DRE_Imp_Incidentes_Sobre_Receita"
			    ),
			    balancetenew[vlr]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			    )
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 98f8fc13-589b-450c-af53-4c17ccb75e86

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MReceita_bruta_rentab = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			    RETURN
			    CALCULATE(
			        SUMX(
			        FILTER(balancetenew, 
			        balancetenew[Query] = "Receita Bruta"
			        ),
			    balancetenew[vlr]
			),
			    dCalendario[data] = UltimoMesTrimestre
			    )
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 4888fcbd-27b3-4fca-9237-85811b3a13aa

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure receita_bruta|impostos_incidentes =
			
			DIVIDE(
			    [Impostos Incidentes sobre a receita],
			    [MReceita_bruta_rentab]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a152195c-4fd5-4529-9068-638c5ff721c4

	measure variacao_receita_bruta =
			
			DIVIDE(
			    [MReceita_bruta_rentab] - [Mreceita_bruta_LM],
			    [Mreceita_bruta_LM])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9165f4be-6319-4984-bbb3-9e43c60e2aba

	measure Mreceita_bruta_LM =
			
			CALCULATE(
			    [MReceita_bruta_rentab], DATEADD(dCalendario[data], -1, MONTH
			    ))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 3eb5629a-34f6-4ff4-9635-509d032d1e0f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure variacao_custo =
			
			DIVIDE(
			    [CCusto_actual_month] - [CCustoLM],
			    [CCustoLM]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d0bcd9d6-0dac-4eec-80ce-9935f6daf6bd

	measure variacao_receita_liquida =
			
			DIVIDE(
			    [MReceita_Liquida_actual_month] - [MReceita_Liquida_LM_rentab],
			    [MReceita_Liquida_LM_rentab])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 06d3414f-1bf3-4ea7-8f65-35d9a65935da

	measure MReceita_Liquida_LM_rentab = CALCULATE('Medidas_balancetenew'[MReceita_Liquida_actual_month], DATEADD(dCalendario[data],-1,MONTH))
		lineageTag: ac962a36-2584-462a-b368-9f96241e3006

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MargemBru|ReceitaLiquida_rentab = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[MMargem_bruta_actual_month]), 
			            SUMX('Medidas_balancetenew', 
			            'Medidas_balancetenew'[MReceita_Liquida_actual_month]
			        )
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e546aeb8-f409-453c-b76e-24fea724b0c9

	measure CCusto_actual_month_rentab = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "Custo dos Produtos Vendidos"
			    ), 
			        balancetenew[vlr]
			    ),
			dCalendario[data] = UltimoMesTrimestre
			) *-1
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 139a631d-2bbc-4489-b3fe-80dd790eb2cd

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure receita_liq_video = [MReceita_Liquida]
		lineageTag: b1df2c38-3b80-4017-8c4a-d9cd4af2b6e9

		formatStringDefinition = ```
				VAR V_receita = [MReceita_Liquida_actual_month]
				VAR V_variacao = 
				DIVIDE(
				    [MReceita_Liquida] - [MReceita_Liquida_LM_rentab],
				    [MReceita_Liquida_LM_rentab])
				VAR V_formato = 
				SWITCH(
				    TRUE(),
				    V_receita >= 1000000000, "R$ #,#0,0B;R$ -#,#0,0B",
				    V_receita >= 1000000, "R$ #,#0,M; R$ -#,#0,M",
				    V_receita >= 1000, "R$ #,#0,K;R$ -#,#0,K",
				    "R$ #,#0,.00;R$ -#,#0,0.00"
				)
				VAR V_icone = 
				IF(V_variacao > 0, " ⇡", " ⇣")
				RETURN
				"""" & FORMAT(V_receita, V_formato) & " | " &
				"""" & FORMAT(V_variacao, "0%;-0%") &
				V_icone
				
				
				
				```

	measure variacao_custo_rentab =
			
			DIVIDE(
			    [CCusto_actual_month_rentab] - [CCustoLM_rentab],
			    [CCustoLM_rentab]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4c4a2b1c-14f4-4674-9e53-1512fc02d042

	measure CCustoLM_rentab = CALCULATE('Medidas_balancetenew'[CCusto_actual_month_rentab], DATEADD(dCalendario[data], -1, MONTH))
		lineageTag: e0121534-a8e7-460b-8eaf-4cbc069c24e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ccusto_video =
			
			[CCusto_actual_month_rentab]
		lineageTag: f5a337bc-5d30-4ad8-a5ca-6234fd4fa185

		formatStringDefinition = ```
				VAR V_receita = [CCusto_actual_month_rentab]
				VAR V_variacao = [variacao_custo_rentab]
				VAR V_formato = 
				SWITCH(
				    TRUE(),
				    V_receita >= 1000000000, "R$ #,#0,0B;R$ -#,#0,0B",
				    V_receita >= 1000000, "R$ #,#0,M; R$ -#,#0,M",
				    V_receita >= 1000, "R$ #,#0,K;R$ -#,#0,K",
				    "R$ #,#0,.00;R$ -#,#0,0.00"
				)
				VAR V_icone = 
				IF(V_variacao > 0, " ⇡", " ⇣")
				RETURN
				"""" & FORMAT(V_receita, V_formato) & " | " &
				"""" & FORMAT(V_variacao, "0,0%;-0,0%") &
				V_icone
				```

	measure Valuation =
			
			([ebitda_medio_CFS] *  [Multiplo_card]) + [divida_liquida]
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 169492b6-22f8-44dc-aab2-efe452deec9a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure divida_liquida = [eemprestEFinanc_CP] + [eemprestEFinanc_LP] - [caixasequicaixas]
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 0daa6b69-8868-4ccd-9784-4bbaa1bd7bf2

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Valor_Bruto_do_negocio =
			
			[Multiplo_card] * [ebitda_medio_CFS] -[ajuste_ebitda_card]
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 689810b4-0425-4a59-83ee-ad9992b29412

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure totpassivo+PL = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			VAR v_passivo_circulante = CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			           balancetenew[Query] = "BL_PASSCIR_soma"
			        ),
			        balancetenew[total_mes_atual]
			    ), dCalendario[data] = UltimoMesTrimestre)
			
			VAR v_passivo_n_circulante = CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "BL_PASSNCIR_soma"
			        ),
			        balancetenew[total_mes_atual]
			    ), dCalendario[data] = UltimoMesTrimestre)  
			
			VAR v_PL = CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "BL_PL_soma"
			        ),
			        balancetenew[total_mes_atual]
			    ), dCalendario[data] = UltimoMesTrimestre)
			    RETURN
			CALCULATE(
			    IF( v_passivo_circulante > 0, v_passivo_circulante, v_passivo_circulante * -1) +
			        IF( v_passivo_n_circulante > 0, v_passivo_n_circulante, v_passivo_n_circulante * -1) +
			            IF( v_PL > 0, v_PL, v_PL * -1)
			    )
			```
		lineageTag: a4696033-1b71-4e0d-964e-969068017ce2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure saldo_passivo_balancetenew =
			
			VAR fornecedores =
			    SUMX(
			        VALUES(balancetenew[cnpj]),
			        VAR CNPJAtual = balancetenew[cnpj]
			        VAR ValorFornecedor =
			            CALCULATE(
			                SUM(balancetenew[vlr]),
			                balancetenew[Query] = "BL_PASSCIR_Fornecedores"
			            )
			        RETURN
			            IF(
			                CNPJAtual IN {
			                    "07543035000116",
			                    "17032154000168"
			                },
			                ValorFornecedor,
			                ABS(ValorFornecedor)
			            )
			    )
			
			VAR passivo_circulante =
			    CALCULATE(
			        SUM(balancetenew[vlr]),
			        balancetenew[Query] = "BL_PASSCIR_soma"
			    ) * -1
			
			VAR passivo_ncircuante =
			    CALCULATE(
			        SUM(balancetenew[vlr]),
			        balancetenew[Query] = "BL_PASSNCIR_soma"
			    ) * -1
			
			VAR todas_as_contas =
			    CALCULATE(
			        SUM(balancetenew[vlr]),
			        balancetenew[Query] <> "BL_PASSCIR_Fornecedores",
			        balancetenew[Query] <> "BL_PASSCIR_soma",
			        balancetenew[Query] <> "BL_PASSNCIR_soma"
			    )
			
			RETURN
			    passivo_circulante
			        + passivo_ncircuante
			        + fornecedores
			        + todas_as_contas
		formatString: #,0
		lineageTag: d71c5b1c-9e48-45dc-9ed5-a8260a7a22e3

		annotation PBI_FormatHint = {"isDecimal":true}

	measure %margem_bruta =
			
			VAR diferenca = [MMargem_bruta_actual_month] - [MMargem_brutaLM]
			VAR variacao = diferenca / ABS([MMargem_brutaLM])
			RETURN
			variacao
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 061d517e-225b-454e-b4b8-0ae558bedfa9

	measure %margem_bruta_acu =
			
			VAR diferenca = [MMargem_Bruta_ACU] - [MMargem_Bruta_acu_LY]
			VAR variacao = diferenca / ABS([MMargem_Bruta_acu_LY])
			RETURN
			variacao
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 408a76fa-754b-432d-89f9-6bd88b99d8d1

	measure CCusto_ACU_rentab = ```
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			CALCULATE(
			    SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "Custo dos Produtos Vendidos"
			    ), 
			        balancetenew[vlr]
			    ), 
			    DATESYTD(dCalendario[data]
			    )
			),
			[CCusto_selecionado]
			) *-1
			```
		lineageTag: f29b57ba-9820-4715-ab89-de661bf16d22

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CCusto|ReceitaLiquida_acu = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[CCusto_ACU]), 
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[MReceita_Liquida_ACU]
			            )
			        ),
			    dCalendario[data] = UltimoMesTrimestre
			) *-1
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e2bf229d-7fa2-439e-a93d-5a4322caed19

	measure TributosIncidentes_ACU_rentab = ```
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			        CALCULATE(
			            [TributosIncidentes_Rentab],
			                DATESYTD(dCalendario[data]
			            )
			        ),
			        Medidas_balancetenew[Tributos_incidentes_selecionado_Rentab]
			        
			) *-1
			```
		lineageTag: cee31fa2-c7db-48c3-85a2-4e5eec360e36

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CCusto|Receitabruta = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[CCusto_actual_month]), 
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[MReceita_bruta]
			            )
			        ),
			    dCalendario[data] = UltimoMesTrimestre
			) *-1
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f6999160-b80f-40fe-9f91-2f5aa5897dd2

	measure CCusto|receitabrutaLM = CALCULATE('Medidas_balancetenew'[CCusto|Receitabruta],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5c5bd9e5-361e-4984-bc00-d4559b9ac5dd

	measure %ccustoAcu_receitabruta_acu = ```
			
			CALCULATE(
			DIVIDE(
			    SUMX('Medidas_balancetenew',
			    'Medidas_balancetenew'[CCusto_ACU]) *-1, 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[MReceita_Bruta_ACU])))
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: eca844cf-8fa4-4ce2-8719-ae378ac7a0b8

	measure TributosIncidentesCPRB = ```
			
			SUMX(
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "DRE_Imp_Incidentes_Sobre_Receita" && 
			        (
			            balancetenew[descricao_cliente] = "(-) INSS SOBRE RECEITA BRUTA" || 
			            balancetenew[descricao_cliente] = "( - ) INSS PLANO BRASIL MAIOR"
			        )
			    ), 
			    balancetenew[vlr]
			) *-1
			```
		lineageTag: 9b0920d5-dfca-4532-b2fb-639530d47df5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure variacao_desp_controladas_acu =
			
			DIVIDE(
			    [DDespesaControladas_ACU] - [DDespesaControladas_ACUanoAnterior],
			    [DDespesaControladas_ACUanoAnterior])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 322898d0-3221-40fd-b79c-45c6a94d7c82

	measure %DDespNaoControladas_Acu_atual|anterior_MC = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			    'Medidas_balancetenew'[DDespesaNaoControladas_ACU_MC] - 'Medidas_balancetenew'[DDespesaNaoControladas_ACUanoAnterior_MC],
			    'Medidas_balancetenew'[DDespesaNaoControladas_ACUanoAnterior_MC]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 71920ba5-0399-472b-9480-23a663cdb675

	measure volumetria_balancetenew =
			
			IF(NOT(ISBLANK(balancetenew[total_mes_atual])), "🟢", "🔴")
		lineageTag: f0f997f2-011d-41b8-a8c8-9c1408db7279

	measure MReceita_Bruta_ACU_rentab =
			
			VAR receita_ano_civil =
			CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew,
			                balancetenew[Query] = "Receita Bruta"
			            ),
			            balancetenew[vlr]
			        ),
			        DATESYTD(dCalendario[data])
			    )
			 VAR MesSelecionado = SELECTEDVALUE(dCalendario[data])
			VAR receita_selecionado =
			    [MReceita_Bruta_Selecionado_KPI]
			
			    RETURN
			
			    IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    receita_ano_civil,
			    receita_selecionado
			    )
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 4187e4cc-77cf-4e32-a716-6521c8827c70

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Legenda_obrigacoes_tributarias = ```
			
			    VAR TotalImposto =[Obrigacoes_Tributarias_ISS]
			    RETURN
			        IF(TotalImposto > 0, [Obrigacoes_Tributarias_ISS],  BLANK())
			
			```
		lineageTag: 583396e0-e641-4feb-ac8f-6a025f768a05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ciclo_financeiro II' =
			
			[ciclo_operacional II] - [Prazo Médio Contas a Pagar]
		formatString: 0
		lineageTag: 903beca0-7836-4fa7-96f1-1ced88dcc104

		annotation PBI_FormatHint = {"isDecimal":true}

	measure rresultado_operacional_selecionado_normal_card = ```
			
			SUMX(
			        FILTER(balancetenew, 
			        balancetenew[Query] = "DRE_LO_antes_res_financeiro"
			        ),
			    balancetenew[vlr]
			)
			```
		lineageTag: a376bc6e-2536-4bdc-8b32-775da21da794

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MReceita_liquida_selecionado_normal_card = ```
			
			CALCULATE(
			SUMX(
			        FILTER(balancetenew, 
			        balancetenew[Query] = "dre_Receita_Liquida"
			        ),
			    balancetenew[vlr]
			),
			DATESBETWEEN(dCalendario[data],
			MIN(dCalendario[data]),
			MAX(dCalendario[data])))
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 9e0775b8-930c-4a6b-8c65-67529035b03a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MReceita_Liquida_ACU_normal_card =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    CALCULATE(
			        [MReceita_Liquida],
			        DATESYTD(
			            dCalendario[data]
			        )
			    ),
			    Medidas_balancetenew[MReceita_liquida_selecionado_normal_card])
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 8dded057-10f8-4ad0-875f-8a8007872e80

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Eebitda_ACU_normal_card =
			
			CALCULATE(
			    [EEBITDA_actual_month], DATESYTD(dCalendario[data]))
		lineageTag: c71f352c-7b0c-443b-b014-f6253a63221a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure gastos_gerais_LM = ```
			
			 CALCULATE(
			    [gastos_gerais_video], 
			    DATEADD(
			        dCalendario[data], -1, MONTH
			        )
			        )
			```
		lineageTag: 3f43e0fb-6209-4454-9735-80c1a9c60101

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure lucratividade = ```
			
			VAR vvariacao_margem = 
			DIVIDE(
			    [MMargem_bruta] - [MMargem_brutaLM], [MMargem_brutaLM])
			
			VAR vvariacao_gastos = 
			DIVIDE([gastos_gerais] - [gastos_gerais_LM], [gastos_gerais_LM])   
			
			VAR vvariacao_ebit =
			DIVIDE(
			    [rresultado_operacional] - [rresultado_operacionalLM], [rresultado_operacionalLM])
			
			
			
			
			VAR ReceitaBruta = [MReceita_bruta_rentab]
			VAR MargemBruta = [MMargem_bruta]
			VAR GastosGerais = [gastos_gerais]
			VAR LucroOperacional = [rresultado_operacional]
			
			VAR Variacoes = 
			
			        SWITCH(
			            TRUE(),
			            balancete, "Receita Bruta",
			            MargemBruta, "Margem Bruta",
			            GastosGerais, "Gastos Gerais",
			            LucroOperacional, "Lucro Operacional"
			        )
			RETURN
			    Variacoes
			
			
			
			```
		lineageTag: e9c19212-5ce5-4270-b270-1249e60015af

	measure variacao_receita_bruta$ = ```
			
			    [MReceita_bruta] - [Mreceita_bruta_LM]
			```
		formatString: #,0
		lineageTag: 10ac9c16-b418-4065-bcaa-cc10309579c6

		annotation PBI_FormatHint = {"isDecimal":true}

	measure variacao_receita_brutaLM =
			
			CALCULATE(
			    [variacao_receita_bruta], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 43540e79-d1e3-4b81-85d9-cd41c679a54e

	measure MReceita_bruta_GD =
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Receita Bruta"
			        ),
			        balancetenew[vlr]
			    )
			)
		formatString: #,0
		lineageTag: 19e6b462-c684-4c07-a348-52f1975d19f7

		annotation PBI_FormatHint = {"isDecimal":true}

	measure periodo_atual_mes_ano = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    MAX(dCalendario[Mês e Ano Abreviado]),
			    ALL(dCalendario),
			    VALUES(dCalendario[Mês e Ano Abreviado]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			
			```
		lineageTag: 9d951aad-fd37-4e6c-be0b-1b5ece3db1cd

	measure periodo_anterior_mes_ano =
			
			CALCULATE(
			    MAX(dCalendario[Mês e Ano Abreviado]),
			    FILTER(
			        ALL(dCalendario),
			        dCalendario[data] = EOMONTH(MAX(dCalendario[data]), -1)
			    )
			)
		lineageTag: c98d4c61-7ded-4a90-95e5-48b1bbe15a71

	measure variacao_receita_bruta_sinal =
			
			IF([variacao_receita_bruta$] > 0, "🟢", "🔴")
		lineageTag: b4fd346d-d8f5-4288-9041-3e7a5919f4cf

	measure diferenca_variacao_receita_bruta% = ```
			
			VAR vvariacao_neg = [variacao_receita_bruta] - [variacao_receita_brutaLM] 
			
			RETURN
			 IF([variacao_receita_bruta] < 0,
			vvariacao_neg *-1,
			[variacao_receita_bruta] - [variacao_receita_brutaLM])
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 98dfafcd-83e5-4d1d-9169-842096e3f8cd

	measure dif_var_receita_bruta_sinal =
			
			IF(
			    [diferenca_variacao_receita_bruta%] < 0, "🔴", "🟢")
		lineageTag: 32ae71d1-c893-4f34-b102-9dd749c50391

	measure variacao_margem_bruta =
			
			[MMargem_bruta_actual_month] - [MMargem_brutaLM]
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: bf36ee73-a9a2-4e41-b912-cae56cd80210

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure variacao_margem_video =
			
			[variacao_margem_bruta]
		lineageTag: 590a006a-1517-4cad-97a7-0ba64f8a63b1

		formatStringDefinition =
				VAR V_margem = [variacao_margem_bruta]
				VAR V_variacao = [variacao_margem_bruta]
				
				
				RETURN
				"""" & FORMAT(V_margem, "R$ 0,0; 0,0")

	measure %margem_bruta|receita_bruta =
			
			DIVIDE([MMargem_bruta_actual_month],
			        [MReceita_bruta]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 223a3ffa-5c10-4d1a-88f5-a6a244a92c25

	measure %margem_bruta|receita_brutaLM =
			
			CALCULATE(Medidas_balancetenew[%margem_bruta|receita_bruta], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 34acde06-7b82-4f49-b504-f635b9eb952f

	measure variacao_margem_bruta% =
			
			[variacao_margem_bruta]
		lineageTag: 84125714-2db6-4e74-a3e9-62932ac89740

		formatStringDefinition =
				VAR V_variacao = [%margem_bruta|receita_bruta] - [%margem_bruta|receita_brutaLM]
				
				RETURN
				"""" & FORMAT(V_variacao, " 0.00%; 0.00%")

	measure variacao_margem_bruta_sinal = ```
			
			VAR V_variacao = [%margem_bruta|receita_bruta] - [%margem_bruta|receita_brutaLM]
			VAR V_icone = 
			IF(V_variacao > 0, "🟢", "🔴")
			
			RETURN
			V_icone
			```
		lineageTag: 40741516-9171-4f3f-8cc3-dcfa7fa34bc0

	measure gastos_gerais_video =
			
			VAR vdiferenca_margem_lucro =
			[MMargem_bruta] - [rresultado_operacional]
			 VAR vdespesas = [Ebitda_despesa_depreciacao]
			 VAR virpj_csll =
			  CALCULATE(
			    SUMX(FILTER(
			        balancetenew,
			        balancetenew[Query] = "DRE_Imposto_de_Renda" ||
			        balancetenew[Query] = "DRE_Contribuicao_Social"
			    ), balancetenew[vlr]))
			
			RETURN
			
			vdiferenca_margem_lucro
		lineageTag: 25c2ee77-f2b2-462e-b444-408155146475

		formatStringDefinition = ```
				VAR V_gastos = [gastos_gerais_video]
				VAR V_variacao = DIVIDE([gastos_gerais_video] - [gastos_gerais_LM], [gastos_gerais_LM])
				VAR V_formato = 
				SWITCH(
				    TRUE(),
				    V_gastos >= 1000000000, "R$ #,#0,0B;R$ -#,#0,0B",
				    V_gastos >= 1000000, "R$ #,#0,M; R$ -#,#0,M",
				    V_gastos >= 1000, "R$ #,#0,K;R$ -#,#0,K",
				    "R$ #,#0,.00;R$ -#,#0,0.00"
				)
				VAR V_icone = 
				IF(V_variacao > 0, " ⇡", " ⇣")
				RETURN
				"""" & FORMAT(V_gastos, V_formato) & " | " &
				"""" & FORMAT(V_variacao, "0%;-0%") &
				V_icone
				```

	measure gastos_gerais$ = ```
			
			VAR vdiferenca_margem_lucro =
			[MMargem_bruta_actual_month] - [rresultado_operacional]
			 
			RETURN
			vdiferenca_margem_lucro
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 7c72ce3b-0f99-4d37-a5e0-9e8e60b48b25

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure gastos_gerais$_LM = ```
			
			 CALCULATE(
			    [gastos_gerais$], 
			    DATEADD(
			        dCalendario[data], -1, MONTH
			        )
			        )
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: ae0d6b19-def7-48ec-81d1-9fe016203f6f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure variacao_gastos_gerais =
			
			[gastos_gerais$] - [gastos_gerais$_LM]
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 00d2394e-b8a7-4d1a-87b9-6b7057e36b4e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure variacao_gastos_gerais_sinal =
			
			IF([variacao_gastos_gerais] > 0, "🔴", "🟢")
		lineageTag: 3f2df3d2-a8fd-4653-bc4b-25c78de2164f

	measure %gastos_gerais|receita_bruta =
			
			DIVIDE([gastos_gerais$], [MReceita_bruta])
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 50c31138-b37b-4791-98e2-a7b3fd5b8da2

	measure %gastos_gerais|receita_brutaLM =
			
			CALCULATE([%gastos_gerais|receita_bruta], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c8b69b78-f8b6-403f-a39d-dca55557a84e

	measure var_%gastos_gerais|receita_bruta =
			
			[%gastos_gerais|receita_bruta] - [%gastos_gerais|receita_brutaLM]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 54dafaed-8ecf-4ccd-a6d9-1c3f6a39af3a

	measure variacao_%gastos_gerais_sinal =
			
			IF(
			    [var_%gastos_gerais|receita_bruta] > 0, "🔴", "🟢")
		lineageTag: 0d13415c-f5d1-4ae5-b001-0ca534b4551a

	measure Medida
		lineageTag: 1fc2db21-124e-4a5e-89b9-7ad3141b33fe

		annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":null}

		annotation 277cc1b9-af89-4597-8e15-cacc25c0886b = Para usar caracteres especiais em um nome de medida, coloque todo o nome entre colchetes ( [] ) e adicione ] a quaisquer colchetes de fechamento no nome.

	measure variacao_resultado_operacional =
			
			[rresultado_operacional] - [rresultado_operacionalLM]
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 658f7aad-4e07-43ea-8446-fdeb463424ec

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure variacao_resultado_operacional_sinal =
			
			IF([variacao_resultado_operacional] > 0, "🟢", "🔴")
		lineageTag: 4a03d7ae-864f-46bf-a7c6-5309cbc2b1f2

	measure %Resultado_Op|Receita_Bruta =
			
			DIVIDE(
			    [rresultado_operacional]
			        , [MReceita_bruta]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 24cc8dcc-9351-432e-9161-5e9bcdfec221

	measure %Resultado_Op|Receita_BrutaLM = ```
			
			 CALCULATE([%Resultado_Op|Receita_Bruta], DATEADD(dCalendario[data], -1, MONTH))
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4c2cb73a-5c44-40db-9039-38e0143b4824

	measure var_%Resultado_Op|Receita_Bruta =
			
			[%Resultado_Op|Receita_Bruta] - [%Resultado_Op|Receita_BrutaLM]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2ee05c03-b7bc-44e5-9b0f-a94e12255c97

	measure var_%resultado_op|receita_bruta_sinal =
			
			IF([var_%Resultado_Op|Receita_Bruta] > 0, "🟢", "🔴")
		lineageTag: 4997a286-d89a-4f87-8cc3-93d6dabc839e

	measure variacao_lucro_liq =
			
			[LLucro_liquido] - [LLucro_liquidoLM]
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: f03dbe2d-9585-4e17-bee9-425f5e8dc953

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure var_lucro_liq_sinal =
			
			IF([variacao_lucro_liq] > 0, "🟢", "🔴")
		lineageTag: 7749721a-d082-47f0-a1e4-fd7e42a4534b

	measure %lucro_liq|receita_bruta =
			
			DIVIDE(
			    [LLucro_liquido],
			    [MReceita_bruta]
			    )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8234ffc8-3bd4-4f1f-b788-75c03e6840c3

	measure %lucro_liq|receita_brutaLM = ```
			
			CALCULATE(
			    [%lucro_liq|receita_bruta], 
			    DATEADD(dCalendario[data], 
			    -1, MONTH
			    )
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 30c9effd-40ee-470d-bc86-3746f3aa0617

	measure var_%lucro_liq|receita_bruta =
			
			[%lucro_liq|receita_bruta] -
			[%lucro_liq|receita_brutaLM]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 68eaea3f-144d-4e90-8520-e7001460287e

	measure VAR_%lucro_liq|receita_bruta_sinal =
			
			IF([var_%lucro_liq|receita_bruta] > 0, "🟢", "🔴")
		lineageTag: 4871e866-c2a2-498d-a038-053e1c04178b

	measure Ano_Atual_ = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    MAX(dCalendario[Ano]),
			    ALL(dCalendario),
			    VALUES(dCalendario[Ano]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0
		lineageTag: ed26cbcd-2823-45ab-a667-1fdca6f744f0

	measure Ano_Anterior_ =
			
			CALCULATE([Ano_Atual_], DATEADD(dCalendario[data], -1, YEAR))
		formatString: 0
		lineageTag: 1fe0fcef-a3e7-407d-a718-c2277216b7f8

	measure gastos_gerais_ACU =
			
			VAR vdiferenca_margem_lucro =
			[MMargem_Bruta_ACU] - [rresultado_operacional_ACU]
			
			RETURN
			    vdiferenca_margem_lucro
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: c7978858-d3f7-4312-8cf6-af0f2aca3803

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure gastos_gerais_ACU_LY =
			
			CALCULATE([gastos_gerais_ACU], SAMEPERIODLASTYEAR(dCalendario[data]))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: d5f5d7a6-c98d-486b-9b08-727b1a584511

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure variacao_receita_bruta_ACU =
			
			DIVIDE(
			    [MReceita_Bruta_ACU] - [MReceita_bruta_acu_LY],
			    [MReceita_bruta_acu_LY])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e9f220e5-29cd-4695-a3e9-920961320bf5

	measure variacao_receita_bruta_ACU_LY = ```
			
			IF(
			    NOT(
			        ISBLANK(
			            CALCULATE([variacao_receita_bruta_ACU], 
			            SAMEPERIODLASTYEAR(dCalendario[data])
			            )
			            )
			            ),
			            CALCULATE([variacao_receita_bruta_ACU], 
			            SAMEPERIODLASTYEAR(dCalendario[data])), 
			            0
			            )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 372565d2-0675-4276-a9f8-80c7c647fbff

	measure variacao_margem_bruta$_ACU =
			
			[MMargem_Bruta_ACU] - [MMargem_Bruta_acu_LY]
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 61d90237-7197-4ef0-b254-ebfde220618e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure variacao_receita_bruta$_ACU = ```
			
			    [MReceita_Bruta_ACU] - [MReceita_bruta_acu_LY]
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 594b4229-b6b1-4533-bd89-0ab495181d81

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure diferenca_variacao_receita_bruta%_ACU = ```
			
			VAR vvariacao_neg = [variacao_receita_bruta_ACU] - [variacao_receita_bruta_ACU_LY] 
			
			RETURN
			 IF([variacao_receita_bruta_ACU_LY] < 0,
			vvariacao_neg *-1,
			[variacao_receita_bruta_ACU] - [variacao_receita_bruta_ACU_LY])
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ce7804df-d6ab-453a-a839-9ab66268fd93

	measure %margem_bruta|receita_bruta_ACU =
			
			DIVIDE([MMargem_Bruta_ACU],
			        [MReceita_Bruta_ACU]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 188e9360-7d8d-4bb4-9f1b-3cba325a1940

	measure %margem_bruta|receita_bruta_ACU_LY =
			
			CALCULATE([%margem_bruta|receita_bruta_ACU], SAMEPERIODLASTYEAR(dCalendario[data]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c43f7892-5a23-4631-b4cd-e34ef74f8cdf

	measure diferenca_variacao_margem_bruta%_ACU =
			
			VAR vvariacao_neg =  [%margem_bruta|receita_bruta_ACU] - [%margem_bruta|receita_bruta_ACU_LY]
			
			RETURN
			 IF([%margem_bruta|receita_bruta_ACU_LY] < 0,
			vvariacao_neg *-1,
			[%margem_bruta|receita_bruta_ACU] - [%margem_bruta|receita_bruta_ACU_LY])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cd848bc1-197a-41fb-8f4b-f3be4c8828c3

	measure variacao_gastos_gerais$_ACU =
			
			[gastos_gerais_ACU] - [gastos_gerais_ACU_LY]
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 7c1cd9eb-8983-4b57-b8a3-60696dd9058f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure %gastos_gerais|receita_bruta_ACU =
			
			DIVIDE([gastos_gerais_ACU], [MReceita_Bruta_ACU])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: af69abe4-65c8-461b-ad2a-8ed8e04db200

	measure %gastos_gerais|receita_bruta_ACU_LY =
			
			CALCULATE([%gastos_gerais|receita_bruta_ACU], SAMEPERIODLASTYEAR(dCalendario[data]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 55f1cd48-7509-489e-bacf-1ef5eb32f922

	measure var_%gastos_gerais|receita_bruta_ACU =
			
			[%gastos_gerais|receita_bruta_ACU] - [%gastos_gerais|receita_bruta_ACU_LY]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0b239d4a-acb5-4e89-9c7e-3765ce04d6a8

	measure variacao_resultado_operacional_ACU =
			
			[rresultado_operacional_ACU] - [rresultado_operacional_ACU_LY]
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 0a1345aa-ad30-4b56-884e-6ead3fb693d8

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure var_%Resultado_Op|Receita_Bruta_ACU =
			
			[%Resultado_Op_ACU|Receita_Bruta_ACU] - [%Resultado_Op_ACU|Receita_Bruta_ACU_LY]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7356f8a0-2187-4c01-a2c4-b15e0a33e0ba

	measure variacao_ebitda$ =
			
			[EEBITDA_actual_month] - [EEbitdaLM]
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: b2d2109e-d05a-475d-ad5f-8459dfd1c13b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure variacao_ebitda_sinal =
			
			IF([variacao_ebitda$] > 0, "🟢", "🔴")
		lineageTag: 12e8a92c-1b7f-4feb-9ac5-cb166698dad9

	measure variacao_ebitda$_ACU =
			
			[EEbitda_ACU] - [EEbitda_ACU_LY]
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 3cddff0a-2836-492d-a9e5-897623d95f96

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure variacao_lucro_liq_ACU =
			
			[LLucro_liquido_ACU] - [LLucro_liquido_acu_LY]
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: ef69e75d-3c35-471d-a678-611e3e97ae0d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure diferenca_%LLucro_liquido_acu|receita_bruta_acu =
			
			[%LLucro_liquido_acu|receita_bruta_acu] - [%LLucro_liquido_acu_LY|Mreceita_bruta_acu_LY]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bc55bdc9-01cc-4149-ae26-de5d0c62238d

	measure dif_var_receita_brutaACU_sinal =
			
			IF(
			    [diferenca_variacao_receita_bruta%_ACU] < 0, "🔴", "🟢")
		lineageTag: 023c8d2e-ba1e-4c77-b745-c1a073b8affa

	measure dif_var_%receita_brutaACU_sinal =
			
			IF(
			    [diferenca_variacao_receita_bruta%_ACU] < 0, "🔴", "🟢")
		lineageTag: 56d6eea6-7baf-46e3-afd2-6b50d1a5c088

	measure dif_var_margem_brutaACU_sinal =
			
			IF(
			    [diferenca_variacao_margem_bruta%_ACU] < 0, "🔴", "🟢")
		lineageTag: 41bbfc1b-3159-43cd-ac2a-3812a44cc1b0

	measure dif_var_receita_bruta%ACU_sinal =
			
			IF(
			    [diferenca_variacao_margem_bruta%_ACU] < 0, "🔴", "🟢")
		lineageTag: 68288683-7067-48de-b592-dd6a2b4d3535

	measure variacao_gastos_gerais_ACU_sinal = ```
			
			IF([variacao_gastos_gerais$_ACU] > 0, 
			"🔴", 
			"🟢"
			)
			```
		lineageTag: c9ffc3ab-5da1-4acf-ad34-6af525f2e1ba

	measure variacao_%gastos_gerais_ACU_sinal = ```
			
			IF(
			    [var_%gastos_gerais|receita_bruta_ACU] > 0, 
			    "🔴", 
			    "🟢"
			    )
			```
		lineageTag: 9eb59d3a-60e1-4395-8936-f1cf0f943c20

	measure variacao_resultado_operacional_ACU_sinal =
			
			IF([variacao_resultado_operacional_ACU] > 0, "🟢", "🔴")
		lineageTag: 0d205cdb-d08b-4e73-9e50-5b215dd5c814

	measure var_%resultado_op|receita_bruta_ACU_sinal =
			
			IF([var_%Resultado_Op|Receita_Bruta_ACU] > 0, "🟢", "🔴")
		lineageTag: 90361edb-e750-4379-aa86-08d5b0d712cb

	measure variacao_ebitda_ACU_sinal =
			
			IF([variacao_ebitda$_ACU] > 0, "🟢", "🔴")
		lineageTag: f1e42a00-8308-49a2-9764-9cee4e471a03

	measure var_lucro_liq_ACU_sinal =
			
			IF([variacao_lucro_liq_ACU] > 0, "🟢", "🔴")
		lineageTag: f9bb4f60-f5b8-4892-860e-b7d0a7b56fac

	measure var_lucro_liq%_ACU_sinal =
			
			IF([diferenca_%LLucro_liquido_acu|receita_bruta_acu] > 0, "🟢", "🔴")
		lineageTag: 5ea2c084-adca-45a0-aa3d-eacf39e0ffe7

	measure LLucro_liquidoII =
			
			CALCULATE(
			        SUM(
			            balancetenew[vlr]
			        ),
			        FILTER(
			                balancetenew,
			                balancetenew[Query] = "DRE_Lucro_ou_Prejuizo_liquido"
			            )
			    )
		formatString: #,0
		lineageTag: 178fb78d-9c69-4af4-ba17-241913495ca6

		annotation PBI_FormatHint = {"isDecimal":true}

	measure MReceita_bruta_acu_LYII =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    CALCULATE(
			    [MReceita_Bruta_ACU], SAMEPERIODLASTYEAR(dCalendario[data])),
			    CALCULATE(
			    [MReceita_Bruta_selecionado_LY_normal_card])
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 91d0d37c-8a36-4650-8cf7-0ed1d18e0346

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'ciclo_operacional II' =
			
			ROUND(
			Medidas_balancetenew[Prazo Médio do Giro do Estoque] + medidas_aginglist[prazo_medio_contas_receber_misto_aging_balancete], 0)
		formatString: 0
		lineageTag: b013dc01-c5c5-4035-a5a5-eae729374158

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'CicloOperacionalLM II' = CALCULATE(Medidas_balancetenew[ciclo_operacional II], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0
		lineageTag: 5e214b39-7408-459c-bd6e-dd4959906d9e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'LLucro_liquido II' = ```
			
			CALCULATE(
			    SUM(balancetenew[vlr]),
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "DRE_Lucro_ou_Prejuizo_liquido"
			    )
			)
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: ec7dee0a-8f3c-4ff1-bfbd-8d85dcd8c7bc

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure gastos_gerais$_actual_month = ```
			
			VAR vdiferenca_margem_lucro =
			[MMargem_bruta_actual_month] - [rresultado_operacional]
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			RETURN
			CALCULATE(
			vdiferenca_margem_lucro,
			dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre)
			```
		lineageTag: 217f8571-19d0-4563-aac2-7c7fc89c1b05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure cfs_distribuicao_de_lucros =
			
			SUMX(
			    FILTER(balancetenew,
			    balancetenew[Query] = "BL_PL_Soma" &&
			    balancetenew[descricao_cliente] = "DISTRIBUICAO DE LUCROS"),
			    balancetenew[vlr]
			) *-1
		formatString: #,0
		lineageTag: 3ad66bd9-76f2-4713-869a-3cc69302cdcb

		annotation PBI_FormatHint = {"isDecimal":true}

	measure cfs_distribuicao_de_lucros_LM =
			
			CALCULATE([cfs_distribuicao_de_lucros], DATEADD(dCalendario[data], -1, MONTH))
		formatString: #,0
		lineageTag: f4991200-1f10-4c90-bb95-82477c03f664

		annotation PBI_FormatHint = {"isDecimal":true}

	measure cfs_distribuicao_de_lucros_DIF =
			
			[cfs_distribuicao_de_lucros] - [cfs_distribuicao_de_lucros_LM]
		formatString: #,0
		lineageTag: eea922d8-2036-4f96-951e-9d9c22daa8e4

		annotation PBI_FormatHint = {"isDecimal":true}

	measure cfs_impostos_recebidos =
			
			SUMX(
			    FILTER(balancetenew,
			    balancetenew[Query] = "DRE_Imposto_de_Renda" ||
			    balancetenew[Query] = "DRE_Contribuicao_Social"),
			    balancetenew[vlr])
		formatString: #,0
		lineageTag: 4be849ea-1d5a-4c6d-954e-99059b018c16

		annotation PBI_FormatHint = {"isDecimal":true}

	measure cfs_renda_extraordinaria =
			
			SUMX(
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "DRE_Desp_Operacionais_Equivalencia_Patrimonial" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Outras_receitas_operacionais"),
			        balancetenew[vlr])
		formatString: #,0
		lineageTag: 115e0d10-3d93-4dad-95b2-69884818d219

		annotation PBI_FormatHint = {"isDecimal":true}

	measure cfs_custos_diretos =
			
			VAR vimpostos_deduc =
			[MReceita_bruta] - [MReceita_Liquida]
			VAR vcustos = [CCusto] *-1
			
			RETURN
			
			vimpostos_deduc + vcustos
		lineageTag: c7e3670d-b9d2-4b83-92af-0679d6bbf073

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure variacao%_receita_bruta_ACU_video = [variacao_receita_bruta_ACU]
		lineageTag: d303dee2-3d61-4cb0-8e48-cfadebc96177

		formatStringDefinition = ```
				VAR V_receita = [variacao_receita_bruta$_ACU]
				VAR V_variacao = [variacao_receita_bruta_ACU]
				VAR V_formato = 
				SWITCH(
				    TRUE(),
				    V_receita >= 1000000000, "R$ #,#0,0B;R$ -#,#0,0B",
				    V_receita >= 1000000, "R$ #,#0,M; R$ -#,#0,M",
				    V_receita >= 1000, "R$ #,#0,K;R$ -#,#0,K",
				    "R$ #,#0,.00;R$ -#,#0,0.00"
				)
				VAR V_icone = 
				IF(V_variacao > 0, " ⇡", " ⇣")
				RETURN
				"""" & FORMAT(V_receita, V_formato) & " | " &
				"""" & FORMAT(V_variacao, "0%;-0%") &
				V_icone
				```

	measure gastos_gerais_geral = ```
			
			VAR vdiferenca_margem_lucro =
			[MMargem_bruta] - [rresultado_operacional]
			 
			RETURN
			vdiferenca_margem_lucro
			```
		formatString: #,0
		lineageTag: eb2da277-eb95-410b-a48f-235e770c7883

		annotation PBI_FormatHint = {"isDecimal":true}

	measure %gastos_gerais|receita_bruta_geral =
			
			VAR vreceita_bruta =
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Receita Bruta"
			        ),
			        balancetenew[vlr]
			    )
			)
			RETURN
			DIVIDE([gastos_gerais_geral], vreceita_bruta)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 60fd600d-faec-41aa-b738-770af65ceb0d

	measure cfs_custos_diretos_ACU =
			
			[MReceita_Bruta_ACU] - [MMargem_Bruta_ACU]
		formatString: #,0
		lineageTag: 169ca8d7-235c-4fd9-a6b9-b02a32859e95

		annotation PBI_FormatHint = {"isDecimal":true}

	measure cfs_gastos_gerais_POO_ACU =
			
			VAR vdiferenca_margem_lucro =
			[MMargem_Bruta_ACU] - [rresultado_operacional_ACU]
			
			RETURN
			    vdiferenca_margem_lucro
		formatString: #,0
		lineageTag: 58cd8e6a-73fa-4a17-9ef0-d5d453b2cd34

		annotation PBI_FormatHint = {"isDecimal":true}

	measure deducoes_ACU =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			CALCULATE([deducoes], DATESYTD(dCalendario[data])),
			[deducoes_selecionado])
		formatString: #,0
		lineageTag: 29efb663-c459-43fe-ba9d-fa54a1b59bdc

		annotation PBI_FormatHint = {"isDecimal":true}

	measure cfs_divida_liquida_LM =
			
			CALCULATE([divida_liquida], DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 70653781-b110-42e3-b9fe-40fda2ec633d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure cfs_divida_liquida_LY =
			
			CALCULATE([divida_liquida], DATEADD(dCalendario[data], -1, YEAR))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 658e60af-2860-4e4b-bb97-6510ef52c221

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure %DDespControladas_Acu_atual|anterior_MC = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			    'Medidas_balancetenew'[DDespesaControladas_ACU] - 'Medidas_balancetenew'[DDespesaControladas_ACUanoAnterior],
			    'Medidas_balancetenew'[DDespesaControladas_ACUanoAnterior]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0731ab8f-9950-46f2-8fe0-d0289cf1a42a

	measure Emprestimos_CP = ```
			
			VAR UltimoDiaMesRecente = 
			    EOMONTH(MAX(dCalendario[data]), 0)
			
			VAR PrimeiroDiaMesRecente = 
			    DATE(YEAR(UltimoDiaMesRecente), MONTH(UltimoDiaMesRecente), 1)
			
			VAR emprestimo =
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew,
			                balancetenew[Query] = "Emprestimos_Financiamentos_Curto_Prazo" &&
			                (
			                    balancetenew[descricao_cliente] = "EMPRESTIMO CAPITAL DE GIRO ITAU 2258595129" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO BANCO ITAU" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO CAPITAL DE GIRO ITAU 2281764577" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO BANCO ALFA" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO CAPITAL DE GIRO ITAU 2258593744" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO BANCO J. SAFRA SA" ||
			                    balancetenew[descricao_cliente] = "BANCO SAFRA - GARANTIDA" ||
			                    balancetenew[descricao_cliente] = "FINANCIAMENTO DE TERCEIROS" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO CAPITAL DE GIRO ITAU 33426.77014" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO CAPITAL DE GIRO ITAU 5619.77012" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO CAPITAL DE GIRO ITAU 1591844" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO CAPITAL DE GIRO ITAU"
			                   // balancetenew[descricao_cliente] = "
			                )
			            ),
			            balancetenew[total_mes_atual]
			        ),
			        dCalendario[data] >= PrimeiroDiaMesRecente && dCalendario[data] <= UltimoDiaMesRecente
			    )
			
			VAR juros =
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew,
			                balancetenew[Query] = "Emprestimos_Financiamentos_Curto_Prazo" &&
			                (
			                    balancetenew[descricao_cliente] = "( - ) ENCARGOS CAPITAL DE GIRO ITAU 2258595129" ||
			                    balancetenew[descricao_cliente] = "( - ) ENCARGOS CAPITAL DE GIRO ITAU 2258593744" ||
			                    balancetenew[descricao_cliente] = "( - ) ENCARGOS CAPITAL DE GIRO ITAU 2281764577" ||
			                    balancetenew[descricao_cliente] = "( - ) ENCARGOS EMPRESTIMO BANCO J. SAFRA SA" ||
			                    balancetenew[descricao_cliente] = "( - ) ENCARGOS CAPITAL DE GIRO ITAU"
			                )
			            ),
			            balancetenew[total_mes_atual]
			        ),
			        dCalendario[data] >= PrimeiroDiaMesRecente && dCalendario[data] <= UltimoDiaMesRecente
			    )
			
			RETURN emprestimo + juros
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 1c6fe2b6-9116-445b-963c-5db5a9821ffb

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure emprestimos_LP = ```
			
			VAR UltimoDiaMesRecente = 
			    EOMONTH(MAX(dCalendario[data]), 0)
			
			VAR PrimeiroDiaMesRecente = 
			    DATE(YEAR(UltimoDiaMesRecente), MONTH(UltimoDiaMesRecente), 1)  // Armazena a última data selecionada no filtro
			
			RETURN
			CALCULATE(
			SUMX(
			                FILTER(
			                    balancetenew,
			                    balancetenew[Query] = "BL_PASSNCIR_Emprestimos_Financiamentos" &&
			                (balancetenew[descricao_cliente] = "EMPRESTIMO CAPITAL DE GIRO ITAU LP 2258595129" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO BANCO ALFA" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO CAPITAL DE GIRO ITAU 33426.77014" ||
			                    balancetenew[descricao_cliente] = "EMRPESTIMO BANCO ALFA" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO BANCO ITAU" ||
			                    balancetenew[descricao_cliente] = "( - ) ENCARGOS CAPITAL DE GIRO ITAU LP 2281764577" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO CAPITAL DE GIRO ITAU LP 2281764577" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO CAPITAL DE GIRO ITAU LP 2258593744" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO CAPITAL DE GIRO ITAU LP" ||
			                    balancetenew[descricao_cliente] = "( - ) ENCARGOS CAPITAL DE GIRO ITAU LP 2258593744" ||
			                    balancetenew[descricao_cliente] = "( - ) ENCARGOS CAPITAL DE GIRO ITAU LP 2258595129" ||
			                    balancetenew[descricao_cliente] = "BANCO ALFA CONTA GARANTIDA" ||
			                    balancetenew[descricao_cliente] = "FINANCIAMENTO DE TERCEIROS LP" ||
			                    balancetenew[descricao_cliente] = "BANCO ITAU GARANTIDA" ||
			                    balancetenew[descricao_cliente] = "BANCO SAFRA GARANTIDA" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO CAPITAL DE GIRO ITAU 1591844" ||
			                    balancetenew[descricao_cliente] = "EMPRESTIMO CAPITAL DE GIRO ITAU 5619.77012" ||
			                    balancetenew[descricao_cliente] = "( - ) ENCARGOS CAPITAL DE GIRO ITAU LP")
			                   // FINANCIAMENTO DE TERCEIROS LP
			                   // EMPRESTIMO BANCO ITAU
			                ),
			                balancetenew[total_mes_atual]
			            ),
			            dCalendario[data] >= PrimeiroDiaMesRecente && dCalendario[data] <= UltimoDiaMesRecente
			            )
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: f26e30a1-5194-4184-a1a8-4cf9477f7124

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure financiamentos_CP =
			
			VAR UltimaDataSelecionada = LASTDATE(dcalendario[data])  // Armazena a última data selecionada no filtro
			RETURN
			CALCULATE(
			    SUMX(
			        FILTER(
			             balancetenew,
			             balancetenew[Query] = "BL_PASSCIR_Emprestimos_Financiamentos" &&
			           ( balancetenew[descricao_cliente] = "FINANCIAMENTO BANCO HONDA SA" ||
			             balancetenew[descricao_cliente] = "BANCO J. SAFRA E LEASING" ||
			             balancetenew[descricao_cliente] = "FINANCIAMENTO BANCO SAFRA 135620" ||
			             balancetenew[descricao_cliente] = "( - ) JUROS S/ FINANCIAMENTO BANCO HONDA SA" ||
			             balancetenew[descricao_cliente] = "( ) ENCARGOS FINANC BANCO SAFRA 135620"
			
			             ) &&
			            balancetenew[data] = UltimaDataSelecionada  // Filtra pela última data
			        ),
			        balancetenew[total_mes_atual]
			    )
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 04aa8a23-5b54-4ddf-a184-95e0fae1b745

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure deducoes_actual_month = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			
			RETURN
			
			CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "Deduções da Receita Bruta"), 
			        balancetenew[vlr]
			        ),
			        dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre)
			```
		formatString: #,0
		lineageTag: 5f067a8a-07c7-446c-830e-0c75c157fbe0

		annotation PBI_FormatHint = {"isDecimal":true}

	measure tributos_incidentes_actual_month = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			RETURN
			CALCULATE(
			    SUMX(
			    FILTER(balancetenew, 
			    balancetenew[Query] = "DRE_Imp_Incidentes_Sobre_Receita"), 
			    balancetenew[vlr]
			    ),
			    dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre)
			```
		formatString: #,0
		lineageTag: d184a800-61a9-4d24-9d26-fafa186fae38

		annotation PBI_FormatHint = {"isDecimal":true}

	measure deducoes_impostos =
			
			([deducoes_actual_month] *-1) + ([tributos_incidentes_actual_month] *-1)
		formatString: #,0
		lineageTag: 5e6b8ae7-bcc9-4253-997e-7048ec97683e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure lucro_bruto_actual_month =
			
			[MReceita_Liquida_actual_month] - ([CCusto_actual_month] *-1)
		formatString: #,0
		lineageTag: 7c1e7869-b7d9-4b70-b134-de28dfb31931

		annotation PBI_FormatHint = {"isDecimal":true}

	measure ppatrimonio_liq_roi =
			
			CALCULATE(
			[PPatrimonio Liquido_retorno_invest],
			DATESYTD(dCalendario[data]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: feb1c849-f439-4c39-ac62-9003b4322dd8

	measure ppatrimonio_roi_actual_month =
			
			DIVIDE(
			    [LLucro_liquido_actual_month],
			    [patrimonioLiq]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e7f5768e-9761-4902-8fcc-491b4b240126

	measure MargemBru|Receitabruta = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    DIVIDE(
			        SUMX(
			            'Medidas_balancetenew', 
			            'Medidas_balancetenew'[MMargem_bruta_actual_month]), 
			            SUMX('Medidas_balancetenew', 
			            'Medidas_balancetenew'[MReceita_bruta]
			        )
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: fd8a7455-6f34-478a-b40f-2d822cda55eb

	measure MargemBruta|ReceitaBruta_LM = CALCULATE('Medidas_balancetenew'[MargemBru|Receitabruta],DATEADD(dCalendario[data],-1,MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 985bf6a7-413b-4dc5-8acf-adc89f2920f2

	measure 'LLucro_liquido | ReceitaBruta' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(    
			    DIVIDE(
			          [LLucro_liquido II],
			            [MReceita_bruta]
			        )
			    ,
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: adcf9f07-dbcd-413b-9de1-4be2fa096909

	measure '%LLucro_liquido | ReceitaBruta_LM' = CALCULATE('Medidas_balancetenew'[LLucro_liquido | ReceitaBruta], DATEADD(dCalendario[data], -1, MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: dc2cfca2-8dfc-4be6-bac3-baf5e5e6a2c8

	measure %CCustoAcu_receita_liqui_acu_LY = ```
			
			CALCULATE(
			DIVIDE(
			    SUMX('Medidas_balancetenew',
			    'Medidas_balancetenew'[CCusto_acu_LY] *-1), 
			    SUMX('Medidas_balancetenew', 
			    'Medidas_balancetenew'[MReceita_Liquida_Acumulada_LY])))
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6b5ffd3e-8c62-42e9-89e9-8f2152ba95b1

	measure Contagem_Meses_Selecionados = ```
			
			VAR DataInicial = MIN(dCalendario[data])
			VAR DataFinal = MAX(dCalendario[data])
			RETURN
			    DATEDIFF(DataInicial, DataFinal, MONTH) + 1
			
			```
		formatString: 0
		lineageTag: ef225e74-0f0e-4803-8218-bb072b8aca39

	measure ebitda_medio_CFS = ```
			
			VAR vebitda = [EEbitda_selecionado]
			VAR vcontagem_meses = [Contagem_Meses_Selecionados]
			VAR vdivisao_meses_selecao = 
			DIVIDE(
			    [EEbitda_selecionado],
			    [Contagem_Meses_Selecionados]
			)
			
			RETURN
			
			vdivisao_meses_selecao * 12
			
			
			```
		formatString: #,0
		lineageTag: 23278001-e6ee-4124-93f2-3d18970ba055

		annotation PBI_FormatHint = {"isDecimal":true}

	measure depreciacao_selecionado = ```
			
			SUMX(
			        FILTER(balancetenew, 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao"
			        ),
			    balancetenew[vlr]
			)
			```
		formatString: #,0
		lineageTag: 2b143ca8-c228-4703-b7b9-e9e8a1640a11

		annotation PBI_FormatHint = {"isDecimal":true}

	measure deducoes_impostos|receita_bruta =
			
			DIVIDE(
			[deducoes_impostos], [MReceita_bruta])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d6185de5-fa7c-4a6e-8460-196649a65654

	measure deducoes_impostos_acu = ```
			
			VAR ano_civil =
			CALCULATE(
			    SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "Deduções da Receita Bruta" ||
			        balancetenew[Query] = "DRE_Imp_Incidentes_Sobre_Receita"), 
			        balancetenew[vlr]
			        ),
			    DATESYTD(dCalendario[data])) *-1
			
			RETURN
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    ano_civil,
			    [deducoes_impostos_selecionado])
			```
		formatString: #,0
		lineageTag: fbfd35e8-ba70-4eb0-a9f4-ad057c6533f3

		annotation PBI_FormatHint = {"isDecimal":true}

	measure CCusto_ACU_normal_card_posit = ```
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			CALCULATE(
			    SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "Custo dos Produtos Vendidos"
			    ), 
			        balancetenew[vlr]
			    ), 
			    DATESYTD(dCalendario[data]
			    )
			),
			[CCusto_selecionado_normal_card]
			) *-1
			```
		formatString: #,0
		lineageTag: 90f220b5-cdca-4b79-a5ae-3c1363580ebf

		annotation PBI_FormatHint = {"isDecimal":true}

	measure financiamentos_CP_LM =
			
			CALCULATE(
			    [financiamentos_CP],
			DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 114dbbf8-bb18-4662-a9ea-63af901debfa

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure emprestimos_CP_LM =
			
			CALCULATE(
			    [Emprestimos_CP], DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 56867712-2508-4cdd-a052-5d2622694c6f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure %Resultado_Op_ACU|Receita_Bruta_ACU_LY = ```
			
			VAR vresultado =
			DIVIDE(
			    SUMX(
			        'Medidas_balancetenew', 
			        'Medidas_balancetenew'[rresultado_operacional_ACU_LY]
			        ), 
			        SUMX('Medidas_balancetenew', 
			        'Medidas_balancetenew'[MReceita_bruta_acu_LY]
			        )
			)
			
			RETURN
			vresultado
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 90d2409f-b11e-4b56-8ac1-47625ca083bc

	measure resultado_financeiro_LM =
			
			CALCULATE(
			    [resultado_financeiro_actual_month],
			    DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 3545a690-d010-4047-95a7-12a2a7dade68

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure resultado_financeiro|receita_liq = ```
			
			DIVIDE(
			    [resultado_financeiro_actual_month],
			    CALCULATE(
			        [MReceita_Liquida_actual_month],
			        ALL('Resultado Financeiro'[Tipo Resultado])
			    )
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 20c1eea9-837f-445f-bf3a-3ab625b4aa0e

	measure resultado_financeiro|receita_liq_LM = ```
			
			//DIVIDE(
			//    [resultado_financeiro_LM],
			//    CALCULATE(
			//    [MReceita_Liquida_LM],
			//    ALL('Resultado Financeiro'[Tipo Resultado]))
			
			CALCULATE(
			    [resultado_financeiro|receita_liq],
			    DATEADD(
			        dCalendario[data], 
			    -1, 
			    MONTH
			    )
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 479d6ffa-646a-47ad-9db1-22cb9e0550a3

	measure resultado_financeiro_ACU =
			
			CALCULATE(
			    [resultado_financeiro],
			    DATESYTD(dCalendario[data]))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 30f04324-d504-48f6-888f-2bbf61b5aa31

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure resultado_financeiro_ACU_LY =
			
			CALCULATE([resultado_financeiro_ACU],
			DATEADD(dCalendario[data], -1, YEAR))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 8bc40c14-04c6-4d6c-92d2-fd3c7ae011bd

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure resultado_financeiro|receita_liq_ACU =
			
			DIVIDE(
			    [resultado_financeiro_ACU],
			    CALCULATE(
			    [MReceita_Liquida_ACU],
			    ALL('Resultado Financeiro'[Tipo Resultado])))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 38078af7-4376-4c3e-940d-5a4003899e42

	measure resultado_financeiro|receita_liq_ACU_LY =
			
			DIVIDE(
			    [resultado_financeiro_ACU_LY],
			    CALCULATE(
			    [MReceita_Liquida_Acumulada_LY],
			    ALL('Resultado Financeiro'[Tipo Resultado])))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d3361c2d-5cea-4415-b683-622ccbdc9950

	measure variacao_resultado_financeiro = ```
			
			VAR resultado =
			DIVIDE(
			    [resultado_financeiro_actual_month] - [resultado_financeiro_LM],
			    ABS([resultado_financeiro_LM])
			)
			
			
			RETURN
			resultado
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f631ecf9-4403-4312-b488-a513be97af8c

	measure variacao_resultado_financeiro_ACU =
			
			DIVIDE(
			    [resultado_financeiro_ACU] - [resultado_financeiro_ACU_LY],
			    ABS([resultado_financeiro_ACU_LY])
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a44e8f9b-62bc-471f-9a55-121ec4c2c7ea

	measure resultado_financeiro_actual_month = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			RETURN
			ROUND(
			CALCULATE(
			    SUMX(
			        VALUES(dCalendario[data]),
			        Medidas_balancetenew[receita_financeira] + Medidas_balancetenew[despesa_financeira]
			    ),
			    dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre), 0)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 7838f85d-8fa0-41f4-a8f4-2be5c475f16c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure narrativa_emprestimos = ```
			
			
			VAR ContaAtual = [Emprestimos_CP]
			VAR TotalMov = [Emprestimos_CP] - [emprestimos_CP_LM]
			VAR MediaMov = [Emprestimos_CP] - [emprestimos_CP_LM]
			VAR MinMov = [Emprestimos_CP]
			VAR MaxMov = [Emprestimos_CP]
			VAR MaiorMovValor = "ESCOLHER MEDIDA"
			VAR MaiorMovData = "ESCOLHER MEDIDA"
			VAR EntradaTotal = "ESCOLHER MEDIDA"
			VAR SaidaTotal = "ESCOLHER MEDIDA"
			
			RETURN
			"<div style='font-family: Arial, sans-serif; margin: 20px;'>
			    <h2 style='color: #2E86C1; border-bottom: 2px solid #2E86C1; padding-bottom: 5px;'>Resumo da Conta " & ContaAtual & "</h2>
			    <p>A conta <strong style='color: #E74C3C;'>" & ContaAtual & "</strong> teve um total de movimentações de <strong style='color: #E74C3C;'>" & TotalMov & "</strong>.</p>
			    <p>O maior movimento foi de <strong style='color: #E74C3C;'>" & MaiorMovValor & "</strong> na data <strong style='color: #E74C3C;'>" & MaiorMovData & "</strong>.</p>
			    <p>A média dos movimentos foi de <strong style='color: #E74C3C;'>" & FORMAT(MediaMov, "0.00") & "</strong>, com um mínimo de <strong style='color: #E74C3C;'>" & MinMov & "</strong> e um máximo de <strong style='color: #E74C3C;'>" & MaxMov & "</strong>.</p>
			    <p>No período, a conta teve um total de entradas de <strong style='color: #E74C3C;'>" & EntradaTotal & "</strong> e saídas de <strong style='color: #E74C3C;'>" & SaidaTotal & "</strong>.</p>
			</div>"
			
			```
		lineageTag: 228e2d6e-d014-462f-9a60-93cbab041e97

	measure narrativa_JurosPagosEmprest = ```
			
			VAR ValorJurosPagos = [TotalJuros]
			VAR ValorJurosPagosLM = CALCULATE([TotalJuros], DATEADD(dCalendario[data], -1, MONTH))
			VAR TendenciaJurosPagos = IF(ValorJurosPagos > ValorJurosPagosLM, "um aumento", "uma diminuição")
			RETURN
			"O total de juros pagos durante " & [periodo_atual] &  " foi de " & FORMAT(ValorJurosPagos, "R$ #,##0.00") & ". Isso representa " & TendenciaJurosPagos & " em comparação com " & [periodo_anterior] & ", indicando " & IF(TendenciaJurosPagos ="um aumento", "um desgate na saúde financeira da empresa", "uma melhora na saúde financeira da empresa")
			
			```
		lineageTag: 541be134-4fd2-46bd-b60d-8394cb4744ad

	measure emprestimos_LP_LM =
			
			CALCULATE( [emprestimos_LP], DATEADD(dCalendario[data], -1, MONTH))
		formatString: #,0
		lineageTag: 76e29c91-f315-408f-9b14-b9fed3e8d28f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure variacao_emprest_CP =
			
			[eemprestEFinanc_CP] - [eemprestEFinanc_CP_LM]
		formatString: #,0
		lineageTag: cfbdd163-689b-4cfc-a716-5ab6c0210707

		annotation PBI_FormatHint = {"isDecimal":true}

	measure variacao_emprest_LP =
			
			[eemprestEFinanc_LP] - [eemprestEFinanc_LP_LM]
		lineageTag: 65915f8b-9e78-4a3d-bdf1-944e79f17404

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure switch_emprestEFinanc =
			
			VAR cp_variacao = DIVIDE([variacao_emprest_CP] + [variacao_emprest_LP], [ssoma_emprestEFinanc_LM])
			
			RETURN
			SWITCH(TRUE(),
			    cp_variacao >= 0.71, "Aumento 71-100%",
			    cp_variacao >= 0.61, "Aumento 61-70%",
			    cp_variacao >= 0.51, "Aumento 51-60%",
			    cp_variacao >= 0.41, "Aumento 41-50%",
			    cp_variacao >= 0.31, "Aumento 31-40%",
			    cp_variacao >= 0.21, "Aumento 21-30%",
			    cp_variacao >= 0.11, "Aumento 11-20%",
			    cp_variacao >= 0, "Aumento 0-10%",
			    cp_variacao >= -0.10, "Redução 0-10%",
			    cp_variacao >= -0.20, "Redução 11-20%",
			    cp_variacao >= -0.30, "Redução 21-30%",
			    cp_variacao >= -0.40, "Redução 31-40%",
			    cp_variacao >= -0.50, "Redução 41-50%",
			    cp_variacao >= -0.60, "Redução 51-60%",
			    cp_variacao >= -0.70, "Redução 61-70%",
			    "Redução 71-100%"
			)
		lineageTag: 69c86747-cb3f-478c-b732-2b8a4b1d077e

	measure narrativa_emprestEFinanc = ```
			
			VAR cp_ratio = DIVIDE([eemprestEFinanc_CP], [ssomaemprestEfinan])
			VAR lp_ratio = DIVIDE([eemprestEFinanc_LP], [ssomaemprestEfinan])
			VAR proporcao_passivo =
			DIVIDE([eemprestEFinanc_CP] + [eemprestEFinanc_LP], [totpassivo II])
			VAR passivo_ratio = 
			    SWITCH(
			        TRUE(),
			        proporcao_passivo >= 0.71, "entre 71% e 100%",
			        proporcao_passivo >= 0.51, "entre 51% e 70%",
			        proporcao_passivo >= 0.21, "entre 21% e 50%",
			        "entre 1% e 20%"
			    )
			VAR cenario = 
			    SWITCH(
			        TRUE(),
			        cp_ratio = 1 && lp_ratio = 0 && passivo_ratio = "entre 1% e 20%", 1,
			        cp_ratio = 1 && lp_ratio = 0 && passivo_ratio = "entre 21% e 50%", 2,
			        cp_ratio = 1 && lp_ratio = 0 && passivo_ratio = "entre 51% e 70%", 3,
			        cp_ratio = 1 && lp_ratio = 0 && passivo_ratio = "entre 71% e 100%", 4,
			        cp_ratio <= 0.20 && lp_ratio >= 0.80 && passivo_ratio = "entre 1% e 20%", 5,
			        cp_ratio >= 0.21 && cp_ratio <= 0.50 && lp_ratio >= 0.50 && lp_ratio <= 0.79 && passivo_ratio = "entre 1% e 20%", 6,
			        cp_ratio >= 0.51 && cp_ratio <= 0.70 && lp_ratio >= 0.31 && lp_ratio <= 0.50 && passivo_ratio = "entre 1% and 20%", 7,
			        cp_ratio >= 0.71 && cp_ratio <= 1 && lp_ratio >= 0 && lp_ratio <= 0.29 && passivo_ratio = "entre 1% e 20%", 8,
			        cp_ratio <= 0.20 && lp_ratio >= 0.80 && passivo_ratio = "entre 21% e 50%", 9,
			        cp_ratio >= 0.21 && cp_ratio <= 0.50 && lp_ratio >= 0.50 && lp_ratio <= 0.79 && passivo_ratio = "entre 21% e 50%", 10,
			        cp_ratio >= 0.51 && cp_ratio <= 0.70 && lp_ratio >= 0.31 && lp_ratio <= 0.50 && passivo_ratio = "entre 21% e 50%", 11,
			        cp_ratio >= 0.71 && cp_ratio <= 1 && lp_ratio >= 0 && lp_ratio <= 0.29 && passivo_ratio = "entre 21% e 50%", 12,
			        cp_ratio <= 0.20 && lp_ratio >= 0.80 && passivo_ratio = "entre 51% e 70%", 13,
			        cp_ratio >= 0.21 && cp_ratio <= 0.50 && lp_ratio >= 0.50 && lp_ratio <= 0.79 && passivo_ratio = "entre 51% e 70%", 14,
			        cp_ratio >= 0.51 && cp_ratio <= 0.70 && lp_ratio >= 0.31 && lp_ratio <= 0.50 && passivo_ratio = "entre 51% e 70%", 15,
			        cp_ratio >= 0.71 && cp_ratio <= 1 && lp_ratio >= 0 && lp_ratio <= 0.29 && passivo_ratio = "entre 51% e 70%", 16,
			        cp_ratio <= 0.20 && lp_ratio >= 0.80 && passivo_ratio = "entre 71% e 100%", 17,
			        cp_ratio >= 0.21 && cp_ratio <= 0.50 && lp_ratio >= 0.50 && lp_ratio <= 0.79 && passivo_ratio = "entre 71% e 100%", 18,
			        cp_ratio >= 0.51 && cp_ratio <= 0.70 && lp_ratio >= 0.31 && lp_ratio <= 0.50 && passivo_ratio = "entre 71% e 100%", 19,
			        cp_ratio >= 0.71 && cp_ratio <= 1 && lp_ratio >= 0 && lp_ratio <= 0.29 && passivo_ratio = "entre 71% e 100%", 20,
			        
			        BLANK()
			    )
			
			VAR saldoInterpretacao = 
			    SWITCH(
			        cenario,
			        1, "O cenário indica que a empresa tem uma baixa dependência de financiamentos de curto prazo, o que é positivo para a saúde financeira. Com 100% dos empréstimos no passivo circulante representando apenas <strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong> do total do passivo <strong style='color: #000000;'>" & FORMAT([totpassivo II], "R$ #,##0,00") & "</strong>, a empresa possui um risco reduzido de liquidez.",
			        2, "A dependência moderada de empréstimos de curto prazo sugere que a empresa utiliza esses recursos de forma estratégica para cobrir necessidades operacionais. No entanto, isso também aumenta a necessidade de uma gestão cuidadosa do fluxo de caixa.",
			        3, " A alta dependência de empréstimos de curto prazo, representando <strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong> do passivo total <strong style='color: #000000;'>" & FORMAT([totpassivo II], "R$ #,##0,00") & "</strong>, coloca a empresa em uma posição de maior risco financeiro devido à necessidade frequente de refinanciamento.",
			        4, "A dependência crítica de empréstimos de curto prazo, com <strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong> do passivo, indica uma vulnerabilidade financeira muito alta. A empresa está exposta a riscos significativos de liquidez e refinanciamento. ",
			        5, "A empresa mantém um baixo nível de dívida total <strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong>, com uma pequena porção em curto prazo e a maioria em longo prazo, o que indica uma gestão financeira conservadora e uma posição de baixa vulnerabilidade. ",
			        6, "A estrutura de dívida equilibrada entre curto e longo prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong> no curto prazo e <strong style='color: #000000;'>" & FORMAT(lp_ratio, "0.0%") & "</strong> no longo prazo), com baixo impacto no passivo total, sugere uma abordagem prudente e bem balanceada na gestão financeira da empresa. ",
			        7, " A maior proporção de dívida de curto prazo, embora ainda com baixo impacto no passivo total, pode indicar uma necessidade de maior atenção ao gerenciamento do fluxo de caixa para evitar problemas de liquidez. ",
			        8, " Alta dependência de curto prazo, com <strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong> do total de empréstimos, mas com um impacto geral baixo, os emprestimos representam <strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong> do passivo apenas, no entanto, isso requer uma gestão cuidadosa para evitar vulnerabilidades financeiras. A empresa precisa monitorar de perto sua capacidade de cumprir obrigações a curto prazo. ",
			        9, "Com uma baixa proporção de dívida de curto prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) e uma dependência maior de longo prazo (<strong style='color: #000000;'>" & FORMAT(lp_ratio, "0.0%") & "</strong>), a empresa se beneficia de uma estrutura financeira mais estável, com os empréstimos representando <strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong> do total do passivo, mas deve continuar vigilante quanto às condições de mercado para manter sua estrutura de capital.",
			        10, "O mix equilibrado de dívida de curto (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>)  e longo prazo, <strong style='color: #000000;'>" & FORMAT(lp_ratio, "0.0%") & "</strong>) com impacto significativo no passivo total, (<strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong>)  indica uma abordagem balanceada, mas a empresa deve monitorar cuidadosamente o custo do capital e as condições de refinanciamento.",
			        11, " A predominância de dívidas de curto prazo, tendo <strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong> de toda a dívida, eleva o risco de liquidez, exigindo uma gestão cuidadosa para evitar dificuldades financeiras. A empresa deve estar atenta à necessidade de refinanciamento constante.",
			        12, "A alta dependência de dívidas de curto prazo com impacto significativo no passivo total requer ação imediata para reduzir o risco financeiro e melhorar a estabilidade da empresa. Atualmente  <strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong> está no curto prazo e o total de empréstimos representa <strong style='color: #000000;'>"  & FORMAT(proporcao_passivo, "0.0%, </strong>"),
			        13, "A baixa dependência de dívidas de curto prazo, representando <strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong> de toda a dívida e com alta alavancagem de longo prazo indica uma necessidade de reavaliar a estrutura de capital para garantir sustentabilidade financeira.",
			        14, "A dependência mista de curto (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) e longo prazo (<strong style='color: #000000;'>" & FORMAT(lp_ratio, "0.0%") & "</strong>) com alta alavancagem sugere a necessidade de equilibrar melhor os prazos de financiamento para reduzir os riscos financeiros.",
			        15, "A alta dependência de dívidas de curto prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong> do total de empréstimos) e elevada alavancagem exigem uma ação imediata para reduzir os riscos financeiros e melhorar a estabilidade da empresa.",
			        16, " A dependência crítica de dívidas de curto prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong> do total de emprestimos) com alta alavancagem representa um risco financeiro significativo. A empresa precisa agir rapidamente para melhorar sua estrutura de financiamento.",
			        17, "A baixa proporção de dívidas de curto prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) combinada com uma elevada alavancagem de longo prazo (<strong style='color: #000000;'>" & FORMAT(lp_ratio, "0.0%") & "</strong>) requer uma revisão estratégica para melhorar a flexibilidade financeira e reduzir riscos. Atualmente o total de empréstimos e financiamentos representam  <strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong> de todo o passivo.",
			        18, "A dependência mista de curto (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) e longo prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) com alavancagem muito alta exige uma abordagem proativa para reduzir os custos financeiros e melhorar a estabilidade a longo prazo.",
			        19, "A alta dependência de empréstimos de curto prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) combinada com uma elevada alavancagem total (<strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong> de todo o passivo) representa um risco financeiro significativo que requer uma ação imediata para melhorar a estrutura de dívida. ",
			        20, "Extremamente alta dependência de curto prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>)  e muito elevada alavancagem (<strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong> de todo o passivo), representando um risco crítico. A empresa está em uma posição financeira vulnerável que exige ações urgentes para melhorar a estabilidade.",
			        "Interpretação não disponível."
			    )
			VAR saldoCurtoPrazo = 
			    SWITCH(
			        cenario,
			        1, "Continuar a manter essa baixa dependência de financiamentos de curto prazo é essencial. A empresa deve focar em manter reservas de caixa adequadas para enfrentar qualquer necessidade de liquidez inesperada e garantir que os pagamentos possam ser realizados sem dificuldades.",
			        2, "Avaliar a possibilidade de renegociar os prazos de parte dos empréstimos para alongar a dívida pode reduzir a pressão sobre o fluxo de caixa e proporcionar mais estabilidade financeira. ",
			        3, "Refinanciar parte da dívida em condições mais favoráveis é crucial para reduzir os custos financeiros e aliviar a pressão sobre o fluxo de caixa a curto prazo. Negociar taxas de juros mais baixas e prazos mais longos pode ser benéfico.",
			        4, "Priorizar a redução da dívida de curto prazo deve ser uma meta imediata. Renegociar prazos e buscar alternativas de financiamento mais sustentáveis são passos essenciais para aliviar a pressão sobre a empresa.",
			        5, "Aproveitar o baixo nível de endividamento para investir em oportunidades estratégicas que possam gerar retornos significativos. A empresa pode explorar investimentos em inovação, expansão de mercado ou aquisição de ativos estratégicos.",
			        6, "Manter essa estrutura de dívida equilibrada para minimizar riscos e custos de capital. Avaliar continuamente o desempenho operacional e financeiro para assegurar que a empresa permaneça em uma posição estável.",
			        7, "Refinanciar parte da dívida de curto prazo para reduzir a pressão sobre o fluxo de caixa é importante. Negociar melhores condições de pagamento com fornecedores e clientes também pode ajudar a melhorar a gestão de caixa.",
			        8, "Implementar estratégias para alongar os prazos das dívidas e reduzir a dependência de curto prazo. Renegociar condições de empréstimos e explorar opções de financiamento alternativas pode aliviar a pressão sobre o caixa.",
			        9, "Explorar oportunidades de financiamento de curto prazo mais barato pode reduzir os custos financeiros e liberar recursos para outras áreas. Avaliar constantemente as condições do mercado para aproveitar oportunidades vantajosas. ",
			        10, "Avaliar constantemente o custo do capital e buscar oportunidades para reduzir os custos financeiros. Manter uma reserva de caixa adequada para cobrir necessidades emergenciais. ",
			        11, "Refinanciar dívidas de curto prazo para longo prazo é essencial para reduzir o risco de liquidez. Negociar melhores condições com credores pode proporcionar mais estabilidade financeira.",
			        12, "Refinanciar e reduzir a dívida de curto prazo deve ser uma prioridade urgente. Negociar condições mais favoráveis e alongar prazos pode ajudar a aliviar a pressão sobre o caixa.",
			        13, "Priorizar a redução da dívida de longo prazo pode ajudar a reduzir os custos financeiros e melhorar a flexibilidade financeira da empresa. Avaliar a possibilidade de amortização antecipada de dívidas com taxas de juros elevadas. ",
			        14, "Refinanciar parte das dívidas para equilibrar os prazos e reduzir os custos financeiros. Negociar condições mais favoráveis com credores para melhorar a estrutura de dívida. ",
			        15, "Alongar os prazos de dívida é uma necessidade urgente para reduzir a pressão sobre o fluxo de caixa. Negociar com credores para obter melhores condições é crucial.",
			        16, "Priorizar a renegociação de prazos e redução da dívida de curto prazo é essencial para evitar problemas de liquidez. Explorar opções de financiamento de longo prazo pode proporcionar mais estabilidade. ",
			        17, "Estruturar financiamento para alongar prazos e reduzir a alavancagem pode ajudar a melhorar a posição financeira. Negociar melhores condições com credores também é importante.",
			        18, " Refinanciar dívidas para reduzir custos e prazos é essencial. Negociar condições mais favoráveis pode ajudar a aliviar a pressão sobre o fluxo de caixa e proporcionar mais estabilidade. ",
			        19, "Focar na renegociação para alongar prazos de empréstimos é essencial para reduzir a pressão sobre o fluxo de caixa e melhorar a estabilidade financeira. Avaliar todas as opções de refinanciamento disponíveis.",
			        20, "Realocar urgentemente a dívida de curto prazo para longo prazo é vital para reduzir a pressão sobre o fluxo de caixa. Negociar melhores condições de financiamento com credores deve ser uma prioridade imediata.",
			        "Estratégia de curto prazo não disponível."
			    )
			VAR saldoLongoPrazo = 
			    SWITCH(
			        cenario,
			         1, "Considerar alternativas de financiamento de longo prazo, como debêntures ou empréstimos bancários com prazos mais longos, pode ajudar a garantir que a empresa esteja preparada para projetos de capital e investimentos futuros, sem comprometer a liquidez.",
			        2, "Monitorar rigorosamente o fluxo de caixa e implementar um sistema robusto de previsões financeiras pode ajudar a identificar e mitigar riscos de liquidez. Além disso, diversificar as fontes de financiamento pode aumentar a resiliência financeira da empresa.",
			        3, "Implementar medidas de controle de custos rigorosas e aumentar a eficiência operacional são fundamentais para melhorar a lucratividade e a capacidade de pagamento da empresa. Investir em automação e otimização de processos pode gerar economias significativas.",
			        4, "Reavaliar a estrutura de capital é necessário para assegurar a estabilidade financeira a longo prazo. A empresa deve considerar buscar novas fontes de financiamento de longo prazo, como emissão de ações ou financiamento bancário com prazos mais estendidos.",
			        5, "Continuar monitorando o custo do capital e as condições do mercado para otimizar o mix de financiamento. Manter a flexibilidade financeira permitirá à empresa se adaptar rapidamente a mudanças no ambiente econômico.",
			        6, "Focar no crescimento e expansão utilizando o financiamento disponível de forma estratégica. Investir em projetos que ofereçam retornos sustentáveis e que possam fortalecer a posição competitiva da empresa no mercado.",
			        7, " Investir em projetos com retorno rápido pode melhorar a liquidez e proporcionar uma base financeira mais sólida para a empresa. Focar em aumentar a eficiência operacional e reduzir custos desnecessários também será benéfico.",
			        8, " Adotar estratégias para aumentar o financiamento de longo prazo, como emissão de títulos ou obtenção de linhas de crédito mais extensas, ajudará a melhorar a gestão do capital de giro e evitar problemas de liquidez.",
			        9, "Manter a estrutura atual de financiamento de longo prazo para minimizar riscos de refinanciamento. Focar em otimizar operações para melhorar a geração de caixa e manter a saúde financeira robusta.",
			        10, "Monitorar a estrutura de capital e ajustar conforme necessário para manter o equilíbrio entre curto e longo prazo. Investir em melhorias operacionais pode gerar mais caixa e reduzir a dívida ao longo do tempo.",
			        11, "Melhorar a gestão de recebíveis e estoques pode liberar caixa adicional e fortalecer a posição financeira da empresa. Implementar práticas de gestão de capital de giro eficientes será benéfico a longo prazo.",
			        12, "Implementar medidas para melhorar a geração de caixa, como aumentar a eficiência operacional e controlar custos, ajudará a empresa a fortalecer sua posição financeira e reduzir a dependência de empréstimos de curto prazo.",
			        13, " Avaliar a estrutura de capital e buscar alternativas de financiamento que ofereçam melhores condições. Considerar a emissão de ações ou outras formas de capital próprio para reduzir a alavancagem e fortalecer a base de capital.",
			        14, "Melhorar a eficiência operacional para aumentar a capacidade de pagamento e reduzir a dependência de financiamentos externos. Investir em tecnologias e processos que aumentem a produtividade e gerem economias de custo.",
			        15, "Implementar uma gestão de custos rigorosa para melhorar a lucratividade e liberar recursos para pagamento de dívidas. Avaliar oportunidades de desinvestimento em ativos não essenciais para fortalecer a posição financeira.",
			        16, "Melhorar a eficiência do capital de giro e implementar práticas robustas de gestão financeira são cruciais para garantir a sustentabilidade a longo prazo. Avaliar a estrutura de capital e considerar a diversificação das fontes de financiamento.",
			        17, "Otimizar operações para aumentar a geração de caixa e reduzir a dependência de financiamentos externos. Investir em melhorias operacionais e inovação pode fortalecer a posição competitiva da empresa e proporcionar uma base financeira mais sólida.",
			        18, "Investir em melhorias operacionais para gerar caixa adicional e reduzir a alavancagem. Focar na eficiência e na otimização de processos pode proporcionar economias significativas e fortalecer a posição financeira da empresa.",
			        19, "Implementar uma estratégia agressiva de redução de custos e aumento da eficiência operacional é crucial para melhorar a lucratividade e a capacidade de pagamento. Investir em tecnologias que aumentem a produtividade e reduzam os custos operacionais pode gerar economias significativas.",
			        20, "Revisar a estrutura de capital da empresa para reduzir a vulnerabilidade financeira. Implementar uma estratégia de desinvestimento em ativos não essenciais pode liberar recursos para reduzir a dívida e fortalecer a posição financeira da empresa.",
			        "Estratégia de longo prazo não disponível."
			    )
			
			    //MOVIMENTAÇÃO
			
			    VAR cp_variacao = DIVIDE([variacao_emprest_CP] + [variacao_emprest_LP], [ssomaemprestEfinan])
			
			VAR var_emprest =
			    SWITCH(
			        TRUE(),
			        cp_variacao >= 0.71, "8",
			        cp_variacao >= 0.61, "7",
			        cp_variacao >= 0.51, "6",
			        cp_variacao >= 0.41, "5",
			        cp_variacao >= 0.31, "4",
			        cp_variacao >= 0.21, "3",
			        cp_variacao >= 0.11, "2",
			        cp_variacao >= 0, "1",
			        cp_variacao >= -0.10, "9",
			        cp_variacao >= -0.20, "10",
			        cp_variacao >= -0.30, "11",
			        cp_variacao >= -0.40, "12",
			        cp_variacao >= -0.50, "13",
			        cp_variacao >= -0.60, "14",
			        cp_variacao >= -0.70, "15",
			        "16"
			    )
			
			VAR interpret_var_comentario =
			    SWITCH(
			        var_emprest,
			        "8", "Aumento crítico, indicando uma dependência extrema de empréstimos.",
			        "7", "Aumento muito alto, o que pode ser preocupante.",
			        "6", "Aumento expressivo, possivelmente indicando problemas de liquidez.",
			        "5", "Aumento substancial no saldo de empréstimos.",
			        "4", "Aumento significativo, sugerindo a realização de grandes projetos ou cobertura de grandes déficits.",
			        "3", "Considerável aumento no saldo de empréstimos.",
			        "2", "Aumento moderado nos empréstimos, indicando maior necessidade de capital.",
			        "1", "Pequeno aumento no saldo de empréstimos.",
			        "9", "Redução pequena nos empréstimos.",
			        "10", "Redução moderada nos empréstimos.",
			        "11", "Considerável redução, melhorando significativamente a alavancagem.",
			        "12", "Redução significativa nos empréstimos.",
			        "13", "Redução substancial, melhorando a posição financeira.",
			        "14", "Redução expressiva na dívida.",
			        "15", "Grande redução, indicando uma melhoria substancial na saúde financeira.",
			        "16", "Redução crítica, possivelmente eliminando a maioria ou toda a dívida."
			    )
			
			RETURN
			"<div style='font-family: Bw Glenn Sans DEMO Medium, sans-serif; margin: 20px;'>
			    <h1 style='color: #000000; font-family: Brush Script MT, cursive; font-style: italic;'>Nossas Considerações</h1>
			    <h3 style='font-weight: bold;'>🔍 Análise do Saldo</h3>
			    <!--<p><strong>Cenário:</strong> " & cenario & "</p>-->
			    <p><strong>💡</strong> " & saldoInterpretacao & "</p>
			    <p><strong>💡 Estratégias a Curto Prazo:</strong> " & saldoCurtoPrazo & "</p>
			    <p><strong>💡 Estratégias a Longo Prazo:</strong> " & saldoLongoPrazo & "</p>
			    <!--<h3 style='font-weight: bold;'>Movimentação</h3>
			    <p><strong>Interpretação:</strong> " & interpret_var_comentario & "</p>-->
			</div>
			"
			```
		lineageTag: 95fef0d0-588a-46c8-98eb-9d88390ba6df

	measure 'totpassivo II' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			VAR _passcir = [ssomapasscircu]
			VAR _passncir = [ssomapassncirculante]
			
			    RETURN
			    CALCULATE(
			_passcir +  
			    IF(_passncir < 0
			    , _passncir * -1
			    , _passncir)
			    ,dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre)
			```
		formatString: #,0.00
		lineageTag: 38ada53b-fc37-4f5e-b891-4772d796c9c5

	measure periodo_data_completo =
			
			CALCULATE(
			    MAX(dCalendario[data])
			
			    )
		formatString: Short Date
		lineageTag: 1e069475-68fc-4ddc-8dd7-e665c951a934

	measure valor_balancetenew = ```
			
			VAR resultado = 
			DIVIDE(
			    CALCULATE(
			        SUM(balancetenew[vlr])
			    ), 1000)
			VAR resultado_ly = 
			DIVIDE(
			    CALCULATE(
			        SUM(balancetenew[vlr]), 
			        SAMEPERIODLASTYEAR(dCalendario[data])
			    ), 1000)
			RETURN
			    IF(
			        resultado = 0 && resultado_ly = 0,
			        BLANK(),
			        resultado
			    )
			```
		formatString: #,0
		lineageTag: f958c919-4d8e-4136-a0db-677a26ca27a8

		annotation PBI_FormatHint = {"isDecimal":true}

	measure valor_balancetenew_LY = ```
			
			VAR resultado_atual = 
			DIVIDE(
			    CALCULATE(
			        SUM(balancetenew[vlr])
			    ), 1000)
			VAR resultado_ly = 
			DIVIDE(
			    CALCULATE(
			        SUM(balancetenew[vlr]), 
			        DATEADD(dCalendario[data], -1, YEAR)
			    ),
			    1000)
			RETURN
			    IF(
			        resultado_ly = BLANK() && resultado_atual <> 0,
			        0,
			        resultado_ly
			    )
			
			```
		formatString: #,0
		lineageTag: 5a37da8e-92ed-413d-8531-1dde2f74d4ac

		annotation PBI_FormatHint = {"isDecimal":true}

	measure saldo_passivo_balancetenew_LY =
			
			CALCULATE(
			    [saLdo_passivo_balancetenew_df_ass], DATEADD(dCalendario[data], -1, YEAR))
		formatString: #,0
		lineageTag: 4123f224-1597-4682-8d96-556ab52282ac

		annotation PBI_FormatHint = {"isDecimal":true}

	measure periodo_num_mes_ano =
			
			CALCULATE(
			    MAX(dCalendario[NuMês/Ano])
			
			    )
		lineageTag: 8d57d5f7-89d2-48cd-aa1f-86c2f72ffa0b

	measure periodo_num_mes_ano_LY =
			
			CALCULATE([periodo_num_mes_ano],
			DATEADD(dCalendario[data], -1, YEAR))
		lineageTag: 677f8b17-b6a4-40cf-8ddd-a0165d847e6a

	measure variacao_valor_balancetenew% = ```
			
			VAR valor_atual = [valor_balancetenew_BP]
			VAR valor_ano_anterior = [valor_balancetenew_BP_LY]
			
			RETURN
			
			IF( valor_atual <> 0 && valor_ano_anterior = 0 || BLANK(), 1,
			DIVIDE(
			valor_atual - 
			valor_ano_anterior,
			valor_ano_anterior))
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 1f55f0b1-959e-40cc-ae08-745382559f5b

	measure variacao_saldo_passivo% =
			
			DIVIDE(
			    [saLdo_passivo_balancetenew_df_ass] - [saldo_passivo_balancetenew_LY],
			    [saldo_passivo_balancetenew_LY]
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 9275f2c3-dcfe-4f49-954b-5771315ebefe

	measure saldo_passivo_balancnew_mil =
			
			DIVIDE(
			    [saldo_passivo_balancetenew],
			    1000)
		formatString: #,0
		lineageTag: d9435a9a-8136-4d53-83e3-e6ff112ecfad

		annotation PBI_FormatHint = {"isDecimal":true}

	measure valor_balancetenew_DRE = ```
			
			VAR resultado = 
			    DIVIDE(
			        CALCULATE(
			            SUM(balancetenew[vlr]), DATESYTD(dCalendario[data])
			        ), 1000
			    )
			VAR resultado_ly = 
			    DIVIDE(
			        CALCULATE(
			            SUM(balancetenew[vlr]), 
			            SAMEPERIODLASTYEAR(dCalendario[data])
			        ), 1000
			    )
			VAR resultado_formatado = 
			    IF(
			        resultado < 0, 
			        "(" & FORMAT(ABS(resultado), "#,##0") & ")", 
			        FORMAT(resultado, "#,##0")
			    )
			RETURN
			    IF(
			        resultado = 0 && resultado_ly = 0,
			        BLANK(),
			        resultado_formatado
			    )
			```
		lineageTag: a88f3918-8d25-468c-b878-752f02a72c80

	measure valor_balancetenew_DRE_LY = ```
			
			VAR resultado_atual = 
			    DIVIDE(
			        CALCULATE(
			            SUM(balancetenew[vlr]), DATESYTD(dCalendario[data])
			        ), 1000
			    )
			VAR resultado_ly = 
			    DIVIDE(
			        CALCULATE(
			            SUM(balancetenew[vlr]),
			             DATESYTD(
			            DATEADD(dCalendario[data], -1, YEAR))
			        ), 
			        1000
			    )
			VAR resultado_ly_formatado = 
			    IF(
			        resultado_ly < 0, 
			        "(" & FORMAT(ABS(resultado_ly), "#,##0") & ")", 
			        FORMAT(resultado_ly, "#,##0")
			    )
			RETURN
			    IF(
			        (resultado_ly = BLANK() && resultado_atual = BLANK()) || 
			        (resultado_ly = 0 && resultado_atual = 0),
			        BLANK(),
			        IF(
			            resultado_ly = BLANK() && resultado_atual <> 0,
			            "0",
			            resultado_ly_formatado
			        )
			    )
			```
		lineageTag: a149143b-44da-4d0c-a452-2acc5369fc38

	measure resultado_DRE =
			
			IF([LLucro_liquido_ACU] > 0, "Lucro Líquido do Exercício", "Prejuízo do Exercício")
		lineageTag: 8bea8771-dcda-4f38-88c8-8a20a44b54cf

	measure valor_balancete_AH_DRE = ```
			
			VAR valor_atual = [valor_balancetenew]
			VAR valor_ano_anterior = [valor_balancetenew_LY]
			
			RETURN
			
			IF( valor_atual <> 0 && valor_ano_anterior = 0 || BLANK(), 1,
			DIVIDE(
			ABS(valor_atual - 
			valor_ano_anterior),
			ABS(valor_ano_anterior)
			))
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 9526c0a4-a813-4d70-a403-aea20f5ccd7b

	measure variacao_valor_balancete_DRE_AH = ```
			
			VAR resultado = 
			    DIVIDE(
			        CALCULATE(
			            SUM(balancetenew[vlr]), 
			            DATESYTD(dCalendario[data])
			        ), 1000
			    )
			VAR resultado_ly = 
			    DIVIDE(
			        CALCULATE(
			            SUM(balancetenew[vlr]), 
			            DATESYTD(SAMEPERIODLASTYEAR(dCalendario[data]))
			        ), 1000
			   )
			VAR diferenca = resultado - resultado_ly
			RETURN
			DIVIDE(
			    diferenca,
			    ABS(resultado_ly)
			) * IF(diferenca < 0, -1, 1)
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 273aac76-092f-4e80-b1f6-f5f0927fe398

	measure variacao_valor_balancetenew$_ACU = ```
			
			VAR resultado = 
			    DIVIDE(
			        CALCULATE(
			            SUM(balancetenew[vlr])
			        ), 1000
			    )
			VAR resultado_ly = 
			    DIVIDE(
			        CALCULATE(
			            SUM(balancetenew[vlr]),
			             SAMEPERIODLASTYEAR(dCalendario[data])
			            ), 1000
			    )
			    RETURN
			
			resultado - resultado_ly    
			```
		formatString: #,0
		lineageTag: 57b55ad9-2e50-445f-a828-79da03e90739

		annotation PBI_FormatHint = {"isDecimal":true}

	measure switch_DMPL =
			
			SWITCH(
			    SELECTEDVALUE(balancetenew[Query]),
			    "BL_PL_Capital_Social",	"Capital Social",
			"BL_PL_Capital_Social_Integralizar",	"Capital Social a Integralizar",
			"BL_PL_Icentivos_Fiscais",	"Incentivos Fiscais",
			"BL_PL_Ajuste_avaliacao_patrimonial",	"Ajuste de avaliação patrimonial",
			"BL_PL_Adto_Aumento_Capital",	"Adto. p/ Aumento de Capital",
			"BL_PL_Reservas",	"Reservas",
			"BL_PL_Lucros_Prejuizos_acumulados",	"Lucros ou Prejuizos acumulados",
			"BL_PL_Lucro_Prejuizo_liquido",	"Lucro ou Prejuizo líquido"
			)
		lineageTag: 1ba87f29-17df-4bff-8e96-86c0aaae69b9

	measure periodo_data_completo_LY =
			
			CALCULATE([periodo_data_completo], SAMEPERIODLASTYEAR(dCalendario[data]))
		formatString: Short Date
		lineageTag: e0d90485-2fb1-45bc-9c33-62f4e7e4dcdb

	measure valor_balancetenew_DMPL = ```
			
			VAR resultado = 
			    DIVIDE(
			        CALCULATE(
			            SUM(balancetenew[vlr])
			        ), 1000
			    )
			VAR resultado_ly = 
			    DIVIDE(
			        CALCULATE(
			            SUM(balancetenew[vlr]), 
			            SAMEPERIODLASTYEAR(dCalendario[data])
			        ), 1000
			    )
			VAR valor =
			    IF(
			        resultado = 0 && resultado_ly = 0,
			        BLANK(),
			        resultado
			    )
			RETURN
			IF(
			    NOT(ISBLANK([variacao_valor_balancetenew$_ACU])) && valor = 0 || BLANK(), 
			    0, 
			    valor
			)
			```
		formatString: #,0
		lineageTag: 71214750-a62a-442a-84c3-3fba02b82c9b

		annotation PBI_FormatHint = {"isDecimal":true}

	measure valor_balancetenew_DMPL_LY = ```
			
			VAR resultado_atual = 
			DIVIDE(
			    CALCULATE(
			        SUM(balancetenew[vlr])
			    ), 1000)
			VAR resultado_ly = 
			DIVIDE(
			    CALCULATE(
			        SUM(balancetenew[vlr]), 
			        DATEADD(dCalendario[data], -1, YEAR)
			    ),
			    1000)
			VAR valor_final =
			    IF(
			        resultado_ly = BLANK() && resultado_atual <> 0,
			        0,
			        resultado_ly
			    )
			
			    RETURN
			    IF(
			    NOT(ISBLANK([variacao_valor_balancetenew$_ACU])) && valor_final = 0 || BLANK(), 
			    0, 
			    valor_final
			)
			```
		formatString: #,0
		lineageTag: dbb54297-0016-47b2-b385-5cdb678cf0fe

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'narrativa_emprestEFinanc II' = ```
			
			VAR cp_ratio = DIVIDE([eemprestEFinanc_CP], [ssomaemprestEfinan])
			VAR lp_ratio = DIVIDE([eemprestEFinanc_LP], [ssomaemprestEfinan])
			VAR proporcao_passivo =
			DIVIDE([eemprestEFinanc_CP] + [eemprestEFinanc_LP], [totpassivo II])
			VAR passivo_ratio = 
			    SWITCH(
			        TRUE(),
			        proporcao_passivo >= 0.71, "entre 71% e 100%",
			        proporcao_passivo >= 0.51, "entre 51% e 70%",
			        proporcao_passivo >= 0.21, "entre 21% e 50%",
			        "entre 1% e 20%"
			    )
			VAR cenario = 
			    SWITCH(
			        TRUE(),
			        cp_ratio >= 0.99 && cp_ratio <= 1 && lp_ratio <= 0.01 && passivo_ratio = "entre 1% e 20%", 1,
			        cp_ratio >= 0.99 && cp_ratio <= 1 && lp_ratio <= 0.01 && passivo_ratio = "entre 21% e 50%", 2,
			        cp_ratio >= 0.99 && cp_ratio <= 1 && lp_ratio <= 0.01 && passivo_ratio = "entre 51% e 70%", 3,
			        cp_ratio >= 0.99 && cp_ratio <= 1 && lp_ratio <= 0.01 && passivo_ratio = "entre 71% e 100%", 4,
			        cp_ratio <= 0.20 && lp_ratio >= 0.80 && passivo_ratio = "entre 1% e 20%", 5,
			        cp_ratio >= 0.21 && cp_ratio <= 0.50 && lp_ratio >= 0.50 && lp_ratio <= 0.79 && passivo_ratio = "entre 1% e 20%", 6,
			        cp_ratio >= 0.51 && cp_ratio <= 0.70 && lp_ratio >= 0.31 && lp_ratio <= 0.50 && passivo_ratio = "entre 1% e 20%", 7,
			        cp_ratio >= 0.71 && cp_ratio <= 1 && lp_ratio >= 0 && lp_ratio <= 0.29 && passivo_ratio = "entre 1% e 20%", 8,
			        cp_ratio <= 0.20 && lp_ratio >= 0.80 && passivo_ratio = "entre 21% e 50%", 9,
			        cp_ratio >= 0.21 && cp_ratio <= 0.50 && lp_ratio >= 0.50 && lp_ratio <= 0.79 && passivo_ratio = "entre 21% e 50%", 10,
			        cp_ratio >= 0.51 && cp_ratio <= 0.70 && lp_ratio >= 0.31 && lp_ratio <= 0.50 && passivo_ratio = "entre 21% e 50%", 11,
			        cp_ratio >= 0.71 && cp_ratio <= 1 && lp_ratio >= 0 && lp_ratio <= 0.29 && passivo_ratio = "entre 21% e 50%", 12,
			        cp_ratio <= 0.20 && lp_ratio >= 0.80 && passivo_ratio = "entre 51% e 70%", 13,
			        cp_ratio >= 0.21 && cp_ratio <= 0.50 && lp_ratio >= 0.50 && lp_ratio <= 0.79 && passivo_ratio = "entre 51% e 70%", 14,
			        cp_ratio >= 0.51 && cp_ratio <= 0.70 && lp_ratio >= 0.31 && lp_ratio <= 0.50 && passivo_ratio = "entre 51% e 70%", 15,
			        cp_ratio >= 0.71 && cp_ratio <= 1 && lp_ratio >= 0 && lp_ratio <= 0.29 && passivo_ratio = "entre 51% e 70%", 16,
			        cp_ratio <= 0.20 && lp_ratio >= 0.80 && passivo_ratio = "entre 71% e 100%", 17,
			        cp_ratio >= 0.21 && cp_ratio <= 0.50 && lp_ratio >= 0.50 && lp_ratio <= 0.79 && passivo_ratio = "entre 71% e 100%", 18,
			        cp_ratio >= 0.51 && cp_ratio <= 0.70 && lp_ratio >= 0.31 && lp_ratio <= 0.50 && passivo_ratio = "entre 71% e 100%", 19,
			        cp_ratio >= 0.71 && cp_ratio <= 1 && lp_ratio >= 0 && lp_ratio <= 0.29 && passivo_ratio = "entre 71% e 100%", 20,
			        BLANK()
			    )
			
			VAR saldoInterpretacao = 
			    SWITCH(
			        cenario,
			        1, "O cenário indica que a empresa tem uma baixa dependência de financiamentos de curto prazo, o que é positivo para a saúde financeira. Com 100% dos empréstimos no passivo circulante representando apenas <strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong> do total do passivo <strong style='color: #000000;'>" & FORMAT([totpassivo II], "R$ #,##0,00") & "</strong>, a empresa possui um risco reduzido de liquidez.",
			        2, "A dependência moderada de empréstimos de curto prazo sugere que a empresa utiliza esses recursos de forma estratégica para cobrir necessidades operacionais. No entanto, isso também aumenta a necessidade de uma gestão cuidadosa do fluxo de caixa.",
			        3, " A alta dependência de empréstimos de curto prazo, representando <strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong> do passivo total <strong style='color: #000000;'>" & FORMAT([totpassivo II], "R$ #,##0,00") & "</strong>, coloca a empresa em uma posição de maior risco financeiro devido à necessidade frequente de refinanciamento.",
			        4, "A dependência crítica de empréstimos de curto prazo, com <strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong> do passivo, indica uma vulnerabilidade financeira muito alta. A empresa está exposta a riscos significativos de liquidez e refinanciamento. ",
			        5, "A empresa mantém um baixo nível de dívida total <strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong>, com uma pequena porção em curto prazo e a maioria em longo prazo, o que indica uma gestão financeira conservadora e uma posição de baixa vulnerabilidade. ",
			        6, "A estrutura de dívida equilibrada entre curto e longo prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong> no curto prazo e <strong style='color: #000000;'>" & FORMAT(lp_ratio, "0.0%") & "</strong> no longo prazo), com baixo impacto no passivo total, sugere uma abordagem prudente e bem balanceada na gestão financeira da empresa. ",
			        7, " A maior proporção de dívida de curto prazo, embora ainda com baixo impacto no passivo total, pode indicar uma necessidade de maior atenção ao gerenciamento do fluxo de caixa para evitar problemas de liquidez. ",
			        8, " Alta dependência de curto prazo, com <strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong> do total de empréstimos, mas com um impacto geral baixo, os emprestimos representam <strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong> do passivo apenas, no entanto, isso requer uma gestão cuidadosa para evitar vulnerabilidades financeiras. A empresa precisa monitorar de perto sua capacidade de cumprir obrigações a curto prazo. ",
			        9, "Com uma baixa proporção de dívida de curto prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) e uma dependência maior de longo prazo (<strong style='color: #000000;'>" & FORMAT(lp_ratio, "0.0%") & "</strong>), a empresa se beneficia de uma estrutura financeira mais estável, com os empréstimos representando <strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong> do passivo. ",
			        10, "A combinação de uma dívida moderada de curto prazo e uma maior proporção de longo prazo indica uma estrutura equilibrada de passivos, embora seja importante manter uma vigilância contínua sobre os níveis de endividamento e sua relação com o passivo total <strong style='color: #000000;'>" & FORMAT([totpassivo II], "R$ #,##0,00") & "</strong>. ",
			        11, "A proporção equilibrada de curto prazo (entre <strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) e longo prazo (entre <strong style='color: #000000;'>" & FORMAT(lp_ratio, "0.0%") & "</strong>) sugere uma estratégia financeira balanceada, com a dívida representando uma parte significativa do passivo total <strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong>. ",
			        12, "A dependência mais alta de curto prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) exige atenção ao gerenciamento do fluxo de caixa para evitar pressões financeiras, especialmente com a dívida representando <strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong> do passivo total. ",
			        13, "A baixa dependência de curto prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) com uma alta proporção de longo prazo (<strong style='color: #000000;'>" & FORMAT(lp_ratio, "0.0%") & "</strong>) proporciona uma base financeira estável, com os empréstimos representando <strong style='color: #000000;'>" & FORMAT(proporcao_passivo, "0.0%") & "</strong> do passivo total. ",
			        14, "A combinação de uma dívida moderada de curto prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) e uma maior proporção de longo prazo (<strong style='color: #000000;'>" & FORMAT(lp_ratio, "0.0%") & "</strong>) indica uma estrutura equilibrada de passivos. ",
			        15, "A proporção equilibrada de curto prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) e longo prazo (<strong style='color: #000000;'>" & FORMAT(lp_ratio, "0.0%") & "</strong>) sugere uma abordagem financeira balanceada, com a dívida representando uma parte significativa do passivo total. ",
			        16, "A dependência mais alta de curto prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) exige atenção ao gerenciamento do fluxo de caixa para evitar pressões financeiras, especialmente com a dívida representando uma parte significativa do passivo total. ",
			        17, "A baixa dependência de curto prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) com uma alta proporção de longo prazo (<strong style='color: #000000;'>" & FORMAT(lp_ratio, "0.0%") & "</strong>) proporciona uma base financeira estável, com os empréstimos representando uma parte substancial do passivo total. ",
			        18, "A combinação de uma dívida moderada de curto prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) e uma maior proporção de longo prazo (<strong style='color: #000000;'>" & FORMAT(lp_ratio, "0.0%") & "</strong>) indica uma estrutura equilibrada de passivos. ",
			        19, "A proporção equilibrada de curto prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) e longo prazo (<strong style='color: #000000;'>" & FORMAT(lp_ratio, "0.0%") & "</strong>) sugere uma abordagem financeira balanceada, com a dívida representando uma parte significativa do passivo total. ",
			        20, "A dependência mais alta de curto prazo (<strong style='color: #000000;'>" & FORMAT(cp_ratio, "0.0%") & "</strong>) exige atenção ao gerenciamento do fluxo de caixa para evitar pressões financeiras, especialmente com a dívida representando uma parte significativa do passivo total. ",
			        BLANK()
			    )
			VAR saldoCurtoPrazo = 
			    SWITCH(
			        cenario,
			        1, "Continuar a manter essa baixa dependência de financiamentos de curto prazo é essencial. A empresa deve focar em manter reservas de caixa adequadas para enfrentar qualquer necessidade de liquidez inesperada e garantir que os pagamentos possam ser realizados sem dificuldades.",
			        2, "Avaliar a possibilidade de renegociar os prazos de parte dos empréstimos para alongar a dívida pode reduzir a pressão sobre o fluxo de caixa e proporcionar mais estabilidade financeira. ",
			        3, "Refinanciar parte da dívida em condições mais favoráveis é crucial para reduzir os custos financeiros e aliviar a pressão sobre o fluxo de caixa a curto prazo. Negociar taxas de juros mais baixas e prazos mais longos pode ser benéfico.",
			        4, "Priorizar a redução da dívida de curto prazo deve ser uma meta imediata. Renegociar prazos e buscar alternativas de financiamento mais sustentáveis são passos essenciais para aliviar a pressão sobre a empresa.",
			        5, "Aproveitar o baixo nível de endividamento para investir em oportunidades estratégicas que possam gerar retornos significativos. A empresa pode explorar investimentos em inovação, expansão de mercado ou aquisição de ativos estratégicos.",
			        6, "Manter essa estrutura de dívida equilibrada para minimizar riscos e custos de capital. Avaliar continuamente o desempenho operacional e financeiro para assegurar que a empresa permaneça em uma posição estável.",
			        7, "Refinanciar parte da dívida de curto prazo para reduzir a pressão sobre o fluxo de caixa é importante. Negociar melhores condições de pagamento com fornecedores e clientes também pode ajudar a melhorar a gestão de caixa.",
			        8, "Implementar estratégias para alongar os prazos das dívidas e reduzir a dependência de curto prazo. Renegociar condições de empréstimos e explorar opções de financiamento alternativas pode aliviar a pressão sobre o caixa.",
			        9, "Explorar oportunidades de financiamento de curto prazo mais barato pode reduzir os custos financeiros e liberar recursos para outras áreas. Avaliar constantemente as condições do mercado para aproveitar oportunidades vantajosas. ",
			        10, "Avaliar constantemente o custo do capital e buscar oportunidades para reduzir os custos financeiros. Manter uma reserva de caixa adequada para cobrir necessidades emergenciais. ",
			        11, "Refinanciar dívidas de curto prazo para longo prazo é essencial para reduzir o risco de liquidez. Negociar melhores condições com credores pode proporcionar mais estabilidade financeira.",
			        12, "Refinanciar e reduzir a dívida de curto prazo deve ser uma prioridade urgente. Negociar condições mais favoráveis e alongar prazos pode ajudar a aliviar a pressão sobre o caixa.",
			        13, "Priorizar a redução da dívida de longo prazo pode ajudar a reduzir os custos financeiros e melhorar a flexibilidade financeira da empresa. Avaliar a possibilidade de amortização antecipada de dívidas com taxas de juros elevadas. ",
			        14, "Refinanciar parte das dívidas para equilibrar os prazos e reduzir os custos financeiros. Negociar condições mais favoráveis com credores para melhorar a estrutura de dívida. ",
			        15, "Alongar os prazos de dívida é uma necessidade urgente para reduzir a pressão sobre o fluxo de caixa. Negociar com credores para obter melhores condições é crucial.",
			        16, "Priorizar a renegociação de prazos e redução da dívida de curto prazo é essencial para evitar problemas de liquidez. Explorar opções de financiamento de longo prazo pode proporcionar mais estabilidade. ",
			        17, "Estruturar financiamento para alongar prazos e reduzir a alavancagem pode ajudar a melhorar a posição financeira. Negociar melhores condições com credores também é importante.",
			        18, " Refinanciar dívidas para reduzir custos e prazos é essencial. Negociar condições mais favoráveis pode ajudar a aliviar a pressão sobre o fluxo de caixa e proporcionar mais estabilidade. ",
			        19, "Focar na renegociação para alongar prazos de empréstimos é essencial para reduzir a pressão sobre o fluxo de caixa e melhorar a estabilidade financeira. Avaliar todas as opções de refinanciamento disponíveis.",
			        20, "Realocar urgentemente a dívida de curto prazo para longo prazo é vital para reduzir a pressão sobre o fluxo de caixa. Negociar melhores condições de financiamento com credores deve ser uma prioridade imediata.",
			        "Estratégia de curto prazo não disponível."
			    )
			VAR saldoLongoPrazo = 
			    SWITCH(
			        cenario,
			         1, "Considerar alternativas de financiamento de longo prazo, como debêntures ou empréstimos bancários com prazos mais longos, pode ajudar a garantir que a empresa esteja preparada para projetos de capital e investimentos futuros, sem comprometer a liquidez.",
			        2, "Monitorar rigorosamente o fluxo de caixa e implementar um sistema robusto de previsões financeiras pode ajudar a identificar e mitigar riscos de liquidez. Além disso, diversificar as fontes de financiamento pode aumentar a resiliência financeira da empresa.",
			        3, "Implementar medidas de controle de custos rigorosas e aumentar a eficiência operacional são fundamentais para melhorar a lucratividade e a capacidade de pagamento da empresa. Investir em automação e otimização de processos pode gerar economias significativas.",
			        4, "Reavaliar a estrutura de capital é necessário para assegurar a estabilidade financeira a longo prazo. A empresa deve considerar buscar novas fontes de financiamento de longo prazo, como emissão de ações ou financiamento bancário com prazos mais estendidos.",
			        5, "Continuar monitorando o custo do capital e as condições do mercado para otimizar o mix de financiamento. Manter a flexibilidade financeira permitirá à empresa se adaptar rapidamente a mudanças no ambiente econômico.",
			        6, "Focar no crescimento e expansão utilizando o financiamento disponível de forma estratégica. Investir em projetos que ofereçam retornos sustentáveis e que possam fortalecer a posição competitiva da empresa no mercado.",
			        7, " Investir em projetos com retorno rápido pode melhorar a liquidez e proporcionar uma base financeira mais sólida para a empresa. Focar em aumentar a eficiência operacional e reduzir custos desnecessários também será benéfico.",
			        8, " Adotar estratégias para aumentar o financiamento de longo prazo, como emissão de títulos ou obtenção de linhas de crédito mais extensas, ajudará a melhorar a gestão do capital de giro e evitar problemas de liquidez.",
			        9, "Manter a estrutura atual de financiamento de longo prazo para minimizar riscos de refinanciamento. Focar em otimizar operações para melhorar a geração de caixa e manter a saúde financeira robusta.",
			        10, "Monitorar a estrutura de capital e ajustar conforme necessário para manter o equilíbrio entre curto e longo prazo. Investir em melhorias operacionais pode gerar mais caixa e reduzir a dívida ao longo do tempo.",
			        11, "Melhorar a gestão de recebíveis e estoques pode liberar caixa adicional e fortalecer a posição financeira da empresa. Implementar práticas de gestão de capital de giro eficientes será benéfico a longo prazo.",
			        12, "Implementar medidas para melhorar a geração de caixa, como aumentar a eficiência operacional e controlar custos, ajudará a empresa a fortalecer sua posição financeira e reduzir a dependência de empréstimos de curto prazo.",
			        13, " Avaliar a estrutura de capital e buscar alternativas de financiamento que ofereçam melhores condições. Considerar a emissão de ações ou outras formas de capital próprio para reduzir a alavancagem e fortalecer a base de capital.",
			        14, "Melhorar a eficiência operacional para aumentar a capacidade de pagamento e reduzir a dependência de financiamentos externos. Investir em tecnologias e processos que aumentem a produtividade e gerem economias de custo.",
			        15, "Implementar uma gestão de custos rigorosa para melhorar a lucratividade e liberar recursos para pagamento de dívidas. Avaliar oportunidades de desinvestimento em ativos não essenciais para fortalecer a posição financeira.",
			        16, "Melhorar a eficiência do capital de giro e implementar práticas robustas de gestão financeira são cruciais para garantir a sustentabilidade a longo prazo. Avaliar a estrutura de capital e considerar a diversificação das fontes de financiamento.",
			        17, "Otimizar operações para aumentar a geração de caixa e reduzir a dependência de financiamentos externos. Investir em melhorias operacionais e inovação pode fortalecer a posição competitiva da empresa e proporcionar uma base financeira mais sólida.",
			        18, "Investir em melhorias operacionais para gerar caixa adicional e reduzir a alavancagem. Focar na eficiência e na otimização de processos pode proporcionar economias significativas e fortalecer a posição financeira da empresa.",
			        19, "Implementar uma estratégia agressiva de redução de custos e aumento da eficiência operacional é crucial para melhorar a lucratividade e a capacidade de pagamento. Investir em tecnologias que aumentem a produtividade e reduzam os custos operacionais pode gerar economias significativas.",
			        20, "Revisar a estrutura de capital da empresa para reduzir a vulnerabilidade financeira. Implementar uma estratégia de desinvestimento em ativos não essenciais pode liberar recursos para reduzir a dívida e fortalecer a posição financeira da empresa.",
			        "Estratégia de longo prazo não disponível."
			    )
			
			    //MOVIMENTAÇÃO
			
			    VAR cp_variacao = DIVIDE([variacao_emprest_CP] + [variacao_emprest_LP], [ssomaemprestEfinan])
			
			VAR var_emprest =
			    SWITCH(
			        TRUE(),
			        cp_variacao >= 0.71, "8",
			        cp_variacao >= 0.61, "7",
			        cp_variacao >= 0.51, "6",
			        cp_variacao >= 0.41, "5",
			        cp_variacao >= 0.31, "4",
			        cp_variacao >= 0.21, "3",
			        cp_variacao >= 0.11, "2",
			        cp_variacao >= 0, "1",
			        cp_variacao >= -0.10, "9",
			        cp_variacao >= -0.20, "10",
			        cp_variacao >= -0.30, "11",
			        cp_variacao >= -0.40, "12",
			        cp_variacao >= -0.50, "13",
			        cp_variacao >= -0.60, "14",
			        cp_variacao >= -0.70, "15",
			        "16"
			    )
			
			VAR interpret_var_comentario =
			    SWITCH(
			        var_emprest,
			        "8", "Aumento crítico, indicando uma dependência extrema de empréstimos.",
			        "7", "Aumento muito alto, o que pode ser preocupante.",
			        "6", "Aumento expressivo, possivelmente indicando problemas de liquidez.",
			        "5", "Aumento substancial no saldo de empréstimos.",
			        "4", "Aumento significativo, sugerindo a realização de grandes projetos ou cobertura de grandes déficits.",
			        "3", "Considerável aumento no saldo de empréstimos.",
			        "2", "Aumento moderado nos empréstimos, indicando maior necessidade de capital.",
			        "1", "Pequeno aumento no saldo de empréstimos.",
			        "9", "Redução pequena nos empréstimos.",
			        "10", "Redução moderada nos empréstimos.",
			        "11", "Considerável redução, melhorando significativamente a alavancagem.",
			        "12", "Redução significativa nos empréstimos.",
			        "13", "Redução substancial, melhorando a posição financeira.",
			        "14", "Redução expressiva na dívida.",
			        "15", "Grande redução, indicando uma melhoria substancial na saúde financeira.",
			        "16", "Redução crítica, possivelmente eliminando a maioria ou toda a dívida."
			    )
			
			RETURN
			"<div style='font-family: Bw Glenn Sans DEMO Medium, sans-serif; margin: 20px;'>
			    <h1 style='color: #000000; font-family: Brush Script MT, cursive; font-style: italic;'>Nossas Considerações</h1>
			    <h3 style='font-weight: bold;'>🔍 Análise do Saldo</h3>
			    <!--<p><strong>Cenário:</strong> " & cenario & "</p>-->
			    <p><strong>💡</strong> " & saldoInterpretacao & "</p>
			    <p><strong>💡 Estratégias a Curto Prazo:</strong> " & saldoCurtoPrazo & "</p>
			    <p><strong>💡 Estratégias a Longo Prazo:</strong> " & saldoLongoPrazo & "</p>
			    <!--<h3 style='font-weight: bold;'>Movimentação</h3>
			    <p><strong>Interpretação:</strong> " & interpret_var_comentario & "</p>-->
			</div>
			"
			
			
			```
		lineageTag: 209dbb5a-1199-496d-9fa6-c51233a6c3da

	measure faturamento_menos_deducoes = ```
			
			VAR MaxDate = MAX(dCalendario[data])  // Obtém a última data selecionada no contexto de filtro
			
			VAR vfaturamento =
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "receita bruta" &&
			            balancetenew[data] >= DATEADD(dCalendario[data], -12, MONTH) &&  // Considera os últimos 12 meses
			            balancetenew[data] <= MaxDate
			        ),
			        balancetenew[vlr]
			    )
			
			VAR vdeducoes =
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Deduções da Receita Bruta" &&
			            balancetenew[data] >= DATEADD(dCalendario[data], -12, MONTH) &&  // Considera os últimos 12 meses
			            balancetenew[data] <= MaxDate
			        ),
			        balancetenew[vlr]
			    ) * -1  // Multiplica por -1 para subtrair as deduções
			
			RETURN
			    vfaturamento - vdeducoes
			
			```
		lineageTag: 5aaf769c-1c83-4d99-aa57-5435bdd6a651

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CCusto|Receitabruta_ACU =
			
			VAR vcusto =
			[CCusto_ACU] *-1
			VAR vreceita =
			[MReceita_Bruta_ACU]
			
			RETURN
			DIVIDE(
			vcusto,
			vreceita
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4cdc81ad-4871-4ae1-a52c-82cf44a4053d

	measure 'LLucro_liquido | Receita_Bruta_ACU' =
			
			DIVIDE(
			          [LLucro_liquido_ACU],
			            [MReceita_Bruta_ACU]
			        )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e72e9d5d-93f0-4b30-9721-4a077fe890b1

	measure cfs_impostos_recebidos_ACU =
			
			CALCULATE(
			SUMX(
			    FILTER(balancetenew,
			    balancetenew[Query] = "DRE_Imposto_de_Renda" ||
			    balancetenew[Query] = "DRE_Contribuicao_Social"),
			    balancetenew[vlr]),
			    DATESYTD(dCalendario[data]))
		formatString: #,0
		lineageTag: 1a192094-9991-4459-9712-e100485f1e46

		annotation PBI_FormatHint = {"isDecimal":true}

	measure cfs_renda_extraordinaria_ACU =
			
			CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "DRE_Desp_Operacionais_Equivalencia_Patrimonial" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Outras_receitas_operacionais"),
			        balancetenew[vlr]),
			        DATESYTD(dCalendario[data]))
		formatString: #,0
		lineageTag: 549b1533-8adc-4108-9d5e-4d7394561b05

		annotation PBI_FormatHint = {"isDecimal":true}

	measure cfs_distribuicao_de_lucros_ACU =
			
			CALCULATE(
			SUMX(
			    FILTER(balancetenew,
			    balancetenew[Query] = "BL_PL_Soma" &&
			    balancetenew[descricao_cliente] = "DISTRIBUICAO DE LUCROS"),
			    balancetenew[vlr]
			) *-1,
			DATESYTD(dCalendario[data]))
		formatString: #,0
		lineageTag: 5ceaddb6-940b-44e7-8a5a-20963414adea

		annotation PBI_FormatHint = {"isDecimal":true}

	measure cfs_distribuicao_de_lucros_ACU_LY =
			
			CALCULATE([cfs_distribuicao_de_lucros_ACU], DATEADD(dCalendario[data], -1, YEAR))
		lineageTag: 3eb666cd-5178-4f40-8776-f485438cfdbc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure cfs_distribuicao_de_lucros_DIF_ACU =
			
			[cfs_distribuicao_de_lucros_ACU] - [cfs_distribuicao_de_lucros_ACU_LY]
		lineageTag: 69449de4-0355-4adc-ad70-40fb93759482

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure var_receita_bruta_ACU_sinal = ```
			
			IF([variacao_receita_bruta$_ACU] > 0, 
			"🟢", 
			"🔴"
			)
			```
		lineageTag: f86905e8-36e9-40e3-9409-a03d5f7dce15

	measure desp_operac_ebit_menos_comerciais_actual_month = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			RETURN
			CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew,
			       // balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_comerciais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Salarios_ordenados" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Beneficios" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Provisoes" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Impostos" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_administrativas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Ocupacao" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_contratuais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_controladas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_nao_controladas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Marketing" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Logistica" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Consultoria_Tecnica" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Alugueis" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Prestacao_de_Servicos" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Manutencoes" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Informatica"
			
			    ),
			    balancetenew[vlr]
			),
			    dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre) *-1
			```
		formatString: #,0
		lineageTag: c97b6c67-d11c-4e7d-bccb-76e566d41fb3

		annotation PBI_FormatHint = {"isDecimal":true}

	measure analise_g&a =
			
			DIVIDE(
			    IF(
			    [desp_operac_ebit_actual_month] > 0, [desp_operac_ebit_actual_month], [desp_operac_ebit_actual_month] *-1),
			    [MReceita_Liquida_actual_month])
		lineageTag: c8dd8cf6-d959-4e6f-8960-a74f8f59f0a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure analise_gs&a =
			
			DIVIDE(
			    [desp_operac_ebit_menos_comerciais_actual_month],
			    [MReceita_Liquida_actual_month]
			)
		lineageTag: 6a927e43-8d72-4ad8-907f-0aa0c1ca6c93

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure desp_operac_ebit_actual_month = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			RETURN
			
			CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_comerciais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Salarios_ordenados" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Beneficios" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Provisoes" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Impostos" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_administrativas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Ocupacao" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_contratuais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_controladas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_nao_controladas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Marketing" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Logistica" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Consultoria_Tecnica" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Alugueis" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Prestacao_de_Servicos" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Manutencoes" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Informatica"
			
			    ),
			    balancetenew[vlr]
			),
			dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre)
			```
		formatString: #,0
		lineageTag: 356cf950-4a17-4c6e-9fd7-88ea0f25070e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure analise_sg&a_ACU =
			
			DIVIDE(
			[desp_operac_ebit_ACU],
			[MReceita_Liquida_ACU]
			)
		lineageTag: 3e6e5efe-8868-48b7-9a3d-9c61ff232113

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure desp_operac_ebit_menos_comerciais_ACU =
			
			CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew,
			        //balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_comerciais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Salarios_ordenados" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Beneficios" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Provisoes" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Impostos" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_administrativas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Ocupacao" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_contratuais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_controladas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_nao_controladas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Marketing" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Logistica" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Consultoria_Tecnica" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Alugueis" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Prestacao_de_Servicos" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Manutencoes" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Informatica"
			
			    ),
			    balancetenew[vlr]
			),
			DATESYTD(dCalendario[data])) *-1
		lineageTag: 05568de7-4502-4547-944d-635c44633e2b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure analise_g&a_ACU =
			
			DIVIDE(
			    [desp_operac_ebit_menos_comerciais_ACU],
			    [MReceita_Liquida_ACU])
		lineageTag: 7eea32e2-57e9-4cfe-a389-e0a2f0e5ad2b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure analise_g&a_LM =
			
			CALCULATE(
			    [analise_g&a],
			    DATEADD(dCalendario[data], -1, MONTH))
		lineageTag: 07ac93fd-2335-4a3b-85df-ca5155f1ca34

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure analise_sg&a_LM =
			
			CALCULATE(
			    [analise_gs&a],
			    DATEADD(dCalendario[data], -1, MONTH))
		lineageTag: a3b9da0e-131d-4f3a-a3b4-24fe2ba4595d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure analise_sg&a_selecionada =
			
			SELECTEDVALUE(analises_sga[tipo analise])
		lineageTag: 94d57334-395e-4d44-aca2-afe42f054595

	measure desp_operac_ebit_menos_comerciais =
			
			
			SUMX(
			    FILTER(
			        balancetenew,
			       // balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_comerciais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Salarios_ordenados" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Beneficios" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Provisoes" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal_Impostos" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_administrativas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Ocupacao" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_depreciacao" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_pessoal" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_contratuais" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_controladas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_nao_controladas" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Marketing" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Logistica" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Consultoria_Tecnica" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Alugueis" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Prestacao_de_Servicos" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Manutencoes" ||
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_com_Informatica"
			
			    ),
			    balancetenew[vlr]
			) *-1
		formatString: #,0
		lineageTag: e08cf2cd-754d-4b0c-98cf-2319a83b9666

		annotation PBI_FormatHint = {"isDecimal":true}

	measure BL_ATCIR_Impostos_recuperar_LM = ```
			
			CALCULATE(
			    [BL_ATCIR_Impostos_recuperar], 
			    DATEADD(
			        dCalendario[data], 
			        -1, 
			        MONTH
			    ))
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 11991c61-d8cd-4386-b245-5b5f80537c74

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure BL_ATCIR_Impostos_recuperar_LY = ```
			
			CALCULATE(
			    [BL_ATCIR_Impostos_recuperar], 
			    DATEADD(
			        dCalendario[data],
			        -1,
			        YEAR
			    )
			    )
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: e029320e-3ab6-4ab7-ae2f-0c867ff8cddb

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure variacao_impostos_recuperar =
			
			DIVIDE(
			    [BL_ATCIR_Impostos_recuperar] - [BL_ATCIR_Impostos_recuperar_LM],
			    [BL_ATCIR_Impostos_recuperar_LM]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 08dd4110-f25e-4c5b-a629-8b1b0482aebd

	measure impostos_recuperar|SomaAtivCircu =
			
			DIVIDE(
			    [BL_ATCIR_Impostos_recuperar],
			    [BL_ATCIR_total_ativo_circulante]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a5415b72-cbc2-4de3-8292-599ea2bc2328

	measure BL_ATCIR_total_ativo_circulante_LM = ```
			
			CALCULATE(
			    [BL_ATCIR_total_ativo_circulante], 
			    DATEADD(dCalendario[data], -1, MONTH))
			```
		formatString: #,0.00
		lineageTag: 3ee742bb-aabe-4f86-877b-6c6de5efa59d

	measure BL_ATCIR_total_ativo_circulante_LY =
			
			CALCULATE(
			    [BL_ATCIR_total_ativo_circulante],
			    DATEADD(dCalendario[data],
			    -1,
			    YEAR
			    ))
		formatString: #,0
		lineageTag: 25c82811-0a8d-44f6-a9e5-623c760462c1

		annotation PBI_FormatHint = {"isDecimal":true}

	measure impostos_recuperar|SomaAtivCircu_LM =
			
			CALCULATE(
			    [impostos_recuperar|SomaAtivCircu],
			    DATEADD(dCalendario[data],
			    -1,
			    MONTH
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 18585836-a4d7-4f9e-b2b3-406eee7ef2b4

	measure impostos_recuperar|SomaAtivCircu_LY =
			
			CALCULATE(
			    [impostos_recuperar|SomaAtivCircu],
			    DATEADD(
			        dCalendario[data],
			        -1,
			        YEAR
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9222351b-02aa-44c6-8485-909d43583018

	measure BL_ATCIR_Adiantamentos_socios = ```
			
			VAR v_adiantamento =
			SUMX(
			    FILTER(
			        balancetenew, 
			    balancetenew[Query] = "BL_ATCIR_Adiantamentos_Socios"), 
			    balancetenew[vlr]
			    )
			
			RETURN
			IF(v_adiantamento = BLANK(), "#,0.00", v_adiantamento)
			```
		lineageTag: cd9d8b74-2e79-452a-97bb-9fba82e6b7b7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BL_ATCIR_partes_relacionadas = ```
			
			VAR v_adiantamento =
			SUMX(
			    FILTER(
			        balancetenew, 
			    balancetenew[Query] = "BL_ATCIR_Partes_Relacionadas"), 
			    balancetenew[vlr]
			    )
			
			RETURN
			v_adiantamento
			```
		formatString: #,0
		lineageTag: a021b207-5ead-4461-a0b6-03c64ffb9d27

		annotation PBI_FormatHint = {"isDecimal":true}

	measure divida_liq_sobre_ebitda = ```
			
			DIVIDE(
			    [divida_liquida],
			    [EEBITDA_actual_month]
			    
			)
			```
		formatString: #,0.00
		lineageTag: ac70aa57-521a-4086-9843-f258a410d391

	measure 'Endividamento total LM' = ```
			
			CALCULATE(
			    [Endividamento total], 
			    DATEADD(
			        dCalendario[data], -1, MONTH
			    )
			)
			```
		formatString: #,0
		lineageTag: 218f22c3-d47c-46d2-bc62-41cbdfce8ee1

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Endividamento CP' = ```
			
			DIVIDE(
			SUMX('Medidas_balancetenew', 
			'Medidas_balancetenew'[ssomapasscircu]), 
			'Medidas_balancetenew'[patrimonioLiq])
			```
		lineageTag: 940e79e1-40ea-4fda-a24d-4523d6cf56f8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Endividamento LP' = ```
			
			DIVIDE(
			'Medidas_balancetenew'[ssomapassncirculante], 
			'Medidas_balancetenew'[patrimonioLiq])
			```
		lineageTag: 89699ea5-2e6e-4714-bc05-aa5a732dc2d3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure divida_liq_sobre_ebitda_LM =
			
			CALCULATE(
			    [divida_liq_sobre_ebitda],
			    DATEADD(
			        dCalendario[data],
			        -1,
			        MONTH
			    )
			)
		lineageTag: 6e55cb77-f52c-42a9-bcf9-fd84de13c466

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure divida_liq_sobre_ebitda_CP =
			
			DIVIDE(
			    [divida_liquida_CP],
			    [EEBITDA_actual_month]
			)
		formatString: #,0
		lineageTag: 54e416bb-742d-4f7a-805e-82d4f0ca0bae

		annotation PBI_FormatHint = {"isDecimal":true}

	measure divida_liq_sobre_ebitda_LP = ```
			
			DIVIDE(
			    [divida_liquida_LP],
			    [EEBITDA_actual_month]
			    
			)
			```
		lineageTag: 90e761c9-029b-4af4-ad36-30fbfb296a1f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure divida_liq_sobre_ebitda_LY =
			
			CALCULATE(
			[divida_liq_sobre_ebitda],
			DATEADD(
			    dCalendario[data],
			    -1,
			    YEAR
			)
			)
		formatString: #,0
		lineageTag: bb183ee7-76eb-4210-a9b8-abf0f834a187

		annotation PBI_FormatHint = {"isDecimal":true}

	measure EEbitdaLY = ```
			CALCULATE(
			    Medidas_balancetenew[EEBITDA_actual_month], 
			    DATEADD(dCalendario[data], -1, YEAR)
			    )
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 8d644ee2-0a60-438a-8ad0-34ed329eb471

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Endividamento total LY' =
			
			CALCULATE(
			    [Endividamento total],
			    DATEADD(
			        dCalendario[data],
			        -1,
			        YEAR
			    )
			)
		lineageTag: f46d8fb7-e308-437f-85ba-1e1d8177c87f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure empresa_selecionada_ou_grupo =
			
			IF(
			    COUNTROWS(VALUES(d_clientes_time[empresa])) = 1,
			    SELECTEDVALUE(d_clientes_time[empresa]),
			    SELECTEDVALUE(d_clientes_time[grupo])
			)
		lineageTag: 221f46e8-5f8f-497c-8746-c5c3a638bfb5

	measure divida_liquida_CP = [eemprestEFinanc_CP] - [caixasequicaixas]
		formatString: #,0
		lineageTag: d2ff05ab-f747-4c66-ade1-e05194c42cab

		annotation PBI_FormatHint = {"isDecimal":true}

	measure divida_liquida_LP = [eemprestEFinanc_LP] - [caixasequicaixas]
		formatString: #,0
		lineageTag: cae8b947-71ee-4fb1-9d40-d7b91fb29597

		annotation PBI_FormatHint = {"isDecimal":true}

	measure ebitda|divida_liquida =
			
			DIVIDE(
			    [EEBITDA_actual_month],
			    [divida_liquida]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: aa69e666-bdc6-4501-80bb-8a2b0686598e

	measure ebitda|divida_liquida_LM =
			
			CALCULATE(
			    [ebitda|divida_liquida],
			    DATEADD(
			        dCalendario[data],
			        -1,
			        MONTH
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4b89c4e3-2dde-498f-a1d1-d938a28f9f14

	measure ebitda|divida_liquida_LY =
			
			CALCULATE(
			    [ebitda|divida_liquida],
			    DATEADD(dCalendario[data],
			    -1,
			    YEAR
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 888635d5-20a4-4e5b-bf33-fda65267ebda

	measure narrativa_Divida_Liquida_EBITDA = ```
			
			VAR RatioAtual = [divida_liq_sobre_ebitda]
			VAR RatioMesAnterior = [divida_liq_sobre_ebitda_LM]
			VAR RatioAnoAnterior = [divida_liq_sobre_ebitda_LY]
			VAR DividaAtual = [divida_liquida]
			VAR DividaCP = [divida_liquida_CP]
			VAR DividaLP = [divida_liquida_LP]
			VAR EBITDAAtual = [EEBITDA_actual_month]
			
			RETURN 
			SWITCH(TRUE(),
			    RatioAtual > 4 && RatioMesAnterior > 4 && RatioAnoAnterior > 4, 
			    "<span style='color:red; font-weight:bold;'>Alerta Crítico:</span> A dívida líquida sobre o EBITDA tem se mantido consistentemente acima de 4 vezes. Com uma dívida líquida atual de <strong>" & FORMAT(DividaAtual, "#,##0.00") & 
			    "</strong> e um EBITDA de <strong>" & FORMAT(EBITDAAtual, "#,##0.00") & 
			    "</strong>, a empresa está em um nível de alavancagem preocupante. A alta proporção de dívida de curto prazo (<strong>" & FORMAT(DividaCP, "#,##0.00") & 
			    "</strong>) em relação à dívida de longo prazo (<strong>" & FORMAT(DividaLP, "#,##0.00") & 
			    "</strong>) indica uma pressão de liquidez iminente. Recomenda-se considerar a renegociação da dívida para prazos mais longos ou ações que aumentem o EBITDA, como corte de custos ou expansão de mercado.",
			
			    RatioAtual > 4 && RatioMesAnterior <= 4 && RatioAnoAnterior <= 4, 
			    "<span style='color:orange; font-weight:bold;'>Alerta Importante:</span> O indicador de dívida líquida sobre o EBITDA saltou acima de 4 vezes neste mês, marcando um aumento significativo em relação ao mês anterior (<strong>" & FORMAT(RatioMesAnterior, "#,##0.00") & 
			    "</strong>). Este aumento pode estar relacionado a uma queda no EBITDA ou a um aumento na dívida líquida, que atualmente está em <strong>" & FORMAT(DividaAtual, "#,##0.00") & 
			    "</strong>. É crucial analisar se o crescimento da dívida está associado a investimentos estratégicos ou a despesas operacionais não controladas.",
			
			    RatioAtual <= 4 && RatioMesAnterior > 4 && RatioAnoAnterior > 4, 
			    "<span style='color:green; font-weight:bold;'>Melhoria Significativa:</span> O indicador de dívida líquida sobre o EBITDA caiu para <strong>" & FORMAT(RatioAtual, "#,##0.00") & 
			    "</strong>, abaixo dos níveis críticos observados nos meses anteriores. A dívida líquida foi reduzida para <strong>" & FORMAT(DividaAtual, "#,##0.00") & 
			    "</strong>, refletindo uma gestão financeira mais rigorosa ou um aumento no EBITDA. Continuar monitorando as obrigações de curto prazo, que ainda representam <strong>" & FORMAT(DividaCP, "#,##0.00") & 
			    "</strong>, é fundamental para manter essa tendência positiva.",
			
			    RatioAtual <= 2 && RatioMesAnterior <= 2 && RatioAnoAnterior <= 2, 
			    "<span style='color:blue; font-weight:bold;'>Situação Saudável:</span> A relação dívida líquida sobre EBITDA está em níveis confortáveis, consistentemente abaixo de 2 vezes. Com uma dívida líquida de <strong>" & FORMAT(DividaAtual, "#,##0.00") & 
			    "</strong> e um EBITDA sólido de <strong>" & FORMAT(EBITDAAtual, "#,##0.00") & 
			    "</strong>, a empresa demonstra uma sólida capacidade de pagamento e baixa alavancagem. Essa estabilidade sugere que a empresa está bem posicionada para enfrentar desafios econômicos ou investir em crescimento futuro.",
			
			    RatioAtual > RatioMesAnterior && RatioAtual > RatioAnoAnterior, 
			    "<span style='color:orange; font-weight:bold;'>Atenção Necessária:</span> A dívida líquida sobre o EBITDA está em alta, agora em <strong>" & FORMAT(RatioAtual, "#,##0.00") & 
			    "</strong>, em comparação aos <strong>" & FORMAT(RatioMesAnterior, "#,##0.00") & 
			    "</strong> do mês anterior e <strong>" & FORMAT(RatioAnoAnterior, "#,##0.00") & 
			    "</strong> do ano anterior. A dívida de curto prazo, que representa <strong>" & FORMAT(DividaCP, "#,##0.00") & 
			    "</strong>, pode estar pressionando o fluxo de caixa. Avaliar o impacto dessa tendência na liquidez e na capacidade de investimento da empresa é essencial.",
			
			    RatioAtual < RatioMesAnterior && RatioAtual < RatioAnoAnterior, 
			    "<span style='color:green; font-weight:bold;'>Evolução Positiva:</span> O indicador de dívida líquida sobre o EBITDA reduziu-se para <strong>" & FORMAT(RatioAtual, "#,##0.00") & 
			    "</strong>, sinalizando uma melhoria em relação aos <strong>" & FORMAT(RatioMesAnterior, "#,##0.00") & 
			    "</strong> do mês anterior e <strong>" & FORMAT(RatioAnoAnterior, "#,##0.00") & 
			    "</strong> do ano anterior. Essa redução pode estar ligada a uma diminuição na dívida líquida, agora em <strong>" & FORMAT(DividaAtual, "#,##0.00") & 
			    "</strong>, ou a um aumento no EBITDA. Continuar essa trajetória pode melhorar ainda mais a solidez financeira da empresa.",
			
			    TRUE(), 
			    "<span style='color:gray; font-weight:bold;'>Estabilidade:</span> O indicador de dívida líquida sobre o EBITDA permanece estável em <strong>" & FORMAT(RatioAtual, "#,##0.00") & 
			    "</strong>. Com uma dívida líquida de <strong>" & FORMAT(DividaAtual, "#,##0.00") & 
			    "</strong> e um EBITDA de <strong>" & FORMAT(EBITDAAtual, "#,##0.00") & 
			    "</strong>, a empresa mantém uma posição financeira equilibrada. Monitorar regularmente esses indicadores ajudará a garantir que a empresa continue em uma trajetória financeira saudável."
			)
			```
		lineageTag: d3e16c57-3ca6-4763-a746-fdce72cdcb91

	measure divida_liq_sobre_ebitda_ACU = ```
			
			DIVIDE(
			    [divida_liquida],
			    [EEbitda_Acumulado_12M]
			    
			)
			```
		formatString: 0.00
		lineageTag: cdd96d04-6b82-4415-a25f-279d39a42715

	measure divida_liq_sobre_ebitda_ACU_LM =
			
			CALCULATE(
			    [divida_liq_sobre_ebitda_ACU],
			    DATEADD(
			        dCalendario[data],
			        -1,
			        MONTH
			    )
			)
		formatString: 0.00
		lineageTag: 838d965a-8bea-4b66-ac8e-d74e52b20e07

	measure divida_liq_sobre_ebitda_ACU_LY =
			
			CALCULATE(
			    [divida_liq_sobre_ebitda_ACU],
			    DATEADD(
			        dCalendario[data],
			        -1,
			        YEAR
			    )
			)
		formatString: 0.00
		lineageTag: 167fdb4b-815e-4cc6-b8c2-6ff46fb1589a

	measure EEbitda_ACU_LM =
			
			CALCULATE(
			    [EEbitda_ACU],
			    DATEADD(dCalendario[data],
			    -1,
			    MONTH
			    )
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 35c91591-680b-41ce-8845-3733273c2e7d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ebitda_ACU|divida_liquida =
			
			DIVIDE(
			    [EEbitda_Acumulado_12M],
			    [divida_liquida]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2d578777-e74b-4227-8cbf-65ed284e3748

	measure ebitda_ACU|divida_liquida_LM =
			
			CALCULATE(
			    [ebitda_ACU|divida_liquida],
			    DATEADD(
			        dCalendario[data],
			        -1,
			        MONTH
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c4b29bd3-60e4-4cd4-9c51-f47502222831

	measure ebitda_ACU|divida_liquida_LY =
			
			CALCULATE(
			    [ebitda_ACU|divida_liquida],
			    DATEADD(dCalendario[data],
			    -1,
			    YEAR
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 907e8aab-c25e-46ae-8e6d-8a572943730e

	measure narrativa_Divida_Liquida_EBITDA_ACU = ```
			
			VAR RatioAtual = [divida_liq_sobre_ebitda_ACU]
			VAR RatioMesAnterior = [divida_liq_sobre_ebitda_ACU_LM]
			VAR RatioAnoAnterior = [divida_liq_sobre_ebitda_ACU_LY]
			VAR DividaAtual = [divida_liquida]
			VAR DividaCP = [divida_liquida_CP]
			VAR DividaLP = [divida_liquida_LP]
			VAR EBITDAAtual = [EEbitda_ACU]
			
			RETURN 
			SWITCH(TRUE(),
			    RatioAtual > 4 && RatioMesAnterior > 4 && RatioAnoAnterior > 4, 
			    "<span style='color:red; font-weight:bold;'>Alerta Crítico:</span> A dívida líquida sobre o EBITDA tem se mantido consistentemente acima de 4 vezes. Com uma dívida líquida atual de <strong>" & FORMAT(DividaAtual, "#,##0.00") & 
			    "</strong> e um EBITDA de <strong>" & FORMAT(EBITDAAtual, "#,##0.00") & 
			    "</strong>, a empresa está em um nível de alavancagem preocupante. A alta proporção de dívida de curto prazo (<strong>" & FORMAT(DividaCP, "#,##0.00") & 
			    "</strong>) em relação à dívida de longo prazo (<strong>" & FORMAT(DividaLP, "#,##0.00") & 
			    "</strong>) indica uma pressão de liquidez iminente. Recomenda-se considerar a renegociação da dívida para prazos mais longos ou ações que aumentem o EBITDA, como corte de custos ou expansão de mercado.",
			
			    RatioAtual > 4 && RatioMesAnterior <= 4 && RatioAnoAnterior <= 4, 
			    "<span style='color:orange; font-weight:bold;'>Alerta Importante:</span> O indicador de dívida líquida sobre o EBITDA saltou acima de 4 vezes neste mês, marcando um aumento significativo em relação ao mês anterior (<strong>" & FORMAT(RatioMesAnterior, "#,##0.00") & 
			    "</strong>). Este aumento pode estar relacionado a uma queda no EBITDA ou a um aumento na dívida líquida, que atualmente está em <strong>" & FORMAT(DividaAtual, "#,##0.00") & 
			    "</strong>. É crucial analisar se o crescimento da dívida está associado a investimentos estratégicos ou a despesas operacionais não controladas.",
			
			    RatioAtual <= 4 && RatioMesAnterior > 4 && RatioAnoAnterior > 4, 
			    "<span style='color:green; font-weight:bold;'>Melhoria Significativa:</span> O indicador de dívida líquida sobre o EBITDA caiu para <strong>" & FORMAT(RatioAtual, "#,##0.00") & 
			    "</strong>, abaixo dos níveis críticos observados nos meses anteriores. A dívida líquida foi reduzida para <strong>" & FORMAT(DividaAtual, "#,##0.00") & 
			    "</strong>, refletindo uma gestão financeira mais rigorosa ou um aumento no EBITDA. Continuar monitorando as obrigações de curto prazo, que ainda representam <strong>" & FORMAT(DividaCP, "#,##0.00") & 
			    "</strong>, é fundamental para manter essa tendência positiva.",
			
			    RatioAtual <= 2 && RatioMesAnterior <= 2 && RatioAnoAnterior <= 2, 
			    "<span style='color:blue; font-weight:bold;'>Situação Saudável:</span> A relação dívida líquida sobre EBITDA está em níveis confortáveis, consistentemente abaixo de 2 vezes. Com uma dívida líquida de <strong>" & FORMAT(DividaAtual, "#,##0.00") & 
			    "</strong> e um EBITDA sólido de <strong>" & FORMAT(EBITDAAtual, "#,##0.00") & 
			    "</strong>, a empresa demonstra uma sólida capacidade de pagamento e baixa alavancagem. Essa estabilidade sugere que a empresa está bem posicionada para enfrentar desafios econômicos ou investir em crescimento futuro.",
			
			    RatioAtual > RatioMesAnterior && RatioAtual > RatioAnoAnterior, 
			    "<span style='color:orange; font-weight:bold;'>Atenção Necessária:</span> A dívida líquida sobre o EBITDA está em alta, agora em <strong>" & FORMAT(RatioAtual, "#,##0.00") & 
			    "</strong>, em comparação aos <strong>" & FORMAT(RatioMesAnterior, "#,##0.00") & 
			    "</strong> do mês anterior e <strong>" & FORMAT(RatioAnoAnterior, "#,##0.00") & 
			    "</strong> do ano anterior. A dívida de curto prazo, que representa <strong>" & FORMAT(DividaCP, "#,##0.00") & 
			    "</strong>, pode estar pressionando o fluxo de caixa. Avaliar o impacto dessa tendência na liquidez e na capacidade de investimento da empresa é essencial.",
			
			    RatioAtual < RatioMesAnterior && RatioAtual < RatioAnoAnterior, 
			    "<span style='color:green; font-weight:bold;'>Evolução Positiva:</span> O indicador de dívida líquida sobre o EBITDA reduziu-se para <strong>" & FORMAT(RatioAtual, "#,##0.00") & 
			    "</strong>, sinalizando uma melhoria em relação aos <strong>" & FORMAT(RatioMesAnterior, "#,##0.00") & 
			    "</strong> do mês anterior e <strong>" & FORMAT(RatioAnoAnterior, "#,##0.00") & 
			    "</strong> do ano anterior. Essa redução pode estar ligada a uma diminuição na dívida líquida, agora em <strong>" & FORMAT(DividaAtual, "#,##0.00") & 
			    "</strong>, ou a um aumento no EBITDA. Continuar essa trajetória pode melhorar ainda mais a solidez financeira da empresa.",
			
			    TRUE(), 
			    "<span style='color:gray; font-weight:bold;'>Estabilidade:</span> O indicador de dívida líquida sobre o EBITDA permanece estável em <strong>" & FORMAT(RatioAtual, "#,##0.00") & 
			    "</strong>. Com uma dívida líquida de <strong>" & FORMAT(DividaAtual, "#,##0.00") & 
			    "</strong> e um EBITDA de <strong>" & FORMAT(EBITDAAtual, "#,##0.00") & 
			    "</strong>, a empresa mantém uma posição financeira equilibrada. Monitorar regularmente esses indicadores ajudará a garantir que a empresa continue em uma trajetória financeira saudável."
			)
			```
		lineageTag: e86d68c1-93bd-487c-b4dc-78f19620b1e2

	measure divida_liquida_anual =
			
			CALCULATE(
			    [divida_liquida],
			    ALL(dCalendario[Ano]))
		lineageTag: e298babd-6f75-4274-9210-1e3d10626188

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure divida_liq_sobre_ebitda_ACU_anual = ```
			
			CALCULATE(
			    DIVIDE(
			        [divida_liquida],
			        [EEbitda_ACU]
			    ),
			    REMOVEFILTERS(dCalendario[Ano]), // Remove o filtro de ano
			    KEEPFILTERS(dCalendario[Mês Num]) // Mantém o filtro de mês
			)
			
			```
		lineageTag: 6489f606-57c1-4ecd-bae7-e3a486e6f5dc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure var_outras_despesas_ACU = ```
			
			
			VAR vdespesas =
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" || 
			            balancetenew[Query] = "DRE_Desp_Operacionais_Outras_despesas_operacionais"
			        ),
			        balancetenew[vlr]
			    ),
			    DATESYTD(dCalendario[data])
			)
			
			VAR vdespesas_ly =
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" || 
			            balancetenew[Query] = "DRE_Desp_Operacionais_Outras_despesas_operacionais"
			        ),
			        balancetenew[vlr]
			    ),
			    DATESYTD(DATEADD(dCalendario[data], -1, YEAR))
			)
			
			VAR vvariacao =
			DIVIDE(
			vdespesas - vdespesas_ly,
			vdespesas_ly)
			
			
			RETURN
			vvariacao
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e8fa2fb8-2f7c-47c3-9856-7a9d68f51dcf

	measure outras_despesas_ACU = ```
			
			CALCULATE(
			    SUMX(
			    FILTER(balancetenew,
			        balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" || 
			        balancetenew[Query] = "DRE_Desp_Operacionais_Outras_despesas_operacionais"
			    ),
			    balancetenew[vlr]
			),
			DATESYTD(dCalendario[data]))
			```
		lineageTag: 0e635f80-8448-4396-9d4e-f869827af55d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure var_outras_receitas =
			
			VAR vreceitas =
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Outras_receitas_operacionais"
			        ),
			        balancetenew[vlr]
			    ),
			    DATESYTD(dCalendario[data])
			)
			
			VAR vreceitas_ly =
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Outras_receitas_operacionais"
			        ),
			        balancetenew[vlr]
			    ),
			    DATESYTD(DATEADD(dCalendario[data], -1, YEAR))
			)
			
			VAR vvariacao =
			DIVIDE(
			vreceitas - vreceitas_ly,
			vreceitas_ly)
			
			
			RETURN
			vvariacao
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b9517412-30fd-45e4-9952-2b7192f66ed5

	measure var_outras_despesas_receitas_video = ```
			
			
			VAR vdespesas =
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" || 
			            balancetenew[Query] = "DRE_Desp_Operacionais_Outras_despesas_operacionais"
			        ),
			        balancetenew[vlr]
			    ),
			    DATESYTD(dCalendario[data])
			)
			
			VAR vreceitas =
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Outras_receitas_operacionais"
			        ),
			        balancetenew[vlr]
			    ),
			    DATESYTD(dCalendario[data])
			)
			
			VAR vdespesas_ly =
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" || 
			            balancetenew[Query] = "DRE_Desp_Operacionais_Outras_despesas_operacionais"
			        ),
			        balancetenew[vlr]
			    ),
			    DATESYTD(DATEADD(dCalendario[data], -1, YEAR))
			)
			
			VAR vreceitas_ly =
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Outras_receitas_operacionais"
			        ),
			        balancetenew[vlr]
			    ),
			    DATESYTD(DATEADD(dCalendario[data], -1, YEAR))
			)
			
			VAR vvariacao_despesas = vdespesas - vdespesas_ly
			VAR vvariacao_receitas = vreceitas - vreceitas_ly
			
			VAR resultado_despesas =
			IF(
			    vvariacao_despesas > 0,
			    "▲ Aumento de " & FORMAT(vvariacao_despesas, "0.00"),
			    "▼ Redução de " & FORMAT(vvariacao_despesas, "0.00")
			)
			
			VAR resultado_receitas =
			IF(
			    vvariacao_receitas > 0,
			    "▲ Aumento de " & FORMAT(vvariacao_receitas, "0.00"),
			    "▼ Redução de " & FORMAT(vvariacao_receitas, "0.00")
			)
			
			RETURN
			"Despesas: " & resultado_despesas & " | Receitas: " & resultado_receitas
			
			```
		lineageTag: d7458c5d-57b1-47a2-996c-9467db97e183

	measure var_outras_despesas =
			
			DIVIDE(
			    [outras_despesas_] - [outras_despesas_LM],
			    [outras_despesas_LM]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2059668f-ce3c-4f7f-90f2-bf8644f8546b

	measure outras_despesas_ = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			RETURN
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Desp_Operacionais_Despesas_tributarias" || 
			            balancetenew[Query] = "DRE_Desp_Operacionais_Outras_despesas_operacionais"
			        ),
			        balancetenew[vlr]
			    ),
			    dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre)
			```
		lineageTag: 3e37a01e-0176-4ad9-a702-0abe3175d3bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure outras_despesas_LM =
			
			CALCULATE(
			    [outras_despesas_],
			    DATEADD(dCalendario[data], -1, MONTH))
		lineageTag: 4df16d4c-1c6b-4130-91f8-fe76ddd4e8b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure EEbitda_Acumulado_12M =
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "DRE_Ebitda"
			        ),
			        balancetenew[vlr]
			    ),
			    DATESINPERIOD(
			        dCalendario[data],
			        MAX(dCalendario[data]),
			        -12,
			        MONTH
			    )
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 5cfeb314-c846-4f85-9136-593a096f1bf9

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure EEbitda_Acumulado_12M_LM =
			
			CALCULATE(
			    [EEbitda_Acumulado_12M],
			    DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 2dd94296-ec3c-4187-b050-19f9106c464a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure EEbitda_Acumulado_12M_LY =
			
			CALCULATE(
			    [EEbitda_Acumulado_12M],
			    DATEADD(dCalendario[data], -1, YEAR))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 612cce72-ffcc-468a-8b90-45d980717b18

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure FFaturamentoII = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			
			    RETURN
			    CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew, 
			        balancetenew[Query] = "receita bruta"
			        ), 
			        balancetenew[vlr]
			        ),
			        dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 4f608d32-9ac0-4b31-a3ee-ed4428dce81a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure deducoes_impostos_selecionado =
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Deduções da Receita Bruta" ||
			            balancetenew[Query] = "DRE_Imp_Incidentes_Sobre_Receita"
			        ),
			        balancetenew[vlr]
			    ),
			    DATESBETWEEN(
			        dCalendario[data],
			        MIN(dCalendario[data]),
			        MAX(dCalendario[data])
			    )
			) * -1
		formatString: #,0
		lineageTag: d8b89ce3-8c9a-496e-8e9d-f1bd63d254ad

		annotation PBI_FormatHint = {"isDecimal":true}

	measure deducoes_impostos_acu_LY =
			
			CALCULATE(
			    [deducoes_impostos_acu],
			    DATEADD(dCalendario[data], -1, YEAR))
		formatString: #,0
		lineageTag: 57163388-0aa8-43b0-8db9-16da9c10e45f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Receita Líquida Selecionada' = ```
			
			CALCULATE(
			    SUM( balancetenew[vlr] ),
			    KEEPFILTERS(
			        balancetenew[Query] IN {
			            "Receita Bruta",
			            "Deduções da Receita Bruta",
			            "DRE_Imp_Incidentes_Sobre_Receita"
			        }
			    )
			)
			
			```
		lineageTag: 7afe78ea-43d6-4ea9-9fee-ba3647812663

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MReceita_Liquida_ACU_kpi =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    CALCULATE(
			        [MReceita_Liquida],
			        DATESYTD(
			            dCalendario[data]
			        )
			    ),
			    Medidas_balancetenew[mreceita_liquiida_selecionada_kpi]
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 960a0dab-dd15-484f-bd9f-9d1f5e68e735

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure mreceita_liquida_selecionado_LY_kpi =
			
			VAR MinData =
			    CALCULATE ( MIN ( 'dCalendario'[Data] ), ALLSELECTED ( 'dCalendario' ) )
			VAR MaxData =
			    CALCULATE ( MAX ( 'dCalendario'[Data] ), ALLSELECTED ( 'dCalendario' ) )
			
			-- desloca o intervalo inteiro 12 meses para trás (LY)
			VAR MinDataLY = EDATE ( MinData, -12 )
			VAR MaxDataLY = EDATE ( MaxData, -12 )
			
			RETURN
			CALCULATE (
			    SUM ( balancetenew[vlr] ),
			    balancetenew[Query] IN {
			        "Receita Bruta",
			        "Deduções da Receita Bruta",
			        "DRE_Imp_Incidentes_Sobre_Receita"
			    },
			    'dCalendario'[Data] >= MinDataLY,
			    'dCalendario'[Data] <= MaxDataLY
			)
		lineageTag: 91387a96-d1ca-4371-9cdf-03919259ccc2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure mreceita_liquida_acu_LY_kpi =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    [MReceita_Liquida_Acumulada_LY],
			    [mreceita_liquida_selecionado_LY_kpi]
			    )
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: c7dff075-132e-4474-9eb5-b94ebc166026

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure deducoes_impostos_selecionado_kpi =
			
			VAR MinData =
			    CALCULATE ( MIN ( 'dCalendario'[Data] ), ALLSELECTED ( 'dCalendario' ) )
			VAR MaxData =
			    CALCULATE ( MAX ( 'dCalendario'[Data] ), ALLSELECTED ( 'dCalendario' ) )
			RETURN
			CALCULATE (
			    SUM ( balancetenew[vlr] ),
			    balancetenew[Query] IN {
			        "Deduções da Receita Bruta",
			        "DRE_Imp_Incidentes_Sobre_Receita"
			    },
			    'dCalendario'[Data] >= MinData,
			    'dCalendario'[Data] <= MaxData
			)
		lineageTag: 65acc6e1-7c98-4a92-ac4d-8481a7d2f29e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure deducoes_impostos_acu_kpi =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    [deducoes_impostos_acu],
			    [deducoes_impostos_selecionado_kpi]
			    )
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: ce1f18d0-bdb8-4ea2-8407-2e52d961c5d3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure deducoes_impostos_acu_LY_kpi =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    [deducoes_impostos_acu_LY],
			    [deducoes_impostos_selecionado_KPI_LY]
			    )
		lineageTag: 85de1efd-46ff-4fe2-8e6c-9f29534df54e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MMargem_bruta_selecionado_kpi =
			
			VAR MinData =
			    CALCULATE ( MIN ( 'dCalendario'[Data] ), ALLSELECTED ( 'dCalendario' ) )
			VAR MaxData =
			    CALCULATE ( MAX ( 'dCalendario'[Data] ), ALLSELECTED ( 'dCalendario' ) )
			RETURN
			CALCULATE (
			    SUM ( balancetenew[vlr] ),
			    balancetenew[Query] IN {
			        "dre_Lucro_bruto"
			    },
			    'dCalendario'[Data] >= MinData,
			    'dCalendario'[Data] <= MaxData
			)
		lineageTag: d675f235-0e84-41f0-8293-e45348808c3d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MMargem_Bruta_ACU_kpi = ```
			
			VAR v_margem_ano_civil = IFERROR(
			CALCULATE(
			        [MMargem_bruta],
			        DATESYTD(
			            dCalendario[data]
			        )
			    ), BLANK())
			
			VAR v_margem_selecionado = [MMargem_bruta_selecionado_kpi] 
			
			RETURN
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    v_margem_ano_civil,
			    v_margem_selecionado
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 48c8b2f6-99c2-4ae4-bfbb-bf6b35f6df63

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MMargem_bruta_ACU_LY_kpi =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    [MMargem_Bruta_acu_LY],
			    [MMargem_Bruta_selecionado_LY_kpi]
			    )
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 3dab28e2-2feb-4001-875e-cb2b8bcd5978

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ATCIR_Estoques_selecionado =
			
			VAR FirstMonthDate = CALCULATE(MIN(dCalendario[data]), ALLSELECTED(dCalendario))
			RETURN
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "BL_ATCIR_Estoques"
			        ),
			        balancetenew[vlr]
			    ),
			    dCalendario[data] = FirstMonthDate
			)
		lineageTag: c3e2ece5-405b-4f54-abf1-b6119a4bb108

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ATCIR_Estoques_prazos medios' =
			// o estoque tem que ser o LM pois o cálculo contempla o saldo inicial do estoque do período, neste caso, 1 mês antes
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    [ATCIR_Estoques_End_of_LY],
			    [ATCIR_Estoques_selecionado_LM]
			)
		formatString: #,0
		lineageTag: cf9b2fe0-c699-4785-b442-374e2522c554

		annotation PBI_FormatHint = {"isDecimal":true}

	measure ATCIR_Estoques_selecionado_LM =
			
			CALCULATE([ATCIR_Estoques_selecionado],
			DATEADD(
			    dCalendario[data], -1, MONTH))
		formatString: #,0
		lineageTag: a0cccadc-63dc-435c-8903-660a546dba5c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Valor_mensal_selecionado =
			
			VAR MesesSelecionados = DATEDIFF(MIN(dCalendario[data]), MAX(dCalendario[data]), MONTH)
			RETURN
			(MesesSelecionados * 30) +30
		formatString: 0
		lineageTag: dcfd3b99-7585-4cf4-89e6-3d3c4baf357e

	measure Valor_mensal_prazos_medios =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    [Valor_mensal],
			    [Valor_mensal_selecionado])
		formatString: 0
		lineageTag: cc172c0f-e135-4533-84a5-48a0758eadb9

	measure Contas_receber_prazo_medio = ```
			
			IF(
			    NOT(ISBLANK(medidas_aginglist[clientes_aging])) && 
			    [clientes_aging] = [contas receber], 
			    medidas_aginglist[clientes_aging], 
			    [contas receber]
			)
			
			```
		formatString: #,0
		lineageTag: 20d1dcd8-f3cc-47da-a7a0-412f1f509633

		annotation PBI_FormatHint = {"isDecimal":true}

	measure deducoes_selecionado =
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew,
			            balancetenew[Query] = "Deduções da Receita Bruta"
			        ),
			        balancetenew[vlr]
			    ),
			    DATESBETWEEN(
			        dCalendario[data],
			        MIN(dCalendario[data]),
			        MAX(dCalendario[data])
			    )
			) * -1
		formatString: #,0
		lineageTag: ca15f4d5-8a2b-4948-9ce2-344a2d44cfbb

		annotation PBI_FormatHint = {"isDecimal":true}

	measure prazo_medio_CR_teste =
			
			DIVIDE(
			[Contas_receber_prazo_medio],
			[VendasANOMenosDevACU])
			 * [Valor_mensal_prazos_medios]
		formatString: 0
		lineageTag: 51f71124-7218-44ff-a0e9-01cfc40e425b

		annotation PBI_FormatHint = {"isDecimal":true}

	measure financiamentos_LP =
			
			VAR UltimaDataSelecionada = LASTDATE(dcalendario[data])  // Armazena a última data selecionada no filtro
			RETURN
			COALESCE(
			CALCULATE(
			    SUMX(
			        FILTER(
			             balancetenew,
			             balancetenew[Query] = "BL_PASSNCIR_Emprestimos_Financiamentos" &&
			           (                balancetenew[descricao_cliente] = "FINANCIAMENTO BANCO SAFRA 135620 LP" ||
			                            balancetenew[descricao_cliente] = "BANCO J. SAFRA E LEASING . FINANCIAMENTO" ||
			                            balancetenew[descricao_cliente] = "( ) ENCARGOS FINANC BANCO SAFRA 135620"
			
			             ) &&
			            balancetenew[data] = UltimaDataSelecionada  // Filtra pela última data
			        ),
			        balancetenew[total_mes_atual]
			    )
			), 0)
		lineageTag: 8b98c71b-014e-442a-a375-f95114fbc2eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure financiamentos_LP_LM =
			
			CALCULATE(
			    [financiamentos_LP],
			    DATEADD(dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 393ddddd-716b-4b42-b373-fb2f16a3b734

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure financiamentos_CP_normal_card = ```
			// medida teste apenas
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			RETURN
			CALCULATE(
			    SUMX(
			        FILTER(
			             balancetenew,
			             balancetenew[Query] = "BL_PASSCIR_Emprestimos_Financiamentos" &&
			           ( balancetenew[descricao_cliente] = "FINANCIAMENTO BANCO HONDA SA" ||
			             balancetenew[descricao_cliente] = "BANCO J. SAFRA E LEASING" ||
			             balancetenew[descricao_cliente] = "FINANCIAMENTO BANCO SAFRA 135620" ||
			             balancetenew[descricao_cliente] = "( - ) JUROS S/ FINANCIAMENTO BANCO HONDA SA" ||
			             balancetenew[descricao_cliente] = "( ) ENCARGOS FINANC BANCO SAFRA 135620"
			
			             )
			        ),
			        balancetenew[total_mes_atual]
			    ),
			    dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre)
			```
		formatString: #,0
		lineageTag: 2c7addb2-b095-4375-8459-5e6708f47cf9

		annotation PBI_FormatHint = {"isDecimal":true}

	measure emprestimos_financiamentos_total = ```
			
			SUMX(
			    FILTER(balancetenew, 
			    balancetenew[Query] = "BL_PASSCIR_Emprestimos_Financiamentos" ||
			    balancetenew[Query] = "BL_PASSNCIR_Emprestimos_Financiamentos"
			    ), balancetenew[vlr])
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 1ff70186-edc4-46a5-abcd-66683834fc51

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure TotalJuros_financiamentos = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    COALESCE(
			CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "Juros_Pagos_Sobre_Emprestimos" &&
			        balancetenew[descricao_cliente] = "JUROS S/ FINANCIAMENTOS BANCO HONDA" ||
			        balancetenew[descricao_cliente] = "JUROS S/ FINANCIAMENTOS"
			    ),
			    balancetenew[vlr]
			),
			dCalendario[data] = UltimoMesTrimestre
			) *-1, 0)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: c2144eab-7741-43ea-8697-f079742ad015

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure TotalJuros_financiamentos_LM =
			
			CALCULATE([TotalJuros_financiamentos],
			DATEADD(
			    dCalendario[data], -1, MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: b5c58878-5829-472e-b588-ec6a0d519ccf

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure TotalJuros_emprestimos = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    COALESCE(
			CALCULATE(
			SUMX(
			    FILTER(
			        balancetenew,
			        balancetenew[Query] = "Juros_Pagos_Sobre_Emprestimos" &&
			        balancetenew[descricao_cliente] = "JUROS S/EMPRESTIMOS DE CONTRATOS"
			    ),
			    balancetenew[vlr]
			),
			dCalendario[data] = UltimoMesTrimestre
			) *-1, 0)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: a2d0f70c-1f51-4db2-bd57-0d847fa75a3b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure TotalJuros_emprestimos_LM =
			
			CALCULATE(
			    [TotalJuros_emprestimos],
			    DATEADD(dCalendario[data],
			    -1,
			    MONTH))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 87925e7f-6386-412e-82db-02ed32b05b03

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure receita_bruta|impostos_incidentes_ACU =
			
			DIVIDE(
			    [TributosIncidentes_ACU],
			    [MReceita_Bruta_ACU]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: efa70ffb-44d2-465c-94fa-99215e4a3cf4

	measure EEbitda_ACUII =
			
			CALCULATE(
			    SUMX(FILTER(
			        balancetenew,
			        balancetenew[Query] = "DRE_Ebitda"),
			        balancetenew[vlr]), DATESYTD(dCalendario[data]))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 741f6180-5bba-411c-b982-d2bbad437e7d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure variacao_ebitda% =
			
			DIVIDE(
			[EEBITDA_actual_month] - [EEbitdaLM],
			[EEbitdaLM]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 150e2003-387d-47bd-abef-a39c1e1f8c2e

	measure variacao_ebitda%_LM = ```
			
			CALCULATE(
			    [variacao_ebitda%], 
			    DATEADD(
			        dCalendario[data],
			        -1,
			        MONTH
			    )
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 487c1756-b8bf-42a9-9f61-0cedc6e871ed

	measure var_variacao_ebitda% =
			
			[variacao_ebitda%] - [variacao_ebitda%_LM]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 34c8d04e-e805-4dfc-ac3f-b233881300ec

	measure variacao_ebitda%_sinal =
			
			IF([var_variacao_ebitda%] > 0, "🟢", "🔴")
		lineageTag: c14f22de-4c23-4842-8fe3-0872bcf2bc77

	measure variacao_ebitda%_ACU =
			
			DIVIDE(
			[EEbitda_ACU] - [EEbitda_ACU_LY],
			[EEbitda_ACU_LY]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: fc51421a-32a9-4210-a126-7ceea24c98ac

	measure variacao_ebitda%_ACU_LY =
			
			COALESCE(
			CALCULATE(
			    [variacao_ebitda%_ACU],
			    DATEADD(
			        dCalendario[data],
			        -1,
			        YEAR
			    )
			), 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c0bf1a8b-d977-4f50-be16-e59f211b8e40

	measure var_variacao_ebitda%_ACU =
			
			[variacao_ebitda%_ACU] - [variacao_ebitda%_ACU_LY]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 65da928d-661e-45ed-9210-da445d56f6c5

	measure variacao_ebitda%_ACU_sinal =
			
			IF(
			    [var_variacao_ebitda%_ACU] > 0,
			    "🟢",
			    "🔴"
			)
		lineageTag: 4c1355de-8cd9-4fd2-8f77-d14a8a48c8b9

	measure MReceita_Bruta_ACU_rentabilidade_LY =
			
			IF(
			    SELECTEDVALUE(
			        d_clientes_time[tipo_analise], BLANK()
			    ) = "Ano Civil",
			    [MReceita_bruta_acu_LY],
			    [MReceita_Bruta_Selecionado_KPI_LY]
			    )
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: e8554878-1b8c-4a19-b0e6-f19034f309de

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure emprestimos_total =
			
			[Emprestimos_CP] + [emprestimos_LP]
		lineageTag: 9af460a9-2f7e-451e-a4e2-2bd88dad6cfd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure juros|emprestimos% =
			
			DIVIDE(
			    [TotalJuros_emprestimos],
			    [emprestimos_total]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: df70d844-c69c-4b4c-88f8-ccfc30eca910

	measure juros|emprestimos%_LM =
			
			CALCULATE(
			    [juros|emprestimos%],
			    DATEADD(dCalendario[data], -1, MONTH
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e23595b4-0116-41b7-8220-e74566648f48

	measure financiamentos_total =
			
			[financiamentos_CP_normal_card] + [financiamentos_LP]
		lineageTag: d79b3df9-d83a-4594-936c-58838600ee50

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure juros|financiamentos% =
			COALESCE(
			DIVIDE(
			    [TotalJuros_financiamentos],
			    [financiamentos_total]
			), 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 553adcbf-5516-46ef-8b70-0a60600eb06b

	measure juros|financiamentos%_LM =
			
			CALCULATE(
			    [juros|financiamentos%],
			    DATEADD(
			        dCalendario[data],
			        -1,
			        MONTH
			    ))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: fc017de3-6c64-4617-aff4-e59f8f7fd4c4

	measure 'LLucro_Liquido | ReceitaLiquida II' =
			
			DIVIDE(
			    [LLucro_liquido_actual_month],
			    [MReceita_Liquida_actual_month]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6d8be50f-2398-40fc-a212-8a3d5d5a6cd4

	measure saLdo_passivo_balancetenew_df_ass = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    DIVIDE(
			    CALCULATE(
			        [saldo_passivo_balancetenew],
			        dCalendario[data] >= UltimoMesTrimestre && 
			        dCalendario[data] <= UltimoDiaTrimestre),
			        1000
			    )
			```
		formatString: #,0
		lineageTag: 4e8e744b-4bea-4355-b6d3-3c2eb1b19602

		annotation PBI_FormatHint = {"isDecimal":true}

	measure valor_balancetenew_BP = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			
			    CALCULATE(
			        [valor_balancetenew],
			        dCalendario[data] >= UltimoMesTrimestre && dCalendario[data] <= UltimoDiaTrimestre)
			```
		formatString: #,0
		lineageTag: e0ea8d0c-10c7-42be-a786-84715f3563bf

		annotation PBI_FormatHint = {"isDecimal":true}

	measure valor_balancetenew_BP_LY = ```
			
			CALCULATE(
			    [valor_balancetenew_BP],
			    DATEADD(dCalendario[data], 
			    -1, 
			    YEAR
			    ))
			```
		formatString: #,0
		lineageTag: e5ee50b1-5b74-49c8-84b7-3628110c9a6e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure desp_nao_operacionais = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    SUMX(
			        FILTER(
			            balancetenew, 
			            balancetenew[Query] = "DRE_Desp_NAO_Operacionais_Despesas_nao_operacionais"
			        ),
			        balancetenew[vlr]
			    ),
			    dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: #,0
		lineageTag: 3cda6710-b65c-4a81-8dac-6a87144115b0

		annotation PBI_FormatHint = {"isDecimal":true}

	measure switch_roic = ```
			
			VAR nopat_ = [LLucro_liquido II] - IF([receita_financeira] < 0, [receita_financeira]*-1, [receita_financeira]) + ([despesa_financeira]*-1) + [desp_nao_operacionais]
			VAR roic_ = 
			FORMAT(
			    DIVIDE(
			        nopat_,
			        [patrimonioLiq]
			    ), "0.00%"
			)
			
			RETURN
			SWITCH(
			    SELECTEDVALUE(
			        D_ROIC[nome]
			    ),
			    "(=) Lucro ou Prejuízo Líquido", [LLucro_liquido II],
			    "(-) Receita Financeira", [receita_financeira],
			    "(+) Despesa Financeira", [despesa_financeira],
			    "(+/-) Despesas não Operacionais", [desp_nao_operacionais],
			    "CAPITAL INVESTIDO (PL + Capital de Terceiros)", [patrimonioLiq] + [Emprestimos_CP] + [emprestimos_LP], /* feito a inclusão de emprestimos CP e LP a pedido de Matheus Fernandes em 11/02/2026 */
			    "ROIC", roic_,
			    "(=) NOPAT", nopat_
			
			)
			```
		lineageTag: 157a9ebf-ed01-4131-99e0-a9f64fbf281b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure switch_roic_LY = ```
			
			VAR nopat_LY = CALCULATE(
			    [LLucro_liquido] - [receita_financeira] + [despesa_financeira] + [desp_nao_operacionais],
			    DATEADD(dCalendario[data], -1, YEAR)
			)
			VAR roic_ = 
			FORMAT(
			    DIVIDE(
			        nopat_LY,
			        CALCULATE(
			        [patrimonioLiq],
			        DATEADD(dCalendario[data], -1, YEAR))
			    ), "0.00%")
			
			VAR roic_LY =
			CALCULATE(
			    roic_,
			    DATEADD(
			        dCalendario[data],
			        -1,
			        YEAR
			    )
			)
			RETURN
			SWITCH(
			    SELECTEDVALUE(
			        D_ROIC[nome]
			    ),
			    "(=) Lucro ou Prejuízo Líquido", [Lucro_liquido_LY],
			    "(-) Receita Financeira", CALCULATE([receita_financeira], DATEADD(dCalendario[data], -1, YEAR)),
			    "(+) Despesa Financeira", CALCULATE([despesa_financeira], DATEADD(dCalendario[data], -1, YEAR)),
			    "(+/-) Despesas não Operacionais", CALCULATE([desp_nao_operacionais], DATEADD(dCalendario[data], -1, YEAR)),
			    "CAPITAL INVESTIDO (PL + Capital de Terceiros)", CALCULATE([patrimonioLiq], DATEADD(dCalendario[data], -1, YEAR)),
			    "ROIC", roic_LY,
			    "(=) NOPAT", nopat_LY
			
			)
			```
		lineageTag: 3a962f6f-78d9-4af2-83bd-b445cd022b39

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tributos_incidentes_selecionado_Rentab = ```
			
			VAR MesSelecionado = SELECTEDVALUE(dCalendario[data])   
			RETURN
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew,
			                balancetenew[Query] = "DRE_Imp_Incidentes_Sobre_Receita" ||
			                balancetenew[Query] = "Deduções da Receita Bruta"
			            ),
			            balancetenew[vlr]
			        ),
			        DATESBETWEEN(dCalendario[data],
			        MIN(dCalendario[data]),
			        MAX(dCalendario[data])
			    ))
			```
		lineageTag: 44e199e7-59b2-4d11-a5de-9fbb0948112e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TributosIncidentes_Rentab = ```
			
			VAR Vtributos =
			SUMX(
			    FILTER(balancetenew, 
			    balancetenew[Query] = "DRE_Imp_Incidentes_Sobre_Receita" ||
			    balancetenew[Query] = "Deduções da Receita Bruta"
			    ), 
			    balancetenew[vlr]
			    )
			
			    RETURN
			    Vtributos
			```
		lineageTag: 9b59fbf3-350d-4341-a783-1feba1413c14

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure receita_bruta|impostos_incidentes_ACU_Rentab =
			
			DIVIDE(
			    [TributosIncidentes_ACU_rentab],
			    [MReceita_Bruta_ACU]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6047f38e-637f-4c54-80cf-3c581e51bd86

	measure variacao%_switch_roic_ = ```
			
			VAR nopat_ = CALCULATE(
			    [LLucro_liquido] - [receita_financeira] + [despesa_financeira] + [desp_nao_operacionais]
			    )
			VAR nopat_LY = CALCULATE(
			    [LLucro_liquido] - [receita_financeira] + [despesa_financeira] + [desp_nao_operacionais],
			    DATEADD(dCalendario[data], -1, YEAR)
			)
			VAR nopat_variacao =
			DIVIDE(
			    nopat_ - nopat_LY,
			    nopat_LY
			)
			VAR roic_ = 
			    DIVIDE(
			        nopat_,
			        [patrimonioLiq]
			    )
			VAR roic_LY = 
			    DIVIDE(
			        nopat_LY,
			        CALCULATE(
			        [patrimonioLiq],
			        DATEADD(dCalendario[data],
			        -1,
			        YEAR
			        )
			    ))
			VAR roic_variacao =
			FORMAT(
			    roic_ - roic_LY, 
			    "0.00%"
			    )
			VAR receita_financeira_LY =
			CALCULATE(
			    [receita_financeira], 
			    DATEADD(
			        dCalendario[data], 
			        -1, 
			        YEAR
			    )
			)
			VAR despesa_financeira_LY =
			CALCULATE(
			    [despesa_financeira], 
			    DATEADD(
			        dCalendario[data], 
			        -1, 
			        YEAR
			    )
			)
			VAR desp_n_operacional_LY =
			CALCULATE(
			    [desp_nao_operacionais], 
			    DATEADD(
			        dCalendario[data], 
			        -1, 
			        YEAR
			    )
			)
			VAR patrimonio_liq_LY =
			CALCULATE(
			    [patrimonioLiq], 
			    DATEADD(
			        dCalendario[data], 
			        -1, 
			        YEAR
			    )
			)
			RETURN
			SWITCH(
			    SELECTEDVALUE(
			        D_ROIC[nome]
			    ),
			    "(=) Lucro ou Prejuízo Líquido", FORMAT([variacao%_lucro_liq_YoY], "0.00%"),
			    "(-) Receita Financeira", FORMAT(DIVIDE([receita_financeira] - receita_financeira_LY, receita_financeira_LY ), "0.00%"),
			    "(+) Despesa Financeira", FORMAT(DIVIDE([despesa_financeira] - despesa_financeira_LY, despesa_financeira_LY), "0.00%"),
			    "(+/-) Despesas não Operacionais", FORMAT(DIVIDE([desp_nao_operacionais] - desp_n_operacional_LY, desp_n_operacional_LY), "0.00%"),
			    "CAPITAL INVESTIDO (PL + Capital de Terceiros)", FORMAT(DIVIDE([patrimonioLiq] - patrimonio_liq_LY, patrimonio_liq_LY), "0.00%"),
			    "ROIC", roic_variacao,
			    "(=) NOPAT", FORMAT(nopat_variacao, "0.00%")
			
			)
			```
		lineageTag: 063a798b-7e33-4c73-973a-94134990def6

	measure variacao%_lucro_liq_YoY = ```
			
			VAR lucro_liq_LY_ =
			[Lucro_liquido_LY]
			RETURN  
			
			DIVIDE(
			    [LLucro_liquido] 
			    - lucro_liq_LY_,
			    lucro_liq_LY_
			)
			```
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: db629e63-94a3-48ef-bc76-1cc2fe8d3a69

	measure %custo_sobre_receita_bruta =
			
			
			VAR _resultado =
			DIVIDE(
			    [CCusto_actual_month]*-1,
			    [MReceita_bruta]
			)
			
			RETURN
			_resultado
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f92afa6a-07bc-4354-9491-ea33a4fae475

	measure %custo_sobre_receita_bruta_ACU =
			
			
			VAR _resultado =
			DIVIDE(
			    [CCusto_ACU]*-1,
			    [MReceita_Bruta_ACU]
			)
			
			RETURN
			_resultado
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6f164ff2-5411-4309-940c-b2a752ceec19

	measure %custo_sobre_receita_bruta_LM =
			
			
			VAR _resultado =
			DIVIDE(
			    [custo_mes_anterior]*-1,
			    [Mreceita_bruta_LM]
			)
			
			RETURN
			_resultado
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cfc39b8c-85d5-4fbc-a0e3-b3629815322c

	measure HTML_GLOSSARIO_PAGINAS = ```
			
			VAR _TabelaGlossario = 
			    DATATABLE(
			        "Bloco", STRING,
			        "Analise", STRING,
			        "Descricao", STRING,
			        {
			            { "Análises e Indicadores de Resultado", "Variação da Margem Bruta", "Exibe a variação percentual e absoluta da margem bruta entre dois períodos, ajudando a identificar tendências na rentabilidade operacional. A análise permite entender se a empresa está conseguindo manter ou melhorar sua capacidade de gerar lucro com as vendas, após descontar os custos diretos." },
			            { "Análises e Indicadores de Resultado", "Variação do Lucro Líquido", "Mostra a variação do lucro líquido entre dois períodos, destacando os principais fatores que influenciaram o aumento ou redução no resultado final. Inclui impactos de Receita, Custos, Despesas Operacionais, Resultados Financeiros e Tributários." },
			            { "Análises e Indicadores de Resultado", "Despesas com Pessoal", "Apresenta um resumo das despesas relacionadas aos funcionários, incluindo salários, benefícios, encargos sociais, impostos sobre folha de pagamento e outras remunerações. A análise permite acompanhar a evolução dos custos com pessoal ao longo do tempo e identificar tendências ou desvios significativos." },
			            { "Análises e Indicadores de Resultado", "Análise de Tributos Incidentes", "Mostra os principais tributos que incidem sobre a receita da empresa, como ICMS, PIS, COFINS, ISS e outros encargos fiscais. A análise permite acompanhar o impacto fiscal sobre o faturamento e identificar possíveis oportunidades de otimização tributária." },
			            { "Análises e Indicadores de Resultado", "Outras Despesas", "Apresenta um resumo das demais despesas que não se enquadram nas categorias acima, como despesas legais, seguros, multas e outras obrigações diversas. Essa análise fornece uma visão geral das responsabilidades financeiras adicionais da empresa, ajudando a identificar possíveis desvios ou oportunidades de controle." },
			            { "Análises e Indicadores Patrimoniais", "Aging List de Clientes", "Exibe a lista de clientes com dívidas pendentes, segmentada por faixas de tempo (ex.: até 30 dias, 31-60 dias, etc.). Essa análise ajuda a identificar clientes com inadimplência, melhorar a gestão do fluxo de caixa e definir estratégias de cobrança mais eficazes." },
			            { "Análises e Indicadores Patrimoniais", "Tributos a Recuperar", "Mostra os tributos incidentes sobre vendas que ainda não foram recuperados pela empresa, como créditos de ICMS, PIS e COFINS. Destaca valores acumulados e tendências ao longo do tempo, permitindo planejar a recuperação desses créditos junto aos órgãos fiscais." },
			            { "Análises e Indicadores Patrimoniais", "Tributos Sobre o Faturamento a Recolher", "Detalha os tributos incidentes sobre as receitas da empresa que ainda precisam ser recolhidos aos órgãos fiscais, como ICMS, ISS, PIS e COFINS. Permite planejar adequadamente os pagamentos e acompanhar o cumprimento das obrigações acessórias." },
			            { "Análises e Indicadores Patrimoniais", "Obrigações Trabalhistas", "Exibe os valores acumulados de obrigações trabalhistas, como FGTS, INSS, férias, décimo terceiro salário e multas trabalhistas. Permite acompanhar a situação fiscal da empresa perante a legislação trabalhista e planejar os pagamentos futuros." },
			            { "Análises e Indicadores Patrimoniais", "Obrigações Tributárias", "Apresenta um resumo das obrigações fiscais da empresa, incluindo impostos e contribuições sociais devidas. Destaca valores acumulados, prazos de pagamento e a evolução ao longo do tempo, permitindo identificar possíveis riscos fiscais e oportunidades de planejamento." },
			            { "Análises e Indicadores Patrimoniais", "Adiantamentos de Clientes", "Detalha os valores recebidos antecipadamente de clientes, como sinal de pedidos ou contratos futuros. Permite monitorar a evolução desses recursos e garantir que sejam utilizados de acordo com os contratos firmados, impactando o fluxo de caixa futuro." },
			            { "Indicadores Econômicos, Financeiros e Operacionais", "Lucro X Fluxo de Caixa", "Compara o lucro líquido com o fluxo de caixa operacional, destacando diferenças entre resultados contábeis e financeiros reais. Essa análise ajuda a identificar inconsistências, como lucro contábil sem geração de caixa, e a necessidade de ajustes na gestão de caixa." },
			            { "Indicadores Econômicos, Financeiros e Operacionais", "Indicadores de Liquidez", "Apresenta indicadores de liquidez, como Liquidez Imediata (Disponível/Passivo Circulante) e Liquidez Corrente (Ativo Circulante/Passivo Circulante). Esses indicadores permitem avaliar a capacidade da empresa de honrar suas obrigações a curto prazo com os recursos disponíveis." },
			            { "Indicadores Econômicos, Financeiros e Operacionais", "ROI (Return on Investment)", "Mostra o retorno sobre o investimento realizado na empresa (ROI), calculado como o lucro líquido dividido pelo valor total dos investimentos. Esse indicador ajuda a avaliar a eficiência no uso dos recursos financeiros e a atratividade dos investimentos realizados." },
			            { "Indicadores Econômicos, Financeiros e Operacionais", "ROIC (Return on Invested Capital)", "Apresenta o retorno sobre o capital investido (ROIC), calculado como o lucro operacional ajustado (após impostos) dividido pelo capital investido (dívida líquida + patrimônio líquido). Esse indicador mede a eficiência da gestão dos ativos e passivos da empresa na geração de valor." },
			            { "Demonstrações Financeiras", "Declaração de Faturamento", "Apresenta a declaração de faturamento da empresa, incluindo receitas totais, deduções fiscais (como devoluções e descontos) e impostos incidentes sobre vendas. Permite acompanhar a evolução das receitas ao longo do tempo e identificar tendências de crescimento ou retração." },
			            { "Demonstrações Financeiras", "Balanço Patrimonial", "Detalha o balanço patrimonial da empresa, mostrando os ativos (circulantes e permanentes), passivos (circulantes e permanentes) e o Patrimônio Líquido. Fornece uma visão completa da estrutura patrimonial da organização em um determinado período." },
			            { "Demonstrações Financeiras", "Demonstração de Resultado do Exercício", "Apresenta a demonstração do resultado do exercício (DRE), destacando a receita líquida, custos, despesas operacionais, resultados financeiros e tributários, além do lucro líquido final. Permite avaliar a performance operacional e financeira da empresa ao longo do período." },
			            { "Demonstrações Financeiras", "Demonstração do Fluxo de Caixa", "Mostra a demonstração do fluxo de caixa, segmentada em atividades operacionais, de investimento e de financiamento. Permite entender como os recursos entram e saem da empresa ao longo do período, identificando as principais fontes e aplicações de caixa." },
			            { "Demonstrações Financeiras", "Simulador Operacional e Financeiro", "Oferece um simulador interativo que permite realizar projeções e simulações de cenários futuros, ajustando variáveis como receitas, custos, despesas e investimentos. Permite avaliar o impacto dessas mudanças no resultado financeiro e na saúde patrimonial da empresa, auxiliando na tomada de decisões estratégicas." }
			        }
			    )
			
			VAR _Header = "
			<html>
			<head>
			  <style>
			    body { font-family: 'Segoe UI', sans-serif; margin: 20px; background: #ffffff; color: #000000; }
			    h2 { color: #000000; border-bottom: 2px solid #14c8fa; padding-bottom: 8px; font-size: 1.4em; }
			    .search-box { 
			      width: 100%; 
			      padding: 10px 14px; 
			      margin: 10px 0 20px 0; 
			      border: 1px solid #ccc; 
			      border-radius: 6px; 
			      font-size: 1em; 
			      box-sizing: border-box; 
			      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
			    }
			    .card { 
			      background: white; 
			      margin: 16px 0; 
			      padding: 16px; 
			      border-radius: 6px; 
			      box-shadow: 0 1px 3px rgba(0,0,0,0.1); 
			      border-left: 5px solid #14c8fa; 
			    }
			    .block { 
			      background: #0ae18c; 
			      color: #000000; 
			      padding: 4px 8px; 
			      border-radius: 4px; 
			      font-size: 0.9em; 
			      font-weight: 600; 
			      margin-bottom: 8px;
			    }
			    .title { 
			      font-weight: 600; 
			      color: #000000; 
			      margin: 0 0 8px 0; 
			      font-size: 1.1em;
			    }
			    .description { 
			      color: #000000; 
			      line-height: 1.5; 
			    }
			  </style>
			</head>
			<body>
			  <h2> Glossário de Páginas</h2>
			  <input type='text' class='search-box' placeholder='Pesquisar por análise...' onkeyup='filterCards(this)'>
			"
			
			VAR _Items = 
			CONCATENATEX(
			    _TabelaGlossario,
			    "<div class='card' data-search='" & [Bloco] & " " & [Analise] & " " & [Descricao] & "'>" &
			       "<div class='block'>" & [Bloco] & "</div>" &
			       "<div class='title'>" & [Analise] & "</div>" &
			       "<div class='description'>" & [Descricao] & "</div>" &
			     "</div>",
			    "",
			    [Bloco], ASC,
			    [Analise], ASC
			)
			
			VAR _Footer = "
			<script>
			function filterCards(input) {
			  let value = input.value.toLowerCase();
			  let cards = document.getElementsByClassName('card');
			  for (let i = 0; i < cards.length; i++) {
			    let text = cards[i].getAttribute('data-search').toLowerCase();
			    cards[i].style.display = text.includes(value) ? 'block' : 'none';
			  }
			}
			</script>
			</body></html>
			"
			
			RETURN
			_Header & _Items & _Footer
			```
		lineageTag: f9d07a5d-be10-4abf-84dc-9cc01f65ae31

	measure solvenciaMemoriaCalculoHTML = ```
			
			VAR RentabilidadeHTML = "<li style='margin: 10px 0; font-size: 12px;'><span style='color: #000;'>0,05</span> * Índice de Rentabilidade <span style='color: #555;'> " & FORMAT([rentabilidade cpt], "0.00") & " </span></li>"
			VAR LiquidezGeralHTML = "<li style='margin: 10px 0; font-size: 12px;'><span style='color: #000;'>+</span> <span style='color: #000;'>1,65</span> * Índice de Liquidez Geral <span style='color: #555;'> " & FORMAT([lliquidez geral], "0.00") & " </span></li>"
			VAR LiquidezSecaHTML = "<li style='margin: 10px 0; font-size: 12px;'><span style='color: #000;'>+</span> <span style='color: #000;'>3,55</span> * Índice de Liquidez Seca <span style='color: #555;'> " & FORMAT([lliquidez seca], "0.00") & " </span></li>"
			VAR LiquidezCorrenteHTML = "<li style='margin: 10px 0; font-size: 12px;'><span style='color: #000;'>-</span> <span style='color: #000;'>1,06</span> * Índice de Liquidez Corrente <span style='color: #555;'> " & FORMAT([lliquidez corrente], "0.00") & " </span></li>"
			VAR EndividamentoTotalHTML = "<li style='margin: 10px 0; font-size: 12px;'><span style='color: #000;'>-</span> <span style='color: #000;'>0,33</span> * Índice de Endividamento Total <span style='color: #555;'> " & FORMAT([Endividamento total], "0.00") & " </span></li>"
			
			RETURN
			"<div style='font-family: Segoe UI, sans-serif; color: #333; padding: 10px; background-color: #ffffff; border-radius: 8px; width: 100%;'>
			    <h3 style='color: #000; text-align: left;'>Memória de Cálculo</h3>
			    <ul style='list-style: none; padding: 0;'>" &
			    RentabilidadeHTML & 
			    LiquidezGeralHTML & 
			    LiquidezSecaHTML & 
			    LiquidezCorrenteHTML & 
			    EndividamentoTotalHTML &
			    "</ul>
			</div>"
			
			```
		lineageTag: 9e667d75-0d05-4482-85a4-9b2bbb9a89c9

	measure 'DDespesaADM_actual_month teste' = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    
			    RETURN
			    CALCULATE(
			[DDespesaADM],
			dCalendario[data] = UltimoMesTrimestre
			)
			
			
			
			```
		lineageTag: eab17f79-817f-4591-ba71-61a2f2323a77

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure mreceita_liquiida_selecionada_kpi = ```
			
			VAR MinData =
			    CALCULATE ( MIN ( 'dCalendario'[Data] ), ALLSELECTED ( 'dCalendario' ) )
			VAR MaxData =
			    CALCULATE ( MAX ( 'dCalendario'[Data] ), ALLSELECTED ( 'dCalendario' ) )
			RETURN
			CALCULATE (
			    SUM ( balancetenew[vlr] ),
			    balancetenew[Query] IN {
			        "Receita Bruta",
			        "Deduções da Receita Bruta",
			        "DRE_Imp_Incidentes_Sobre_Receita"
			    },
			    'dCalendario'[Data] >= MinData,
			    'dCalendario'[Data] <= MaxData
			)
			
			
			```
		lineageTag: 95d359c0-5bfb-43f3-9368-9aa75b06f404

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MReceita_Bruta_Selecionado_KPI =
			
			VAR MinData =
			    CALCULATE ( MIN ( 'dCalendario'[Data] ), ALLSELECTED ( 'dCalendario' ) )
			VAR MaxData =
			    CALCULATE ( MAX ( 'dCalendario'[Data] ), ALLSELECTED ( 'dCalendario' ) )
			RETURN
			CALCULATE (
			    SUM ( balancetenew[vlr] ),
			    balancetenew[Query] IN {
			        "Receita Bruta"   },
			    'dCalendario'[Data] >= MinData,
			    'dCalendario'[Data] <= MaxData
			)
		lineageTag: 7448bebc-13ec-48e2-a154-1b7e49280e3f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MReceita_Bruta_Selecionado_KPI_LY =
			
			VAR MinData =
			    CALCULATE ( MIN ( 'dCalendario'[Data] ), ALLSELECTED ( 'dCalendario' ) )
			VAR MaxData =
			    CALCULATE ( MAX ( 'dCalendario'[Data] ), ALLSELECTED ( 'dCalendario' ) )
			
			-- desloca o intervalo inteiro 12 meses para trás (LY)
			VAR MinDataLY = EDATE ( MinData, -12 )
			VAR MaxDataLY = EDATE ( MaxData, -12 )
			
			RETURN
			CALCULATE (
			    SUM ( balancetenew[vlr] ),
			    balancetenew[Query] IN {
			        "Receita Bruta"
			    },
			    'dCalendario'[Data] >= MinDataLY,
			    'dCalendario'[Data] <= MaxDataLY
			)
		lineageTag: 21f963ae-005b-48ce-96b4-6e10d91f0636

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure deducoes_impostos_selecionado_KPI_LY =
			
			VAR MinData =
			    CALCULATE ( MIN ( 'dCalendario'[Data] ), ALLSELECTED ( 'dCalendario' ) )
			VAR MaxData =
			    CALCULATE ( MAX ( 'dCalendario'[Data] ), ALLSELECTED ( 'dCalendario' ) )
			
			-- desloca o intervalo inteiro 12 meses para trás (LY)
			VAR MinDataLY = EDATE ( MinData, -12 )
			VAR MaxDataLY = EDATE ( MaxData, -12 )
			
			RETURN
			CALCULATE (
			    SUM ( balancetenew[vlr] ),
			    balancetenew[Query] IN {
			        "Deduções da Receita Bruta",
			        "DRE_Imp_Incidentes_Sobre_Receita"
			    },
			    'dCalendario'[Data] >= MinDataLY,
			    'dCalendario'[Data] <= MaxDataLY
			)
		lineageTag: acc397dd-3246-4318-997e-a0b65daaee03

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MMargem_Bruta_selecionado_LY_kpi =
			
			VAR MinData =
			    CALCULATE ( MIN ( 'dCalendario'[Data] ), ALLSELECTED ( 'dCalendario' ) )
			VAR MaxData =
			    CALCULATE ( MAX ( 'dCalendario'[Data] ), ALLSELECTED ( 'dCalendario' ) )
			
			-- desloca o intervalo inteiro 12 meses para trás (LY)
			VAR MinDataLY = EDATE ( MinData, -12 )
			VAR MaxDataLY = EDATE ( MaxData, -12 )
			
			RETURN
			CALCULATE (
			    SUM ( balancetenew[vlr] ),
			    balancetenew[Query] IN {
			        "dre_Lucro_bruto"
			    },
			    'dCalendario'[Data] >= MinDataLY,
			    'dCalendario'[Data] <= MaxDataLY
			)
		lineageTag: 5eb1d1dd-8e40-42f4-9f66-6351ed19f188

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Analise_Horizontal_Ativos_Short = ```
			
			VAR Var_AT = [desvio%_ativo_total]
			VAR Var_AC = [desvio%_ativo_circulante]
			VAR Var_ANC = [desvio%_ativo_n_circulante]
			
			VAR TopTable =
			    FILTER(
			        ALL( 'balancetenew' ),
			        'balancetenew'[Query] IN { "BL_AT_soma", "BL_ATCIR_soma", "BL_ATNCIR_soma" }
			    )
			
			VAR RowMax = TOPN( 1, TopTable, [desvio%], DESC )
			VAR RowMin = TOPN( 1, TopTable, [desvio%], ASC )
			
			VAR NomeMax = LEFT( CONCATENATEX( RowMax, 'balancetenew'[Query], "," ), 24 )
			VAR NomeMin = LEFT( CONCATENATEX( RowMin, 'balancetenew'[Query], "," ), 24 )
			
			VAR ValorMax = MAXX( RowMax, [desvio%] )
			VAR ValorMin = MINX( RowMin, [desvio%] )
			
			RETURN
			IF(
			    ISBLANK( Var_AT ) && ISBLANK( Var_AC ) && ISBLANK( Var_ANC ),
			    BLANK(),
			    "AT:" & FORMAT( Var_AT, "0.00%" ) &
			    " AC:" & FORMAT( Var_AC, "0.00%" ) &
			    " ANC:" & FORMAT( Var_ANC, "0.00%" ) &
			    " | Max:" & NomeMax & ":" & FORMAT( ValorMax, "0.00%" ) &
			    " Min:" & NomeMin & ":" & FORMAT( ValorMin, "0.00%" )
			)
			
			```
		lineageTag: e3583f66-c1b8-4bc5-be1d-06653dcefae4

	measure desvio%_ativo_circulante =
			
			CALCULATE(
			    [desvio%],
			    balancetenew[Query] = "BL_ATCIR_soma"
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: c6f9c0cc-9ab5-49c5-862a-84cb9224b7d7

	measure desvio%_ativo_n_circulante =
			
			CALCULATE(
			    [desvio%],
			    balancetenew[Query] = "BL_ATNCIR_soma"
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 6e0839a9-750a-4a63-958b-d3f9aab8513c

	measure desvio%_ativo_total =
			
			CALCULATE(
			    [desvio%],
			    balancetenew[Query] = "BL_AT_soma"
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: f15bd4e5-243b-4177-9dd2-9d9db09088c9

	measure Narrativa_Ativos_Resumo = ```
			
			VAR Var_AT = [desvio%_ativo_total]
			VAR Var_AC = [desvio%_ativo_circulante]
			VAR Var_ANC = [desvio%_ativo_n_circulante]
			
			VAR AC_Sent = IF(Var_AC >= 0, "crescimento", "queda")
			VAR ANC_Sent = IF(Var_ANC >= 0, "leve alta", "retração")
			VAR AT_Sent = IF(Var_AT >= 0, "expansão", "redução")
			
			RETURN
			"
			<div style='font-family:Segoe UI; font-size:13px; padding:4px;'>
			<b>Análise Horizontal dos Ativos</b><br><br>
			
			O <b>Ativo Total</b> apresentou <b>" & AT_Sent & "</b> de 
			<span style='color:" & IF(Var_AT>=0,"green","red") & "'>" &
			FORMAT(Var_AT,"0.00%") & "</span>, refletindo os movimentos combinados dos
			grupos circulante e não circulante.<br><br>
			
			O <b>Ativo Circulante</b> mostrou <b>" & AC_Sent & "</b> de 
			<span style='color:" & IF(Var_AC>=0,"green","red") & "'>" &
			FORMAT(Var_AC,"0.00%") & "</span>, influenciado principalmente pelas 
			contas de maior giro.<br><br>
			
			Já o <b>Ativo Não Circulante</b> registrou <b>" & ANC_Sent & "</b> de 
			<span style='color:" & IF(Var_ANC>=0,"green","red") & "'>" &
			FORMAT(Var_ANC,"0.00%") & "</span>, mantendo tendência estrutural do período.
			</div>"
			
			```
		lineageTag: dc77cffc-02b7-47ae-aa53-1d2297c0a5fc

	measure Narrativa_Ativos_Aumento = ```
			
			VAR _data_table =
			    FILTER(
			        ALL('balancetenew'),
			        'balancetenew'[Query] IN { 
			            "BL_AT_soma",
			            "BL_ATCIR_soma",
			            "BL_ATNCIR_soma"
			        }
			    )
			
			VAR RowMax =
			    TOPN(1, _data_table, [desvio%], DESC)
			
			VAR Nome =
			    CONCATENATEX(RowMax, 'balancetenew'[Query], ", ")
			
			VAR Valor =
			    MAXX(RowMax, [desvio%])
			
			RETURN
			"
			<div style='font-family:Segoe UI; font-size:13px; padding:4px;'>
			<b>Maior Crescimento:</b> 
			<span style='color:green; font-weight:bold;'>" &
			Nome & "</span> apresentou aumento de 
			<span style='color:green'>" &
			FORMAT(Valor, "0.00%") & "</span>, sendo o principal fator de impulso do 
			<b>Ativo Total</b> no período.
			</div>"
			
			```
		lineageTag: 1c83d679-b7fc-4b7d-94c6-b8f316e84ae2

	measure Narrativa_Ativos_Queda = ```
			
			VAR _data_table =
			    FILTER(
			        ALL('balancetenew'),
			        'balancetenew'[Query] IN { 
			            "BL_AT_soma",
			            "BL_ATCIR_soma",
			            "BL_ATNCIR_soma"
			        }
			    )
			
			VAR RowMin =
			    TOPN(1, _data_table, [desvio%], ASC)
			
			VAR Nome =
			    CONCATENATEX(RowMin, 'balancetenew'[Query], ", ")
			
			VAR Valor =
			    MINX(RowMin, [desvio%])
			
			RETURN
			"
			<div style='font-family:Segoe UI; font-size:13px; padding:4px;'>
			<b>Maior Queda:</b> 
			<span style='color:red; font-weight:bold;'>" &
			Nome & "</span> registrou variação negativa de 
			<span style='color:red'>" &
			FORMAT(Valor, "0.00%") & "</span>, contribuindo para moderar o avanço
			global dos ativos no período.
			</div>"
			
			```
		lineageTag: 024bb1a3-d4ba-4002-9227-aba6a67a5547

	measure MMargem_Bruta_Rentab =
			
			[MReceita_Liquida_actual_month] + [CCusto_actual_month_rentab]
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 72c863bc-092e-4ae7-b01d-7a20a1739743

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MMargem_Bruta|Receita_Liq_Rentab =
			
			DIVIDE(
			    [MMargem_bruta_actual_month_Rentab]
			    , [MReceita_Liquida_actual_month]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6635f050-ad27-4c04-a6d2-7dcaae5366b5

	measure MMargem_Bruta_Acu_Rentab =
			
			[MReceita_Liquida_ACU] + [CCusto_ACU]
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: aca38c28-8b66-4ded-9493-3a9acabd02c9

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MMargem_Bruta|Receita_Liq_Acu_Rentab =
			
			DIVIDE(
			    [MMargem_Bruta_Acu_Rentab]
			    , [MReceita_Liquida_ACU]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bb19bfd8-25ae-4dff-bc29-3ac90426f803

	measure MMargem_bruta_actual_month_Rentab = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			    CALCULATE(
			        CALCULATE(
			        SUM(
			            balancetenew[vlr]
			        ),
			        FILTER(
			                balancetenew,
			                balancetenew[Query] = "Receita Bruta" || 
			                balancetenew[Query] = "Deduções da Receita Bruta" || 
			                balancetenew[Query] = "DRE_Imp_Incidentes_Sobre_Receita" ||
			                balancetenew[Query] = "Custo dos Produtos Vendidos" ||
			                balancetenew[Query] = "Custo dos Serviços" ||
			                balancetenew[Query] = "custo_vendas"
			            ),
			                dCalendario[data] = UltimoMesTrimestre
			    ))
			```
		lineageTag: 10617aa8-9642-41d4-9d4e-50a4e45a8112

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Timeline Capital de Giro HTML' =
			
			VAR PMP_  = COALESCE([Prazo Médio Contas a Pagar], 0)
			VAR PMR_  = COALESCE([Prazo Médio Contas a Receber], 0)
			VAR PMGE_ = COALESCE([prazo_medio_giro_estoque_aging], 0)
			
			-- marcos da timeline
			VAR DiaEntrada       = 0
			VAR DiaEstoque       = PMGE_
			VAR DiaPagamentos    = PMP_
			VAR DiaRecebimentos  = PMR_
			
			-- capital de giro conforme solicitado
			VAR DiasCapitalGiro  = PMR_ - PMP_
			
			VAR MaxDia =
			    MAX(
			        1,
			        MAX(
			            DiaEstoque,
			            MAX(DiaPagamentos, DiaRecebimentos)
			        )
			    )
			
			VAR PctEntradaNum      = DIVIDE(DiaEntrada, MaxDia, 0) * 100
			VAR PctEstoqueNum      = DIVIDE(DiaEstoque, MaxDia, 0) * 100
			VAR PctPagamentosNum   = DIVIDE(DiaPagamentos, MaxDia, 0) * 100
			VAR PctRecebimentosNum = DIVIDE(DiaRecebimentos, MaxDia, 0) * 100
			
			-- trecho azul do capital de giro: entre pagamentos e recebimentos
			VAR PctCGIniNum   = PctPagamentosNum
			VAR PctCGFimNum   = PctRecebimentosNum
			VAR PctCGLargNum  = PctCGFimNum - PctCGIniNum
			
			VAR PctEntrada      = SUBSTITUTE(FORMAT(PctEntradaNum, "0.0"), ",", ".")
			VAR PctEstoque      = SUBSTITUTE(FORMAT(PctEstoqueNum, "0.0"), ",", ".")
			VAR PctPagamentos   = SUBSTITUTE(FORMAT(PctPagamentosNum, "0.0"), ",", ".")
			VAR PctRecebimentos = SUBSTITUTE(FORMAT(PctRecebimentosNum, "0.0"), ",", ".")
			VAR PctCGIni        = SUBSTITUTE(FORMAT(PctCGIniNum, "0.0"), ",", ".")
			VAR PctCGLarg       = SUBSTITUTE(FORMAT(PctCGLargNum, "0.0"), ",", ".")
			
			RETURN
			"
			<div style='
			    font-family:Segoe UI, Arial, sans-serif;
			    background:#ffffff;
			    border:1px solid #E6EAF0;
			    border-radius:8px;
			    padding:16px 18px 14px 18px;
			    box-sizing:border-box;
			    width:100%;
			    min-height:210px;
			    color:#23384D;
			'>
			
			    <div style='font-size:15px; font-weight:600; color:#26435C; margin-bottom:10px;'>
			        Timeline do Capital de Giro
			    </div>
			
			    <div style='font-size:11px; font-weight:600; color:#6B7A8C; margin-bottom:16px;'>
			        Este período
			    </div>
			
			    <div style='display:flex; gap:20px; align-items:center;'>
			
			        <div style='flex:1; min-width:0;'>
			            <div style='position:relative; height:130px;'>
			
			                <!-- linha base -->
			                <div style='
			                    position:absolute;
			                    left:0;
			                    right:0;
			                    top:58px;
			                    height:3px;
			                    background:#BFC9D4;
			                    border-radius:999px;
			                '></div>
			
			                <!-- seta da linha -->
			                <div style='
			                    position:absolute;
			                    right:-1px;
			                    top:54px;
			                    width:0;
			                    height:0;
			                    border-top:5px solid transparent;
			                    border-bottom:5px solid transparent;
			                    border-left:12px solid #BFC9D4;
			                '></div>
			
			                <!-- trecho capital de giro -->
			                <div style='
			                    position:absolute;
			                    left:" & PctCGIni & "%;
			                    width:" & PctCGLarg & "%;
			                    top:57px;
			                    height:4px;
			                    background:#2D9CDB;
			                    border-radius:999px;
			                '></div>
			
			                <!-- Entrada -->
			                <div style='position:absolute; left:calc(" & PctEntrada & "% - 3px); top:34px;'>
			                    <div style='width:6px; height:28px; background:#2F80ED; border-radius:999px;'></div>
			                </div>
			                <div style='position:absolute; left:" & PctEntrada & "%; top:6px; transform:translateX(-8%); font-size:10px; color:#6B7A8C; font-weight:600; white-space:nowrap;'>
			                    Dia 0
			                </div>
			                <div style='position:absolute; left:" & PctEntrada & "%; top:72px; transform:translateX(-8%); font-size:10px; color:#6B7A8C; text-align:left; width:88px; line-height:1.25;'>
			                    Entradas nos<br/>Estoques
			                </div>
			
			                <!-- Estoque vendido -->
			                <div style='position:absolute; left:calc(" & PctEstoque & "% - 3px); top:34px;'>
			                    <div style='width:6px; height:28px; background:#F2994A; border-radius:999px;'></div>
			                </div>
			                <div style='position:absolute; left:" & PctEstoque & "%; top:6px; transform:translateX(-50%); font-size:10px; color:#6B7A8C; font-weight:600; white-space:nowrap;'>
			                    Dia " & FORMAT(DiaEstoque, "0") & "
			                </div>
			                <div style='position:absolute; left:" & PctEstoque & "%; top:72px; transform:translateX(-50%); font-size:10px; color:#6B7A8C; text-align:center; width:86px; line-height:1.25;'>
			                    Estoque<br/>Vendido
			                </div>
			
			                <!-- Fornecedores pagos -->
			                <div style='position:absolute; left:calc(" & PctPagamentos & "% - 3px); top:34px;'>
			                    <div style='width:6px; height:28px; background:#BB4C97; border-radius:999px;'></div>
			                </div>
			                <div style='position:absolute; left:" & PctPagamentos & "%; top:6px; transform:translateX(-50%); font-size:10px; color:#6B7A8C; font-weight:600; white-space:nowrap;'>
			                    Dia " & FORMAT(DiaPagamentos, "0") & "
			                </div>
			                <div style='position:absolute; left:" & PctPagamentos & "%; top:72px; transform:translateX(-50%); font-size:10px; color:#6B7A8C; text-align:center; width:96px; line-height:1.25;'>
			                    Fornecedores<br/>Pagos
			                </div>
			
			                <!-- Recebimentos -->
			                <div style='position:absolute; left:calc(" & PctRecebimentos & "% - 3px); top:34px;'>
			                    <div style='width:6px; height:28px; background:#34A853; border-radius:999px;'></div>
			                </div>
			                <div style='position:absolute; left:" & PctRecebimentos & "%; top:6px; transform:translateX(-50%); font-size:10px; color:#6B7A8C; font-weight:600; white-space:nowrap;'>
			                    Dia " & FORMAT(DiaRecebimentos, "0") & "
			                </div>
			                <div style='position:absolute; left:" & PctRecebimentos & "%; top:72px; transform:translateX(-50%); font-size:10px; color:#6B7A8C; text-align:center; width:84px; line-height:1.25;'>
			                    Recebimentos
			                </div>
			
			            </div>
			        </div>
			
			        <div style='
			            width:124px;
			            min-width:124px;
			            background:#0F8FA6;
			            color:#ffffff;
			            border-radius:8px;
			            padding:16px 10px;
			            text-align:center;
			            box-sizing:border-box;
			        '>
			            <div style='font-size:31px; font-weight:700; line-height:1; margin-bottom:10px;'>
			                " & FORMAT(DiasCapitalGiro, "0") & "
			            </div>
			            <div style='font-size:12px; line-height:1.25;'>
			                Dias de Capital<br/>de Giro
			            </div>
			        </div>
			
			    </div>
			</div>
			"
		lineageTag: e894306e-09c3-4dba-bf17-445936277b9d

	measure 'Timeline Ciclo Operacional HTML' =
			
			VAR PMR_  = COALESCE([Prazo Médio Contas a Receber], 0)
			VAR PMGE_ = COALESCE([prazo_medio_giro_estoque_aging], 0)
			
			VAR DiaEntrada      = 0
			VAR DiaEstoque      = PMGE_
			VAR DiaPagamentos   = 0
			VAR DiaRecebimentos = PMGE_ + PMR_
			
			VAR DiasRecebimento = DiaRecebimentos - DiaEstoque
			
			VAR MaxDia =
			    MAX(
			        1,
			        MAX(
			            DiaEstoque,
			            MAX(DiaPagamentos, DiaRecebimentos)
			        )
			    )
			
			VAR PctEntradaNum      = DIVIDE(DiaEntrada, MaxDia, 0) * 100
			VAR PctEstoqueNum      = DIVIDE(DiaEstoque, MaxDia, 0) * 100
			VAR PctPagamentosNum   = DIVIDE(DiaPagamentos, MaxDia, 0) * 100
			VAR PctRecebimentosNum = DIVIDE(DiaRecebimentos, MaxDia, 0) * 100
			
			-- agora a faixa fica entre PMGE e PMR
			VAR PctCGIniNum  = MIN(PctEstoqueNum, PctRecebimentosNum)
			VAR PctCGFimNum  = MAX(PctEstoqueNum, PctRecebimentosNum)
			VAR PctCGLargNum = PctCGFimNum - PctCGIniNum
			
			VAR PctEntrada      = SUBSTITUTE(FORMAT(PctEntradaNum, "0.0"), ",", ".")
			VAR PctEstoque      = SUBSTITUTE(FORMAT(PctEstoqueNum, "0.0"), ",", ".")
			VAR PctPagamentos   = SUBSTITUTE(FORMAT(PctPagamentosNum, "0.0"), ",", ".")
			VAR PctRecebimentos = SUBSTITUTE(FORMAT(PctRecebimentosNum, "0.0"), ",", ".")
			VAR PctCGIni        = SUBSTITUTE(FORMAT(PctCGIniNum, "0.0"), ",", ".")
			VAR PctCGLarg       = SUBSTITUTE(FORMAT(PctCGLargNum, "0.0"), ",", ".")
			
			VAR CorCapitalGiro =
			    IF(DiasRecebimento < 0, "#D64545", "#2D9CDB")
			
			RETURN
			"
			<div style='
			    font-family:Segoe UI, Arial, sans-serif;
			    background:#ffffff;
			    border:1px solid #E6EAF0;
			    border-radius:8px;
			    padding:18px 20px 18px 20px;
			    box-sizing:border-box;
			    width:100%;
			    color:#23384D;
			    overflow:hidden;
			'>
			
			    <div style='font-size:15px; font-weight:600; color:#26435C; margin-bottom:10px;'>
			        Timeline do Ciclo Operacional
			    </div>
			
			    <div style='font-size:11px; font-weight:600; color:#6B7A8C; margin-bottom:18px;'>
			        Este Período
			    </div>
			
			    <div style='
			        display:flex;
			        align-items:center;
			        justify-content:space-between;
			        gap:36px;
			        flex-wrap:nowrap;
			        width:100%;
			    '>
			
			        <div style='
			            flex:1 1 auto;
			            min-width:0;
			            width:100%;
			        '>
			            <div style='position:relative; height:132px; width:100%;'>
			
			                <!-- linha base -->
			                <div style='
			                    position:absolute;
			                    left:0;
			                    right:0;
			                    top:58px;
			                    height:3px;
			                    background:#BFC9D4;
			                    border-radius:999px;
			                '></div>
			
			                <!-- seta -->
			                <div style='
			                    position:absolute;
			                    right:-1px;
			                    top:54px;
			                    width:0;
			                    height:0;
			                    border-top:5px solid transparent;
			                    border-bottom:5px solid transparent;
			                    border-left:12px solid #BFC9D4;
			                '></div>
			
			                <!-- faixa entre PMGE e PMR -->
			                <div style='
			                    position:absolute;
			                    left:" & PctCGIni & "%;
			                    width:" & PctCGLarg & "%;
			                    top:57px;
			                    height:4px;
			                    background:" & CorCapitalGiro & ";
			                    border-radius:999px;
			                '></div>
			
			                <!-- Entrada -->
			                <div style='position:absolute; left:calc(" & PctEntrada & "% - 3px); top:34px;'>
			                    <div style='width:6px; height:28px; background:#2F80ED; border-radius:999px;'></div>
			                </div>
			                <div style='
			                    position:absolute;
			                    left:" & PctEntrada & "%;
			                    top:6px;
			                    transform:translateX(-8%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    font-weight:600;
			                    white-space:nowrap;
			                '>
			                    Dia 0
			                </div>
			                <div style='
			                    position:absolute;
			                    left:" & PctEntrada & "%;
			                    top:74px;
			                    transform:translateX(-8%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    text-align:left;
			                    width:88px;
			                    line-height:1.25;
			                '>
			                    Entradas nos<br/>Estoques
			                </div>
			
			                <!-- Estoque vendido -->
			                <div style='position:absolute; left:calc(" & PctEstoque & "% - 3px); top:34px;'>
			                    <div style='width:6px; height:28px; background:#F2994A; border-radius:999px;'></div>
			                </div>
			                <div style='
			                    position:absolute;
			                    left:" & PctEstoque & "%;
			                    top:6px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    font-weight:600;
			                    white-space:nowrap;
			                '>
			                    Dia " & FORMAT(DiaEstoque, "0") & "
			                </div>
			                <div style='
			                    position:absolute;
			                    left:" & PctEstoque & "%;
			                    top:74px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    text-align:center;
			                    width:86px;
			                    line-height:1.25;
			                '>
			                    Estoque<br/>Vendido
			                </div>
			
			                <!-- marco ocultado para não embolar no início -->
			                <div style='display:none; position:absolute; left:calc(" & PctPagamentos & "% - 3px); top:34px;'>
			                    <div style='width:6px; height:28px; background:#BB4C97; border-radius:999px;'></div>
			                </div>
			                <div style='display:none;
			                    position:absolute;
			                    left:" & PctPagamentos & "%;
			                    top:6px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    font-weight:600;
			                    white-space:nowrap;
			                '>
			                    Dia " & FORMAT(DiaPagamentos, "0") & "
			                </div>
			                <div style='display:none;
			                    position:absolute;
			                    left:" & PctPagamentos & "%;
			                    top:74px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    text-align:center;
			                    width:96px;
			                    line-height:1.25;
			                '>
			                    Fornecedores<br/>Pagos
			                </div>
			
			                <!-- Recebimentos -->
			                <div style='position:absolute; left:calc(" & PctRecebimentos & "% - 3px); top:34px;'>
			                    <div style='width:6px; height:28px; background:#34A853; border-radius:999px;'></div>
			                </div>
			                <div style='
			                    position:absolute;
			                    left:" & PctRecebimentos & "%;
			                    top:6px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    font-weight:600;
			                    white-space:nowrap;
			                '>
			                    Dia " & FORMAT(DiaRecebimentos, "0") & "
			                </div>
			                <div style='
			                    position:absolute;
			                    left:" & PctRecebimentos & "%;
			                    top:74px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    text-align:center;
			                    width:84px;
			                    line-height:1.25;
			                '>
			                    Recebimentos
			                </div>
			
			            </div>
			        </div>
			
			        <div style='
			            flex:0 0 132px;
			            width:132px;
			            min-width:132px;
			            max-width:132px;
			            background:#0F8FA6;
			            color:#ffffff;
			            border-radius:8px;
			            padding:18px 12px;
			            text-align:center;
			            box-sizing:border-box;
			            margin-left:8px;
			        '>
			            <div style='font-size:32px; font-weight:700; line-height:1; margin-bottom:10px;'>
			                " & FORMAT(DiasRecebimento, "0") & "
			            </div>
			            <div style='font-size:12px; line-height:1.25;'>
			                Dias para<br/>Recebimento
			            </div>
			        </div>
			
			    </div>
			</div>
			"
		lineageTag: a063dcbc-a32f-43f8-837c-c5b6e78ac228

	measure 'Timeline Ciclo Financeiro HTML II prazos puros' =
			
			VAR PMP_  = COALESCE([Prazo Médio Contas a Pagar], 0)
			VAR PMR_  = COALESCE([Prazo Médio Contas a Receber], 0)
			VAR PMGE_ = COALESCE([prazo_medio_giro_estoque_aging], 0)
			
			VAR DiaEntrada      = 0
			VAR DiaEstoque      = 0
			VAR DiaPagamentos   = PMP_
			VAR DiaRecebimentos = PMGE_ + PMR_
			
			VAR DiasCapitalGiro = PMGE_ + PMR_ - PMP_
			
			VAR MaxDia =
			    MAX(
			        1,
			        MAX(
			            DiaEntrada,
			            MAX(DiaPagamentos, DiaRecebimentos)
			        )
			    )
			
			VAR PctEntradaNum      = DIVIDE(DiaEntrada, MaxDia, 0) * 100
			VAR PctEstoqueNum      = DIVIDE(DiaEstoque, MaxDia, 0) * 100
			VAR PctPagamentosNum   = DIVIDE(DiaPagamentos, MaxDia, 0) * 100
			VAR PctRecebimentosNum = DIVIDE(DiaRecebimentos, MaxDia, 0) * 100
			
			VAR PctCGIniNum  = MIN(PctPagamentosNum, PctRecebimentosNum)
			VAR PctCGFimNum  = MAX(PctPagamentosNum, PctRecebimentosNum)
			VAR PctCGLargNum = PctCGFimNum - PctCGIniNum
			
			VAR PctEntrada      = SUBSTITUTE(FORMAT(PctEntradaNum, "0.0"), ",", ".")
			VAR PctEstoque      = SUBSTITUTE(FORMAT(PctEstoqueNum, "0.0"), ",", ".")
			VAR PctPagamentos   = SUBSTITUTE(FORMAT(PctPagamentosNum, "0.0"), ",", ".")
			VAR PctRecebimentos = SUBSTITUTE(FORMAT(PctRecebimentosNum, "0.0"), ",", ".")
			VAR PctCGIni        = SUBSTITUTE(FORMAT(PctCGIniNum, "0.0"), ",", ".")
			VAR PctCGLarg       = SUBSTITUTE(FORMAT(PctCGLargNum, "0.0"), ",", ".")
			
			VAR CorCapitalGiro =
			    IF(DiasCapitalGiro < 0, "#D64545", "#2D9CDB")
			
			RETURN
			"
			<div style='
			    font-family:Segoe UI, Arial, sans-serif;
			    background:#ffffff;
			    border:1px solid #E6EAF0;
			    border-radius:8px;
			    padding:18px 20px 18px 20px;
			    box-sizing:border-box;
			    width:100%;
			    color:#23384D;
			    overflow:hidden;
			'>
			
			    <div style='font-size:15px; font-weight:600; color:#26435C; margin-bottom:10px;'>
			        Timeline do Ciclo Financeiro
			    </div>
			
			    <div style='font-size:11px; font-weight:600; color:#6B7A8C; margin-bottom:18px;'>
			        Este Período
			    </div>
			
			    <div style='
			        display:flex;
			        align-items:center;
			        justify-content:space-between;
			        gap:36px;
			        flex-wrap:nowrap;
			        width:100%;
			    '>
			
			        <div style='
			            flex:1 1 auto;
			            min-width:0;
			            width:100%;
			        '>
			            <div style='position:relative; height:132px; width:100%;'>
			
			                <!-- linha base -->
			                <div style='
			                    position:absolute;
			                    left:0;
			                    right:0;
			                    top:58px;
			                    height:3px;
			                    background:#BFC9D4;
			                    border-radius:999px;
			                '></div>
			
			                <!-- seta -->
			                <div style='
			                    position:absolute;
			                    right:-1px;
			                    top:54px;
			                    width:0;
			                    height:0;
			                    border-top:5px solid transparent;
			                    border-bottom:5px solid transparent;
			                    border-left:12px solid #BFC9D4;
			                '></div>
			
			                <!-- faixa capital de giro -->
			                <div style='
			                    position:absolute;
			                    left:" & PctCGIni & "%;
			                    width:" & PctCGLarg & "%;
			                    top:57px;
			                    height:4px;
			                    background:" & CorCapitalGiro & ";
			                    border-radius:999px;
			                '></div>
			
			                <!-- Saída dos estoques -->
			                <div style='position:absolute; left:0; top:34px;'>
			                    <div style='width:6px; height:28px; background:#2F80ED; border-radius:999px;'></div>
			                </div>
			                <div style='
			                    position:absolute;
			                    left:0;
			                    top:6px;
			                    font-size:10px;
			                    color:#6B7A8C;
			                    font-weight:600;
			                    white-space:nowrap;
			                '>
			                    Dia 0
			                </div>
			                <div style='
			                    position:absolute;
			                    left:0;
			                    top:74px;
			                    font-size:10px;
			                    color:#6B7A8C;
			                    text-align:left;
			                    width:96px;
			                    line-height:1.25;
			                '>
			                    Entrada nos<br/>Estoques
			                </div>
			
			                <!-- bloco oculto para não embolar o início -->
			                <div style='display:none; position:absolute; left:calc(" & PctEstoque & "% - 3px); top:34px;'>
			                    <div style='width:6px; height:28px; background:#F2994A; border-radius:999px;'></div>
			                </div>
			                <div style='display:none;
			                    position:absolute;
			                    left:" & PctEstoque & "%;
			                    top:6px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    font-weight:600;
			                    white-space:nowrap;
			                '>
			                    Dia " & FORMAT(DiaEstoque, "0") & "
			                </div>
			                <div style='display:none;
			                    position:absolute;
			                    left:" & PctEstoque & "%;
			                    top:74px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    text-align:center;
			                    width:86px;
			                    line-height:1.25;
			                '>
			                    Estoque<br/>Vendido
			                </div>
			
			                <!-- Recebimentos -->
			                <div style='position:absolute; left:calc(" & PctRecebimentos & "% - 3px); top:34px;'>
			                    <div style='width:6px; height:28px; background:#34A853; border-radius:999px;'></div>
			                </div>
			                <div style='
			                    position:absolute;
			                    left:" & PctRecebimentos & "%;
			                    top:6px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    font-weight:600;
			                    white-space:nowrap;
			                '>
			                    Dia " & FORMAT(DiaRecebimentos, "0") & "
			                </div>
			                <div style='
			                    position:absolute;
			                    left:" & PctRecebimentos & "%;
			                    top:74px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    text-align:center;
			                    width:84px;
			                    line-height:1.25;
			                '>
			                    Recebimentos
			                </div>
			
			                <!-- Fornecedores pagos -->
			                <div style='position:absolute; left:calc(" & PctPagamentos & "% - 3px); top:34px;'>
			                    <div style='width:6px; height:28px; background:#BB4C97; border-radius:999px;'></div>
			                </div>
			                <div style='
			                    position:absolute;
			                    left:" & PctPagamentos & "%;
			                    top:6px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    font-weight:600;
			                    white-space:nowrap;
			                '>
			                    Dia " & FORMAT(DiaPagamentos, "0") & "
			                </div>
			                <div style='
			                    position:absolute;
			                    left:" & PctPagamentos & "%;
			                    top:74px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    text-align:center;
			                    width:96px;
			                    line-height:1.25;
			                '>
			                    Fornecedores<br/>Pagos
			                </div>
			
			            </div>
			        </div>
			
			        <div style='
			            flex:0 0 132px;
			            width:132px;
			            min-width:132px;
			            max-width:132px;
			            background:#0F8FA6;
			            color:#ffffff;
			            border-radius:8px;
			            padding:18px 12px;
			            text-align:center;
			            box-sizing:border-box;
			            margin-left:8px;
			        '>
			            <div style='font-size:32px; font-weight:700; line-height:1; margin-bottom:10px;'>
			                " & FORMAT(DiasCapitalGiro, "0") & "
			            </div>
			            <div style='font-size:12px; line-height:1.25;'>
			                Ciclo<br/>Financeiro
			            </div>
			        </div>
			
			    </div>
			</div>
			"
		lineageTag: deb5526a-ac2d-4137-8fe3-479c2df0c36c

	measure saldo_balancete_AM = ```
			
			VAR UltimoDiaTrimestre = 
			    LASTDATE(
			        DATESINPERIOD(
			            dCalendario[data], 
			            MAX(dCalendario[data]), -3, 
			            QUARTER
			        )
			    )
			VAR UltimoMesTrimestre = 
			    EOMONTH(UltimoDiaTrimestre,-1)+1
			    RETURN
			CALCULATE(
			    SUM(balancetenew[vlr])
			    , dCalendario[data] = UltimoMesTrimestre
			)
			```
		formatString: #,0
		lineageTag: aa9b480c-4cba-4a55-beba-5533b34a1bf3

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Timeline Ciclo Financeiro HTML' =
			
			VAR PMR_  = COALESCE([Prazo Médio Contas a Receber], 0)
			VAR PMGE_ = COALESCE([prazo_medio_giro_estoque_aging], 0)
			
			VAR DiaEntrada      = 0
			VAR DiaEstoque      = PMGE_
			VAR DiaPagamentos   = 0
			VAR DiaRecebimentos = PMGE_ + PMR_
			
			VAR DiasRecebimento = DiaRecebimentos - DiaEstoque
			
			VAR MaxDia =
			    MAX(
			        1,
			        MAX(
			            DiaEstoque,
			            MAX(DiaPagamentos, DiaRecebimentos)
			        )
			    )
			
			VAR PctEntradaNum      = DIVIDE(DiaEntrada, MaxDia, 0) * 100
			VAR PctEstoqueNum      = DIVIDE(DiaEstoque, MaxDia, 0) * 100
			VAR PctPagamentosNum   = DIVIDE(DiaPagamentos, MaxDia, 0) * 100
			VAR PctRecebimentosNum = DIVIDE(DiaRecebimentos, MaxDia, 0) * 100
			
			-- agora a faixa fica entre PMGE e PMR
			VAR PctCGIniNum  = MIN(PctEstoqueNum, PctRecebimentosNum)
			VAR PctCGFimNum  = MAX(PctEstoqueNum, PctRecebimentosNum)
			VAR PctCGLargNum = PctCGFimNum - PctCGIniNum
			
			VAR PctEntrada      = SUBSTITUTE(FORMAT(PctEntradaNum, "0.0"), ",", ".")
			VAR PctEstoque      = SUBSTITUTE(FORMAT(PctEstoqueNum, "0.0"), ",", ".")
			VAR PctPagamentos   = SUBSTITUTE(FORMAT(PctPagamentosNum, "0.0"), ",", ".")
			VAR PctRecebimentos = SUBSTITUTE(FORMAT(PctRecebimentosNum, "0.0"), ",", ".")
			VAR PctCGIni        = SUBSTITUTE(FORMAT(PctCGIniNum, "0.0"), ",", ".")
			VAR PctCGLarg       = SUBSTITUTE(FORMAT(PctCGLargNum, "0.0"), ",", ".")
			
			VAR CorCapitalGiro =
			    IF(DiasRecebimento < 0, "#D64545", "#2D9CDB")
			
			RETURN
			"
			<div style='
			    font-family:Segoe UI, Arial, sans-serif;
			    background:#ffffff;
			    border:1px solid #E6EAF0;
			    border-radius:8px;
			    padding:18px 20px 18px 20px;
			    box-sizing:border-box;
			    width:100%;
			    color:#23384D;
			    overflow:hidden;
			'>
			
			    <div style='font-size:15px; font-weight:600; color:#26435C; margin-bottom:10px;'>
			        Timeline do Capital de Giro
			    </div>
			
			    <div style='font-size:11px; font-weight:600; color:#6B7A8C; margin-bottom:18px;'>
			        Este período
			    </div>
			
			    <div style='
			        display:flex;
			        align-items:center;
			        justify-content:space-between;
			        gap:36px;
			        flex-wrap:nowrap;
			        width:100%;
			    '>
			
			        <div style='
			            flex:1 1 auto;
			            min-width:0;
			            width:100%;
			        '>
			            <div style='position:relative; height:132px; width:100%;'>
			
			                <!-- linha base -->
			                <div style='
			                    position:absolute;
			                    left:0;
			                    right:0;
			                    top:58px;
			                    height:3px;
			                    background:#BFC9D4;
			                    border-radius:999px;
			                '></div>
			
			                <!-- seta -->
			                <div style='
			                    position:absolute;
			                    right:-1px;
			                    top:54px;
			                    width:0;
			                    height:0;
			                    border-top:5px solid transparent;
			                    border-bottom:5px solid transparent;
			                    border-left:12px solid #BFC9D4;
			                '></div>
			
			                <!-- faixa entre PMGE e PMR -->
			                <div style='
			                    position:absolute;
			                    left:" & PctCGIni & "%;
			                    width:" & PctCGLarg & "%;
			                    top:57px;
			                    height:4px;
			                    background:" & CorCapitalGiro & ";
			                    border-radius:999px;
			                '></div>
			
			                <!-- Entrada -->
			                <div style='position:absolute; left:calc(" & PctEntrada & "% - 3px); top:34px;'>
			                    <div style='width:6px; height:28px; background:#2F80ED; border-radius:999px;'></div>
			                </div>
			                <div style='
			                    position:absolute;
			                    left:" & PctEntrada & "%;
			                    top:6px;
			                    transform:translateX(-8%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    font-weight:600;
			                    white-space:nowrap;
			                '>
			                    Dia 0
			                </div>
			                <div style='
			                    position:absolute;
			                    left:" & PctEntrada & "%;
			                    top:74px;
			                    transform:translateX(-8%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    text-align:left;
			                    width:88px;
			                    line-height:1.25;
			                '>
			                    Entradas nos<br/>Estoques
			                </div>
			
			                <!-- Estoque vendido -->
			                <div style='position:absolute; left:calc(" & PctEstoque & "% - 3px); top:34px;'>
			                    <div style='width:6px; height:28px; background:#F2994A; border-radius:999px;'></div>
			                </div>
			                <div style='
			                    position:absolute;
			                    left:" & PctEstoque & "%;
			                    top:6px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    font-weight:600;
			                    white-space:nowrap;
			                '>
			                    Dia " & FORMAT(DiaEstoque, "0") & "
			                </div>
			                <div style='
			                    position:absolute;
			                    left:" & PctEstoque & "%;
			                    top:74px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    text-align:center;
			                    width:86px;
			                    line-height:1.25;
			                '>
			                    Estoque<br/>Vendido
			                </div>
			
			                <!-- marco ocultado para não embolar no início -->
			                <div style='display:none; position:absolute; left:calc(" & PctPagamentos & "% - 3px); top:34px;'>
			                    <div style='width:6px; height:28px; background:#BB4C97; border-radius:999px;'></div>
			                </div>
			                <div style='display:none;
			                    position:absolute;
			                    left:" & PctPagamentos & "%;
			                    top:6px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    font-weight:600;
			                    white-space:nowrap;
			                '>
			                    Dia " & FORMAT(DiaPagamentos, "0") & "
			                </div>
			                <div style='display:none;
			                    position:absolute;
			                    left:" & PctPagamentos & "%;
			                    top:74px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    text-align:center;
			                    width:96px;
			                    line-height:1.25;
			                '>
			                    Fornecedores<br/>Pagos
			                </div>
			
			                <!-- Recebimentos -->
			                <div style='position:absolute; left:calc(" & PctRecebimentos & "% - 3px); top:34px;'>
			                    <div style='width:6px; height:28px; background:#34A853; border-radius:999px;'></div>
			                </div>
			                <div style='
			                    position:absolute;
			                    left:" & PctRecebimentos & "%;
			                    top:6px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    font-weight:600;
			                    white-space:nowrap;
			                '>
			                    Dia " & FORMAT(DiaRecebimentos, "0") & "
			                </div>
			                <div style='
			                    position:absolute;
			                    left:" & PctRecebimentos & "%;
			                    top:74px;
			                    transform:translateX(-50%);
			                    font-size:10px;
			                    color:#6B7A8C;
			                    text-align:center;
			                    width:84px;
			                    line-height:1.25;
			                '>
			                    Recebimentos
			                </div>
			
			            </div>
			        </div>
			
			        <div style='
			            flex:0 0 132px;
			            width:132px;
			            min-width:132px;
			            max-width:132px;
			            background:#0F8FA6;
			            color:#ffffff;
			            border-radius:8px;
			            padding:18px 12px;
			            text-align:center;
			            box-sizing:border-box;
			            margin-left:8px;
			        '>
			            <div style='font-size:32px; font-weight:700; line-height:1; margin-bottom:10px;'>
			                " & FORMAT(DiasRecebimento, "0") & "
			            </div>
			            <div style='font-size:12px; line-height:1.25;'>
			                Dias para<br/>Recebimento
			            </div>
			        </div>
			
			    </div>
			</div>
			"
		lineageTag: 1cf64322-1858-4830-9d18-9cc1c2d6ef74

	measure Emprestimos_CP_floorplan_haikar = ```
			
			VAR UltimoDiaMesRecente = 
			    EOMONTH(MAX(dCalendario[data]), 0)
			
			VAR PrimeiroDiaMesRecente = 
			    DATE(YEAR(UltimoDiaMesRecente), MONTH(UltimoDiaMesRecente), 1)
			
			VAR emprestimo =
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew,
			                balancetenew[Query] = "Emprestimos_Financiamentos_Curto_Prazo" &&
			                (
			                    balancetenew[descricao_cliente] = "CTA GARANTIDA HDA FLOORPLAN US"
			                   // balancetenew[descricao_cliente] = ""
			                )
			            ),
			            balancetenew[total_mes_atual]
			        ),
			        dCalendario[data] >= PrimeiroDiaMesRecente && dCalendario[data] <= UltimoDiaMesRecente
			    )
			
			VAR juros =
			    CALCULATE(
			        SUMX(
			            FILTER(
			                balancetenew,
			                balancetenew[Query] = "Emprestimos_Financiamentos_Curto_Prazo" &&
			                (
			                    balancetenew[descricao_cliente] = "CTA GARANTIDA HDA FLOORPLAN US"
			                )
			            ),
			            balancetenew[total_mes_atual]
			        ),
			        dCalendario[data] >= PrimeiroDiaMesRecente && dCalendario[data] <= UltimoDiaMesRecente
			    )
			
			RETURN emprestimo
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: cd14c6f6-8829-4676-af4b-19fd349f8658

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'emprestimos_CP_LM floorplan' =
			
			COALESCE(
			CALCULATE(
			    [Emprestimos_CP_floorplan_haikar], DATEADD(dCalendario[data], -1, MONTH))
			    , 0 )
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 6013771b-4331-4dd7-a6bf-972bf0815d33

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Coluna
		formatString: 0
		lineageTag: 5489a507-f052-4bae-940d-1d182900c6b6
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Coluna]

		annotation SummarizationSetBy = Automatic

	partition Medidas_balancetenew-c4001706-af8e-476f-a597-567c86f8ecfe = calculated
		mode: import
		source = Row("Coluna", BLANK())

	annotation PBI_Id = 54e7b6f944da4ba18e7e1434779fdedb

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

