table medidas_estoque_ABC
	lineageTag: 44688ea7-5ebb-469e-96d2-14ebe2879d4e

	measure estoque_valor_unit$ =
			
			SUM( F_estoques_ABC[valor_unitario])
		lineageTag: 0eb6c8f5-0c27-425d-a234-ad8148c77d9f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure estoque_valor_total$ = ```
			
			    SUM(F_estoques_ABC[Valor Total])
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 4ab7f326-61df-4126-b921-a035115c8ad5

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure total_estoque =
			
			SUM(F_estoques_ABC[Quantidade])
		formatString: #,0
		lineageTag: f87c4f46-4547-422d-8b93-f211bc30d7eb

		annotation PBI_FormatHint = {"isDecimal":true}

	measure total_itens_estoque =
			
			DISTINCTCOUNT(F_estoques_ABC[Descrição])
		formatString: #,0
		lineageTag: 84e56236-07f4-4675-b366-d8d51f1cd9b8

	measure Estoque_ABC_Acumulado_descricao$ = ```
			
			CALCULATE(
			    [estoque_valor_total$],
			    TOPN(
			        [rankig_produtos],
			        ALL(
			            F_estoques_ABC[Descrição]),
			            medidas_estoque_ABC[estoque_valor_total$],
			            DESC
			        )
			)
			
			
			
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: ce2804bc-6cfa-4be7-982d-3b372965c24c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure rankig_produtos =
			
			RANKX(
			    ALL(
			    F_estoques_ABC[Descrição]),
			    [estoque_valor_total$])
		formatString: 0
		lineageTag: 0222ffbe-757c-45bb-a25d-937f8109c490

	measure %_estoque_acumulado = ```
			
			
			VAR v_estoque_acumulado =
			CALCULATE(
			    [estoque_valor_total$],
			    TOPN(
			        [rankig_produtos],
			        ALL(
			            F_estoques_ABC[Descrição]),
			            medidas_estoque_ABC[estoque_valor_total$],
			            DESC
			        )
			)
			RETURN
			   v_estoque_acumulado / 
			CALCULATE(
			    [estoque_valor_total$],
			    ALL(F_estoques_ABC[Descrição]))
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 251e25ad-e3d4-42ee-9a3d-865fe55f37b5

	measure classe_abc = ```
			
			IF(
			    medidas_estoque_ABC[Estoque_ABC_Acumulado_descricao$] >= 0,
			    IF(medidas_estoque_ABC[%_estoque_acumulado] <= 0.8, "A",
			    IF(medidas_estoque_ABC[%_estoque_acumulado] <= 0.9, "B",
			      //  IF(
			      //  medidas_estoque_ABC[Estoque_ABC_Acumulado_operacao] >= 0,
			      //  IF(medidas_estoque_ABC[%_estoque_acumulado_operacao] <= 0.8, "A",
			       // IF(medidas_estoque_ABC[%_estoque_acumulado_operacao] <= 0.9, "B",
			    
			    "C")
			    )
			)
			// )))
			//SWITCH(
			   // TRUE(),
			    //medidas_estoque_ABC[Estoque_ABC_Acumulado_descricao] >= 0.8, "A",
			    //medidas_estoque_ABC[Estoque_ABC_Acumulado_descricao] >= 0.9, "B",
			    //"C"
			//)
			//)
			
			```
		lineageTag: d867f434-05b2-4bb6-bee4-ba7a71aa52cd

	measure rankig_operacao =
			
			RANKX(
			    ALL(
			    F_estoques_ABC[Origem Operação]),
			    [estoque_valor_total$])
		formatString: 0
		lineageTag: 131d165f-c155-48db-8ff9-61e9f3e1eb8d

	measure Estoque_ABC_Acumulado_operacao$ =
			
			CALCULATE(
			    [estoque_valor_total$],
			    TOPN(
			        [rankig_operacao],
			        ALL(
			            F_estoques_ABC[Origem Operação]),
			            medidas_estoque_ABC[estoque_valor_total$],
			            DESC
			        )
			)
		lineageTag: cccce95e-e603-48e3-9576-feaf0a61c153

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %_estoque_acumulado_operacao = ```
			
			[Estoque_ABC_Acumulado_operacao$] / 
			CALCULATE(
			    [estoque_valor_total$],
			    ALL(F_estoques_ABC[Origem Operação]))
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 99916ae1-e362-4021-987d-6d0a975f5e33

	measure classe_abc_operacao =
			
			IF(
			    medidas_estoque_ABC[Estoque_ABC_Acumulado_operacao$] >= 0,
			SWITCH(
			    TRUE(),
			    medidas_estoque_ABC[%_estoque_acumulado_operacao] <= 0.8, "A",
			    medidas_estoque_ABC[%_estoque_acumulado_operacao] <= 0.9, "B",
			    "C"
			)
			)
		lineageTag: 1c285e48-1c94-4cee-bad7-78d13d7aaf08

	measure filtroABC_ =
			
			IF(
			    SELECTEDVALUE(d_classe_abc[Classe]) = [classe_abc], 1, 0)
		formatString: 0
		lineageTag: f5626cb4-b5ff-481f-b383-e06a00851d32

	measure estoque_ABC =
			
			CALCULATE(
			    [estoque_valor_total$],
			    FILTER(
			        VALUES(F_estoques_ABC[Descrição]),
			        [%_estoque_acumulado] <= MAX(d_classe_abc[limite_superior]) &&
			        [%_estoque_acumulado] > MIN(d_classe_abc[limite_inf])
			    )
			)
		formatString: #,0
		lineageTag: 5d9ddab3-5f30-410d-8c24-0ef0fe7a2f22

		annotation PBI_FormatHint = {"isDecimal":true}

	measure rankig_quantidade_origem_op =
			
			RANKX(
			    ALL(
			    F_estoques_ABC[Origem Operação]),
			    [total_estoque])
		formatString: 0
		lineageTag: 97fac2aa-5258-4763-9a06-df65b6daa57b

	measure Estoque_ABC_quantidade_Acumulado_operacao =
			
			CALCULATE(
			    [total_estoque],
			    TOPN(
			        [rankig_quantidade_origem_op],
			        ALL(
			            F_estoques_ABC[Origem Operação]),
			            medidas_estoque_ABC[total_estoque],
			            DESC
			        )
			)
		formatString: #,0
		lineageTag: 6aa95e5f-8563-48ec-aef9-745ce1a19c97

		annotation PBI_FormatHint = {"isDecimal":true}

	measure %_estoque_quantidade_acumulado_operacao = ```
			
			[Estoque_ABC_quantidade_Acumulado_operacao] / 
			CALCULATE(
			    [total_estoque],
			    ALL(F_estoques_ABC[Origem Operação]))
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 566ffe8b-e9c5-4b68-b6ca-640837275eb3

	measure classe_abc_quantidade_operacao =
			
			IF(
			    medidas_estoque_ABC[Estoque_ABC_quantidade_Acumulado_operacao] >= 0,
			SWITCH(
			    TRUE(),
			    medidas_estoque_ABC[%_estoque_quantidade_acumulado_operacao] <= 0.8, "A",
			    medidas_estoque_ABC[%_estoque_quantidade_acumulado_operacao] <= 0.9, "B",
			    "C"
			)
			)
		lineageTag: fa80fa43-7218-47b8-988e-5f57351c5c41

	measure rankig_quantidade_descricao =
			
			RANKX(
			    ALL(
			    F_estoques_ABC[Descrição]),
			    [total_estoque])
		formatString: 0
		lineageTag: 767c4d14-3fba-4e73-b273-0cb11fc7c1e2

	measure Estoque_ABC_quantidade_Acumulado_descricao =
			
			CALCULATE(
			    [total_estoque],
			    TOPN(
			        [rankig_quantidade_descricao],
			        ALL(
			            F_estoques_ABC[Descrição]),
			            medidas_estoque_ABC[total_estoque],
			            DESC
			        )
			)
		lineageTag: 985674cd-07c4-4635-9f44-8bc3b88d24bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %_estoque_quantidade_acumulado_descricao = ```
			
			[Estoque_ABC_quantidade_Acumulado_descricao] / 
			CALCULATE(
			    [total_estoque],
			    ALL(F_estoques_ABC[Descrição]))
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3df0ff5a-afc2-41a3-ae63-77ff3eb2f937

	measure classe_abc_quantidade_descricao =
			
			IF(
			    medidas_estoque_ABC[Estoque_ABC_quantidade_Acumulado_descricao] >= 0,
			SWITCH(
			    TRUE(),
			    medidas_estoque_ABC[%_estoque_quantidade_acumulado_descricao] <= 0.8, "A",
			    medidas_estoque_ABC[%_estoque_quantidade_acumulado_descricao] <= 0.9, "B",
			    "C"
			)
			)
		lineageTag: 3fc19aac-484f-499b-a212-8d96d45866e3

	measure qtd_produtos_representam_80% =
			
			COUNTROWS(
			    FILTER(
			        VALUES(
			    F_estoques_ABC[Descrição]),
			    medidas_estoque_ABC[%_estoque_acumulado] <= 0.8
			    ))
		formatString: 0
		lineageTag: 7dbe510a-fbd3-449f-baed-a26f18f27a5f

	measure subtitulo_produtos =
			
			[qtd_produtos_representam_80%] & " Produtos representam 80% do estoque de " & FORMAT([total_itens_estoque], "#0,#00") & " itens"
		lineageTag: bf6b6444-030c-4df6-97ec-173baa06d58c

	measure qtd_produto_A = ```
			
			CALCULATE(
			DISTINCTCOUNT(d_produtos_estoques_ABC[descricao]),
			    FILTER(
			        F_estoques_ABC,
			        F_estoques_ABC[ABC] = "A"
			    )
			)
			
			```
		formatString: #,0
		lineageTag: bf251e56-2581-4a0c-9c5a-b7119aafd4ee

	measure qtd_produto_B =
			
			CALCULATE(
			DISTINCTCOUNT(d_produtos_estoques_ABC[descricao]),
			    FILTER(
			        F_estoques_ABC,
			        F_estoques_ABC[ABC] = "B"
			    )
			)
		formatString: #,0
		lineageTag: 331b757d-637c-407e-a86f-c3672406db8a

	measure qtd_produto_C =
			
			CALCULATE(
			DISTINCTCOUNT(d_produtos_estoques_ABC[descricao]),
			    FILTER(
			        F_estoques_ABC,
			        F_estoques_ABC[ABC] = "C"
			    )
			)
		formatString: #,0
		lineageTag: cf435426-b8dc-41f0-ae0a-f56071caf208

	measure custo_total_produto_A$ =
			
			CALCULATE(
			     SUM(F_estoques_ABC[Valor Total]),
			    FILTER(F_estoques_ABC,
			            F_estoques_ABC[ABC] = "A"
			    ))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 81746672-0372-4d3f-8f3d-cd1e26d27c31

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure custo_total_produto_B$ =
			
			CALCULATE(
			     SUM(F_estoques_ABC[Valor Total]),
			    FILTER(F_estoques_ABC,
			            F_estoques_ABC[ABC] = "B"
			    ))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: c0a8cf74-4b1b-4221-aa47-294964e47c2a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure custo_total_produto_C$ =
			
			CALCULATE(
			     SUM(F_estoques_ABC[Valor Total]),
			    FILTER(F_estoques_ABC,
			            F_estoques_ABC[ABC] = "C"
			    ))
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 6e264f7f-e3a9-46ff-a214-b19ad70e525a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure %_produto_A =
			
			DIVIDE(
			    [custo_total_produto_A$],
			    [estoque_valor_total$]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2f2fb7b4-2d72-496c-8d4c-d202750e9865

	measure %_produto_B =
			
			DIVIDE(
			    [custo_total_produto_B$],
			    [estoque_valor_total$]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 24f1f9e9-2b1e-48a2-9c72-6aba16f8b1e2

	measure %_produto_C =
			
			DIVIDE(
			    [custo_total_produto_C$],
			    [estoque_valor_total$]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 646de59d-93ac-4f2d-a45a-59da14c34d2d

	measure volumetria_estoque_abc =
			
			IF(NOT(ISBLANK(medidas_estoque_ABC[total_estoque])), "🟢", "🔴")
		lineageTag: 8ee151b0-2d1a-43fe-bdba-1749c2f960eb

	measure resumo_grupo_A = ```
			
			VAR vquant_itens = CALCULATE(
			DISTINCTCOUNT(d_produtos_estoques_ABC[descricao]),
			    FILTER(
			        ALL(F_estoques_ABC),
			        F_estoques_ABC[ABC] = "A"
			    )
			)
			
			VAR vcusto_grupo_A =
			    CALCULATE(
			     SUM(F_estoques_ABC[Valor Total]),
			    FILTER(F_estoques_ABC,
			            F_estoques_ABC[ABC] = "A"
			    ))
			
			VAR vcusto_grupo_A_perc = DIVIDE(
			    [custo_total_produto_A$],
			    [estoque_valor_total$]
			)
			
			RETURN
			"""" & "Os" & vquant_itens &  " " & "do GRUPO A tem um custo total de " & vcusto_grupo_A &  " representando" &  " do total em estoque."  
			```
		lineageTag: eadb622e-e4d0-4886-9938-3eb975a2db26

	column Column
		formatString: 0
		lineageTag: bd34cc7f-04f3-4164-8209-faeec8e35829
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition medidas_estoque_ABC = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 5a2f596e78ca4f5096547ca870df67b5

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

