table medidas_mcd
	lineageTag: 84da9fb9-5de5-4959-a0ea-b903f0b098e6

	measure despesas_controladas = ```
			
			    SUMX(
			        FILTER(
			            F_Despesas_McD,
			            F_Despesas_McD[descricao] = "DRE_Desp_Operacionais_Despesas_controladas"),
			        F_Despesas_McD[vlr]
			    )
			```
		formatString: #,0
		lineageTag: 87a4294d-6e49-4702-b31b-7b70f78699f2

		annotation PBI_FormatHint = {"isDecimal":true}

	measure despesas_nao_controladas = ```
			
			  SUMX(
			        FILTER(
			            F_Despesas_McD,
			            F_Despesas_McD[descricao] = "DRE_Desp_Operacionais_Despesas_nao_controladas"),
			        F_Despesas_McD[vlr]
			    )
			```
		formatString: #,0
		lineageTag: 24a0a967-d01a-4c14-8315-e4f3144d471f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure despesas_controladas_ACU =
			
			CALCULATE(
			    [despesas_controladas],
			    DATESYTD(dCalendario[data]))
		formatString: #,0
		lineageTag: c26b92cf-9347-4fa6-9e58-320555510f87

		annotation PBI_FormatHint = {"isDecimal":true}

	measure despesas_nao_controladas_ACU =
			
			CALCULATE(
			    [despesas_nao_controladas],
			    DATESYTD(dCalendario[data]))
		formatString: #,0
		lineageTag: c1eed56a-5485-4619-b7be-d089494c4778

		annotation PBI_FormatHint = {"isDecimal":true}

	measure despesas_controladas_ACU_LY = ```
			
			CALCULATE(
			    [despesas_controladas_ACU], 
			    DATEADD(dCalendario[data], -1, YEAR)
			    )
			```
		formatString: #,0
		lineageTag: 3380b69e-5eac-4b1c-9102-6ecce0c72c88

		annotation PBI_FormatHint = {"isDecimal":true}

	measure despesas_nao_controladas_ACU_LY =
			
			CALCULATE(
			    [despesas_nao_controladas_ACU],
			    DATEADD(dCalendario[data], -1, YEAR)
			)
		formatString: #,0
		lineageTag: fc392af2-1ff6-425b-8893-ca282e8f1231

		annotation PBI_FormatHint = {"isDecimal":true}

	measure variacao%_despesas_nao_controladas_ACU =
			
			DIVIDE(
			    [despesas_nao_controladas_ACU] - [despesas_nao_controladas_ACU_LY],
			    [despesas_nao_controladas_ACU_LY])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 28073bd6-253a-4ac4-bcb6-21a07f19703e

	measure variacao%_despesas_controladas_ACU =
			
			DIVIDE(
			    [despesas_controladas_ACU] - [despesas_controladas_ACU_LY],
			    [despesas_controladas_ACU_LY])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 538f3f56-1f34-4c18-a043-97be6e1b6f3b

	column 'Coluna 1'
		dataType: string
		lineageTag: 2eae947b-0a87-4b49-b67e-ef5a85798fab
		summarizeBy: none
		sourceColumn: Coluna 1

		annotation SummarizationSetBy = Automatic

	partition medidas_mcd = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t])
				in
				    Fonte

	annotation PBI_ResultType = Table

